### ISSUE TITLE
refactor: コア関連モジュールのディレクトリ集約

### ISSUE THREAD

**Issue by tarepan** [VOICEVOX/voicevox_engine#1012]
## 内容
概要: コア関連モジュールのディレクトリ集約によるリファクタリング  

様々なリファクタリングにより、現在 `voicevox_engine` 直下に 3 つのコア関連モジュールが存在している（`core_adapter` / `core_initializer` / `core_wrapper`）。  
`tts_engine` や `preset` と同様に、`core` ディレクトリを用意し上記3モジュールをここへ集約すれば見通しを改善できる。  

このような背景から、新設する `core` ディレクトリへのコア関連モジュール集約によるリファクタリングを提案します。  

### Pros 良くなる点
- `voicevox_engine` ディレクトリ見通し改善

### Cons 悪くなる点
- 無し

### 実現方法
- `core` ディレクトリ新設
- `core_adapter` / `core_initializer` / `core_wrapper` 移植

## VOICEVOXのバージョン
0.14.7

## OSの種類/ディストリ/バージョン
- [x] Windows
- [x] macOS
- [x] Linux

**Comment by Hiroshiba** [comment]
賛成です！！

そういえばなのですが、コアのモックが`dev`ディレクトリの下にあったと思います。
これも`core/mock`辺りに移動する手も考えられるのですが、モックをひとまとめにしてディレクトリに置いていくパターンと、個々の概念の下にモック用のファイルを配置するのと、どっちの方が良さそうでしょうか 👀 

個人的には･･････とても判断しにくいのですが、どっちかというと今の形のようにモック全部がまとまっていた方が分かりやすいかもと思っています。
MockEngineはMockCoreに依存する、とかがわかりやすいので。
ちょっと気になってたので相談してみた次第です！

**Comment by tarepan** [comment]
> 賛成です！！  

👍  
PR着手します。

> コアのモック ... どっちの方が良さそうでしょうか 👀  
> 個人的には ... 今の形のようにモック全部がまとまっていた方が分かりやすいかも  

コア追従の修正がモックによく入るなら `core/mock` がベストです。  
現状ほぼ固定なので、今の形のようにモック全部まとめるので問題ないと感じます。
