### ISSUE TITLE
Pyinstaller v6でビルドすると、macOS版エディタがエラーになる

### ISSUE THREAD

**Issue by Hiroshiba** [VOICEVOX/voicevox_engine#1022]
## 不具合の内容

題のとおりです。0.15.0のビルドで発生しました。

### 現象・ログ

0.15.0のmacエディタが動かない

```bash
# ログ見るためにエンジンを直接起動
$ /Applications/VOICEVOX.app/Contents/MacOS/run
[10649] Error loading Python lib '/Applications/VOICEVOX.app/Contents/Frameworks/Python': dlopen: dlopen(/Applications/VOICEVOX.app/Contents/Frameworks/Python, 0x000A): tried: '/Applications/VOICEVOX.app/Contents/Frameworks/Python' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/Applications/VOICEVOX.app/Contents/Frameworks/Python' (no such file), '/Applications/VOICEVOX.app/Contents/Frameworks/Python' (no such file)
```

たしかにpython.frameworkがなさそう
```bash
$ ls /Applications/VOICEVOX.app/Contents/Frameworks/
Electron Framework.framework/   ReactiveObjC.framework/         VOICEVOX Helper (GPU).app/      VOICEVOX Helper (Renderer).app/
Mantle.framework/               Squirrel.framework/             VOICEVOX Helper (Plugin).app/   VOICEVOX Helper.app/
```

かわりに`/Applications/VOICEVOX.app/Contents/MacOS/engine_internal/`にありました。

でもまだ問題がありそう

- https://github.com/VOICEVOX/voicevox_engine/pull/1020#issuecomment-1902490013

### 再現手順

0.15.0のmac版エディタを起動

## その他

とりあえずまとめるためのissueです。

ref: discord.com/channels/879570910208733277/893889888208977960/1198352832311599305
ref: #857

**Comment by Hiroshiba** [comment]
こちらのPRで一旦問題を迂回する予定です。

- https://github.com/VOICEVOX/voicevox_engine/pull/1023

**Comment by Hiroshiba** [comment]
@yamachu さんがDiscordに貼ってくださったこちらを見る感じ、仮にパス周りの問題を解決しても署名周りの問題がありそう･･･？

- https://github.com/pyinstaller/pyinstaller/issues/8160

**Comment by Hiroshiba** [comment]
@PickledChair さんのDiscordでの会話を引用させていただきます！
https://discord.com/channels/879570910208733277/893889888208977960/1198542083015835648

---

@PickledChair 
エンジン単体なら期待通り動くのに、App bundleにすると動かなくなるという点で、奇妙な動作ですね……手元でも動かして調べてみたら、VOICEVOX.app の中に含まれているエンジン関連のファイルを外に出して動かすと、普通にエンジンが動きます。なので、v6のPyInstallerが出力した実行ファイルは、起動するとまず自分が App bundle内にあるのかどうかを調べて、App bundle内ならContents/Frameworks以下のPython関連ファイルを、そうでなければengine_internal以下のPython関連ファイルを見にいくようです。

これを踏まえて、engine_internal以下のファイルを全部Contents/Frameworks直下に移すと、エンジンが動くようになりました

---

@Hiroshiba 
お～なるほどです！！！
エンジンのリビルドが不要になるからそちらの方が早いかもですね。ちょっと状況把握します
ここ変えるだけで動くかもって感じなのか～
https://github.com/VOICEVOX/voicevox/blob/8d82be87de841e71f3a23b932118c4b9deb2c766/.github/workflows/build.yml#L284-L288

---

@PickledChair 
そうですね、engine_internal以下のファイルはMacOSディレクトリではなくFrameworksディレクトリに持ってく感じです

**Comment by PickledChair** [comment]
@Hiroshiba 

DIscord のやり取りの転記ありがとうございます！

> ここ変えるだけで動くかもって感じなのか～
> https://github.com/VOICEVOX/voicevox/blob/8d82be87de841e71f3a23b932118c4b9deb2c766/.github/workflows/build.yml#L284-L288

実際に以下の変更を適用してビルドを回してみました：

https://github.com/PickledChair/voicevox/blob/fix/problem-with-pyinstaller-v6/.github/workflows/build.yml#L284-L290

ビルド結果 ([dmg](https://github.com/PickledChair/voicevox/releases/download/0.15.0-pickledchair-preview.0/VOICEVOX.dmg) / [zip](https://github.com/PickledChair/voicevox/releases/download/0.15.0-pickledchair-preview.0/voicevox-macos-cpu-0.15.0-pickledchair-preview.0.zip)) を動かしてみた感じでは、実際に動作するようになりました（エディタのバージョン判定の関係で config.json を消したりする必要があるかもしれませんが）。

ただし、Discord でもおっしゃっていた通りワークアラウンド感が強いので、根本解決かというとちょっと微妙というのは同感です（[PyInstaller のドキュメント](https://pyinstaller.org/en/v6.3.0/usage.html#building-macos-app-bundles)の「Frameworks ディレクトリは空」という記述と矛盾している感じもありますし、PyInstaller のバグの可能性は大いにあります）。 https://github.com/VOICEVOX/voicevox_engine/issues/1022#issuecomment-1902549984 の通り、今回は revert で対応というのが堅実だと思いました。

**Comment by Hiroshiba** [comment]
@PickledChair 緊急の調査本当に助かりました、ありがとうございました！！

> [PyInstaller のドキュメント](https://pyinstaller.org/en/v6.3.0/usage.html#building-macos-app-bundles)の「Frameworks ディレクトリは空」という記述と矛盾している感じもありますし

こちらに関しては、pyinstallerを`.app`にするビルドをすればそうなる、ということなのかもと思いました！
ただ結局、なぜ`Contents/MacOS`にrunがあるのに`Contents/Framework`を探しに行くのかは謎なのですが･･･。

ということでPyinstallerのコードをちょっとだけ探ったのですが、近そうな内容の理由が書いてました。`MacOS`は署名が必要で～みたいな感じっぽいです。
https://github.com/pyinstaller/pyinstaller/blob/225c0ad56db0ab94b34250c860f408c04019604b/PyInstaller/building/osx.py#L153-L305
（ChatGPTで和訳してみました https://chat.openai.com/share/09f5ea99-0aff-4a55-93d9-3f1b9a7d6a31 ）

署名周りも考慮した良い方法は、たぶんpyinstallerで`.app`を作るようにビルドし、出来上がったものを`Contents`以下のディレクトリにそれぞれコピーする感じかなと思いました。
けどまあ大変なので、 @PickledChair さんの方法もありなのかなと思いました！
より正確にするなら、`*.framework`は`Frameworks`に、それ以外は`Resources`に移動･･･？

あるいは、今まで通りengine関連のファイルを全部rootに展開する（engine_internalディレクトリをやめる）ようにして、↓の`internal_dir`を使わず`root_dir`を使うようにする手もあるかもとか思いました。
https://github.com/VOICEVOX/voicevox_engine/blob/9e1b0f07137e67e84a766a0828f8bad10cd64cd0/voicevox_engine/utility/path_utility.py#L44-L50
このあたりはたぶん @sabonerune さんが土地勘あると思うので、直感どうかお聞きしたいです。
（エンジン関連のファイルがべちゃっと展開されても、エディタ側でrevertした[エンジンディレクトリを分ける方針](https://github.com/VOICEVOX/voicevox/issues/1603)が進んだら解決するので、まあ分けなくても良いのかなとか思ってます。）

**Comment by sabonerune** [comment]
`engine_internal`ディレクトリをやめる場合はビルド時に渡している`engine_internal`を空文字にすればいいはずです。
https://github.com/VOICEVOX/voicevox_engine/blob/9e1b0f07137e67e84a766a0828f8bad10cd64cd0/run.spec#L72
その場合、`internal_dir`は`root_dir`と同じ場所を返すようになるだけなので必ずしも`internal_dir`を廃止する必要はないと思います。

**Comment by Hiroshiba** [comment]
@sabonerune たしかにです！！

`contents_directory`に入れずに全部ぶちまけてMacOSに突っ込むのが良い気がしてきました。
（`Contents/Framewoks`に入れるのは将来pyinstallerの仕様が変わるかもだけど、run.exeのある場所にぶちまける方法はv5/v6どちらも有効なので一旦メンテナンス性が高そう）

もう１点ちょっと確認したいことが 🙇 
たしかlinux環境でキーボードが使えなくなる？みたいなエディタ側の不具合があったと思うのですが、あれってrun.exeと同階層にエンジン関連ファイルが大量に置かれていても、エディタ側で`vv-engine`ディレクトリに突っ込むようにすれば解決される、という認識であってそうでしょうか 👀

**Comment by sabonerune** [comment]
Linux環境でキーボードが効かなくなっていたのは`vv-engine`ディレクトリにエンジンを移動すれば解決するはずです。
確かエンジン由来の共有ライブラリをエディタが誤って読み込んでいたことが原因のはずなので…

**Comment by Hiroshiba** [comment]
@sabonerune ありがとうございます！！

最終的な判断のメモです！
Pyinstallerをv6にバージョンアップする場合でも、とりあえずrun.exeと同じディレクトリにいろんなファイルが入っても良い形（`contents_directory`を利用しない形）が良いのかなと思いました！

もしMac版でも署名するようになった場合はおそらくこの辺りをどうするか考える必要が出てくるかもしれません。
またrun.exe以外のファイルが大量に散乱しているのはあまり良くないことだとも思います。
`contents_directory`を使いつつ、エディター側（`.app`下）でも問題がなさそうな形があればそれも良いのかなと思います。

皆様ありがとうございました！！
