### ISSUE TITLE
[project-s] ハミングスタイルはTTSできないので、全スタイルでTTSできることを前提にしたアプリがエラーになる

### ISSUE THREAD

**Issue by Hiroshiba** [VOICEVOX/voicevox_engine#1027]
## 不具合の内容

project-sで不都合を思いついたのでメモです。

ハミングスタイルは他のスタイルと同様、style idと名前を持ちます。
今までのスタイルとの区別は新しく追加される`type`で識別する予定です。
エディタ側ではこのtypeを用いてフィルタリングを行い、talkスタイルだけをTTS欄に、hummingスタイルは歌手として表示される形を考えています。

問題はサードパーティアプリで、style typeが新たに追加されて、かつTTS非対応なスタイルが増えることを知らないはずです。
なのでTTS一覧に普通にハミングが表示されたり、ハミングとわからない（nameがtalkのと一緒なので）形になりそうです。
アップデート準備期間が長ければ問題はないかもしれませんが、今回はいきなりの変更になるので、できればなんとかしたいです。

思いつく手はいくつかあります。

1. スタイル情報を返すAPIの引数で返ってくるスタイルタイプを選別できるようにし、デフォルトではtalkだけ返す
2. エンジン起動引数でハミングスタイルなどを返すかどうか制御可能にし、デフォルトではtalkだけ返す
    * こっちはエディタがハミングありで起動した場合に無力
3. 何もしない

個人的には1が便利そうに感じてます。
やるならたぶん`/speakers`と`/speaker_info`の両方につける形かなと。
`style_type_filter: list["talk" | "humming" | "sing_teacher"] | None`みたいな引数を追加して、デフォルトは`["talk"]`とか･･･。

## その他

なんかまだ見落としてることありそうな気がしないでもない。。。

**Comment by Hiroshiba** [comment]
@y-chan お手空きの際にご意見いただけると。。。 🙇

**Comment by Segu-g** [comment]
1のアイデアに近いですが、ハミング用スタイルは別のURI('/sing/speakers'等)で提供し、既存の'/speakers'はそのままにしておくのはどうでしょうか？
トーク用の話者情報とハミング用の話者情報では、そもそもスキーマとして異なるものになり得るので、別のURIにするのも自然かなと思いました。

**Comment by Hiroshiba** [comment]
@Segu-g 確かにと思ったのですが、ちょっと記憶を掘り返して何でまとめたか思い出しました！！
将来ハミング用の機能を使ってトークを生成することがあり得るんですよね･･････。
（そして仮にそうなった時、「humming：口ずさむ」でしゃべり声生成することになってなんか変だということに気づきました。`frame_decode`タイプとかにした方が自然かも･･･。）

**Comment by Segu-g** [comment]
@Hiroshiba なるほど！経緯が理解できました。
`speaker` と `singer` の役割的な違いと、`mora単位` と `frame単位` の合成手法の違いの2軸があるということですね。
確かに `/speakers` はその名前的にも「話者」という役割的な側面がありそうです。

ただ、現状 `frame_decode` でしゃべり声合成することが標準でないことを考えると、互換を破壊してまでspeakerを変更する必要はないと思います。
 `frame_decode` のオプションは新しく追加する必要があるので新しいURI (`/singers` or `/sing/speakers` or `/frame_decoder/speakers` 等)に記載し、
`frame_decode` でのしゃべり声合成が可能になるタイミングではサードパーティー開発者も対応すると思うので、その時になってから `/speakers` のスキーマを破壊的変更するのはどうでしょうか。

**Comment by Hiroshiba** [comment]
@Segu-g 
> その時になってから `/speakers` のスキーマを破壊的変更するのはどうでしょうか。

あれ、ここに認識の違いがあるかもです！
`/speakers`にスタイルTypeをフィルタリングできる引数を追加して、その引数のデフォルト値を[`talk`]とする手を考えてました。
正確に言うと`StyleModel`の中に`type`が入るのですが、まあ破壊的変更ではない･･･かなと。

**Comment by Hiroshiba** [comment]
こちらですが、とりあえず`/singers`と`/singer_info`を作成し、トーク用スタイルと分けることで一旦迂回することにしました！
`/singers`にはhummingスタイル・singing_teacherスタイル・songスタイルが返る形になります。
`/speakers`とSpeaker（キャラ）がかぶりますが、まあそれは集約する形で･･･。
@Segu-g さんありがとうございました！！
