### ISSUE TITLE
remove: `FramePhoneme` クラス削除

### ISSUE THREAD

**Issue by tarepan** [VOICEVOX/voicevox_engine#1045]
## 内容
要望概要: `FramePhoneme` クラスの削除によるAPI変更とリファクタリング  

現在の Song 機能は中間特徴量として `f0` / `volume` / `phonemes` を用いている。  
このうち `f0` / `volume` は時間スケールがフレームである一方、`phonemes` では音素である。  
よって `phonemes` では音素持続時間を表現するために `FramePhoneme` を導入している。  
つまり以下のようになっている：  

```
f0: List[float]              = [0, 100, 100, 100, 100, 100, 0]
volume: List[float]          = [0,   1,   2,   3,   4,   5, 0]
phonemes: List[FramePhoneme] = [FP("pau", 1), FP("a", 5), FP("pau", 1)]
```

この方式は `FramePhoneme.frame_length` が編集可能に見えるが、既にフレームスケールである `f0` / `volume` との整合性を取る必要があるため、実際に編集するケースはほぼ無い。  

別の実装方式として、`phonemes` の時間スケールをフレームにするアプローチがあり得る。  
つまり以下のような中間特徴量を用いる：  

```
f0: List[float]     = [    0, 100, 100, 100, 100, 100,     0]
volume: List[float] = [    0,   1,   2,   3,   4,   5,     0]
phonemes: List[str] = ["pau", "a", "a", "a", "a", "a", "pau"]
```

この形式であれば直感的に特徴量間の対応が理解できる。  
また、内部処理を複数個削減できる。  

このような背景から、`FramePhoneme` クラス削除を提案します。  

### Pros 良くなる点
- API パラメータ簡略化
- 内部処理削減

### Cons 悪くなる点
- ベータ版 API の破壊的変更

### 実現方法
- `phonemes` の時間スケールをフレームに変更
- API 変更

## VOICEVOXのバージョン
0.16.0

## OSの種類/ディストリ/バージョン
- [x] Windows
- [x] macOS
- [x] Linux

**Comment by Hiroshiba** [comment]
音素も音素単位ではなくフレーム単位に使用か結構迷ったのですが、一応こちらの表現じゃないとできないことがちょくちょくあるので列挙してみます。

* フレームごとに音素を書くと、同じ音素が続いた時に区切りがわからない
	* まあ推論モデルによっては意外と問題にならないのですが
* エディタ側で制御したいのは音素の開始位置と終了位置
	* なのでエディター側は結局フレームレベルのもの音素レベルに直し、それをまたフレームレベルに直す処理を書く
* ノートとの対応関係が取りづらくなる
	* エディタで表示しやすいように、将来的にどの音素がどのノートに結びついているか ID で 紐付けする
	* その対応関係もフレームレベルになってしまう
* 容量が大きくなる
	* jsonで返す時、フレーム数×8バイトくらい増えそう
	* まあ30秒のフレームでも61440バイト程度なのであまり問題にならないかもですが

まあ結局、どこかでフレームレベルと音素レベルを書き換える処理が必要なのですが、それをエンジンで吸収するかエディターで吸収するかだと思います。
どっちで吸収するのが良いかわからないのですが、現状はエンジンの責務かなということでこうなってます！

**Comment by tarepan** [comment]
> 同じ音素が続いた時に区切りがわからない
> まあ推論モデルによっては意外と問題にならない  

モデルによっては `FramePhoneme` 形式が必須であることに同意です。  
現行のVOICEVOX Song 推論モデルは区切り無し（`FramePhoneme` をフレーム数で展開したうえで core に引き渡し）なため、廃止が可能かなと考えた次第です。  

> エディタ側  

👍  
中間表現の編集・最終的な波形合成以外にも、表示用途として必要ということですね。  
理解しました、妥当な設計に感じます。  

> 現状はエンジンの責務  

👍
