### ISSUE TITLE
can I use custom espnet model? 

### ISSUE THREAD

**Issue by samiabat** [VOICEVOX/voicevox_engine#1053]
Hi @smly @raa0121 @oov @mes51 @qwerty2501 
I want to use my own trained model instead of the models for speech synthesis.

1, is that possible to use my model?
2, if so how can I use it, or is there any documentation or resource to do so?

Thank you!

**Comment by sevenc-nanashi** [comment]
You can't.
You can use [bridge-plugin](https://github.com/voicevox-bridge/bridge-plugin) to load your espnet model, but voicevox/voicevox_engine can't.

**Comment by samiabat** [comment]
Hi @sevenc-nanashi @oov @raa0121 
私が正しければ、ブリッジ プラグインにはピッチ、母音の長さ、子音の長さなどを計算するための実装がありません。オーディオ クエリを生成し、口パクに使用したいと考えています。

質問が 2 つあります。

1、ピッチや母音の長さ、子音の長さなどの値はPythonのライブラリだけで取得できますか？ 「はい」の場合、リソースまたはライブラリを推奨してください。
2、Voicevox では、オーディオ クエリを生成するためのモデルを使用していますか?

![image](https://github.com/VOICEVOX/voicevox_engine/assets/91486438/893b31f6-3dea-4800-b5f3-8bdd7358f03c)

**Comment by Hiroshiba** [comment]
@samiabat 
Please stop mentioning unrelated people as it is bothersome.

1. No. You can obtain the lengths of consonants and vowels with OpenJTalk.
2. Yes.

The topic has shifted from the development of the VOICEVOX engine to something you want to create. This place is for discussing the VOICEVOX engine, so please avoid unrelated topics.

---

無関係な人にメンションを送るのは迷惑なのでやめてください。

1. Noです。子音・母音の長さだけならOpenJTalkで取得できます。
2. Yesです。

話題がVOICEVOXエンジンの開発からあなたが制作したい何かに変わっています。
ここはVOICEVOXエンジンについて議論する場所ですので、関係ない話題は避けてください。

**Comment by samiabat** [comment]
大変申し訳ございません。今、私は分かる
助けてくれてありがとう！
もう二度とこんなことはしません
