### ISSUE TITLE
辞書の形式に関しての意見

### ISSUE THREAD

**Issue by misogihagi** [VOICEVOX/voicevox_engine#1055]
#715 

にも関連してですが、
辞書が使いづらいです。

MeCabの辞書に準拠しているかと思えばコストが抜けています。（参考：https://github.com/taku910/mecab/blob/master/dic.html#L86）

MeCab形式で置いてある辞書もあるのでそれを使いたいです。

**Comment by Hiroshiba** [comment]
なるほどです！！

mecab準拠にすると、mecabを知らない大多数の人にとって使いづらくなってしまいます。
とはいえ現状だと辞書に機能が足りないと思います。

少し議論を深められると嬉しいです。
どのようなことを、なぜ実現したく、どうすれば解決可能でしょうか。
VOICEVOXにとってのメリット・デメリットも教えてください！

**Comment by Hiroshiba** [comment]
@misogihagi どうでしょう 👀 

お返事なさそうであれば、issueをいったんcloseしていろんな方のコメントをお待ちするのもありかもです！

**Comment by misogihagi** [comment]
@Hiroshiba 
voicevoxでは英語をそのまま読めず、アルファベットをそのまま読み上げてしまいます。
適当に探したら困っている人を他にも見つけました→https://qiita.com/fwatty/items/c9655188b41b55b23459

対策としては英語が出るたびに辞書に単語とその読み方を追加するのが挙げられます。

今の所voicevoxでメンテしている辞書がない（はず）のでunidicなどの外の辞書を使うことになると思います。
そこのところの手引きもあったほうがいいとは思いますが…

元のデータファイルはmecab形式なのでそれをインポートするときはvoicevoxの辞書というよりはmecabの形式のほうが連携しやすいと思いました。

**Comment by sabonerune** [comment]
VOICVOXの辞書はOpenJTalkのものを使っています。
これはNAIST-JDICにアクセント情報を追加したものでunidicとは品詞体系等が異なるためそのまま使うことができないはずです。

**Comment by Hiroshiba** [comment]
@misogihagi なるほどです！！　詳しくありがとうございます。
英語をなんとかしたい気持ちは結構あります。

mecab形式の辞書→VOICEVOXのユーザー辞書の変換ツールがあると良さそうなのかなと思いました。
ちょっとVOICEVOXとしてメンテするのは難しいかも知れませんが、変換ツールを作るサポートであればできるかもしれません。

costに関してはpriorityに変えています。このあたりです。
https://github.com/VOICEVOX/voicevox_engine/blob/c75b657a5c53feafaba418aa99ed4d9359991ffb/voicevox_engine/user_dict/user_dict.py#L179
ちなみにこれは元の辞書が変わった場合costが変わってしまうので、prioirtyとして独自に管理することで将来の辞書変更に備えたためです。

---

@sabonerune さんもありがとうございます。
たしかにアクセント位置がない場合は難しいことを考慮できていませんでした、助かりました 🙇

**Comment by takana-v** [comment]
> unidicなどの外の辞書を使うことになると思います。

現状のVOICEVOX（というかOpenJTalk）は、NAIST-jdicとUniDicを両方使っています。
（以下のnaist-jdic.csvとunidic-csj.csvが該当のファイル）
https://github.com/VOICEVOX/open_jtalk/tree/1.11/src/mecab-naist-jdic

> 事情があってpriorityに変えています。

こちらに関してですが、一般ユーザーにとってコストという概念は理解が難しいため、分かりやすいpriorityにしたという理由もあった記憶があります。

> MeCab形式で置いてある辞書もあるのでそれを使いたいです。

default.csvに書かれた内容は、自動的にユーザー辞書としてコンパイルされて読みの推定に利用されます。
https://github.com/VOICEVOX/voicevox_engine/blob/master/default.csv
そのため、default.csvにOpenJTalk形式の辞書を書き込むことで、一応実現可能です。
（これは意図された機能ではないため、推奨はしません）

なお、MeCab形式の辞書をOpenJTalk形式の辞書に変換するためには、Mecab形式の辞書データの後ろに、以下の情報を付け足す必要があります。
`アクセント核/モーラ数, アクセント結合規則`
つまり、全て書くと、以下のようになります。
`表層形,左文脈ID,右文脈ID,コスト,品詞,品詞細分類1,品詞細分類2,品詞細分類3,活用型,活用形,原形,読み,発音,アクセント核/モーラ数,アクセント結合規則`

アクセント核位置については[tdmelodicのマニュアル](https://tdmelodic.readthedocs.io/ja/latest/pages/introduction.html)、アクセント結合規則については[UniDicのマニュアル](https://clrd.ninjal.ac.jp/unidic/UNIDIC_manual.pdf)を読むと理解が深まるかもしれません。

**Comment by Hiroshiba** [comment]
@takana-v さん、詳しくありがとうございます！！

必要性ですが、一旦現状のままで進める形が良いのかなと思いました。

* アクセントがない場合辞書として使えないので、mecabの辞書がそのまま使えないのは問題がない
* cost→priorityにしているのは結構良い仕様だと考えている
* 仮にmecabからVOICEVOX用辞書に変換するコードを実装する場合、独自に作ってもそこまで難しくない

ということでcloseの方針が良いのかなと思いました！
議論ありがとうございます！！

**Comment by misogihagi** [comment]
もともとは辞書の形ではなく英単語をそのままアルファベットを読み上げることでしたが…
別のissueに立てるorもう立っているのであればcloseでいいです
