### ISSUE TITLE
Engine OSS ガバナンス体制が知りたい

### ISSUE THREAD

**Issue by tarepan** [VOICEVOX/voicevox_engine#1056]
## 質問の内容
概要: VOICEVOX engine OSS のガバナンス体制、特にレビュー体制が知りたい

有用な pull request が review 待ちで「レビュー手伝えるけどどうしたもんか」と感じるケースがしばしばある。  
reviewコメントを残すこと自体は可能であるが、どのレベルのreviewをすべきか/しないべきかのドキュメントが存在しない。  
例えば一般コントリビュータがしうるreviewには「問題点指摘」「改善案提示」「author修正要望」「approve」など様々あるが、OSSによってはそもそも一般コントリビュータによる review を望んでいないものもある。  
ゆえに私は安全側に倒して（メンションで求められない限り）レビューを行っていないが、同様の一般コントリビュータがいる可能性がある。  

このような背景から、VOICEVOX engine OSS のガバナンス体制（特にレビュー体制）を知りたいです。  
特に以下の項目について明確化されていると嬉しいです：  

- ガバナンス一般
  - OSSでのロールは何があるか（メンテナ？ 指定レビュア？ ロール無し？）
- レビュー
  - assignされていない人によるレビューを推奨するか（推奨 / 自由 / 控えめ希望 / 禁止）
  - approve 可能なロールはなにか（メンテナonly？ Reviewロールがある？ 誰でもreviewでLGTMすればapprove?）

**Comment by Hiroshiba** [comment]
issue 作成ありがとうございます！

approveやコメントは今のところ自由です！
何人かの方にはレビュワーメンバーとしてレビューをお願いさせていただいています。
メモ書き程度なのですがこちらにちょっとした詳細があります。（少し現状と違ってるかもです）
https://github.com/VOICEVOX/voicevox_project/tree/main/docs

参考になれば！！

**Comment by tarepan** [comment]
- ロール関係無くレビュー (approve/comment) 自由
- ガバナンス体制は VOICEVOX project 側で管理

と理解しました。非常に参考になりました、ありがとうございます！
