### ISSUE TITLE
長期未再現バグの取り扱い

### ISSUE THREAD

**Issue by tarepan** [VOICEVOX/voicevox_engine#1063]
## 質問の内容
概要: 長期未再現バグを報告した issue の取り扱い方針が知りたい  

バグレポート issue のいくつかは次の状態になっている：  

- 長期未解決
- 他利用者の再現報告無し

例えば #377 (2022.5 ~) や #527 (2022.12 ~) が挙げられる。  

VOICEVOXがアクティブに開発されている（バグ源を気づかず消しうる）ことや、GPU等を利用する関係で特殊な環境原因が発生しやすいことを考慮すると、これらのバグが再発・解決する見込みは低いと考えられる。  
「バグ」タグ付きの open issue はそれなりに管理コストが掛かる（例: 新規コントリビュータが着手できるか検討に時間を使ってしまう、バグタグをそもそも重視しなくなる）ため、何らかの対応が必要である。  

1つのやり方として、再現不能バグは一定時間後に「unresolved」のようなタグを付けて close する運用がありうる。  
別の考え方として、未解決なのだから open でずっと置いておく、という方向性もありうる。  

このような背景から、長期未再現バグを報告した issue の取り扱い方針が知りたいです。

**Comment by Hiroshiba** [comment]
issue 作成ありがとうございます！

確かに課題に感じました。再現できていないバグを新規参入の方が時間をかけて読んだり、そもそもバグタグが重視されなくなるのはよくさそうです。

個人的には再現不能から1ヶ月ほど経過したらメンテナorレビュワーによりcloseするのが良いかなと思いました。
本来は Organization 全体として OSS の方針を取り決め、そこから意思決定するべきですが、時間かけて考えるのはしばらくコストを割けなさそうなので、えいやで決めちゃうのが良いかなと。

もしよければ @y-chan さんの意見もお聞きできれば･･･！

**Comment by tarepan** [comment]
特に反対意見等ないようですので、

暫定方針「再現不能から1ヶ月ほど経過したらメンテナorレビュワーによりclose」  

@Hiroshiba  
とする感じで良いでしょうか？

**Comment by Hiroshiba** [comment]
@tarepan すごく良いと思います！！
ありがとうございます！！！
