### ISSUE TITLE
asyncにできるところをasyncにして高速化する

### ISSUE THREAD

**Issue by sevenc-nanashi** [VOICEVOX/voicevox_engine#1071]
## 内容

タイトル通りです。具体的には`GET /speaker_info`あたりが該当すると思います。

### Pros 良くなる点

- 速くなる

### Cons 悪くなる点

- ないはず？

### 実現方法

aiofilesとかを使う？

## VOICEVOXのバージョン

0.?.0

## OSの種類/ディストリ/バージョン

- [ ] Windows
- [ ] macOS
- [ ] Linux

## その他

（なし）

**Comment by tarepan** [comment]
#1073 でのチャレンジにより、定量指標を用いた高速化評価が必要だと明確化されました。  
本 issue の方向性としては「asyncにできるところをasyncにして高速化」の前段階として「async の価値を測るための速度計測実装」が入りそうですね。

**Comment by Hiroshiba** [comment]
高速化する前にまず測定という鉄則をもとにすれば、たしかにまずは計測可能にするのが大切そうかもですね！
まあ知識があればわりと測定せずとも良いのですが、Pythonのasyncに関する知識がおそらく誰にもないという感じなので…。

---

これはこのissueと直接関係ないのですが、ちなみに @tarepan さんがself assignedされてる意図って「取り組みます」という意思表明であってそうでしょうか？
もしかしたら違うかもと思い始めたのでお聞きした次第です🙇

**Comment by tarepan** [comment]
> self assignedされてる意図  

「issue を主体的に前に進める」という意思表明です。  
`議論中` label がついていれば「議論の進行をする」、`実装中` label がついていれば「取り組みます」ですね。

**Comment by tarepan** [comment]
> 「作業している人」  

👍  
実装者が assign されるように運用を変更します。

**Comment by tarepan** [comment]
#1134 により、無条件で async 化できる関数は全て async 化されました。  
コレ以外の関数はそれぞれ個別の事情に合わせて高速化され、async 化はその中で取りうる 1 方策という位置づけになります。  

よって async 化に主眼を置いた本 issue は resolved により close が妥当そうです。  
async に主眼を置いて更なる改善が出来そうな場合は re-open して議論深められればと思います。  
また個別関数の更なる改善もドシドシ募集しています、興味のある方は気軽に issue open してください👍️
