### ISSUE TITLE
add: パッケージ bump

### ISSUE THREAD

**Issue by tarepan** [VOICEVOX/voicevox_engine#1072]
## 内容
概要: 各種パッケージのバージョンアップ  

[判断等メモ.md#ライブラリのアップデート頻度](https://github.com/VOICEVOX/voicevox_project/blob/main/docs/%E5%88%A4%E6%96%AD%E7%AD%89%E3%83%A1%E3%83%A2.md#%E3%83%A9%E3%82%A4%E3%83%96%E3%83%A9%E3%83%AA%E3%81%AE%E3%82%A2%E3%83%83%E3%83%97%E3%83%87%E3%83%BC%E3%83%88%E9%A0%BB%E5%BA%A6)に基づく定期アップデートを提案します。

### Pros 良くなる点
- 脆弱性回避
- ビッグバンアップデートの回避

### Cons 悪くなる点
無し

### 実現方法
- step1: 開発関連（機能性に影響の無い） bump
- step2: 機能関連 bump

## VOICEVOXのバージョン
0.16.0

## OSの種類/ディストリ/バージョン
- [x] Windows
- [x] macOS
- [x] Linux

**Comment by Hiroshiba** [comment]
賛成です！！

テストがいろいろ実装された今、わりと安心してアップデートできる気がちょっとします。
pyinstaller辺りがちょっと怖いですが･･･。
