### ISSUE TITLE
add: `poetry` バージョン固定

### ISSUE THREAD

**Issue by tarepan** [VOICEVOX/voicevox_engine#1075]
## 内容
提案概要: `poetry` バージョンの厳密な固定

現在の VOICEVOX ENGINE は `poetry` のバージョンを緩く管理している：  

https://github.com/VOICEVOX/voicevox_engine/blob/0c698d6a9fcdefa5ade25a0191aba7820d5ee5e9/pyproject.toml#L63

一方で lock ファイルでは厳密に `1.6.1` を要求している：  
https://github.com/VOICEVOX/voicevox_engine/blob/0c698d6a9fcdefa5ade25a0191aba7820d5ee5e9/poetry.lock#L1411-L1413

https://github.com/VOICEVOX/voicevox_engine/blob/0c698d6a9fcdefa5ade25a0191aba7820d5ee5e9/requirements-dev.txt#L44

そして lock ファイル側は `poetry` バージョンに依存した文字列が存在しており、異なるバージョンを利用するとここに（無意味な）diffが発生する：  
https://github.com/VOICEVOX/voicevox_engine/blob/0c698d6a9fcdefa5ade25a0191aba7820d5ee5e9/poetry.lock#L1

lock ファイル形式が`poetry` バージョンに依存するという危険性は以前より指摘されており（#750）、緩いバージョン指定はこの危険性を大きくする。  

このような背景から、`poetry` バージョン固定を提案します。  

### Pros 良くなる点
- 無意味 diff の予防
- 良きせぬフォーマット変更の予防

### Cons 悪くなる点
- global 環境で多数のプロジェクトを並列開発しづらくなる

### 実現方法
- `pyproject.toml` バージョン指定の厳密化

## VOICEVOXのバージョン
0.16.0

## OSの種類/ディストリ/バージョン
- [x] Windows
- [x] macOS
- [x] Linux

**Comment by Hiroshiba** [comment]
勘違いしそうなので厳密な固定が良いと思いました！

まあたぶん全部厳密に固定した方が良い気もします。
まあ衝突した時大変ですが…。

**Comment by tarepan** [comment]
着手します。
