### ISSUE TITLE
記録: VOICEVOX ライセンス一覧

### ISSUE THREAD

**Issue by tarepan** [VOICEVOX/voicevox_engine#1084]
VOICEVOX プロジェクト傘下各レポジトリのライセンスを一覧にした。  

## 一覧表
| Repository      | Licence  |
| --------------- | -------- |
| voicevox        | LGPL-3.0 |
| voicevox_engine | LGPL-3.0 |
| voicevox_core   | MIT      |
| open_jtalk-rs   | BSD-3    |

## VOICEVOXのバージョン

0.16.0

## その他
必要があれば project へ transfer

**Comment by qryxip** [comment]
| Repository                   | License                                      |
| :-                           | :-                                           |
| voicevox                     | 第二ライセンス (all rights reserved by ヒホ) |
| voicevox\_engine             | 第二ライセンス (all rights reserved by ヒホ) |
| voicevox\_core               | プロプライエタリ [1]                         |
| ONNX Runtime, onnxruntime-rs | MIT [1]                                      |
| Open JTalk, open\_jtalk-rs   | BSD-3-Clause                                 |

[1] <https://github.com/VOICEVOX/voicevox_project/issues/24>ができたら、コアはMITになり、その代わりORTがプロプラになって
