### ISSUE TITLE
ソング未対応のコアを読み込めなくなっている

### ISSUE THREAD

**Issue by Hiroshiba** [VOICEVOX/voicevox_engine#1087]
## 不具合の内容

エンジンは過去のコアに関してある程度の互換性を保つように設計されています。
しかしソング実装のタイミングで、ソング未実装のコアライブラリを読み込めないようになっていました。
とりあえず現状のまとめをissueにしてみました。

### 現象・ログ

0.14.6などの過去のコアを読み込もうとするとエラーになる

### 期待動作

0.14.6などの過去のコアも読み込める

## その他

関連

- https://github.com/VOICEVOX/voicevox_engine/issues/303#issuecomment-1962291300

**Comment by Hiroshiba** [comment]
@PickledChair さん @takana-v さん

すみません、もしよかったらお力お借りできないでしょうか･･･ 🙇 
PythonのCDLL周りに詳しくなく･･･。

ちなみに過去のコアを配置できる場所は以前から変わらずユーザーディレクトリとかのままです！
https://github.com/VOICEVOX/voicevox_engine#%E3%83%A6%E3%83%BC%E3%82%B6%E3%83%BC%E3%83%87%E3%82%A3%E3%83%AC%E3%82%AF%E3%83%88%E3%83%AA%E3%81%AB%E9%85%8D%E7%BD%AE%E3%81%99%E3%82%8B

（自分の把握漏れなのにお願いしてしまって申し訳ないです 🙇 ）

**Comment by qryxip** [comment]
とりあえずメソッドの存在の判別は、`hasattr`でできると思います。

```console
❯ python
Python 3.8.15 (default, Nov  6 2022, 22:50:15)
[GCC 12.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from ctypes import CDLL
>>> core = CDLL("./libvoicevox_core.so")
>>> "initialize" in dir(core)
False
>>> hasattr(core, "initialize")
True
>>> "initialize" in dir(core)
True
>>> hasattr(core, "存在しないメソッド")
False
```

**Comment by PickledChair** [comment]
明後日くらいから時間ができるので、実装を担当できます

@qryxip 

> とりあえずメソッドの存在の判別は、hasattrでできると思います。

その方法で行こうと思います👍
