### ISSUE TITLE
refactor: `poetry` 関連 pre-commit を poetry 公式 hook で置換

### ISSUE THREAD

**Issue by tarepan** [VOICEVOX/voicevox_engine#1090]
## 内容
要望概要: `poetry` 関連のpre-commit コマンドを、`poetry` 公式の predefined hook で置換してリファクタリング  

[poetry-defined hooks](https://python-poetry.org/docs/main/pre-commit-hooks/)  

詳細: https://github.com/VOICEVOX/voicevox_engine/pull/1081#issuecomment-1964704259

### Pros 良くなる点
- コード簡略化（？）

### Cons 悪くなる点
無し

## VOICEVOXのバージョン
0.16.0

## OSの種類/ディストリ/バージョン
- [x] Windows
- [x] macOS
- [x] Linux

**Comment by Hiroshiba** [comment]
pre-comitに追加、ありだと思います！

ちなみに昔poetry exportを同じくpre commitで実装した際のプルリクエストがこちらです。（ thx. @FujisakiEx ！）

- https://github.com/VOICEVOX/voicevox_engine/pull/716

**Comment by tarepan** [comment]
> pre-comitに追加、ありだと思います！  

誤解を招く、紛らわしい冒頭説明でした🙇  
#1091 が新規hookの追加、本 issue は「既存 hook を poetry-provided hook で置き換えてリファクタリング」という意図です。  
冒頭説明を明瞭化しました。

**Comment by Hiroshiba** [comment]
ああ、なるほどです！！

issueタイトルだけでなんとなくわかると良いかもと思いました。コメントと同様、「（いつどこで）何をどうする」か書くと明確になりやすいかもと思いました！

「petry関連precommitをpoetry公式のものに置き換える」とかでしょうか。

**Comment by tarepan** [comment]
検討の結果、poetry 公式の predefined hook を使う場合、`.pre-commit-config.yaml` にて `poetry` バージョンの指定が必要と判明しました。  
この場合、バージョン追従忘れによる `pyproject.toml` および各種lockファイルとの整合性バグを起こしやすくなります。  

このリスクを飲んで predefined hook を導入したとしても、リファクタリングにより簡略化できるのは数行に限られます。  

メリット・デメリットを天秤にかけ、本 issue 提案は NoGo とします。

**Comment by Hiroshiba** [comment]
課題に対するNoGo、賛成寄りです！

一応バージョンが追従されてるかをGithub Actionsでテストするとかはできるかもです。
でもライブラリ更新も、poetryバージョンアップも頻度高くないので、がっつり拘らなくてと良いかなと思いました！
