### ISSUE TITLE
`cpu_num_threads`が未指定または0の場合に、論理コア数の半分をコアに渡すようにする

### ISSUE THREAD

**Issue by sigprogramming** [VOICEVOX/voicevox_engine#1092]
## 内容

現在、`cpu_num_threads`はコア（[VOICEVOX CORE](https://github.com/VOICEVOX/voicevox_core)）にそのまま渡されていて（たぶん）、「`cpu_num_threads`が未指定または0」の場合にどうなるかはコアの実装依存です。

そして現在のコアの実装は、「`cpu_num_threads`が未指定または0」の場合に物理コア数が使用されるようになっていて、一部のCPUでCPUのすべてのコアが使用されるので、[論理コア数の半分が使用されるようにするissue](https://github.com/VOICEVOX/voicevox_core/issues/756)を立てています。

エンジンも、「`cpu_numhreads`が未指定または0」の場合は、「論理コア数の半分」の値を渡すようにするのが良さそうです。

### Pros 良くなる点

- 「`cpu_num_threads`が未指定または0」の場合の挙動がコアの実装依存ではなくなる

### Cons 悪くなる点

- <s>仕様が変わる</s>

## その他

**Comment by tarepan** [comment]
## 前提: `README.md` の関連記述

```
--cpu_num_threads CPU_NUM_THREADS
                        音声合成を行うスレッド数です。指定しないと、代わりに環境変数VV_CPU_NUM_THREADSの値が使われます。VV_CPU_NUM_THREADSが空文字列でなく数値でもない場合はエラー終了します。

#### CPU スレッド数を指定する

CPU スレッド数が未指定の場合は、論理コア数の半分か物理コア数が使われます。（殆どの CPU で、これは全体の処理能力の半分です）  
もし IaaS 上で実行していたり、専用サーバーで実行している場合など、  
エンジンが使う処理能力を調節したい場合は、CPU スレッド数を指定することで実現できます。

- 実行時引数で指定する
  python run.py --voicevox_dir=$VOICEVOX_DIR --cpu_num_threads=4
- 環境変数で指定する
  export VV_CPU_NUM_THREADS=4
  python run.py --voicevox_dir=$VOICEVOX_DIR
```

## 意見
上記の通り、現在の ENGINE 仕様は `CPU スレッド数が未指定の場合は、論理コア数の半分か物理コア数が使われます。（殆どの CPU で、これは全体の処理能力の半分です）` です。  
ENGINEの観点からは、むしろ現状の実装がバグ（50%でなく100%使ってしまう）だと言えそうです。  
100%使い切りが好ましくない観点からも、明示的に50%を渡すのは効果的です。  
「バグ修正により、デフォルト設定では全スレッドの50%のみを利用するようになります」とChangeLogに書く形で納得感が得られると考えます。  
結論として、実装に賛成です。

**Comment by Hiroshiba** [comment]
@tarepan さんの意見と同感です！
50%だけ使われるのが正しい挙動だと勘違いしていたので、100%使われるのはバグだと感じます！

**Comment by tomoish** [comment]
実装を希望します。
Draft PR #1113 を作成しましたので、確認いただけると幸いです。
