### ISSUE TITLE
remove: GitHub Label `OS`

### ISSUE THREAD

**Issue by tarepan** [VOICEVOX/voicevox_engine#1097]
## 内容
要望: GitHub Label `OS` を廃止する

現在の VOICEVOX ENGINE は GitHub Label として以下の3つを運用している：  

- `OS：linux`
- `OS：mac`
- `OS：win`

この Label は issue 冒頭内の `OSの種類` を labeler Actions で自動検知して付与されている。  
この Label は各 OS 特有の issues を見分けられるように設計されていると思われる。   

しかし現在のところ、issue のほとんどが「`OS :` label 無し」あるいは「全 `OS :` label 付き」となっている。  
すなわち、現在の ENGINE は OS 固有の問題がほぼ無く、有効な label として機能していない。  

過度の label は真に必要な label を埋もらせ、また、actions 等の管理コストを一定量発生させ続ける（例: PR #831）。  

このような背景から、歴史的役割を終えた `OS :` label の廃止を提案します。  

### Pros 良くなる点
- label 単純化、可読性向上
- actions 単純化、管理コスト 0 に

### Cons 悪くなる点
- OS 固有 issues は label ベースでなく検索ベースで絞り込み

### 実現方法
- actions 廃止
- label 廃止

## VOICEVOXのバージョン
0.16.0

## OSの種類/ディストリ/バージョン
- [x] Windows
- [x] macOS
- [x] Linux

**Comment by tarepan** [comment]
現在のラベル状況を集約しました。  
影響範囲の小ささも確認できたため、反対意見が無ければ数日中に GitHub Label `OS` を廃止します。  

## 現在のラベル状況
- 2: `OS：linux`
- 0: `OS：mac`
- 0: `OS：win`
- 0: `OS：linux` + `OS：mac`
- 0: `OS：mac` + `OS：win`
- 1: `OS：win` + `OS：linux`
- 11: `OS：linux` + `OS：mac` + `OS：win`

**Comment by tarepan** [comment]
open issue に付与された GitHub Label `OS` を外し、labeler 廃止 PR を提出しました。本 PR merge 後、以下の最終段階をもって label 廃止は完了します。    

最終段階として Label そのものの削除をおこなう予定です。過去 issue に付与された label も削除されますが、上記の pros/cons に照らし、それでもなお削除が妥当と考えます。

**Comment by Hiroshiba** [comment]
返信遅くなりすみません！！
ラベルを消す判断は過去の遺産を全て消すということなので、ちょっと慎重に進めた方が良いかもですね！

僕もOSラベルは意味をなしてないなと感じてました。
影響するの全部につけるのか、OS固有な時につけるのかを判別できず、かつそれがラベリングする時とラベルを使ってフィルタする時どちらにも起こるからだと思います。
あと自分が使うPCのOSをつける人もいるのでごちゃごちゃだと思います。

他のossの運用とかも参考に調べてみました。
どれだったかわからないですが、「OS:全部」というラベルが用意されてたり、「OS:mac only」というのがかったりするのもあった気がします。

提案ですが、自動ラベルを消すかはさておき、ラベルを「OS:mac特有」「windows特有」などとするのはどうでしょうか。
「特有」意外に良い名前があると良いのですが…。

---

おそらく全リポジトリの運用も追従するのでメンテナ意見あれば🙏 @qryxip @y-chan

**Comment by Hiroshiba** [comment]
特有かどうかを判断できないのは、経験とカンで付ければ大体うまくいく気がします。
その後で間違ってることがわかれば変更すれば良いかもです。
明らかに全OSに影響あるissueに、間違えてこのラベルを付けちゃうのを防止すれば大丈夫かなと。

> 固有

なるほどです！
特有よりはわかりやすい…のかなぁ。もっと良いのがあると嬉しいかも…

ここまでの議論をChatGPT君に投げてみました。「OS依存:mac」とかなかなか良いかも？
https://chat.openai.com/share/aa0e54ac-d648-450b-b90f-753c6c78225f

**Comment by tarepan** [comment]
> 経験とカンで付ければ大体うまくいく ... 間違ってることがわかれば変更  

👍  
label が大事故を起こすことはほぼ無いので、バランスの取れたやり方だと感じます。  
経験あるレビュアが判断するということで、自動 labeler は廃止の方向性になる気がします（PR: #1111）

> OS依存:mac  

👍  
`依存` は良い言葉選びですね。「どの OS でも起きる = OS 依存性がない」となるので、誤解がかなり減りそうです。  

-------------------------------------------------------------------------
現状は以下に集約できそうです：  

- `OS` 系 label は意味明確化のうえ維持
  - `OS：mac` → `OS 依存：mac`
  - `OS：linux` → `OS 依存：linux`
  - `OS：win` → `OS 依存：win`
- label は経験あるレビュアがある程度えいやで付与
  - 自動 labeler は廃止

@Hiroshiba  
これで合意であれば私の方で label 改名を実行します、PR review の方はよろしくお願いします。

**Comment by Hiroshiba** [comment]
@tarepan 名称変更は良いと思います！
それらのラベルはもしかしたらorganization共通のやつかもなので、変更ができないかもしれません。
なんか無理そうだったらまたコメントいただけると！

自動ラベラーに関しては導入したのは実は僕ではなく @y-chan さんなので意見お待ちしたいです。

**Comment by y-chan** [comment]
すみません...!大変遅くなりました 🙇 

ラベルの改名については特に問題はないと判断しました。このまま進めて良いと思います！

自動ラベラーについてですが、実際に自動ラベラーを導入してみると、OS依存の問題が起きることはあまりなく、コントリビュートする際にチェックボックスの使い方に迷うことが増えてしまったと私も感じています。
なので、ラベラーを廃止し、レビュワー・メンテナが気づいたタイミングでOS依存ラベルを振ることで問題ないのかなと思いました！

**Comment by qryxip** [comment]
CORE側として、`OS依存`に賛成します。

**Comment by tarepan** [comment]
@qryxip  
`OS` ラベルは エディタ/エンジン/コア で独立してそうですが、どのレポジトリで labeler コケてそうでしょうか？  

![image](https://github.com/VOICEVOX/voicevox_engine/assets/19833110/610e605f-29cf-4d4e-b779-8c2590804946)
![image](https://github.com/VOICEVOX/voicevox_engine/assets/19833110/c217fc8a-ff13-438d-ab8d-b4d159512c3a)
![image](https://github.com/VOICEVOX/voicevox_engine/assets/19833110/be6b0a67-fc33-42ea-91cc-40ba87597563)

**Comment by qryxip** [comment]
コケたのはコアですが、そうですね、ラベルのリネームによってというのは私の勘違いでした。

コケたのはWindows, macOS, Linuxのどれのチェックボックスにもチェックを入れていないやつでした。labelerって元々そういうものなんですね…

<https://github.com/VOICEVOX/voicevox_core/actions/workflows/labeler.yml>

**Comment by Hiroshiba** [comment]
ラベル、よくわからないのですが、org共通じゃないかもですね…！🙇
初期値だけorgのものになるのかも…？

とりあえず自動ラベラーはエディタ側でも無くそうかなと思ってます。
（そちらはそちらでissue立てて進めるのが良さそうですが）

**Comment by Hiroshiba** [comment]
issueタイトルと結論がずれてるのでまとめときます。（こういうときタイトル変えたほうが良いのか迷いますね･･･）

https://github.com/VOICEVOX/voicevox_engine/issues/1097#issuecomment-2009528213 より

- `OS` 系 label は意味明確化のうえ維持
  - `OS：mac` → `OS 依存：mac`
  - `OS：linux` → `OS 依存：linux`
  - `OS：win` → `OS 依存：win`
- label は経験あるレビュアがある程度えいやで付与
  - 自動 labeler は廃止

エディタとコアでも同様の課題がありますが、それぞれどうするかはそれぞれにissue作って進めていきましょう！
