### ISSUE TITLE
GitHub Label 運用の明確化

### ISSUE THREAD

**Issue by tarepan** [VOICEVOX/voicevox_engine#1098]
## 内容
要望概要: GitHub Label 運用の明確化

現在の VOICEVOX ENGINE は issue のタイプと進行に関わる以下の label を運用している：  

- タイプ
  - `バグ`
  - `機能向上`
- 状態
  - `要議論`: 実行する前に議論が必要そうなもの

現 issues を整理する中で、これらの立ち位置に不明瞭さがあり、label の変更を控えている。  

このような背景から、label 運用の明確化を要望します。  
具体的には以下の項目を明確化したいです：

「① `機能向上` は以下のいずれの変更予定 issues に対して付与するのか」  

- ユーザー向け機能追加
- ユーザー向け仕様変更
- 内部向け機能追加
- テスト追加
- リファクタリング

「② `要議論` は以下のいずれのタイミングで外すべきか」  

- 問題を解くべきと確定したとき
- 問題に対する解答の実装議論が確定したとき
- PR着手の宣言があったとき

### Pros 良くなる点
- label 意味明確化
- open issues の状態明確化

### Cons 悪くなる点
無し

### 実現方法
- label 明確化
- open issues の label 再付与

**Comment by Hiroshiba** [comment]
issue化ありがとうございます！！

ラベルの扱いに関して、大前提としてあまり決まっていないです。
現状のラベル構成が最高だとも思っておらず、より良くしていきたい気持ちもあります。
雰囲気で定めてしまうと逆にメンテナンス性を下げかねないので過去事例を調べた方が良さそうに思うのですが、調査と思考にリソースが割けてない感じです。

---

> 「① 機能向上 は以下のいずれの変更予定 issues に対して付与するのか」
> 
> ユーザー向け機能追加
> ユーザー向け仕様変更
> 内部向け機能追加
> テスト追加
> リファクタリング

全部に対して付けています。
issueは大体質問・バグ報告・それ以外の提案にわかれると感じていて、とりあえず３つ目にこのラベルをくらいで運用されていると思います。
この仕組みが最も良いとは思いませんが、かといって妥当な方法を考える時間が･･･という感じです。

> 「② `要議論` は以下のいずれのタイミングで外すべきか」  
> 
> - 問題を解くべきと確定したとき
> - 問題に対する解答の実装議論が確定したとき
> - PR着手の宣言があったとき

議論が完了したタイミングで外すのが良いと思います。
このラベルが外れたとき、着手かcloseが可能になるというニュアンスです。

**Comment by tarepan** [comment]
回答ありがとうございます！  
①②に基づき open issues の label 整理を進めます。  
運用上の課題が出たら別 issue にて改善策を提案させて頂く予定です。
