### ISSUE TITLE
製品版音声合成モデルのアップデート履歴

### ISSUE THREAD

**Issue by tarepan** [VOICEVOX/voicevox_engine#1101]
## 質問の内容
質問概要: 製品版音声合成モデルのアップデート履歴が知りたい

現状の ENGINE は後方互換性を重視し、過去の CORE バージョンをサポートし続けている。  
これはユーザーの使用感保護（キャラの発話が一定であり続ける）の観点で非常に重要である。  

一方で、複数 CORE バージョンの併存は ENGINE の大きなバグ源になっている。  
CDLL の関係でほぼテストが無く、実際に #1087 にてエンバグしている。  

ところで、CORE バージョンはあくまで CORE のバージョンであり、製品版音声合成モデルの内部的バージョン（発話のアップデート）とは理論上別になりうる。すなわち、合成モデル自体は維持されている（例: Song が追加されているが TTS はずっと同じモデル、キャラは追加されているが既存キャラはずっと同じ）ケースが有りうる。  
この場合、過去 CORE バージョンのサポートを打ち切ってもユーザー使用感に影響がない。  
ここの簡略化は大きなバグ源を1つ消すことに繋がる。  

このような背景から、製品版音声合成モデルのアップデート履歴が知りたいです。   

## VOICEVOXのバージョン
0.16.0

**Comment by Hiroshiba** [comment]
issue作成ありがとうございます！
ちょっとアプデ履歴をまとめるのは大変なので、一旦すぐお答えできるとこを書きます🙇

声の破壊的変更は何度か行われています。同じスタイルIDで、別の音声が出てくる感じです。
最近だとこちらとか。
https://x.com/voicevox_pj/status/1741021305007489030?s=20

スタイルの更新履歴は一応アプデ履歴に自然言語で書いてあります。エンジンの変更履歴は最近書けるようになった関係で、更に古い履歴はエディタ側にだけ書いてます。
いつどのスタイルが変わったかは追いづらい形で管理してしまっているので、より正確な履歴を出すのはなかなか大変な状況です。

**Comment by Hiroshiba** [comment]
@tarepan 

> 現段階では「Wrapper/Adapter の複雑化を甘んじて受け入れ、COREの古いバージョンまでサポートしていく」という方針で合っているでしょうか？

ですね･･･！

あまりにも超複雑になりそうだったら話は変わってくるかもと思っています。
まだ全然考えられてないのですが、[別のところ](https://github.com/VOICEVOX/voicevox_engine/issues/709#issuecomment-2002433136)で出てたCUDAのバージョンの話を考えると、課題が超複雑になりそうなので整理＆議論が必要かもと少し感じています。

話がややこしくなってしまうかもですが、ライブラリのインストール機能も検討されています。

- https://github.com/VOICEVOX/voicevox_project/issues/21

「ライブラリ」というのはコアとは異なる単語で、抽象的にしています。
エンジンによってはVOICEVOXのようにコアがない時もあるためです。
今は「複数のコアを持つ」設計ですが、例えば「コアとCUDAなども含んだ動的ライブラリ群」のことを「ライブラリ」扱いして、「複数のライブラリを持つ」設計にしてあげる設計もありかも･･･？

---

あ、とりあえずこのissueはクローズできるのかなと思いました！
