### ISSUE TITLE
Settingクラスのcors_policy_modeフィールドの型をCorsPolicyModeのみに制限する

### ISSUE THREAD

**Issue by tomoish** [VOICEVOX/voicevox_engine#1102]
## 内容
現在、`Setting`クラス(./voicevox_engine/setting/Setting.py)では`cors_policy_mode: CorsPolicyMode`となっており、`CorsPolicyMode`の型ヒントが与えられている。
しかし、このフィールドはEnumのvalueである`str`型の値をそのまま受け入れることができ、これにより型安全性が低下する可能性がある。

実際、起動時の引数で`cors_policy_mode`を指定した際は`CorsPolicyMode`型となっており、設定ファイル経由で指示した場合は`str`型となるため、この値の参照時に場合分けが必要となる。

### Pros 良くなる点

`'all'`, `'lacalapps'`を取り出す時に `cors_policy_mode.value`で統一的に参照できるようになる

### 実現方法

`cors_policy_mode`フィールドを`CorsPolicyMode`型のみに制限する。

**Comment by tarepan** [comment]
> このフィールドはEnumのvalueであるstr型の値をそのまま受け入れることができ、これにより型安全性が低下する可能性がある

👍  
正しい指摘です。  
例えば `SettingLoader` は `cors_policy_mode` 引数に `Any` 型の値を渡しています。   
https://github.com/VOICEVOX/voicevox_engine/blob/c97806bd1ea0478763b0f74f5e18635068c452e3/voicevox_engine/setting/SettingLoader.py#L30-L33

---------------------------------------------------------------

> この値の参照時に場合分けが必要となる  

型システムではなく、値アクセスの段階ではこのような問題は起きないと認識しています。以下参考コードです：  
```python
from enum import Enum
from pydantic import BaseModel, Field

class CorsPolicyMode(str, Enum):
    all = "all"
    localapps = "localapps"

class Setting(BaseModel):
    cors_policy_mode: CorsPolicyMode = Field(title="リソース共有ポリシー")
    class Config:
        use_enum_values = True

s1 = Setting(cors_policy_mode=CorsPolicyMode.all)
print(s1.cors_policy_mode)
# all

s2 = Setting(cors_policy_mode="all")
print(s2.cors_policy_mode)
# all
```
これは Pydantic の暗示的バリデーション & 型変換によって実現しています。

**Comment by tomoish** [comment]
@tarepan さん、返信ありがとうございます。
ご指摘のとおり、参考コードを実行し、どちらも`str`型のallであることを確認しました。

経緯として、#963 の`/setting`画面で表示される`cors_policy_mode`がサーバー起動時と異なることがあるという問題に取り組むために`Setting`周りの実装をみておりました。

`run.py`の1618行目以降に以下のコードを追加して、以下のコマンドで起動したところ後に続くような結果が得られました。

コマンド: `python run.py --enable_mock --cors_policy_mode all`

追加コード
```
print("cors_policy_mode from setting file: ", settings.cors_policy_mode)
print("type of cors_policy_mode from setting file: ", type(settings.cors_policy_mode))
print("cores_policy_mode from args: ", cors_policy_mode)
print("type of cors_policy_mode from args: ", type(cors_policy_mode))
```

使用した設定ファイル
```
allow_origin: "*"
cors_policy_mode: all
```

結果
```
cors_policy_mode from setting file:  all
type of cors_policy_mode from setting file:  <class 'str'>
cores_policy_mode from args:  CorsPolicyMode.all
type of cors_policy_mode from args:  <enum 'CorsPolicyMode'>
```

設定ファイルからロードした時に`cors_policy_mode`が`str`になってしまうことが問題だと考えていたのですが、
ご指摘のコードの通りだと、 Pydantic の暗示的バリデーション & 型変換によって`str`型となるように確認できるので、argsによって指定したときに型が`enum 'CorsPolicyMode'`となっていることが問題なのでしょうか。
よろしくお願いします。

**Comment by tarepan** [comment]
> `run.py`の1618行目以降に以下のコードを追加して、以下のコマンドで起動  

👍  
提示頂いたコード追加により、同様の出力を確認できました。  
@tomoish さんの指摘する「参照時に場合分けが必要となる」が実際に起きていますね。  

------------------------------------------------

> 設定ファイルからロードした時に`cors_policy_mode`が`str`になってしまうことが問題

👍  
この認識で正しいです。  
`settings.cors_policy_mode` は `CorsPolicyMode` 型だと型推論されます。しかし実行時に Pydantic が型推論をすり抜ける形で実行時暗示的型変換（`CorsPolicyMode` -> `str`）し、この問題が起きているようです。  

------------------------------------------------

上記の参考コードを提示した経緯は以下の通りです：  

> このフィールドはEnumのvalueである`str`型の値をそのまま受け入れることができ  

こちらを受けて「`Setting(cors_policy_mode=CorsPolicyMode.all)` と `Setting(cors_policy_mode="all")` は入力違えど参照時には同じだったような」と考え、提示しました。  

------------------------------------------------

@tomoish さんの `run.py` の例で分かったように、参照に場合分けが必要なるのは入力が異なるときではなくオブジェクト生成手順が違う（`Setting(cors_policy_mode="all").cors_policy_mode` or `CorsPolicyMode("all")` ）ときでした。  
ゆえに私の上記の参考コードはちょっとズレた話をしていて、 @tomoish さんの「設定ファイルからロードした時に`cors_policy_mode`が`str`になってしまうことが問題」が結論として正しいです。

**Comment by tomoish** [comment]
@tarepan さん、返信ありがとうございます。

曖昧な表現となってしまい申し訳ありません。
こちらも最初に投稿する段階で動作確認したコードをつけておくべきでした。

---
> この認識で正しいです。
settings.cors_policy_mode は CorsPolicyMode 型だと型推論されます。しかし実行時に Pydantic が型推論をすり抜ける形で実行時暗示的型変換（CorsPolicyMode -> str）し、この問題が起きているようです。

確認いただきありがとうございます。
Draft PR #1103 にて、この問題の解決策を提案しました。
お時間があるときにご確認いただき、フィードバックをいただければ幸いです。
