### ISSUE TITLE
remove: GitHub Label `優先度：低`

### ISSUE THREAD

**Issue by tarepan** [VOICEVOX/voicevox_engine#1104]
## 内容
要望概要: GitHub Label `優先度：低` を廃止する  

VOICEVOX ENGINE は issue の着手優先度を示す GitHub Label として `優先度：低` `優先度：中` `優先度：高` を運用している。現在 open な issues に対してこれらの Label が以下の配分で付与されている：  

- `優先度：高`: 2
- `優先度：中`: 5
- `優先度：低`: 22
- Label無し: 39

`優先度：高` は hotfix系、`優先度：中` は重要課題を中心に付与されており、一定の目印になっている。  

一方 `優先度：低` はそれ以外の全てに付与され、かつ、ここ半年ほどの新規 issues にはほぼ付与されていない。  
ここ半年で `優先度：低` 無しに起因する運用上の問題が起きていないため、`優先度：低` は現状積極的な役割を果たしていないと思われる。  
過度の label は真に必要な label を埋もらせ、また、新規コントリビュータが `優先度：低` と「Label無し」の関係に困惑するリスクを増大させる。  
歴史的役割を果たし現状メリットがなく、コストは今後もかかり続ける機能を廃止することは、ENGINE の長期的発展に資する。  

このような背景から、GitHub Label `優先度：低` の廃止を提案します。  

### Pros 良くなる点
- Label 明瞭度改善
- 管理コスト減

### Cons 悪くなる点
無し

### 実現方法
- `優先度：低` Label 廃止

## VOICEVOXのバージョン
0.16.0

**Comment by tarepan** [comment]
## 現在のラベル状況
2023-08-06 までの issue (~ #654) には `優先度：低` がおおよそ付与され、それ以降は付与がほぼなくなっている。  
それ以降の open issue に付与されているのは以下のみ：  

- #759
- #760
- #1051

## 方向性
上記のラベル状況整理により、「ラベル無し」と `優先度：低` は単なる時期的違いであることが示唆された。  
また、上記のラベル状況に基づいてラベル復元（切り戻し）が可能になった。  

これらに基づき、反対意見が無ければ数日中に open issue に付与された GitHub Label `優先度：低` を除去します。

**Comment by tarepan** [comment]
open issue に付与された GitHub Label `優先度：低` を外しました。  

最終段階として Label `優先度：低` そのものの削除をおこなう予定です。過去 issue に付与された `優先度：低` も削除されますが、上記の pros/cons に照らし、削除が妥当と考えます。  

@Hiroshiba  
`優先度：低` 削除の方向で良いでしょうか？

**Comment by Hiroshiba** [comment]
べき論でいうと「優先度：低」ラベルはあるべきだと思います！
というのもラベルが振られてないだけなのか、判断された上でその優先度なのかがわからないためです。
（ただまあそのことを意識せずに今までいたので振っていないことが多々あったのは事実ですが）

ただまぁラベルを必ず1つ振らないといけなくなるわけで、その管理コストがコントリビューターの方が見た時の気持ちに見合うのかはちょっとわからないのが本音です。
どうすべきですかねぇ･･･。

ちょっとそれとは別なのですが、優先度ラベルももっと分かりやすくできるだろうなと思いました。
そもそもやりたいこととしてはmust/should/want/canのどれなのかがわかるようにしたい感じかもです。
特に「中」はちょっと分かりにくいかも？　とはいえmust/should/want/canもなんか分かりにくいですが･･･。

**Comment by tarepan** [comment]
> べき論でいうと「優先度：低」ラベルはあるべき  

👍  
同意です。  
べき論でいうと「充分なリソースがあるべき」であり、その前提であれば本ラベルは有益だと考えます。  

> 管理コスト ... どうすべきですかねぇ  

上記で「ここ半年ほどの新規 issues にはほぼ付与されていない」「ここ半年で `優先度：低` 無しに起因する運用上の問題が起きていない」と述べた通り、メリット・必要性がそもそも大きくない（canレベルのメリット）のが現実です。  
そのうえで現実としてリソース不足であり、付けられていないゆえの混乱リスクが顕在化しています。  
理想上メリット < 現実デメリット になっているため、現実論でいうと廃止が妥当かなと思います。  

------------------------------------------------------------

> 優先度ラベルももっと分かりやすく ... そもそもやりたいこととしてはmust/should/want/can

なるほどです。重要度の label だったんですね。  
てっきり着手順序用の label かと思っていました（「優先」度なので「優先」順位の話かと）。  

（just ideaですが）#1112 で定義される「必要性議論」段階において、必要性が明確になったらその大きさに応じて must/should/want/can label を付ける、とかだと、label の立ち位置がわかりやすくなりそうな気はします。  
大中小は温度感伝わらないかもですね…。

**Comment by Hiroshiba** [comment]
> 「優先度：低」ラベル

なるほどです。いったん「優先度：低」は無しで良いかなと思いました。
ただこれはorgレベルでラベルが存在しているので、エンジンではしばらく付けない運用になると思います。

> なるほどです。重要度の label だったんですね。
てっきり着手順序用の label かと思っていました（「優先」度なので「優先」順位の話かと）。

確かに、優先度と書いてましたが、感覚は重要度かもです。
ラベルを変えるなら「重要度：Must/Should/Want/Can」が無難そうに感じました。
無理やり日本語にすると「重要度：緊急/早めに/あると嬉しい/余裕があれば」とかですかね。うーん。

**Comment by tarepan** [comment]
> いったん「優先度：低」は無し ... エンジンではしばらく付けない運用  

👍  
「`優先度：低` label 運用は中止、label 完全廃止/削除は NoGo」ですね。  

この運用変更により、今後の優先度系 label は  

- `優先度：高` : hotfix やリリース優先 pending 事項など、最重要
- `優先度：中` : `高` よりは低いが重要と考える事項

の 2 種に絞られます。

---------------------------------------------------------
> ラベルを変えるなら  

より詳細な重要度運用を行う際にこの方向性を取る、のに同意です。  
現状では label 運用を軽くする方向かと思いますので、一旦は名称変更無しがいいかなと思います。  

---------------------------------------------------------
上記の方向でよいでしょうか？  
OKでしたら resolved ということで issue close 可能です。

**Comment by Hiroshiba** [comment]
はい、その方針で…！

もし方針にコメントあればいつでも頂けると…！ @y-chan

**Comment by qryxip** [comment]
VOICEVOX全体の話として、CORE側としては異論は無いです。運用停止のみでも削除でもどちらでも。

**Comment by Hiroshiba** [comment]
エディター側も別に消去する形で問題なさそうな印象です。
タイミング見つけて削除していってもいいかもですね！
