### ISSUE TITLE
議論リソースを効率運用する issue 進行方針

### ISSUE THREAD

**Issue by tarepan** [VOICEVOX/voicevox_engine#1112]
## 内容
提案概要: 議論リソースを効率的に活用するため「長期議論停滞 issue を close」する issue 進行方針を採用したい

VOICEVOX ENGINE では多様な機能実装・仕様変更が自由に提案され、これらはより良い ENGINE を作る基盤である。  
一方で、限られたリソースを効率よく運用しリソース制約の中でより良いプロダクトを作れることも重要である。  

現在多くの issue では「アイデア提案 → 必要性議論 → 設計 → 実装者募集 → 着手宣言 → PR」の段階を踏んでいる。  
前半の「アイデア提案 → 必要性議論 → 設計」では議論リソースが必要であるため、議論が途中で止まる issue がそれなりにあり、これらは open issue として存在し続けている。  
これら open issues の一部は「当時必要性があったが、現在では必要性が下がった」という状況にある。新しいコントリビュータがこれらに「open issue だから取り組んでみるか」と手を付けると、結果として低優先度の課題を解くことになる。不幸なケースだと「提案してもらったけど、状況が変わったので採用できないかもです…」となる（なった）。  
これは議論リソースの効率的運用とは言えない。  

この問題は長期議論停滞 issue が open であり続けることに起因している。  
昨今の運用体制改善により、議論で必要性が認められた issue は close してもロードマップ (#1106) にリンクを残す等の対応が可能であり、open であり続けるメリットは減っている。  
ENGINE 運用開始から30ヶ月以上が経ち、古い open issues が目立ち始めたこのタイミングで、上記のメリットとデメリットを天秤にかける価値があると考える。  

このような背景から、「長期議論停滞 issue を close」する issue 進行方針を提案します。  

より具体的には次の運用方針案を考えています：  

- 「必要性議論」がまとまらなかった長期停滞 issue: アイデアに感謝して close
- 「設計」が固まらず長期停滞した issue: ロードマップへリンクして close
- 「実装者募集」まで進行した issue: [`実装者募集`](https://github.com/VOICEVOX/voicevox_engine/issues?q=is%3Aissue+is%3Aopen+label%3A%E5%AE%9F%E8%A3%85%E8%80%85%E5%8B%9F%E9%9B%86) label を付けて open 放置OK (レビュア権限で既に実験中)

### Pros 良くなる点
- 議論リソースの効率的運用
- 必要性が認められた議論途上 issue のロードマップへの集約による一覧性向上

### Cons 悪くなる点
- 提案管理場所の分散（issue only → issue + ロードマップ)

### 実現方法
- 議論
- レビュアー向け情報への記載

**Comment by Hiroshiba** [comment]
提案ありがとうございます！
まとまっていて課題点がすごくわかりやすかったです。

ちょっと論点と異なるかもなのですが、近いところに問題意識を持っています。まずそのあたりをすり合わせできればと。

> 新しいコントリビュータがこれらに「open issue だから取り組んでみるか」と手を付けると、結果として低優先度の課題を解くことになる。不幸なケースだと「提案してもらったけど、状況が変わったので採用できないかもです…」となる（なった）。
> この問題は長期議論停滞 issue が open であり続けることに起因している。

これは「長期議論停滞 issue」だけでなく、議論が終わったものでも起こり得るなと感じました。
長いことopenになっているissueの棚卸しも必要かもですね。

> より具体的には次の運用方針案を考えています：
> 「必要性議論」がまとまらなかった長期停滞 issue: アイデアに感謝して close
> 「設計」が固まらず長期停滞した issue: ロードマップへリンクして close
> 「実装者募集」まで進行した issue: [実装者募集](https://github.com/VOICEVOX/voicevox_engine/issues?q=is%3Aissue+is%3Aopen+label%3A%E5%AE%9F%E8%A3%85%E8%80%85%E5%8B%9F%E9%9B%86+sort%3Aupdated-desc) label を付けて open 放置OK (レビュア権限で既に実験中)

ラベルの運用や名称は一旦置いといて、大枠良さそうな感じがしました！
途中で必要性が下がったとかもあると思うので、必ずしもロードマップへリンクする必要はないなど細かい部分が実運用時に異なりそうです。

---

本当はコアやエディタと強調して同じ方針を取った方が良いのですが、一旦実験的にということでエンジンをこの運用で回すというのはどうでしょうか？

実現方法としてのアイデアは、フローチャートをmermaidで作ってみたり、ロードマップを将来的にProjectやDiscussionに移動させたりとかも楽しそうです。
あとはどのラベルがどのクラスに属するかわからないので、フェーズを分けるなら全部フェーズだとわかるようにしとくと初見時の理解の助けになるかもですね！

という感じで煮詰めていくのが良いのかなと思いました。
ラベル等の提案はたしかいろんなissueに散らばっているのでここで議論すべきかはわかりませんが･･･！

cc メンテナ @y-chan @qryxip

**Comment by Hiroshiba** [comment]
フロー図ありがとうございます！

設計が含まれてるの面白いですね。そこも実装者の方に結構おまかせしたりしていました。
僕たち側で手が回らなくなったらそこも募集かけても良いかも。

「設計するまでもないもの」とか「issue作ってくださった方がそのまま取り組んでくださる場合」とかは設計や実装者募集をスキップできるかもですね！
必要性判断も待たない方が良い時もあるかもと思いました。発見された方がノってる時とか。まあその代わりプルリクを棄却させていただくこともあるかもって感じですが･･･。

ラベリングは必要性議論か設計のときにって感じですかね！

**Comment by tarepan** [comment]
> 設計 ... そこも実装者の方に結構おまかせしたり ... そこも募集  

👍  
ラフな設計をメモ的にするに留めて `設計` 段階を終わらせるのも全然ありだと思います。  
ケースバイケースで柔軟にやれればと。  

> 設計や実装者募集をスキップ  

👍  
issue 提案者が「実現方法」節でキッチリ設計してくださるケースや、issue 提案時点で draft PR を付与してくれる（着手宣言している）ケースも多々あります。  
その場合は「`設計` や `実装者募集` をクリアして現在`実装` 状態」と単純に理解して良いと思います。  

フロー図の意図は「ウォータフォール的に順番に達成すべき段階」ではなく「issue の移り変わる状態を示した状態遷移図」というイメージです。   
なのでおっしゃるとおり、「`必要性議論` をスキップとはけしからん！」ではなく「初っ端から `実装中` 状態ね、了解」な温度感で向き合うのがいいと考えます。棄却パターンも「頂いた PR のメリットを慎重に判断したいので `必要性議論` に立ち戻って議論しましょう」でコントリビュータの理解を得られると思います。  

-------------------------------------------------------
> ラベリングは必要性議論か設計のときにって感じですかね！  

👍  
同意です。  
必要性が見えたら `優先度` 系 label が付与できると考えます。 `OS依存` はスコープが理解でき次第順次で。  

------------------------------------------------------

状態遷移の同意がある程度取れたと思いますので、`pendding` / `not_planned` 行き（長期停滞 issue 処理）の遷移条件を議論できればと思います。  

- 最終コメントから何日で遷移判定とするか
- 日数は issue の状態で変えるか（例: `必要性議論` は 14日待機、`実装者募集` は半年待機）

が私がパッと気になる論点です。

**Comment by Hiroshiba** [comment]
> フロー図の意図は「ウォータフォール的に順番に達成すべき段階」ではなく「issue の移り変わる状態を示した状態遷移図」というイメージです。

なるほどです！
状態遷移がいくつかスキップされることもあるという考え方で納得です。まあそもそもそんなに厳格に進める雰囲気じゃないという感じですかね！

> 棄却パターンも「頂いた PR のメリットを慎重に判断したいので 必要性議論 に立ち戻って議論しましょう」でコントリビュータの理解を得られると思います。

確かにです。となるとこのフロー図をどこかで案内すると良さそうですね。
まあでも最初はとりあえずこの流れに従って活発にエンジンissueにラベリングを振る僕たち（ @Hiroshiba と @tarepan）が動いてみて、良さそうだったら他のレビュアの方や他のリポジトリでも同じ流れにしていけるとよさそうかなと。

---

> 状態遷移の同意がある程度取れたと思いますので、`pendding` / `not_planned` 行き（長期停滞 issue 処理）の遷移条件を議論できればと思います。  
> 
> - 最終コメントから何日で遷移判定とするか
> - 日数は issue の状態で変えるか（例: `必要性議論` は 14日待機、`実装者募集` は半年待機）
> 
> が私がパッと気になる論点です。

妥当な日数を考えるのが結構時間かかりそうです 🙇 
ちょっとたたき台を考えるのお願いしてもいいでしょうか 🙇 

---

あとこれらの「必要性議論」ラベルとかは全部同じ概念であるということがわかるように、何かしらプレフィックスをつけるのお願いしたいです！

**Comment by Hiroshiba** [comment]
提案ありがとうございます！！

> - `必要性議論` : 30 日
> - `設計` : 180 日
> - `実装者募集` : 180 日
> - `実装` : 180 日

根拠含めこちらが良さそうに感じました！
180日の方は様子を見てもっと代謝を激しくしてもいいかもですね！！
とりあえず運用を変えすぎないという意図でも、一旦長めに設定しておくのが良さそうに感じました！

---

> 「state: 必要性議論 / state: 実装」「状態：必要性議論 / 状態：実装」あたりが有り得そうです。
どちらがしっくりきますか（あるいは他の案）？

他のラベルに合わせて「状態：」が良さそうに思いました！
