### ISSUE TITLE
レビュア issue 進行速度

### ISSUE THREAD

**Issue by tarepan** [VOICEVOX/voicevox_engine#1127]
## 質問の内容
質問概要: レビュアが issue 進行/キャッチボールする際の速度感が知りたい

@Hiroshiba  
以前 Discord の方で PR に関して VOICEVOX での進行/キャッチボールの速度感を聞いた際、「経験上3日を目安」「急ぎじゃないなら1週間でも」との回答を頂きました。  
（もちろんケースバイケースなのは大前提として）issue 進行でも同様の基準で動いて問題ないでしょうか？  
#1097 や #1104 、他にもメンテナさんへのccメンション等で迷う機会が増えてきたため、回答を頂ければ幸いです。

**Comment by Hiroshiba** [comment]
基本３日で大丈夫だと思います！
反応なしと判断するのは１週間お待ちしても良いかもくらいかなーと。

レビュア判断がいりそうなものは、ヒホか２名の判断があれば（他の方のコメントを３日ほど待って）進む形でOKだと思います。
自分は早めにほしいときはDiscordでメンション飛ばしたりしています。リリース前とかたまに。

３日ほど返信できなかったのはすみませんでした 🙇 　ちょっと３日は早いかもですね･･･。
とはいえ結構スピーディに進められたほうが良いと思うので、テンポ良い方が良さそうなときは３日とかで大丈夫ですかなと！

**Comment by tarepan** [comment]
> 基本３日で大丈夫 ... レビュア判断がいりそうなものは、ヒホか２名の判断があれば  

👍  
明確化ありがとうございます！  

> 早めにほしいときはDiscordでメンション飛ばしたり  

なるほど、柔軟で良いですね。頭の片隅に置いておきます。  

> ３日ほど返信できなかったのはすみませんでした 🙇   

いえいえ全然大丈夫です！OSS は一時の速度より長期的健康の方が圧倒的に重要ですから👍  

> ちょっと３日は早いかも ... テンポ良い方が良さそうなときは３日とかで大丈夫  

👍  
「切り戻し可能な判断かつ要テンポの案件であれば 3 日で進めても良い。基本は 1 週間くらいドンと構える」感じの進行でいきたいと思います。
