### ISSUE TITLE
ランタイム多重ロード時の振る舞い

### ISSUE THREAD

**Issue by tarepan** [VOICEVOX/voicevox_engine#1133]
## 質問の内容
質問概要: `load_runtime_lib()` が複数のランタイムを読み込んだ際どういった振る舞いをするのか

`README.md` の「[音声ライブラリを直接指定する](https://github.com/VOICEVOX/voicevox_engine?tab=readme-ov-file#%E9%9F%B3%E5%A3%B0%E3%83%A9%E3%82%A4%E3%83%96%E3%83%A9%E3%83%AA%E3%82%92%E7%9B%B4%E6%8E%A5%E6%8C%87%E5%AE%9A%E3%81%99%E3%82%8B)」節では複数ランタイムのロードをサポートしている。  

> `--runtime_dir`引数は複数回使用可能

ENGINE 内部の [`load_runtime_lib()`](https://github.com/VOICEVOX/voicevox_engine/blob/c75b657a5c53feafaba418aa99ed4d9359991ffb/voicevox_engine/core/core_wrapper.py#L23) はランタイム DLL を読み込む関数であり、`--runtime_dir` で指定された全ランタイム DLL をロードする。   
特に CORE バージョンとの対応等はコードされておらず、単に `CDLL()` している。  

この前提で次の質問があります：  

「`--runtime_dir` 複数指定により複数ランタイムがロードされた場合、どのランタイムが利用されるのか」  

例えば CORE 側が自分に合ったバージョンの CDLL を自動探索する場合もありそうですし、最後に読み込んだ CDLL のみを利用する可能性もありそうです。  
#709 での複数ランタイム等との兼ね合いから、この引数の正常系振る舞いを知りたいです。  

## VOICEVOXのバージョン
0.17.1

**Comment by Hiroshiba** [comment]
どう振る舞うかはソースコードのみぞ知る感じですが、どう振る舞うべきかで言うとやっぱり正しく動作するべきだと思います！
どう振る舞うべきかでいうと、とりあえず最新版のonnxruntime等が使われるので問題ない気がします。
https://github.com/VOICEVOX/voicevox_engine/issues/709#issuecomment-2010535164

**Comment by tarepan** [comment]
> どう振る舞うべきかでいうと、とりあえず最新版のonnxruntime等が使われる  

👍️  
明確化ありがとうございます！  
「ランタイム多重ロード時の設計上の正常動作は『最新版のonnxruntime等が使われる』である」ですね、理解しました。
