### ISSUE TITLE
refactor: Workflow 命名規則を統一

### ISSUE THREAD

**Issue by tarepan** [VOICEVOX/voicevox_engine#1145]
## 内容
要望概要: workflow ファイル名の命名規則を統一したい  

現在の ENGINE は複数の workflow ファイルを定義し、それらは以下の名称・目的・対象を持つ：  

| workflow 名               | 目的   | 対象                 |
| :------------------------ | ------ | ------------------- |
| `build-docker.yml`        | ビルド | docker              |
| `build.yml`               | ビルド | executable          |
| `release-latest-dev.yml`  | ビルド | docker & executable |
| `release-test-docker.yml` | テスト | docker              |
| `release-test.yml`        | テスト | executable          |
| `test.yml`                | テスト | executable          |

ここからわかるように、名称が混線している。例えば `release-latest-dev.yml` は「***release*** する、***latest-dev*** を」の語順だが、`release-test.yml` は「***release*** 版を、***test*** する」の語順になっている。  
この結果、workflow 名からその workflow の機能を類推できなくなっている。  

このような背景から、workflow ファイル名の命名規則統一によるリファクタリングを提案します。  

名称改善案として以下を挙げます：  

| 旧名                       | 新名                   |
| :------------------------ | :--------------------- |
| `build-docker.yml`        | `build-docker.yml`     |
| `build.yml`               | `build-executable.yml` |
| `release-latest-dev.yml`  | `build-latest-dev.yml` |
| `release-test-docker.yml` | `test-docker.yml`      |
| `release-test.yml`        | `test-executable.yml`  |
| `test.yml`                | `test-code.yml`        |

### Pros 良くなる点
- workflow 一覧の見通し改善

### Cons 悪くなる点
無し

### 実現方法
名称変更

**Comment by Hiroshiba** [comment]
良いと思います！！

executable→engineはどうでしょう？
これだけ形容詞なのと、vvppというパッケージのビルドも担ってるのと、初見で直感的かなと思ったので提案してみました！
合わせてdocker→docker-engineにするのもありかも？

**Comment by tarepan** [comment]
> executable ... これだけ形容詞  

英語 *executable* は名詞で、日本語訳は「実行可能ファイル」です ([出典](https://ejje.weblio.jp/content/executable))。VOICEVOX ENGINE だと `.exe` や `.bin` にあたります。  

> vvppというパッケージのビルドも担ってる  

👍️  
たしかに executable そのもの以外にも、パッケージビルドまで担っていますね。  

> engine  

ENGINE の実体として Docker 版、exe/7z 版、VVPP 版があると認識しています。  
となると `engine` という語はどれを指しているか曖昧な気もします。  

----------------------------------------------

`executable` を `exe-and-vvpp` に変更、というのはどうでしょうか？

**Comment by Hiroshiba** [comment]
> executable を exe-and-vvpp に変更、というのはどうでしょうか？

細かいけどwindows以外はexeではないかもです。まあ略称としては正しいはずですが。
パッケージとか…？

> ENGINE の実体として Docker 版、exe/7z 版、VVPP 版があると認識しています。
となると engine という語はどれを指しているか曖昧な気もします。

もともとはこのdockerではない方が主流だと思ってたので、無印のengineで良いと思ってました。
まあでもどれもエンジンなのはそうなので、postfix付けても良いかなーと思いました！

**Comment by tarepan** [comment]
「パッケージ」「postfix」の方向性に同意です。  
単純に採用すると `docker-engine` となり、Docker ランタイムの名称と丸被りで困惑しそうに思いました。  
よって `container` に置き換え、語順を自然にして、以下の名称を提案します。  

| 旧名                       | 新名                   |
| :------------------------ | :--------------------- |
| `build-docker.yml`        | `build-engine-container.yml`     |
| `build.yml`               | `build-engine-package.yml` |
| `release-latest-dev.yml`  | `build-latest-dev.yml` |
| `release-test-docker.yml` | `test-engine-container.yml`      |
| `release-test.yml`        | `test-engine-package.yml`  |
| `test.yml`                | `test-code.yml`        |

（こう並べると `engine` 無くしてシンプルにした方が良さげ…か…？）

**Comment by Hiroshiba** [comment]
@tarepan 良さそうに思いました！

engineなくすとbuild-package.ymlみたいになって、パッケージをビルドするのか、ビルドするパッケージなのか分かんなくなるかもですね。

同じようにtest-code.ymlもコードをテストしてるのか（正解）、テストコードなのか（こっちが不正解）わかんないかもですね。
test.ymlが適している気がしました！

**Comment by tarepan** [comment]
着手します。
