### ISSUE TITLE
ランタイム CDLL ロードの仕組み

### ISSUE THREAD

**Issue by tarepan** [VOICEVOX/voicevox_engine#1146]
## 質問の内容
質問概要: ランタイム CDLL ロードの仕組みが知りたい

現在の ENGINE は `load_runtime_lib()` においてランタイム CDLL (例: `onnxruntime.dll`) をロードしている。  

https://github.com/VOICEVOX/voicevox_engine/blob/e2a531aff785351fbc98e6f0b0d1e75aef7ade37/voicevox_engine/core/core_wrapper.py#L46

この CDLL は純粋にロードのみがなされ、ENGINE 内ではその後明示的に利用されていない。  
CORE 側の仕組みによって上手く利用されていると想定されるが、その挙動は ENGINE 的には不明である。  

#709 や #1133 でランタイム CDLL の読み込み方式が論点となっているが、議論の前提としてこの仕組みの理解が必要となっている。  

このような背景から、次の質問があります：  

「ランタイム CDLL はロードされたのちどのように選択・利用されるのか」  

ENGINE コントリビュータからすると CORE の理解は相当なハードルがあります。  
可能であれば CORE 側のランタイムロード関連の仕組みについて簡単な解説があると非常に助かります。  
もしご多忙でしたら、読むべき CORE 側のコードを示して頂ければ幸いです。  

詳しそうな方々: @Hiroshiba @qryxip  

## VOICEVOXのバージョン
0.18.0

**Comment by qryxip** [comment]
例えばonnxruntime.dllは、voicevox_core.dllのロード時点で

1. 解決可能か
2. 既にロードされている

必要があります。1.だとWindows上では難しいため、2.とするために`CDLL`、すなわち`dlopen`/`LoadLibrary`でonnxruntime.dllを読み込んでいます。

もし1.でも2.でもない場合、Linuxの場合はこのようになるはずです。

```console
ImportError: libonnxruntime.so.1.14.0: cannot open shared object file: No such file or directory
```

Windowsの場合は2.でない限り、[C:\Windows\System32\onnxruntime.dllが解決されてしまい人間にはわかりにくいエラーになります](https://github.com/VOICEVOX/voicevox_core/issues/474)。

**Comment by qryxip** [comment]
今後の話ですが、<https://github.com/VOICEVOX/voicevox_core/issues/721>ができるとlibvoicevox\_core → libonnxruntimeの依存の関係が通常の動的リンクから`dlopen`/`LoadLibrary`に変わるため、CORE側で自分ですべてなんとかすることができるようになります。そうなったらENGINE側での対処は無くてもよいし、有っても問題は起こさないと思います(`RTLD_LOCAL`相当のはずなので)。なので`core_wrapper.load_runtime_lib`は≦0.15のコアのための処理になると思います。

さらに<https://github.com/VOICEVOX/voicevox_core/issues/721>を達成すると、依存DLLがonnxruntime.dllからvoicevox_onnxruntime.dllに代わります。

今のところコアは、上記二つとも行った上でリリースする予定です。

**Comment by tarepan** [comment]
@qryxip  
丁寧にありがとうございます、非常に助かります！  
「`onnxruntime.dll` がパス解決可能 or プロセスにロード済みじゃないと CORE ロード時に落ちる」があり、そのために ENGINE 側で事前ロードしているということですね。  

CORE ロード時についてなのですが、`onnxruntime.dll` へ直接アクセスを試みるのは CORE でしょうか、それとも依存している https://github.com/VOICEVOX/onnxruntime-rs でしょうか？  
複数ロード等の理解のために `onnxruntime.dll` アクセス箇所（落ちうるポイント）を探したのですが、CORE に見当たらない…？となりまして。

**Comment by qryxip** [comment]
強いて言うなら**ビルド時に実行される**ここでしょうか。onnxruntime.dll側の各関数シンボルを宣言し、それらの解決をonnxruntime.dllで行うように指示、というのを`onnxruntime-sys` (onnxruntime-rs)はビルド時にやっているという理解です。
<https://github.com/VOICEVOX/onnxruntime-rs/blob/7d9eeedf4c39cee965c0385cf8601d9392b62cde/onnxruntime-sys/build.rs#L132-L134>

**Comment by tarepan** [comment]
> それらの解決をonnxruntime.dllで行うように指示、というのを`onnxruntime-sys` (onnxruntime-rs)はビルド時にやっている  

まさにこのコードが知りたい箇所の1つでした、ありがとうございます！  

- 「`onnxruntime` 名で実行時に DLL アクセスしろ」との指示で `onnxruntime-sys` がビルド
-  実行時に `onnxruntime-sys` 内で DLL アクセス実行
- 見つからないと `cannot open shared object file` になったり、Win で build-in `onnxruntime` に解決されたり

という感じですかね。  

## 多重ロード時の実動作
#1133 で議題になった多重ロード時の実動作に関して。  

上記の情報に基づくと「CORE 側でロード順を制御してる」というより「Python ctypes の CDLL 複数回コール時挙動で実動作が左右される」が妥当そうに見えます。  
（なのでCORE 側の挙動に関する質問 issue である本 issue は close 可能かも。）  
CDLL 周りの情報持っている方のアドバイスが頂ければ幸いです。

**Comment by tarepan** [comment]
（Discord から情報転記）  

- ctypes / 多重ロード実装時PR: #254

**Comment by tarepan** [comment]
Python ctypes の CDLL 複数回コール時挙動は以下の形と推定されます（情報転記）：  

> 同名のライブラリを複数読み込んだ場合の挙動は、一番初めに読み込んだものを使うようになっているようです。  
> https://ikb.hatenablog.com/entry/20110830/1314684440  
> そのため、現在の挙動としては、  
> `--runtime_dir`→`--voicevox_dir`もしくは`engine_root`  
> の順でディレクトリ内を検索し、先に見つかったものが使われるのではないかと思います。  
>（それでも見つからない場合は、ctypes.util.find_libraryの検索結果が使われる）  
> takana-v. (2024). https://github.com/VOICEVOX/voicevox_engine/issues/1148#issuecomment-2040800864

**Comment by tarepan** [comment]
CORE 側の DLL 利用方法および Python 側の DLL 多重ロード挙動が理解されたため、本 issue は resolve につき close とします。
