### ISSUE TITLE
[ソング] 音量更新APIを追加する

### ISSUE THREAD

**Issue by y-chan** [VOICEVOX/voicevox_engine#1185]
## 内容

現在、 VOICEVOX/voicevox#2003 でソングエディタにピッチ調整機能が実装されています。
VOICEVOX ソング機能は現状音量を編集することはできないですが、ピッチの変更に伴って音量も変わったほうが、よりよい音声に聞こえるはずです。
そこで、音素・ピッチを入力して音量を推論するAPIを実装します。

### Pros 良くなる点

最終的により良い音声の出力につながる

### Cons 悪くなる点

なし

### 実現方法

音量推論のC APIを叩く

## VOICEVOXのバージョン

0.?.0

## OSの種類/ディストリ/バージョン

- [ ] Windows
- [ ] macOS
- [ ] Linux

## その他

@sigprogramming さん、よければ意見を伺いたいのですが、APIの形式として嬉しい形はありますかね...? :eyes:
トークと似たような形で、FrameAudioQueryを渡せば、それが更新されて返ってくる形にするか、それとも音量推論に必要なデータだけ(音素列・ピッチ)を抜き出して、音量列が返ってくるような形にするかで少し迷っています...
良い案があれば、教えていただけると :bow:

**Comment by sigprogramming** [comment]
@y-chan 
コメントが遅くなりすみません…！
discordの方で議論がありましたが、私もFrameAudioQueryを渡してvolumeが返ってくる形が良いと思います！
推論に必要ないものも渡すことになるかもですが、マルチエンジンも考慮するとこの形が良いと思います。
出力は推論結果のみで良いと思います。（受け取る側でFrameAudioQueryに差し込んだり保持したり行えばよいかなと）

**Comment by Hiroshiba** [comment]
なぜこのシグネチャにしたのか、[コア側のAPI実装](https://github.com/VOICEVOX/voicevox_core/pull/1073)に情報が必要そうだったのでサルベージしたのでメモまで！
（この頃ソングの正式リリースのためにすごい急いでて、ソングのメイン 開発チームの DM に記録が残ってました 🙇 ）

音量先生の時にスコア情報を渡してる理由は、VOICEVOXにとってはノートのキー情報を得るためでした。
でもスコアの情報全部を渡す必要はないはずなのですが、「マルチエンジンのためにこのシグネチャがいいかも」と結論付けた結果今のシグネチャになってそうです。

> マルチエンジンのため
