### ISSUE TITLE
hotfix: 音量更新 API 関連テストの追加

### ISSUE THREAD

**Issue by tarepan** [VOICEVOX/voicevox_engine#1188]
## 内容
リリース日程に由来する特例として実装しなかった音量更新 API 関連テストを実装する。
ref: https://github.com/VOICEVOX/voicevox_engine/pull/1187#discussion_r1580513431

### Pros 良くなる点
- 開発安定性の向上
- レビュープロセスの適正化

### Cons 悪くなる点
無し

### 実現方法
ref https://github.com/VOICEVOX/voicevox_engine/pull/1187#discussion_r1580513431

## VOICEVOXのバージョン
0.19.0

**Comment by Hiroshiba** [comment]
📝 web APIのe2eテストは `test/e2e/single_api/test_sing_frame_volume.py` にあるけど、TTSEngineの`create_sing_volume_from_phoneme_and_f0`メソッドのテストがない
https://github.com/VOICEVOX/voicevox_engine/pull/1187#discussion_r1580513431

**Comment by Hiroshiba** [comment]
こちらちょっと自分やってみようと思います！

**Comment by Hiroshiba** [comment]
こちらちょっと自分やってみようと思います！
cc @y-chan

**Comment by Hiroshiba** [comment]
@tarepan 
既存コードだとsing系APIは`create_sing_phoneme_and_f0_and_volume`と`frame_synthsize_wave`があり、その両方が１つのテスト関数内でテストされていそうでした。
（`test_mocked_synthesize_wave_from_score_output`関数）

新しく生えた`create_sing_volume_from_phoneme_and_f0`APIのテストを行う方法が何通り考えられるのですが、どうやるのが妥当でしょうか。

* `create_sing_volume_from_phoneme_and_f0`の入力
	1. scoreから`create_sing_phoneme_and_f0_and_volume`実行→そこから作られた`frame_audio_query`の`f0`とscoreを入力
	2. 専用の入力作る`_gen`関数を作る（f0がフレーム長のベクトルなので愚直にやると長くなる）
	3. `create_sing_phoneme_and_f0_and_volume`だけをテストするsnapshotテストを用意し、そのsnapshotテスト用のデータを読み込んで入力とする（snapshotテスト用のデータを、出力検査用と入力用の２種の用途でつかうのが若干危なそう）
* `create_sing_volume_from_phoneme_and_f0`の出力検査
	1. 更に`frame_audio_query`にvolumeを再代入して`frame_synthsize_wave`に入力し、出力されたものをsnapshotテストする（以前のテストと同じ流れだけど、わりと複雑な複合テストになる）
	2. 出力された`volume`だけを検査する

個人的にはここは単体テストする場所な気がするので、各関数を１つだけテストする形が良さそうに感じました。
とはいえ専用の入力を用意する部分をどうしたものかと迷っています･･･････。
（過去言ったこととずれてたらすみません 🙇 もしずれてる場合なにか僕の認識が漏れてる気がします。。）

とりあえず今までの関数に習いつつお手軽にするということで、入力は1、出力は2で実装してみたいと思います。

**Comment by tarepan** [comment]
unit test 実装の基本方針として問題ないと感じました👍️  
具体的実装を PR 側で議論できればと思います。
