### ISSUE TITLE
delete: 自動レビュアーアサインの無効化

### ISSUE THREAD

**Issue by tarepan** [VOICEVOX/voicevox_engine#1201]
## 内容
要望: 自動レビュアーアサインの無効化による機能廃止

現在の VOICEVOX ENGINE は `CODEOWNERS` ファイルに基づく自動レビュアーアサインをおこなっている（模様である）。  
しかし実態として自動割り当て結果を利用していない。ゆえに実務上の利点がない。   
一方で形式的なアサインは reviewer・reviewee 両者にとって混乱のもとである。また不要な通知・心理的負荷にもなりうる。  

このような背景から、自動レビュアーアサインの無効化による機能廃止を提案します。  

### Pros 良くなる点
- 形式的アサインによる混乱の解消

### Cons 悪くなる点
無し

### 実現方法
（GitHub の setting はメンテナしか見れないので以下の実現方法は推測）  
ENGINE の "Enable auto assignment" 設定を変更

## VOICEVOXのバージョン
0.19.1

**Comment by tarepan** [comment]
resolved by #1206 (assignee change)

**Comment by Hiroshiba** [comment]
あ、issue立ててくださってたんですね！！
課題だなあと感じてたのでちょっと裏で調整してました･･･！
