### ISSUE TITLE
定期脆弱性診断の結果をDiscordに通知

### ISSUE THREAD

**Issue by takejohn** [VOICEVOX/voicevox_engine#1204]
## 内容

#1152 で追加された定期脆弱性診断の実行時、Discord にテストの結果を送信しましょう。
> https://github.com/VOICEVOX/voicevox_engine/pull/1152#pullrequestreview-2030812198

### Pros 良くなる点

セキュリティテストが回ったことに気づくことができるようになる。

### Cons 悪くなる点

なし

### 実現方法

GithHub Actions から curl コマンドで Discord の Webhook を叩くか、
[既存の action](https://github.com/marketplace/actions/actions-status-discord) を使用する。
Webhook URL は secrets にもっておくようにする。
該当 workflow: https://github.com/VOICEVOX/voicevox_engine/blob/master/.github/workflows/test-security.yml

## VOICEVOXのバージョン

0.?.0

## OSの種類/ディストリ/バージョン

- [ ] Windows
- [ ] macOS
- [ ] Linux

**Comment by Hiroshiba** [comment]
個人的にはwebhook経由でworkflowからDiscordに通知を飛ばすの、ありなのではと思ってます！
そもそもDiscordのgithubチャンネルにいろいろ飛ばしてますし。

ただ永久にメンテし続けるべきかというとそうではないとも思ってます。
とりあえず使い心地を調べてみるために、せっかくだから１回実装してみるのも面白いのかなと。
（こう、月１回の小さいお祭りみたいな感じになれば楽しいのかなとか思ってます）

**Comment by tarepan** [comment]
通知が正常に機能したことを確認しました ([Actions](https://github.com/VOICEVOX/voicevox_engine/actions/runs/9089896804), [Discord](https://discord.com/channels/879570910208733277/880100454292422766/1240155705902764063))。  
@weweweok さん実装ありがとうございました！
