### ISSUE TITLE
SpeakerInfoの画像や音声のデータをURLで返すようにする？

### ISSUE THREAD

**Issue by Hiroshiba** [VOICEVOX/voicevox_engine#1208]
## 内容

エンジンのリソース情報を取得しようとすると結構な時間がかかることがわかっています。
VOICEVOXエディタは全キャラのリソース取得を起動時に行い、かつそれが必須な形であらゆるものがコーディングされていて、起動時間が１０秒ほどかかる要因の１つとなっています。

時間がかかっているのは話者情報の取得API（`/speaker_info`と`/singer_info`）です。
その中でもファイル取得やbase64エンコードに時間がかかっていることもわかっています（その他の関連リンク参照）。
これらの課題を一挙に解決できる方法の１つが、ファイル取得そのものを遅延させる方法です。

このissueでは画像や音声ファイルをbase64エンコードして`/speaker_info`等で返さず、何らかの方法でURLとして返すようにするかどうかを議論するissueです。

### そもそもURL化するのが良いと思う理由

そっちのが一般的なことと、スケーラビリティが高いことと、エディタと親和性が高いためです。

* そっちのが一般的
	* base64を返すのはあまり一般的じゃない　気がする
	* URLを返す他にも、IDを返してそのIDを元にリクエストしてもらう形式があるけど、後々のスケールのことも考えるとURLのがお得な気がする（↓参照）
* スケーラビリティが高い
	* URLで返すなら、エンジンと関係ない場所にあるリソースを返すこともできる
	* 外部URLに立ち絵を置いておけば、立ち絵を後から自由に変更できるなど、柔軟な設計も可能にはなる
* エディタと親和性が高い
	* そもそも画像や音声は[blob化して](https://github.com/VOICEVOX/voicevox/blob/2b13c1eb333816bc7de3e5bf7a408eed6b149feb/src/store/audio.ts#L371)`src`などに指定してます
		* 画像は[こんな感じ](https://github.com/VOICEVOX/voicevox/blob/2b13c1eb333816bc7de3e5bf7a408eed6b149feb/src/components/CharacterButton.vue#L159)
		* 音声は[こんな感じ](https://github.com/VOICEVOX/voicevox/blob/2b13c1eb333816bc7de3e5bf7a408eed6b149feb/src/components/Dialog/CharacterOrderDialog.vue#L222)
	* なのでURLだった場合はblob化しなければ自然と置き換えができる（はず）

### 実現方法

リソースファイルのURLは`/static/speaker_info`APIを作って[static](https://fastapi.tiangolo.com/ja/tutorial/static-files/)でファイルを返せば良さそう。
ファイルパスは`speaker_info`関数内で取ってきてるので、それをbase64エンコードするか、ファイルURLにするかの違いなだけなのでコード変更量は大きくなさそう。
エンジン自身のURLを取得するのは`request.url`を取ってこれば[できるはず](https://stackoverflow.com/a/70477788/8503463)？

互換性を考慮しつつファイルURLを返すように切り替える方法は、ワークアラウンド引数を追加する方法と、v2 APIを作る方法があると思います。

* `/speaker_info` APIの引数に「URLで返すかどうか」情報をもたせるワークアラウンド
  * `/speaker_info?workaround_resource_url=true`などとすれば画像・音声をURLで返す
  * 型の変更がないのでエンジン・エディタともに変更が少なくて済む
  * `engine_manifest`は変えなくても良い･･･かも？
  * ワークアラウンドとしてるけど、正式な方法として提供しても良いかも（問題ないか結構検討したほうが良さそう）
* `/v2/speaker_info` APIを作り、`SpeakerInfoV2`のようなモデルを返す
	* APIとモデルを作ること自体は簡単
	* APIが増えるので`engine_manifest`を変える必要がある
	* エディタ側もマルチエンジンのこと考えるとそれなりの改修が必要
	* 他のv2 APIの拡張性も考え始めると検討事項が増えていく

個人的には議論の末引数指定を正式リリースできそうならそっちが良さそうに思いました。
できなそうなら、v2化するかワークアラウンドにするか諦めるかを考える感じかなと。

## その他

関連リンク

- https://github.com/VOICEVOX/voicevox_engine/issues/1129
- https://github.com/VOICEVOX/voicevox_engine/pull/1073#issuecomment-1963998561

**Comment by y-chan** [comment]
少し開発が止まっている感じはありますが、 ライブラリ管理APIのうちの`/downloadable_library`は、URLを返せる仕様になっているはずで、[エディタ側でもそれをパースできるような仕様](https://github.com/VOICEVOX/voicevox/pull/1560/files)になっています。
これは、現状のエンジン・エディタが抱えているパフォーマンス問題に似た問題を抱えていたためなので、同様の仕様に変更することは、仕様の統一につながり、扱いやすさが向上すると思います。

エンジン側では、クエリ引数を使えるようにするとよいのかなと思いました。
URLモードかbase64文字列モードを切り替えられるオプショナルクエリにしてしまうことは別に破壊的変更ではないので、`workaround`はなくても良いかなと思いました。
また、v2 apiは統一してすべてのAPIで作ったほうが扱いがしやすいと思うので、現状作るべきではないと思いました。

**Comment by sabonerune** [comment]
VOICEVOXエンジンのリソースを指すURL全体を返すとサーバーとして運用していると困るかもしれない？

あとはキャッシュ周り？
軽く動作を確認したところ
`date`、`last-modified`、`etag:`が付与され`Cache-Control`ヘッダは付与されませんでした。
そのためブラウザは自動的にキャッシュの有効期限を推定して有効と判断した間はリクエストをせずにキャッシュを使い回します。
そのためエンジンの更新をしても表示が変わらないという不具合を起こす可能性があります。

**Comment by Hiroshiba** [comment]
@y-chan なるほどです！

クエリパラメータの場合、なんか落とし穴があるきがするんですよね･･･。
エディタ側からマルチエンジンとして引数がない既存エンジンにリクエストを投げる･･･ときは問題ないはずですが･･･。

既存エンジンにはない場合があるということをユーザーが知らない、みたいな･･･？
まあ、大丈夫かな。。。

**Comment by Hiroshiba** [comment]
@sabonerune キャッシュなるほどです！考慮ありがとうございます！！

仕様はどこにも書いてなかったのですが、コードを追っていくとたぶんファイルサイズとファイル作成日からetag作る感じでした。
https://github.com/encode/starlette/blob/9f16bf5c25e126200701f6e04330864f4a91a898/starlette/responses.py#L317-L318

StaticFilesのコードはここ
https://github.com/encode/starlette/blob/9f16bf5c25e126200701f6e04330864f4a91a898/starlette/staticfiles.py#L185-L187

将来ファイル作成日を消す変更を行った上、ファイルサイズが偶然被ったらキャッシュがバグになりますが、まあ、普通にしてたら大丈夫かな〜。

**Comment by sabonerune** [comment]
@Hiroshiba `date`と`last-modified`からブラウザは勝手にキャッシュの有効期限を推測して有効期限の間は**サーバーにリクエストを送らずに**キャッシュを利用してしまいます。サーバーにリクエストを送らないため`etag`の照合も行われません。

**Comment by Hiroshiba** [comment]
@sabonerune お～～～～なるほどです！！　確かにキャッシュが入ってきそうですね！！！

うーん、no-cacheを付けるか、etag見てもらうようにするか、あるいは気づかなかったことにするかって感じですねぇ。
立ち絵を更新してそれを告知することもある以上、何もしないのはイマイチかも。

**Comment by sabonerune** [comment]
@Hiroshiba あとはリソースが更新されたらURLを毎回変更するとかでしょうか？
この場合は逆にキャッシュの有効期限を極端に長くしてしまっても構わないというのがメリットで、リソース管理かコードが面倒になるのがデメリットですね…

**Comment by Hiroshiba** [comment]
@sabonerune 調べたらキャッシュを不要にしたりするのをキャッシュバスティングだとか言うというのを見つけました。
FastAPIやStarletteでそういう機能は公式で提供されてなさそうですね･･･。

一応サードパーティで作られてる方はいらっしゃいました。
https://github.com/tmkontra/fastapi-static-digest
まあたぶん起動時にハッシュ化するので（普通それで問題ない）起動が遅くなってしまうのですが･･･。

頑張る価値はある気はちょっとしますねぇ。
事前にファイル名をコンパイルする形が手っ取り早い気がしました。
例えば話者ごとのリソースファイルへのパスをjsonで管理するようにして、ビルド時にファイル名をmd5ハッシュ等に置き換えてjsonも置き換え、あとはそのURLを`/speaker_infos`で案内、とかが現実的でしょうか。
