### ISSUE TITLE
Linux版のVOICEVOX Engineの起動について

### ISSUE THREAD

**Issue by YTJVDCM** [VOICEVOX/voicevox_engine#121]
## 質問の内容

VOICEVOX Engineの実行についてなのですが、`README.md`の説明にあるように、`--voicevox_dir`に製品版VOICEVOXのパスを指定しても、
```
ModuleNotFoundError: No module named 'core'
Notice: mock-library will be used. Try re-run with valid --voicevox_dir
```
と言われてモックで起動してしまいます。
文言を見るに、おそらくモジュールの読み込みに失敗しており、どこかで実行方法を間違えているものだと思うのですが、具体的にどのようにすると製品版VOICEVOXでサーバーを起動することができるのでしょうか。

## VOICEVOXのバージョン

0.6.0

## OSの種類/ディストリ/バージョン

- OS : Arch Linux x86_64
- Kernel : 5.13.5-arch1-1

## その他

製品版VOICEVOXがWindows用バイナリだからではないかと思い、試しにLinux用ビルドとvoicevox_coreのあるディレクトリをを`--voicevox_dir`に指定して実行してみたのですが、voicevox_coreの場合は同様の文言、Linux用ビルドでは`ModuleNotfoundError`の代わりに
```
ImportError: libcore.so: cannot open shared object file: No such file or directory
```
と表示され同様にモックで起動しました。

**Comment by buckw6eat** [comment]
特に指摘がない（エンジンを開発で動かすニーズがない？）のですが、最近のバージョンでは `--voicevox_dir` に加えて `--voicelib_dir` オプションも同値を指定しないと機能しないです。

参照：コンテナ化されてる方の起動オプション
https://github.com/Hiroshiba/voicevox_engine/blob/39b5777b503b1c9868891c198d764a46b3d56362/Dockerfile#L248-L253

**Comment by YTJVDCM** [comment]
`--voicelib_dir`に同じディレクトリを指定して起動を試みましたが、やはり`ModuleNotFoundError`で起動しませんでした。

(それと、`run.py`の75行目を見るに、`--voicelib_dir`の指定がない場合は自動的に`--voicevox_dir`と同値が指定されるようになっているようです)

**Comment by Hiroshiba** [comment]
@YTJVDCM 
Issueありがとうございます！

Pythonのエラー内容なのですが、`ModuleNotFoundError: No module named 'core'`はPythonのcoreモジュールが見つからなかったというのが原因で、`ImportError: libcore.so:`は（coreモジュールは見つかったけど）libcore.soライブラリが見つからなかったというのが原因です。
`libcore.so`があるパスを`LD_LIBRARY_PATH`に指定して実行するとどうなりますか？👀

**Comment by buckw6eat** [comment]
おそらく動きましたが、なかなか面倒な状況のようです。複合的要因であり ENGINE のみならず CORE とも調整が必要と推定されます。

## 準備

このプロジェクトの git clone および ENGINE のビルド済みファイルを取得 (`linux-nvidia.7z.001`, `linux-nvidia.7z.001`)
https://github.com/Hiroshiba/voicevox_engine/releases/tag/check-2021-09-25

```bash
git clone https://github.com/Hiroshiba/voicevox_engine.git

curl -L -O https://github.com/Hiroshiba/voicevox_engine/releases/download/check-2021-09-25/linux-nvidia.7z.001
curl -L -O https://github.com/Hiroshiba/voicevox_engine/releases/download/check-2021-09-25/linux-nvidia.7z.002
7za x linux-nvidia.7z.001

chmod +x linux-nvidia/run
```

結果

```
../
├── linux-nvidia
├── linux-nvidia.7z.001
├── linux-nvidia.7z.002
└── voicevox_engine
```

Linux 環境は Debian 11 / Kernel 5.10.0-8-amd64、Python 3.9.2

# ビルド済みファイル編

## NG: ビルド済みファイルを素直に実行

- 直接参照でない共有ライブラリーの参照 NG
- Mock 内でもパス位置の問題

```bash
$ cd linux-nvidia
$ ./run

Traceback (most recent call last):
  File "/home/buckw6eat/Documents/linux-nvidia/run.py", line 59, in make_synthesis_engine
ImportError: libnvToolsExt.so.1: cannot open shared object file: No such file or directory
Notice: mock-library will be used. Try re-run with valid --voicevox_dir
Traceback (most recent call last):
  File "/home/buckw6eat/Documents/linux-nvidia/run.py", line 424, in <module>
  File "/home/buckw6eat/Documents/linux-nvidia/run.py", line 92, in make_synthesis_engine
  File "/home/buckw6eat/Documents/linux-nvidia/voicevox_engine/dev/core/mock.py", line 76, in metas
  File "/home/buckw6eat/Documents/linux-nvidia/pathlib.py", line 1221, in read_text
  File "/home/buckw6eat/Documents/linux-nvidia/pathlib.py", line 1208, in open
  File "/home/buckw6eat/Documents/linux-nvidia/pathlib.py", line 1063, in _opener
FileNotFoundError: [Errno 2] No such file or directory: '/home/buckw6eat/Documents/linux-nvidia/voicevox_engine/dev/core/../../../VERSION.txt'
```

## 対応：LD_LIBRARY_PATH

```
$ LD_LIBRARY_PATH=./ ./run

INFO:     Started server process [7697]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://127.0.0.1:50021 (Press CTRL+C to quit)
```

ちなみにほかのディレクトリから動かそうとするのは NG。

```
$ LD_LIBRARY_PATH=./linux-nvidia/ ./linux-nvidia/run

Traceback (most recent call last):
  File "/home/buckw6eat/Documents/linux-nvidia/run.py", line 59, in make_synthesis_engine
ImportError: ./libc10.so: cannot open shared object file: No such file or directory
Notice: mock-library will be used. Try re-run with valid --voicevox_dir
Traceback (most recent call last):
  File "/home/buckw6eat/Documents/linux-nvidia/run.py", line 424, in <module>
  File "/home/buckw6eat/Documents/linux-nvidia/run.py", line 92, in make_synthesis_engine
  File "/home/buckw6eat/Documents/linux-nvidia/voicevox_engine/dev/core/mock.py", line 76, in metas
  File "/home/buckw6eat/Documents/linux-nvidia/pathlib.py", line 1221, in read_text
  File "/home/buckw6eat/Documents/linux-nvidia/pathlib.py", line 1208, in open
  File "/home/buckw6eat/Documents/linux-nvidia/pathlib.py", line 1063, in _opener
FileNotFoundError: [Errno 2] No such file or directory: '/home/buckw6eat/Documents/linux-nvidia/voicevox_engine/dev/core/../../../VERSION.txt'
```

# プロジェクトのファイル編

## NG: プロジェクトのファイルを素直に実行

- core がインポートされない

```bash
$ cd voicevox_engine

# 前提 - cmake, python3-dev
$ pip install -r requirements.txt

$ python ./run.py

Traceback (most recent call last):
  File "/home/buckw6eat/Documents/voicevox_engine/./run.py", line 59, in make_synthesis_engine
    import core
ModuleNotFoundError: No module named 'core'
Notice: mock-library will be used. Try re-run with valid --voicevox_dir
INFO:     Started server process [7719]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://127.0.0.1:50021 (Press CTRL+C to quit)
```

## NG: `--voicevox_dir` を設定

- `libcore.so` を参照できない

```
# 変数名をつけておく
$ VVENGINE_DIR=${HOME}/Documents/linux-nvidia

$ python ./run.py --voicevox_dir $VVENGINE_DIR

Notice: --voicevox_dir is /home/buckw6eat/Documents/linux-nvidia
Traceback (most recent call last):
  File "/home/buckw6eat/Documents/voicevox_engine/./run.py", line 59, in make_synthesis_engine
    import core
ImportError: libcore.so: cannot open shared object file: No such file or directory
Notice: mock-library will be used. Try re-run with valid --voicevox_dir
INFO:     Started server process [7744]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://127.0.0.1:50021 (Press CTRL+C to quit)
```

## NG: LD_LIBRARY_PATH & `--voicevox_dir`

- `./libc10.so` を参照できない

```bash
$ LD_LIBRARY_PATH=$VVENGINE_DIR python ./run.py --voicevox_dir $VVENGINE_DIR

Notice: --voicevox_dir is /home/buckw6eat/Documents/linux-nvidia
Traceback (most recent call last):
  File "/home/buckw6eat/Documents/voicevox_engine/./run.py", line 59, in make_synthesis_engine
    import core
ImportError: ./libc10.so: cannot open shared object file: No such file or directory
Notice: mock-library will be used. Try re-run with valid --voicevox_dir
INFO:     Started server process [7753]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://127.0.0.1:50021 (Press CTRL+C to quit)
```

補足：このバージョンの libcore.so は、カレントディレクトリ (どのタイミング、どのファイルから見て？) に共有ライブラリーを求める

```bash
$ ldd $VVENGINE_DIR/libcore.so

        linux-vdso.so.1 (0x00007ffe487f8000)
        ./libc10.so => not found
        ./libtorch_cuda.so => not found
        ./libtorch_cuda_cpp.so => not found
        ./libtorch_cpu.so => not found
        libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f8006e07000)
        ./libtorch_cuda_cu.so => not found
        ./libtorch.so => not found
        libnvToolsExt.so.1 => not found
        libcudart.so.11.0 => not found
        libstdc++.so.6 => /lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007f8006c38000)
        libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f8006c1e000)
        libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f8006a57000)
        /lib64/ld-linux-x86-64.so.2 (0x00007f8007309000)
        libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f8006913000)
```

## NG: カレントディレクトリ移動 & LD_LIBRARY_PATH & `--voicevox_dir`

- なぜか初期化できない、メッセージがもう少しあれば分かるか？。

```bash
$ VVE_PROJECT_DIR=${HOME}/Documents/voicevox_engine
$ cd $VVENGINE_DIR

$ LD_LIBRARY_PATH=$VVENGINE_DIR python $VVE_PROJECT_DIR/run.py --voicevox_dir $VVENGINE_DIR

Notice: --voicevox_dir is /home/buckw6eat/Documents/linux-nvidia
<frozen importlib._bootstrap>:228: RuntimeWarning: compiletime version 3.7 of module 'core' does not match runtime version 3.9
<frozen importlib._bootstrap>:228: RuntimeWarning: builtins.type size changed, may indicate binary incompatibility. Expected 864 from C header, got 880 from PyObject
Traceback (most recent call last):
  File "/home/buckw6eat/Documents/voicevox_engine/run.py", line 424, in <module>
    make_synthesis_engine(
  File "/home/buckw6eat/Documents/voicevox_engine/run.py", line 77, in make_synthesis_engine
    core.initialize(voicelib_dir.as_posix() + "/", use_gpu)
  File "core.pyx", line 6, in core.initialize
  File "core.pyx", line 14, in core.initialize
Exception: [json.exception.parse_error.101] parse error at line 1, column 1: syntax error while parsing value -...
```

## 最終系: カレントディレクトリ移動 & LD_LIBRARY_PATH & `--voicevox_dir` & `--voicelib_dir`

```
$ LD_LIBRARY_PATH=$VVENGINE_DIR python $VVE_PROJECT_DIR/run.py --voicevox_dir $VVENGINE_DIR --voicelib_dir $VVENGINE_DIR

Notice: --voicevox_dir is /home/buckw6eat/Documents/linux-nvidia
<frozen importlib._bootstrap>:228: RuntimeWarning: compiletime version 3.7 of module 'core' does not match runtime version 3.9
<frozen importlib._bootstrap>:228: RuntimeWarning: builtins.type size changed, may indicate binary incompatibility. Expected 864 from C header, got 880 from PyObject
INFO:     Started server process [7798]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://127.0.0.1:50021 (Press CTRL+C to quit)
```

ちなみに `RuntimeWarning: compiletime version 3.7 of module 'core' does not match runtime version 3.9` の指摘通りかは不明であるが `/version` (metas.json) のレスポンスが `b''` (空文字列) になる。基本の音声合成 (AudioQuery → Synthesis) は動作した。

**Comment by Hiroshiba** [comment]
詳細ありがとうございます！
結論から言うと、 @buckw6eat さんの最終形にあるように、エンジンのrunがあるディレクトリにcdしたあと
`LD_LIBRARY_PATH=./ python /path/to/clone/run.py --voicevox_dir ./ --voicelib_dir ./`
するのが迂回作になりそうです。

READMEの方法＋`LD_LIBRARY_PATH`指定で動いてほしいところですが、どう解決すれば良いのかは思いつきませんでした・・・。Linuxに詳しい方いらっしゃったらアドバイス頂きたいです。

以下詳細です。

---

> NG: LD_LIBRARY_PATH & --voicevox_dir

この条件で動いてほしいところですね。。

> ./libc10.so を参照できない

こちらの処理が起因していそうです。
https://github.com/Hiroshiba/voicevox_engine/blob/39b5777b503b1c9868891c198d764a46b3d56362/Dockerfile#L314-L321

この処理が必要な理由はこちらにメモされていました https://github.com/Hiroshiba/voicevox_engine/issues/95#issuecomment-922331721

> VOICEVOX ENGINE（run）は 、run と同じディレクトリにLibTorchがあることを想定するのがいいのかな、とは思っています。
つまり、いまのところ、 #101 と同様に、patchelf を使って、実行バイナリ同梱用に libcore.so からLibTorchへのリンクを相対パスに書き換えるのがいいのかなと思っています。

engineをダブルクリックで起動できるようにするには相対パスにするくらいしか打開策がなさそうで、そうすると別ディレクトリから参照できない、というのが問題の根本だと思います。
linuxにお詳しい方がいたら、どうするのが良いかお伺いしたいです・・・。

**Comment by buckw6eat** [comment]
ビルド工程中のトリックでやるべきことは、libXXX の依存を ./libXXX に置き換えるのではなく rpath の設定であるようです。

```bash
# 設定値表示
$ patchelf --print-rpath ./libcore.so
/home/runner/work/voicevox_core_priv/voicevox_core_priv/download/libtorch/lib:/usr/local/cuda-11.1/lib64/stubs:/usr/local/cuda-11.1/lib64
```

```bash
# 設定値上書き
patchelf --set-rpath '$ORIGIN:/usr/local/cuda-11.1/lib64/stubs:/usr/local/cuda-11.1/lib64' ./libcore.so

# Python モジュールの core の方も仕込むと他所のディレクトリからのインポートに対応できる？
patchelf --set-rpath '$ORIGIN' ./core.so
```

[Man page of ld.sp (jp)](https://linuxjm.osdn.jp/html/LDP_man-pages/man8/ld.so.8.html)

> ### rpath トークンの展開
> ld.so では rpath 指定 (DT_RPATH や DT_RUNPATH) 中にいくつかの特定の文字列を使うことができる。 それらの文字列は以下のように置き換えられる。
>
> $ORIGIN (${ORIGIN} も同じ)
>
> プログラムや共有ライブラリが入っているディレクトリに展開される。 したがって、 somedir/app に置かれたアプリケーションを
>
> gcc -Wl,-rpath,'$ORIGIN/../lib'
>
> でコンパイルすることで、 somedir がディレクトリ階層のどこにあっても、 ld.so は somedir/lib にある対応する共有ライブラリを見つけることができる。 この機能を使うと、 特別なディレクトリではなく任意のディレクトリにインストールしても「ややこしい設定なしで」独自の共有ライブラリを使えるアプリケーションを作成することができる。

これで LD_LIBRARY_PATH はたぶん不要になるでしょう。

**Comment by Hiroshiba** [comment]
おーーーなるほどです！！！ `rpath`という概念があるんですね、完全に初見でした。
もしよかったらプルリクエストもお待ちしています・・・！

**Comment by aoirint** [comment]
- `--voicevox_dir`に製品版VOICEVOXのパスを指定したとき、coreモジュールを参照できない
    - Windows用製品版にはLinux用のcoreパッケージが含まれていないため
- `example/python`のcoreパッケージをインストール後、`--voicevox_dir`にReleaseのcore.zipを展開したパスを指定したとき、coreパッケージからlibcore.soを参照できない
    - 実行時にlibcore.soのあるディレクトリへのLD_LIBRARY_PATHが設定されていなかった
- libcore.soがリンクしたLibTorchを参照できない
    - #122 で解消

という流れかなと思いました。

動きがないので解決したと考えて、いったんクローズしますが、問題が続くようであれば再オープンしたり、新しいIssueを作ったりでお願いします！

製品版VOICEVOXではなく、core.zipをダウンロード・ENGINEをcloneしてrun.pyを動かす方法（LinuxではLD_LIBRARY_PATHを設定する必要がある）は、ドキュメント化されていない気がしたので、追加してもいいかなと思いました。

**Comment by Hiroshiba** [comment]
> 製品版VOICEVOXではなく、core.zipをダウンロード・ENGINEをcloneしてrun.pyを動かす方法（LinuxではLD_LIBRARY_PATHを設定する必要がある）は、ドキュメント化されていない気がしたので、追加してもいいかなと思いました。

たしかに、この辺りの整備は、新しいコアができたときとかに便利なので、機運があれば整備しておきたいなと感じました。
