### ISSUE TITLE
refactor: リソースディレクトリを新設

### ISSUE THREAD

**Issue by tarepan** [VOICEVOX/voicevox_engine#1243]
## 内容
概要: リソースディレクトリを新設してリファクタリング  

現在の VOICEVOX ENGINE は複数のリソースファイル・ディレクトリをルートに置いている。以下はその一覧である：  

- [x] `engine_manifest_assets/`
- [x] `speaker_info/`
- [x] `ui_template/`
- [x] `default.csv`
- [ ] `presets.yaml`

その結果、ビルド時にこれらのファイルを逐一指定して移動・登録する必要が出てきている。  
また初学者のリポジトリ見通しの観点からもルートはセマンティックに整理されている方が好ましい。  

これらのリソースは「静的かつ情報源である」という特性を共有しているため、`resources` として抽象化できる。  
`resources/` ディレクトリ下に各リソースを収納すれば、`resources/` のみの指定で移動・登録が可能であり、初学者もその意味を一見して理解できる。 　

このような背景から、`resources/` 新設によるリファクタリングを提案します。  

### Pros 良くなる点
- ビルドコマンド削減
- ビルド誤設定リスク低減
- ルート簡略化による見通し改善

### Cons 悪くなる点
無し

### 実現方法
- `resources` ディレクトリの新設
- 各リソースの移動
- リソースパスの修正

## VOICEVOXのバージョン
0.19.1

## その他
Go/NoGo 判断の一助として一部のリソースを `resources/` 下へ移す draft PR を作成しました（#1244, #1247, #1251）。必要であればご活用ください。

**Comment by sabonerune** [comment]
`--voicevox_dir`によって変更可能な`speaker_info`リソースの処理については注意が必要だと思います。
特にPyInstaller v6(mac環境で問題が発生したためv5に戻した)では実行ファイルのディレクトリと`_internal`ディレクトリに分かれることに注意です。
- ref: #828 
- ref: #857

**Comment by Hiroshiba** [comment]
良いと思います！！
ルートディレクトリは積極的に整理していきたいですねぇ。

@sabonerune さんの仰るとおり注意点はあるけど、破壊的な変更は無い･･･はず！

見落としやダメなフォルダ・ファイルがあるか確認しましたが、挙げられている５つで必要十分だと感じました！

**Comment by tarepan** [comment]
着手します。
