### ISSUE TITLE
`setup.cfg` の用途は何か

### ISSUE THREAD

**Issue by tarepan** [VOICEVOX/voicevox_engine#1252]
## 質問の内容
概要: `setup.cfg` の用途は何か

`setup.cfg` は `flake8` と `mypy` の設定値らしき内容を含んでおり、また `pysen` の自動生成結果をカスタマイズしたとの記述も含まれている。ここを見るとリンターの設定ファイルに見える。  
一方で同じリンターでも `black` や `isort` の設定は `pyproject.toml` に書かれている。また`pysen` のドキュメントには設定値は `pyproject.toml` に書くとの指定がある（[ref](https://github.com/pfnet/pysen?tab=readme-ov-file#quickstart-set-up-linters-using-pysen)）。これを見ると `setup.cfg` の役割は不明確である。  
2024年の Python エコシステムでは設定値を `pyproject.toml` に集約することが主流であるから、もし `setup.cfg` の内容が移植可能なら移植したほうが好ましい。  

このような背景から、以下の質問があります：  

- `setup.cfg` の用途は何か
- `setup.cfg`コンテンツを `pyproject.toml` ファイルへ移植・集約することは可能か

## VOICEVOXのバージョン
0.19.0

**Comment by sabonerune** [comment]
https://github.com/pfnet/pysen?tab=readme-ov-file#how-it-works-settings-file-directory
>You may want to keep those setting files on your disk, e.g. when you want to use them for your editor.

主にエディタ等で`pysen`を直接使用しないエディタ等で使用するためのものだと思います。

>また`pysen`の自動生成結果をカスタマイズしたとの記述も含まれている。

自動生成のコメント(`pysen`が各リンターのデフォルトから変更したことについてのもの)のはずでこれを操作しても`pysen`の動作を変えることはできないはずです。

> もし setup.cfg の内容が移植可能なら移植したほうが好ましい。

そもそも`flake8`が`pyproject.toml`非対応かつ対応に[かなり否定的](https://github.com/PyCQA/flake8/issues/234#issuecomment-812800722)。
`pysen`自体の変更(もしくはプラグインを書く？)必要もあるはず。
`pysen`から[`ruff`](https://docs.astral.sh/ruff/)+`mypy`に変える方が現実的かも？

**Comment by tarepan** [comment]
> `pysen`を直接使用しないエディタ等で使用  
> ...  
> これを操作しても`pysen`の動作を変えることはできない  

なるほどです。`pysen` の設定値を外部に吐き出したファイル（≠ config ファイル）で、外部参照用なんですね。  

> そもそも`flake8`が`pyproject.toml`非対応  

知りませんでした。たしかに現状（多分将来的にも）移植不可、ライブラリ入れ替え等が必要そうですね。  

疑問点解決しました、ありがとうございました！
