### ISSUE TITLE
refactor: `Makefile` を解体

### ISSUE THREAD

**Issue by tarepan** [VOICEVOX/voicevox_engine#1269]
## 質問の内容
概要: `Makefile` の用途が知りたい

現在の VOICEVOX ENGINE は pyinstaller ベースのビルドをおこなっており、GitHub Actions での自動ビルドでも pyinstaller を呼び出している。  
一方、レポジトリルートには [`Makefile`](https://github.com/VOICEVOX/voicevox_engine/blob/master/Makefile) も定義されており、Docker 関連らしきコードが書かれている。  
`make` コマンドが見つからなかったため、この `Makefile` の用途は判然としない。  

このような背景から、以下の質問があります：  

- [x] `Makefile` は現在も機能しているファイルか否か
- [x] `Makefile` を削除することは可能か

## VOICEVOXのバージョン
0.19.0

**Comment by Hiroshiba** [comment]
昔docker版を作るときに便利コマンドとして配置された、という感じの記憶が微かにあります！
ただテストされていないため、いつの間にか使えなくなってることがあるかもです。

コマンド集として便利そうですが、もしかしたら然るべきところにドキュメントとして書く方が良いのかもとか思いました。
docs/docker.mdを作るとか。

ビルドノウハウがあるかもなので、コメントや引数などをworkflows/build-docker.ymlへの移植を検討しても良いかも。

作成当時から２年が経ち、世間的にmakeユーザーも減少傾向かもなので運用を見直す機会かもしれません。
個人的にはREADMEにコマンドを移すか検討しつつ、

@aoirint さんも良かったら気軽にご意見伺えると🙏

**Comment by aoirint** [comment]
方針としては、機能しておらず、いろいろと問題を抱えているので、消していいと思います。

- ドキュメントが存在しない
- 非サポートになったUbuntu 18.04の消し忘れ
- arm64版の未サポート

用途としては、以下のようなものがあると思います。

- Dockerイメージをローカルでビルドするため、Dockerイメージの各バリエーションごとのビルド時オプション`--build-arg`の既定値を提供する
- Dockerイメージのビルド不具合の調査のため、ステージ`--target`ごとにタグを付けてビルドする機能

ドキュメントとして代替できるといいと思います。対応関係としては、開発者・貢献者向けガイドの内容になると思います。

**Comment by tarepan** [comment]
着手します。
