### ISSUE TITLE
refactor: poetry の group `dev` と `test` を統合

### ISSUE THREAD

**Issue by tarepan** [VOICEVOX/voicevox_engine#1282]
## 内容
概要: poetry の group `dev` と `test` を統合してリファクタリング  

現在の VOICEVOX ENGINE は依存パッケージを poetry で管理している。それらパッケージは group 機能を用いて分割管理されており、これにより必要最少量のパッケージを場面に応じてインストールできる。  
具体的には必須パッケージ以外に `dev` と `test` が用意されている。`dev` はビルド用、`test` はテスト用である。  

しかし `dev` に実質的に含まれているパッケージは `pyinstaller` と `pre-commit` の 2 つのみである（`poetry`/`poetry-plugin-export` は `test` と二重管理、`safety` は #1280 で除去予定）。  
この 2 パッケージをインストールするのにかかる時間は 5 秒以下である（実測値）。ゆえに `test` 側にとっては分割管理のメリットがほぼ無い。  
`dev` 側にとっては `pip install -r requirements-dev.txt` 時に `test` のパッケージをインストールせずに済むのでメリットがある。しかし、このコマンドは  `build-engine-package.yml` で 1 回登場するのみである。インストールにかかる時間は 20 秒程度である（実測値）。  

`dev` と `test` を統合できれば、`requirements-test.txt` を廃止できる。  
この場合、使い分けを理解し、都度更新し、変更をレビューするコストを低減できる。また CI と pre-commit で走っている `group.test` と `requirements-test.txt` の乖離確認自動テストを廃止できる。  
代償は（上記にある ）master マージ時のビルド CI が 1 環境 20 秒ほど伸びることである（PR での CI はテストしか走らないので無関係）。  

このような背景から、poetry の group `dev` と `test` を統合するリファクタリングを提案します。  

### Pros 良くなる点
- `pyproject.toml` 単純化・requirements ファイル 1 つ削減による見通し改善
- `dev`/`test` 使い分けの理解コスト削減
- 使い分けミスによるエンバグの予防 (c.f. #1280)

### Cons 悪くなる点
- master ビルド CI 実行時間増（合計 1~2 分？）

### 実現方法
- `test` group 廃止
- スクリプト変更

## VOICEVOXのバージョン
0.19.0

**Comment by sabonerune** [comment]
devグループがあるのはPyInstallerのビルド時に余計な依存をビルド結果に含めないためだったような気がします。(特に`numpy`を入れると`pytest`もビルド結果に含まれてしまいます。)
なので少なくと`PyInstaller`とテストは分離しておく必要があると思います。

`dev`を`PyInstaller`のみにして適切な名前に変更するべき？

**Comment by tarepan** [comment]
> devグループがあるのはPyInstallerのビルド時に余計な依存をビルド結果に含めないため

PyInstaller は依存性解決をせず `site-packages` 内部のパッケージを全て取り込んでしまう、的な話でしょうか？  
（その場合、指摘内容に同意です。現 `dev` 相当の group は必要ですね。PyInstaller に私が疎く…🥺）

**Comment by sabonerune** [comment]
ある程度依存性解決をしますが完璧ではないという感じです。
特にオプションの依存、動的インポート、C/C++拡張パッケージ辺りは弱いと思います。(また、`conda`環境でビルドすると極端に肥大化するという話も聞きます)
`numpy`の場合はテスト機能がパッケージに含まれていて`pytest`をインポートしているためだったような記憶があります。

こういった余計な依存関係の不要な取り込みを手っ取り早く防ぐ方法は「ビルド時にインストールしない」だと思います。

**Comment by tarepan** [comment]
> ある程度依存性解決をしますが完璧ではない  

👍️  
理解しました。  
依存性解決が曖昧/複雑になると手抜いて `site-packages` 見て判断する、とかが PyInstaller でも発生するのかもとざっくり認識しました。  

> `conda`環境でビルドすると極端に肥大化  

具体的な影響の知見ありがとうございます！非常に参考になります。  

----------------------------------------------------------------

> `numpy`の場合はテスト機能がパッケージに含まれていて`pytest`をインポートしているため  

VOICEVOX ENGINE ビルド産物 (`dist/run/run` ファイル) をデコンパイルして中の `.pyc` 一覧を確認しました。  
どうも install all しても `pytest` パッケージは入らないようでした。`_pytesttester.pyc` という 7 KB のファイルが numpy パッケージの中に入っていましたが、パッケージでは無さそうです。  

----------------------------------------------------------------

実際の影響を測るため、インストール済み依存パッケージによるビルドサイズへの影響を計測しました。  
Linux 環境にて CPU mock ビルドをおこない、`dist/run/` ディレクトリのサイズをコマンドで出力しました。  
コマンドと結果は以下になります：  

```bash
# install dev-only, then build
vscode ➜ /workspaces/voicevox_engine (master) $ du dist/run -m -s
141     dist/run

# reset env.

# install all, then build
vscode ➜ /workspaces/voicevox_engine (master) $ du dist/run -m -s
146     dist/run
```

結果として 5 MB のサイズ増を確認しました。  

# dev-only
vscode ➜ /workspaces/voicevox_engine (master) $ du dist/run/run -k -s
6096    dist/run/run

**Comment by tarepan** [comment]
> ある程度依存性解決をしますが完璧ではない  

👍️  
なるほどです。  
依存性解決が曖昧/複雑になると手抜いて `site-packages` 見て判断する、とかが PyInstaller でも発生するのかもとざっくり認識しました。  

> `conda`環境でビルドすると極端に肥大化  

具体的な影響の知見ありがとうございます！非常に参考になります。  

----------------------------------------------------------------

> `numpy`の場合はテスト機能がパッケージに含まれていて`pytest`をインポートしているため  

VOICEVOX ENGINE ビルド産物 (`dist/run/run` ファイル) をデコンパイルして中の `.pyc` 一覧を確認しました。  
どうも install all しても `pytest` パッケージは入らないようでした。`_pytesttester.pyc` という 7 KB のファイルが numpy パッケージの中に入っていましたが、`pytest` そのものではないと考えます。

----------------------------------------------------------------

実際の影響を測るため、インストール済み依存パッケージによるビルドサイズへの影響を計測しました。  
Linux 環境にて CPU mock ビルドをおこない、`dist/run/` ディレクトリおよび `dist/run/run` ファイルのサイズをコマンドで出力しました。  
コマンドと結果は以下になります：  

```bash
# install dev-only
vscode ➜ /workspaces/voicevox_engine (master) $ python -m pip install -r requirements-dev.txt
...
vscode ➜ /workspaces/voicevox_engine (master) $ pyinstaller --noconfirm run.spec
...
vscode ➜ /workspaces/voicevox_engine (master) $ du dist/run -m -s
141     dist/run
vscode ➜ /workspaces/voicevox_engine (master) $ du dist/run/run -k -s
6096    dist/run/run

# reset env.

# install all
vscode ➜ /workspaces/voicevox_engine (master) $ python -m pip install -r requirements.txt -r requirements-dev.txt -r requirements-test.txt
...
vscode ➜ /workspaces/voicevox_engine (master) $ pyinstaller --noconfirm run.spec
...
vscode ➜ /workspaces/voicevox_engine (master) $ du dist/run -m -s
141     dist/run
vscode ➜ /workspaces/voicevox_engine (master) $ du dist/run/run -k -s
6096    dist/run/run
```

- dev-only
  - `dist/run/`: 141 MB
  - `dist/run/run`: 6.096MB
- full
  - `dist/run/`: 141 MB
  - `dist/run/run`: 6.096MB

Linux 環境かつ現在の依存パッケージであれば変化無しとの結果になりました。

------------------------------------------------------------------------

上記の知識と実験結果から、次の 2 つの方針が取りうると考えます：  

- `dev` / `test` は統合しない（特定環境・将来のパッケージ構成でサイズ肥大化のリスクはゼロじゃないから）
- `dev` / `test` は統合する（現状でサイズ肥大化が無い一方メンテ性向上の恩恵にはすぐあずかれるから）

最終的にはメンテナ判断の案件な気もします（@hiroshiba）。  
よろしければ @sabonerune さんのご意見も聞いてみたいです。

**Comment by sabonerune** [comment]
>どうも install all しても pytest パッケージは入らないようでした。

軽く調べたところ`numpy`v1.23.0からフック(パッケージ側からPyInstallerの動作を変更する機能)の提供されるようになり自動的に`pytest`やその他の不要な依存が入らないようになったみたいです。

---

個人的には
- `PyInstaller`のみのグループはあった方がいい。(単なるファイルサイズだけでなくライセンスファイルのリスクもある)
- `dev`グループに`PyInstaller`と`poetry`周りだけというのがおかしい。(開発にはLinterも必要では?)

と考えています。なので、

- `dev`と`test`を`PyInstaller`を除いて統合する。
- `PyInstaller`のみのグループを新設する。

がいいと思います。

**Comment by tarepan** [comment]
> `numpy`v1.23.0からフック  

初めて知りました、NumPy 側も問題視していたんですね。情報ありがとうございます！  

----------------------------------------------------------------------------

> `dev`グループ ... 開発にはLinterも必要では?
> ...  
> `dev`と`test`をPyInstallerを除いて統合する。  

👍️  
現状の `dev` が `build` 的な動きをしていて名称に違和感があることに同意です。  
`dev` であれば linter や test 系まで含むのが自然であり、その点で「`dev`と`test`を`PyInstaller`を除いて統合」にも同意です。  

> ライセンスファイルのリスク  

認識確認させてください。  
このリスクというのは「思わぬ test 系ライブラリがビルド産物に混入したが、`requirements.txt` ベースで自動生成した `licenses.json` には混入ライブラリが乗っておらず、結果としてライセンス違反になる」的なリスク、で解釈合っているでしょうか？  
もしこれならなるほどです、考えたこと無かったです。レピュテーション上の深刻な問題を引き起こしうるため、万全を期す価値があると感じます。

**Comment by sabonerune** [comment]
@tarepan 
>「思わぬ test 系ライブラリがビルド産物に混入したが、requirements.txt ベースで自動生成した licenses.json には混入ライブラリが乗っておらず、結果としてライセンス違反になる」的なリスク

はい。その通りです。

**Comment by tarepan** [comment]
@sabonerune さんの方針に同意します。  

- [ ] PyInstaller のみを含む `build` group を新設 (#1292)
- [ ] 現 `dev` を廃止 (ref #1280)
- [ ] `test` を `dev` へリネーム

の段階を経て実装します。  

@sabonerune さん、議論ありがとうございました。お時間あれば PR review 頂けるととても心強いです。

**Comment by Hiroshiba** [comment]
僕もライセンスの混入を避けるのが目的だと認識してました！
pyinstallerが余計なものを、というのもなるほどです。

buildの新設、良いと思います！
