### ISSUE TITLE
非アクティブ issue 180日チェックの動作確認

### ISSUE THREAD

**Issue by tarepan** [VOICEVOX/voicevox_engine#1303]
（未確定バグ。一旦報告として issue 作成）

## 不具合の内容
非アクティブ issue 180日チェックが機能していない可能性があり、動作確認が必要である。  

https://github.com/VOICEVOX/voicevox_engine/pull/1220#issuecomment-2118644702

## VOICEVOXのバージョン
0.19.0

**Comment by Hiroshiba** [comment]
一番時間立っているissueがこれでしょうか･･･？

- https://github.com/VOICEVOX/voicevox_engine/issues/322

たぶんラベル付与とかはリセットにならない感じですよね。
となるとたしかに反応してないのかも･･･？（あるいは180日ちょうどのときに反応する･･･？）

**Comment by Hiroshiba** [comment]
たぶん確認できたのでcloseします！
