### ISSUE TITLE
後ろの無音時間を少し長くして生成して品質を上げる

### ISSUE THREAD

**Issue by Hiroshiba** [VOICEVOX/voicevox_engine#132]
## 内容

今のコアは、前後の無音時間を0.5秒ほど設定することで、最初と最後の音声が途切れやすい問題を軽減することができます。
最初の音声の無音は0.7.0アップデートで対処したのですが、最後の無音はそのままになっています。
ワークアラウンドですが、この処理もエンジンに含めると音声の品質が上がったように感じられそうです。

## VOICEVOXのバージョン

0.?.0

**Comment by qwerty2501** [comment]
このissueですが、 https://github.com/VOICEVOX/voicevox_core/issues/17 でまとめてやった方が良さそうですか？

**Comment by Hiroshiba** [comment]
そうですね、コアの方に実装が入るならエンジン側の実装は要らないはずです！

**Comment by Hiroshiba** [comment]
https://github.com/VOICEVOX/voicevox_core/issues/17 で解決されたのでclose！
