### ISSUE TITLE
remove: Preset は voicevox_dir に依存すべきではない

### ISSUE THREAD

**Issue by tarepan** [VOICEVOX/voicevox_engine#1377]
## 内容
概要: プリセットが voicevox_dir へ依存しないように仕様を変更したい

プリセット機能が参照するプリセットファイルは引数等から設定可能である（以下、`参照ファイル設定` と呼ぶ）。  
参照ファイル設定は「エンジン既定値を使うか」「ユーザー指定値を使うか」を選択可能にすることでユーザーに気に入ったプリセットを利用してもらう意義がある。  

ところで、設定可能なファイルの 1 つに `"{voicevox_dir}/presets.yaml` がある。  

https://github.com/VOICEVOX/voicevox_engine/blob/71aa41402285770db23e570a3e1a930afb4fee73/run.py#L321-L324

これは参照ファイル設定の意義と合致しない。  
なぜなら voicevox_dir は別バージョンエンジンへのリンクであり、これを使うことは「古いエンジン既定値を使う」ことになる。  
新しいエンジンに古いエンジンのプリセット既定値を渡す意義はほとんど無い。あるとしても、それはユーザー指定値として渡せばいい。  
現在の仕様ではむしろ、コア等のために voicevox_dir を設定したらなぜかプリセットまで別物が参照されるという不自然な動作を生んでしまう。  

このような背景から、プリセットが voicevox_dir へ依存しないような仕様変更を要望します。  

### Pros 良くなる点
- 意図しない参照ファイル設定が起きなくなる
- 実装が単純化する

### Cons 悪くなる点
- （現状がトリッキーな動作だとはいえ）後方互換性を破壊する

### 実現方法
- プリセットファイルの parent を `root_dir` → `engine_root()` に変更

## VOICEVOXのバージョン
0.19.0

**Comment by Hiroshiba** [comment]
`voicevox_dir`に依存しない形が綺麗だと思います！

↓のissueのアイデアに「保存先ディレクトリを設定ファイルと同じとこにする」とあるので、もう`voicevox_dir`も`engine_root`もやめて`save_dir`内に保存する方式にすれば一石二鳥かも・・・？

- https://github.com/VOICEVOX/voicevox_engine/issues/876

**Comment by tarepan** [comment]
> `voicevox_dirに依存しない形が綺麗  

👍️  
実装します。

-------------------------------------------------------------------------

> 一石二鳥  

以下の課題があるため、段階的に取り組むべきと考えます。  

現在の辞書機能は「不変のデフォルト辞書 + 可変のユーザー辞書」という構成です。  
一方、現在のプリセットはデフォルトプリセットとユーザープリセットが混ざった実装になっています。すなわち、プリセットファイルを指定するとそれが初期化として利用され、かつプリセットの追加がこのファイルへの append になっています。  
この状態で保存先ディレクトリを `local` 等にした場合、初期値指定の仕組みがなくなります。  
ゆえに現状では一石二鳥ができません。

**Comment by Hiroshiba** [comment]
たしかに一石二鳥ではない気がしました！

PR見て、voicevox_dirではなくengine_dirに依存すべきだというのを把握しました！
とても良いと思います！！
