### ISSUE TITLE
refactor: `build_util` ディレクトリを `scripts` へリネーム

### ISSUE THREAD

**Issue by tarepan** [VOICEVOX/voicevox_engine#1380]
## 内容
概要: `build_util` ディレクトリを `scripts` へリネームしてリファクタリング

現在の `build_util` は様々なスクリプトを含んでおり、その目的はビルドに限らない（例: [`get_cost_candidates.py`](https://github.com/VOICEVOX/voicevox_engine/blob/master/build_util/get_cost_candidates.py)）。  
Python のメジャーなレポジトリではビルドスクリプトその他をまとめて `scripts` ディレクトリに入れるのがデファクトである（例: [PyTorch - `/scripts`](https://github.com/pytorch/pytorch/tree/main/scripts), [FastAPI - `/scripts`](https://github.com/tiangolo/fastapi/tree/master/scripts)）。  

このような背景から、`build_util` ディレクトリを `scripts` へリネームするリファクタリングを提案します。  

ref #688

### Pros 良くなる点
- Python デファクトに沿った命名による見通し改善

### Cons 悪くなる点
無し

### 実現方法
- リネーム

## VOICEVOXのバージョン
0.19.0

**Comment by Hiroshiba** [comment]
とりあえず`scripts`を目指すのが良さそうに思いました！
ビルド時にしか使わない系のは更に`build`とかで分けるとわかりやすそうですね！
まあ･･･ライセンスファイルの作成とか、buildなのかそうじゃないのかどっちなんだってなりますが･･･。

pytorchは`tools`と`scripts`がありますね。何が違うんだろう。

**Comment by tarepan** [comment]
> scriptsを目指すのが良さそう  

👍️  
実装します。

-------------------------------------------------------------------------

> pytorchは`tools`と`scripts` ... 何が違う  

両方ともビルド系含めて色々入っています。  
`scripts` は（不思議ですが）Python パッケージになってます。pip install したい事情とかがあったんですかね？
