### ISSUE TITLE
refactor: 外部の値（例: 環境変数、CLI 引数）を読み込む際に型を付ける

### ISSUE THREAD

**Issue by tarepan** [VOICEVOX/voicevox_engine#1404]
## 内容
（追記: バリデーションは実装しない）

概要: 外部の値を読み込む際にバリデーションし型を付けるリファクタリング

現在の VOICEVOX ENGINE は外部の値（例: 環境変数、CLI 引数）を読み込む際、バリデーションをしていない。  
それら値の型は型アノテーション付き変数に代入する際に与えられている。  

https://github.com/VOICEVOX/voicevox_engine/blob/e3d49cc03390db9bf9feb8076991e2691d7b7507/run.py#L255

読み込むべき外部の値は事前に判明しているため、その名前と型はコード上に明示できる（ある種のスキーマ）。  
そしてこのスキーマを利用すれば、実際に来た外部の値をバリデーション・型付けできる。  
pydantic はこの用途に適したライブラリであり、ENGINE はこれを採用している。  

このような背景から、外部の値を読み込む際にバリデーションし型を付けるリファクタリングを提案します。  

### Pros 良くなる点
- バリデーションによる安全性向上
- 型付けによる見通し改善

### Cons 悪くなる点
無し

### 実現方法
- dataclass によるスキーマ定義
- pydantic TypeAdapter によるバリデーション

## VOICEVOXのバージョン
0.19.0

## その他
実例として CLI および環境変数へ適用する PR を作成しました（バリデーション未実装, #1401, #1402）。Go/NoGo 判断の一助にお使いください。

**Comment by Hiroshiba** [comment]
構造体に詰め込むの、良いと思います！！

CLI引数の方はargparseの時点で型のバリデーションが完了しているかもしれません。
たぶん`int`なとこに文字列入れるとエラーになると思います。

環境変数の方も`int()`とかを通したときに型はバリデーションされているかもです。

---

別観点なのですが、環境変数とCLI引数は統一できるのではとちょっと考えてます。
[uvicornとかはそうなっていて](https://www.uvicorn.org/settings/#:~:text=You%20can%20also%20configure%20Uvicorn%20using%20environment%20variables%20with%20the%20prefix%20UVICORN_.%20For%20example%2C%20in%20case%20you%20want%20to%20run%20the%20app%20on%20port%205000%2C%20just%20set%20the%20environment%20variable%20UVICORN_PORT%20to%205000.)、全部のオプションが環境変数とCLI引数で指定可能です。
どうやら[click](https://github.com/encode/uvicorn/blob/40b99b8436c0c261e3a85d10e291424072946292/uvicorn/main.py#L59)で実現されてるらしいです。
こういう感じで、先にclickや、あるいはTyperとかでしょうか（ちょっとリッチすぎるかもですが）、とかで構造体の統一化するのもありかもと思いました。

とはいえデータ構造にするのは一旦賛成です！

**Comment by tarepan** [comment]
> バリデーションが完了  

👍️  
妥当な指摘です。  
バリデーションは別の仕組みで実装済みであるため、構造体化（型付け）のみをおこないます。  

-------------------------------------------------------------------

> 別観点なのですが、環境変数とCLI引数は統一できるのでは

👍️  
同意です。  
言語関わらずよくあるニーズであるため、Python ライブラリも充実していると想像しています。  
ライブラリ選定が重要そうであるため、（できれば利用経験ある方を入れて）個別 issue でゴール像とそれにあったライブラリを丁寧に議論するのが良さそうです。  

--------------------------------------------------------------------

> 先にデータ構造にするのは一旦賛成  

👍️  
着手します。

**Comment by tarepan** [comment]
完了につき close します。
