### ISSUE TITLE
API 用 BaseModel 名の変更による影響範囲が知りたい

### ISSUE THREAD

**Issue by tarepan** [VOICEVOX/voicevox_engine#1411]
## 質問の内容

概要: API 用 BaseModel 名の変更による影響範囲が知りたい

API 用 BaseModel（例: `MorphableTargetInfo`）は API の入出力を規定している。  
https://github.com/VOICEVOX/voicevox_engine/blob/f26d12410d711c89a7d2861d27de2b96f47a939f/voicevox_engine/app/routers/morphing.py#L48-L50

その属性は API の型そのものであり、その変更は API 変更となる。ゆえに変更は厳密に管理されている。    

ところで API 用 BaseModel はクラスであり、クラス名を持っている。このクラス名は API の引数名・属性名には現れてこないが、スキーマを通じてユーザーへ開示されている。  

https://github.com/VOICEVOX/voicevox_engine/blob/f26d12410d711c89a7d2861d27de2b96f47a939f/test/e2e/__snapshots__/test_openapi/test_OpenAPI%E3%81%AE%E5%BD%A2%E3%81%8C%E5%A4%89%E3%82%8F%E3%81%A3%E3%81%A6%E3%81%84%E3%81%AA%E3%81%84%E3%81%93%E3%81%A8%E3%82%92%E7%A2%BA%E8%AA%8D.json#L534-L536

API 用 BaseModel の名称を変更したいケースがしばしば発生しているが、スキーマ変更を伴うので現時点では避けている。しかし、もし「引数名・属性名変更を伴わないスキーマ変更」が問題無いのであればリネームが可能になる。  
これを判断するには影響範囲の理解が大前提である。  

このような背景から次の質問があります：  

Q: **API 用 BaseModel 名の変更による影響範囲はどの程度か**

## VOICEVOXのバージョン

0.19.0

**Comment by Hiroshiba** [comment]
なるほどです！

とりあえずパッと思いつくのは、OpenAPIを使って型を自動定義している場合は破壊的変更になる点かなと思います。
といってもたぶん一番影響があるのはエディタなので、とりあえずエディタが大丈夫か考えることになりそう。
なので影響範囲はとりあえずエディタかなと。

大変さはBaseModelによると思います。AudioQueryやAccentPhraseなんかはすごい広範囲で使ってるので大変かもです。

名前を変更しない他の案ですが、もしopenapi.jsonを全く変えず、ENGINEコード内のBaseModelの名前だけ変えられればよいのかもです。
マイグレーションのためにスキーマの名前を変えたくない、みたいなのはよくあることだと思うので、もしかしたらfastapi側がリネームに対応しているかも･･･？
（引数名の変更は対応してるんですよね。`style_id`あたりがそうです。）

**Comment by tarepan** [comment]
> OpenAPIを使って型を自動定義している場合は破壊的変更になる  
> ... 影響範囲はとりあえずエディタ

👍️  
回答ありがとうございます！非常に参考になります。  

> fastapi側がリネームに対応しているかも  

pydantic 含め、クラス名そのもののリネームには対応していないようでした。

**Comment by Hiroshiba** [comment]
> pydantic 含め、クラス名そのもののリネームには対応していないようでした。

なるほどです。残念ですね。。
あるいは`custom_openapi`でスキーマ名を変えるみたいなのができれば良いのですが･･･。
