### ISSUE TITLE
ドキュメント（とコメント）の「スコア」と「楽譜」が表記揺れしている

### ISSUE THREAD

**Issue by Hiroshiba** [VOICEVOX/voicevox_engine#1461]
## 不具合の内容

どちらも同じ意味ですが、表記揺れしているのは微妙なので直したいです。
とりあえずメモまで。

## その他

どっちに寄せるのがいいか難しいけど、ノートは音符にしているので、楽譜に寄せる方が良さそう！

**Comment by naga-na** [comment]
こちら対応しても良いでしょうか？
「スコア」→「楽譜」のイメージで置換しようと思います！

**Comment by Hiroshiba** [comment]
すみません遅くなりました！
置き換え良いと思います、ありがとうございます！！

**Comment by naga-na** [comment]
@Hiroshiba 
ご確認いただきありがとうございました！
また対応できそうなissueがあれば、挑戦してみようと思います！

1点お願いがあります。
issueのクローズだけお願いできますでしょうか？
プルリクに「close #1461」の記載が漏れていて、issue側では私の方でクローズができなそうです。
ご面倒をおかけして申し訳ないですが、お手隙の際にクローズお願いします🙇

**Comment by sevenc-nanashi** [comment]
閉じておきました。
