### ISSUE TITLE
プリセット保存先ディレクトリのデフォルトを、設定ファイルが保存されるディレクトリと同じディレクトリにする

### ISSUE THREAD

**Issue by Hiroshiba** [VOICEVOX/voicevox_engine#1479]
## 内容

プリセットの保存先はデフォルトでエンジンディレクトリに保存されます。
これは例えば管理者権限が必要なディレクトリにエンジンがインストールされていた場合にエラーになります。

- https://github.com/VOICEVOX/voicevox_engine/issues/1478

もっと権限が簡単なディレクトリ、例えば設定ディレクトリに保存するようにすればこの問題は回避できるはずです。

ちなみに設定ファイルの保存先はここで決まっています。

https://github.com/VOICEVOX/voicevox_engine/blob/3ec65ed4e50fda8972d13285636779bd956ffa86/voicevox_engine/setting/setting_manager.py#L26C27-L26C41

### Pros 良くなる点

広い環境で正しく実行できる

### 実現方法

可能なら以前のプリセットファイルをmvする処理もあると良さそう！
結構大変だと思うのでどういう実装がいいか聞いていただければ 🙏 

## その他

結構簡単だと思うのでもしよかったらぜひ！

**Comment by takana-v** [comment]
こちら未修正のままだと全ユーザー向けでインストールした時にエラーが発生してしまうため、私の方で修正したいと思います。

**Comment by Hiroshiba** [comment]
！！　使い辛いポイントが減るのでとても良さそう！！
