### ISSUE TITLE
REST API: GET /downloadable_libraries が 500 Internal Server Errorを返す

### ISSUE THREAD

**Issue by TORISOUP** [VOICEVOX/voicevox_engine#1481]
## 不具合の内容

voicevox.exe　0.21.1を使用しています。
REST API の : GET /downloadable_libraries が "Internal Server Error"というレスポンスを返します。
エラーログは何も出力されませんでした。

### 現象・ログ

上記REST APIを使用すると"Internal Server Error"とだけ返ってくる。

### 再現手順

```
curl -X 'GET' \
  'http://localhost:50021/downloadable_libraries' \
  -H 'accept: application/json'
```

## VOICEVOXのバージョン

0.21.1

## OSの種類/ディストリ/バージョン

- [x] Windows
- [ ] macOS
- [ ] Linux

Windows 11 Pro 64bit (23H2 22631.4391)
AMD Ryzen 9 5950X
RTX3090

**Comment by Hiroshiba** [comment]
ご報告ありがとうございます！！

`/downloadable_libraries`は製品版VOICEVOX.exeでまだサポートされていないもので、API は露出していないべきなのですが、露出していることが問題そうです。

調べてみたところ、サポートフラグをfalseにし忘れていることに気づきました 🙇 
下記issueが解決すると、自動的にこちらのissueも解決となりそうです。

- https://github.com/VOICEVOX/voicevox_resource/issues/70

修正したいと思います！

**Comment by TORISOUP** [comment]
ありがとうございます！状況を把握できました。
よろしくお願い致します。
