### ISSUE TITLE
テストを書いてCIを設定したい

### ISSUE THREAD

**Issue by Hiroshiba** [VOICEVOX/voicevox_engine#16]
バージョン0.3.0アップデートの際に、簡単に気づけそうなバグがあった状態でリリースされてしまいました。
https://github.com/Hiroshiba/voicevox_engine/pull/15/files#diff-d6af0459a37d985953d7040c14f53feb3b9cc9e58b543aa3c2b80256d276c5e0

この部分は音声ライブラリがなくても動くので、テストを書いていれば気づけたはずです。
とりあえずgithub actionsでCIを設定して、音声ライブラリのモックを作ってテストを充実させていきたいです。

**Comment by y-chan** [comment]
出来るところまでやってみようかと思います。

**Comment by Hiroshiba** [comment]
ありがとうございます、ぜひお願いします。

テストライブラリは何を用いられる予定でしょうか。
（pytestであればちょっとわかりますが、もっと良いのがあればそちらを適用したいです。）

**Comment by y-chan** [comment]
以前、FastAPIを用いたアプリケーションのテストを途中まで実装したことがあるのですが、この際はunittestとpytestの合わせ技みたいな形でやりましたね。
https://github.com/atomicswap-network/asns/blob/develop/test/test_api.py
上の例のような形で実装してみようかと思います。

**Comment by Hiroshiba** [comment]
良いと思います！

**Comment by y-chan** [comment]
叩けるAPIを叩いて、予想される挙動をするか(何かしらエラーを吐かないか)、というテストを書いていたんですが、これだと音声ライブラリが必要になってしまいますね...
各classや関数ごとにテストを書くのが正しいと思われるので、その方向で調整します...

**Comment by Hiroshiba** [comment]
ランダムな値を返す音声ライブラリのモックを作っても良いかもと思いました。

**Comment by Hiroshiba** [comment]
とりあえずCIが整備され、かつテストも実装されたのでcloseしたいと思います。
（ @y-chan さんありがとうございました！）
