### ISSUE TITLE
Github Actionsでビルドしたものをテスト実行する

### ISSUE THREAD

**Issue by Hiroshiba** [VOICEVOX/voicevox_engine#176]
## 内容

自動ビルドされたエンジンをローカルの環境で動かしたときに動かないことがちょくちょくあります。
おそらくその環境依存であることが多いのかもしれませんが、そもそもちゃんと動くはずであるということを保証できるとCD的にはかっこいいのかなと思いました。

ref: https://github.com/Hiroshiba/voicevox/issues/399#issuecomment-958948648

### Pros 良くなる点

動かなかったときの問題の切り分けが簡単になる

### Cons 悪くなる点

GPU版の実行テストはどうしてもできない

### 実現方法

ビルド済みのバイナリを、Github Actions上で動かしてみるのが良いのかなと思いました。

**Comment by y-chan** [comment]
リリース作成時にテストを実行してあげるとよいのかなと思いましたが、そもそもmasterのコードが変更(push/merge)された際に毎回ビルドしてテストを回してあげるとよさそうだなと思いました。

ちょっと実装してみようかなと思います。

**Comment by Hiroshiba** [comment]
良いと思います！！

**Comment by Hiroshiba** [comment]
- https://github.com/VOICEVOX/voicevox_engine/issues/264

のように、バイナリにしたときにエラーが出ることもありそうなので、ビルド済み実行ファイルをテストする機運が高まった気がしました。
（↑の場合だとエディタ側をビルドする前に気づけたので、時間にして１日ほど加速できたかもです。）
ということで優先度を高にしてみます･･･！

**Comment by Hiroshiba** [comment]
ちょっと挑戦してみています！
