### ISSUE TITLE
.gitattributesでリポジトリ内のファイルの改行コードを統一したい

### ISSUE THREAD

**Issue by qwerty2501** [VOICEVOX/voicevox_engine#221]
## 内容
現在のこのリポジトリは基本的に改行コードがLFだが一部CRLFとなっており統一されてない。
[.gitattributes](https://qiita.com/nacam403/items/23511637335fc221bba2)を使用することによって改行コードをLFに統一したい。

### Pros 良くなる点
- 改行コードが統一されることにより将来的にPR出した際に変な差分が出ることを軽減できる

### Cons 悪くなる点
- 既存ファイルがCRLFのものがあるので、しばらくの間はその差分が出てくる可能性がある

### 実現方法
リポジトリのルートディレクトリに.gitattributesファイルを作成し、以下のような感じに設定する？
```
* text eol=lf
*.png -text
```
バイナリファイルが他にもあるなら.pngのように設定する必要がありそう

## その他
やった経験がないので[公式ドキュメント](https://git-scm.com/docs/gitattributes#_text)をちゃんと読み込む必要あり

**Comment by Hiroshiba** [comment]
良いですね！！
たまに `^M` みたいなマークが現れることがあったので、早い目に対処して良いと思います。

**Comment by aoirint** [comment]
#225 で.gitattributesが追加され、既存コードの改行コードもLFに統一されたので、このIssueはCloseします。

漏れなどあればIssueやプルリクエストで！
