### ISSUE TITLE
自動調整によって擬似的に疑問文に対応する

### ISSUE THREAD

**Issue by Hiroshiba** [VOICEVOX/voicevox_engine#222]
## 内容

現状のVOICEVOXは疑問文に対応できていませんが、「語尾を伸ばし、伸ばした方の音の音高を上げ、伸ばした方の音を少し短くする」調整をすれば、疑問文っぽい音声を作れます。
この調整を自動で行えば、擬似的に疑問文に対応できそうです。

### Pros 良くなる点

疑問文対応っぽいことができる

### Cons 悪くなる点

大体の場合でうまくいくパラメータを見つける必要がある

### 実現方法

疑問文かどうかはopenjtalkから得られます。（単純に？が含まれるかどうかでも良いかも）
あとは最後のアクセント句に伸ばし棒用の音素を追加して、普通に音素長・音高を取得したあと、自動調整すればそれっぽくなるんじゃないかなと思っています。

こうするとエディタ側から見ると「疑問文にするとなぜか伸ばし棒が最後に付く」という挙動になりますが、まあ、疑問文未対応よりは良いのかなぁと思っています。。
（伸ばし棒用の音素だけ非表示にする実装にしても良いかも）

## その他

- https://github.com/VOICEVOX/voicevox_project/issues/5

**Comment by qwerty2501** [comment]
> 疑問文かどうかはopenjtalkから得られます。（単純に？が含まれるかどうかでも良いかも）

openjtalkの精度がどの程度かはわからないですが、疑問系にしたつもりがないのに疑問系な音声がえられるのは違和感をユーザーに与えてしまうのではないでしょうか。
単純に?の有無で判定したほうがユーザーとしても得られる音声を予め想像しやすいかなと感じました。手間としても一文字足すだけですし

**Comment by Hiroshiba** [comment]
おっしゃる通りだと思います。ちなみにopenjtalkも？の有無で疑問文かどうかを判断してそうな気がします。

**Comment by qwerty2501** [comment]
それならopenjtalk利用ありかもですね。ある程度の事前確認は必要そうですが

**Comment by qwerty2501** [comment]
requirementsの更新がないという保証があるか、更新があってもrequirements.txt英の改行の差分については許容していただきたいです。
そうでなければ、gitattributesの修正がmergeされてrequirements.txt系の改行コードが完全に統一されるまでは絶対にNoです。
あの作業はトラウマなのでもう二度とやりたくありません！！！

**Comment by takana-v** [comment]
#219 がマージされたらrequirementsの改行コードを統一するPRを出そうかと思います。
因みに改行はnkfコマンドで変換できます。
https://atmarkit.itmedia.co.jp/ait/spv/1609/29/news016.html

**Comment by takana-v** [comment]
#225 がマージされましたが、このissueに取り組まれますか？ @qwerty2501 
難しいようであれば私の方で対応したいと思います。

**Comment by qwerty2501** [comment]
わがままを通していただいて心苦しいのですが、私がやる場合これからPythonについて調べるので時間がかかってしまうかもしれません。
やれるだけやってみますが、優先度中とのことなのでもし急いでて待てないようなら私のことは無視してそちらで作業していただいて構いません。

私が担当する場合以下の情報をいただけると非常に助かります。
- engine内のどの部分に機能追加すればよいか？
- openjtalkのAPIドキュメントへのリンク

**Comment by qwerty2501** [comment]
おそらく [ここ](https://github.com/VOICEVOX/voicevox_engine/blob/master/voicevox_engine/full_context_label.py#L517)のあとに疑問文だったら疑問文ぽい音素をphonemesの最後に追加してあげればいいのかなと思ったんですがどうですかね？
疑問文かどうかの判定ですが、 `pyopenjtalk.extract_fullcontext`  から返ってくるlabelにその情報が含まれているのでしょうか？

**Comment by Hiroshiba** [comment]
疑問文かどうかは仰るとおりフルコンテキストラベルの中に含まれています！
おそらくe3かf3かg3で、アクセント句（accent_phrase）ごとに0/1が振られているっぽいです。

ちなみにフルコンテキストラベルの仕様は、
http://hts.sp.nitech.ac.jp/?Download の HTS-2.3のJapanese tar.bz2 (126 MB)をダウンロードして、data/lab_format.pdfを見るとリストが見つかります。

> engine内のどの部分に機能追加すればよいか？

今リファクタリング中なのでコードの場所が変わってしまうかもですが、
create_accent_phrasesと同じとこが良いのかなと感じました。
https://github.com/VOICEVOX/voicevox_engine/blob/5fe249eb3bb7b5a03009c5ce418a623b35bdfd3a/voicevox_engine/synthesis_engine/synthesis_engine_base.py#L71

AccentPhraseに音高や音素ごとの長さの情報が入っています。
これを疑問文っぽくしたAccentPhraseを出力することになるのかなとか想像しています。

**Comment by qwerty2501** [comment]
まだ実装途中ですが、コード見ながらのほうが議論しやすいと思ってDraft PR出しました。

**Comment by Hiroshiba** [comment]
実装されたのでcloseします！
エディタ側のissueはこちらにあります

- https://github.com/VOICEVOX/voicevox/issues/608
