### ISSUE TITLE
pre-push時にgenerate_licenses.pyが成功するか確認する

### ISSUE THREAD

**Issue by qwerty2501** [VOICEVOX/voicevox_engine#223]
## 内容
requirements-dev.txtに変更が入った際に、generate_licenses.pyの修正を忘れてしまうとpushしてから間違いに気づくので負担が増えてしまう。
push前にgenerate_licenses.pyが成功するか確認してレビュワーの負担を減らす

### Pros 良くなる点

レビュワーの負担が減る

### Cons 悪くなる点

pre-push時の処理がやや重くなる

### 実現方法

pre-commitの設定を追加してpre-push時のイベントをhookする

## その他
pre-commitの設定で特定ファイルにのみ変更があった場合にhookする設定があったはずなので、requirements-dev.txtに変更があった場合にのみhookするように設定すれば、pre-push時に処理が重くなるのを可能な限り避けることができるはずです。

refs https://github.com/VOICEVOX/voicevox_engine/pull/219#issuecomment-986738807

**Comment by qwerty2501** [comment]
@Hiroshiba CIと処理を同じにしたいので、シェルスクリプトファイルを作って共通化したほうが良いかもです。
また[エラーメッセージをわかりやすくしたい](https://github.com/VOICEVOX/voicevox_engine/pull/219#issuecomment-986798131)とのことですが、これについてはgenerate_licenses.pyを修正してわかりやすいメッセージを出力するようにしたほうが良いかもですね

**Comment by Hiroshiba** [comment]
> CIと処理を同じにしたいので、シェルスクリプトファイルを作って共通化したほうが良いかもです。

意図がちょっとつかめていないのですが、コマンドプロンプトなどの環境によってはシェルスクリプトが動かないので、シェルスクリプトを使っても共通化できないかもしれません・・・。

**Comment by qwerty2501** [comment]
CIで行っている[ここ](https://github.com/VOICEVOX/voicevox_engine/blob/master/.github/workflows/test.yml#L79-L88)と全く同じ処理をして確認する必要があると思いますので、この部分をシェルスクリプトファイルで書き出してCIとpre-pushの際に呼び出すようにしたほうが良いと思います。

Windowsの場合だと[Git Bash経由でgit hooksが呼ばれている](https://yanor.net/wiki/?Git/%E3%83%95%E3%83%83%E3%82%AF/Windows%E3%81%A7pre-commit%E3%82%92%E5%AE%9F%E8%A1%8C%E3%81%99%E3%82%8B)ようなので、多分大丈夫だとは思ってます。
ただ私はWindows環境を持ってないのでどなたかに追加したpre-pushの処理がちゃんと動作するか確認していただく必要がありますが

**Comment by Hiroshiba** [comment]
なるほどです、よくわかりました！
該当箇所のシェルスクリプトは、`python generate_licenses.py`以外は環境依存なので、`python generate_licenses.py`だけ実行するのが正しそうです。

**Comment by qwerty2501** [comment]
> 該当箇所のシェルスクリプトは、python generate_licenses.py以外は環境依存なので、python generate_licenses.pyだけ実行するのが正しそうです。

それ以外も必要だと思います。
generate_licenses.pyはrequirements-dev.txt以外のパッケージをインストールしてる環境だとエラーになるようです。
実際私の環境で `python generate_licenses.py` をそのまま実行するとエラーで落ちます
venvはptyhonの標準機能として組み込まれてるので誰でも実行できますし、環境に依存しない形で書こうとするとむしろCIに書かれてるスクリプトをそのまま実行しないと人によってはエラーになると思います。

**Comment by Hiroshiba** [comment]
なるほどです。たしかに環境を作り直すほうが正しそうです。
となると、venv作って`pip install`する必要があるので、pre-pushに含めてしまうとpushするたびに時間がかかってしまいそうですね･･･

pushするたび数分かかる処理を全員にお願いするか、ライセンスが不明なライブラリが入った場合だけ修正をお願いするかのトレードオフという形になりそうです。
この２択なら、後者の方が良いのかなと思いました。

もしくは普段実行するテストからは省いてしまって、releaseするときだけ実行するのもありかもです。

**Comment by qwerty2501** [comment]
その他に書いておきましたが、pre-commitの機能でrequirements-dev.txtに対する変更が入ったときだけこの確認を実行することができたと思うので、実際に実行するのは最小限に抑えれると思います。
ただ頻繁にrequirements-dev.txtの更新が入るようならやはりストレスになるかと思いますのでそれが気になるならこの対応はしないほうが良いでしょう。

一番ベストなのは`generate_licenses.py`の処理をrequirements-dev.txtの内容を読み取ってそこからライセンス生成するように修正するのが良いような気がしますが、そこまでのコストをかけるべきかはやや疑問ではあります。

**Comment by qwerty2501** [comment]
追記: そもそもpre-commitの導入自体が受け入れられるかまだわからないのでいったん保留でいいかもしれませんね。

> もしくは普段実行するテストからは省いてしまって、releaseするときだけ実行するのもありかもです。

現実的なのでアリだと思います。

**Comment by Hiroshiba** [comment]
> requirements-dev.txtに対する変更が入ったときだけこの確認を実行することができたと思う

すみません、ちゃんと内容を把握できていませんでした…
なるほどです！！
変更&push時だけであれば、確認するのも良いかなと感じました。

**Comment by qwerty2501** [comment]
このリポジトリの.gitignoreにvenvディレクトリが含まれてるようなので、すでにvenvディレクトリを使用してvenvを使ってengineの開発を行っている人がいそうです。
なので実際にこのissueに対応する必要がある場合はCIの処理からvenvに使用するディレクトリ名を変更する必要があると思います

**Comment by tarepan** [comment]
本 issue が解決したい最大の問題は「CI test failed な PR をレビュアーが逐一チェックしなければならない」点であり、これを解決するために「`generate_licenses.py` が fail するものを pre-push 段階で fail させ、PRにさせない」を導入するか議論していると理解しました。  

上記議論で判明したように、ライセンスチェック用のパッケージインストール周りでそれなりの実装コストが掛かりそうです。  
そして2024年まで運用した実態としてパッケージ変更の頻度はかなり低く、メリットは思ったほど無さそうです。  

代替案として「『レビュー開始は CI test pass を確認してから』に運用変更」はどうでしょうか？  
CIがコケると author へメール通知が飛ぶため、authorは CI を自分でチェックし修正してくれるはずです。より安全に進めるなら、`CONTRIBUTING.md` に「CI fail の場合は修正し、pass を確認後にメンションしてね。詰まったら遠慮なく相談してね」と書けば良さそうです。  
これなら実装コストはかからず、最大の問題も解決すると考えます。  

@Hiroshiba  
レポジトリ運用方針絡みなのでご意見伺えれば幸いです。

**Comment by Hiroshiba** [comment]
@tarepan まとめありがとうございます！！助かります！！

僕も「パッケージ変更の頻度はかなり低く、メリットは思ったほど無さそう」に賛成です。

CIに関しては、実はコントリビューターの初回PRはテストを回して良いか許可制な設定だったりします。（githubのデフォルト設定）
なので気付くのが遅れるとかはあるかもですが、まあそもそも頻度が少ないよなーと思いました。

レビューはテスト通ってからもありだと思います！
長らく誰も反応してなかったら見に行く、みたいな感じでも。
とりあえず現運用（ベストエフォート）でも上手く行ってる気がしなくもないので、保留でも良いかも？

乱文ですがこんな感じの感想です！

**Comment by tarepan** [comment]
> 現運用（ベストエフォート）でも上手く行ってる気がしなくもないので、保留  

👍  
同意です。  

現状では「メリット < コスト」であるため、プログラミングによる解決を保留します。運用方針についても現状維持で保留とします。  

具体的な提言のおかげで具体的な試算ができました、@qwerty2501 さんありがとうございました！
