### ISSUE TITLE
run.pyのテストと全体のテストを書く

### ISSUE THREAD

**Issue by Hiroshiba** [VOICEVOX/voicevox_engine#230]
## 内容

- https://github.com/VOICEVOX/voicevox_engine/issues/16

の続きです。
まだテストが実装されていない部分もある一方、一段落したので、別issueを作って引き続きという感じです

**Comment by qwerty2501** [comment]
ここで求められているテストは実際にrun.pyを起動してサーバーを立ち上げてhttp通信することで確認するようなものですかね？

**Comment by qwerty2501** [comment]
FastAPIのドキュメントを見た限りだとわざわざhttp通信しなくても各APIがグローバル関数化されたならそれに対する呼び出しでも良さそうな印象でした。

**Comment by y-chan** [comment]
> 各APIがグローバル関数化されたなら

現状の構造だとそれはちょっと厳しそうです...
http通信を行ってテストをしてくれるクラスがFastAPIには存在するので、それを使うつもりでいました。
テストの実装は引き続き私の方でやるつもりでいますし、少し書いています。

**Comment by qwerty2501** [comment]
あ、FastAPIにそういうクラスがあるんですね。
テスト実装すでにやられているようなのでお任せします

**Comment by Hiroshiba** [comment]
個人的にはy-chanさんの言う、FastAPIのテスト機能を使うのが筋かなと感じています！

ただqwerty2501さんの言うhttp通信を経由するテスト（E2Eテスト）も、あると嬉しそうです。
こちらのissueが近いのかなと感じました。

**Comment by Hiroshiba** [comment]
- https://github.com/VOICEVOX/voicevox_engine/pull/426

にて、`/engine_manifest`APIがエラーを返してしまうようになったのですが、気づける仕組みがありませんでした。
run.pyのテストがあると色々とスムーズに行きそうに思います･･･！

**Comment by sarisia** [comment]
OpenAPI スキーマをちょっと修正したかったのですが, #119, #501 を見つけて, 更にそれらは多分この Issue にブロックされてそうだな～と思いました.

もし宙ぶらりんな感じでしたら対応させていただきたいのですが, いかがでしょうか？

**Comment by Hiroshiba** [comment]
@sarisia お久しぶりです！！　その後進捗いかがでしょうか････？ 👀 

たぶんバージョンが返るかどうかなどの簡単なe2eテストさえあれば、あとはいろんな方が足していきやすいのかなと想像しました。
もし調べたところまでなどあれば教えていただけると次始める方の助けになるかなと･･･！

**Comment by stmtk1** [comment]
[tavern](https://tavern.readthedocs.io/en/latest/examples.html)というライブラリを見つけたのでこれで実装してみますね。

**Comment by stmtk1** [comment]
なるほど。FastAPIのテスト使ってみますね。
ちなみにどんなテストがあると嬉しいとかありますかね？

**Comment by sarisia** [comment]
お疲れ様です,
今年は本業の方がなかなかでして, 正直全然触れていませんでした…！
落ち着くまではもう数ヶ月かかりそうで...

アサイン頂いてしまった後で本当に申し訳ないのですが, 次の方いらっしゃればよろしくお願いします...！

**Comment by Hiroshiba** [comment]
@stmtk1 欲しいテストいろいろまとめておこうと思います！！
とりあえず一番最初に実装すると良さそうなのは一番簡単なやつが良いと思うので、`/version`APIがちゃんと欲しい値が帰ってくるかどうかとかどうでしょう 👀

**Comment by stmtk1** [comment]
> @stmtk1 欲しいテストいろいろまとめておこうと思います！！ とりあえず一番最初に実装すると良さそうなのは一番簡単なやつが良いと思うので、`/version`APIがちゃんと欲しい値が帰ってくるかどうかとかどうでしょう 👀

ありがとうございます。たしかに簡単なテストからやりたいので、`version`からやりたいと思います。

**Comment by Hiroshiba** [comment]
@sabonerune 実際にやろうとしてみてのつまずきポイントとても助かります！！

> 自分が諦めた場所はテストケースに何を指定するべきか(特にgenerate_appの引数に何を指定するべきか)という点と設定ファイルの保存場所をうまく切り替えることができなかったことですね。([unittest.mock](https://docs.python.org/ja/3/library/unittest.mock.html#module-unittest.mock)を使おうとしたがうまく動かせなかった)

設定ファイルの保存場所に関しては、`generate_app`関数などで指定可能にしてしまって、テスト時だけテスト用のパスにするのもありかも･･･？

**Comment by tarepan** [comment]
@Hiroshiba  

本 issue は議論の結果「#730 でe2eテストを書く」と結論付けられた感じでしょうか？（close可能？）

**Comment by Hiroshiba** [comment]
@tarepan あ、ですね！！

---

もう既にちょくちょく `test/e2e` ディレクトリあたりで実装され始めています。
議論ありがとうございました！
