### ISSUE TITLE
aquestalk記法（parse_kana関数）の疑問文対応

### ISSUE THREAD

**Issue by qwerty2501** [VOICEVOX/voicevox_engine#235]
## 内容

#222 に関連して、aquestalk記法の疑問文対応を行う

## Pros 良くなる点
aquestalkで疑問文に対応できる
## Cons 悪くなる点
おそらくない

その他
refs https://github.com/VOICEVOX/voicevox_engine/pull/229#issuecomment-992623862

**Comment by Hiroshiba** [comment]
aquestalk記法の実装は @Yosshi999 さんでした。
疑問文記法を追加できればと考えているのですが、実装の躓きポイント等のアドバイス、願わくば実装を頂けるととても嬉しいです！

**Comment by qwerty2501** [comment]
対応してる人いなさそうならちょっとやってみます！！

**Comment by Hiroshiba** [comment]
ありがとうございます、アサインします！！

**Comment by Hiroshiba** [comment]
@qwerty2501 さん
こちらは完了のステートという認識で合っていそうでしょうか？👀
