### ISSUE TITLE
ドキュメントの追加: 製品版コアライブラリをダウンロードしてrun.pyを動かす手順

### ISSUE THREAD

**Issue by aoirint** [VOICEVOX/voicevox_engine#236]
## 内容

製品版VOICEVOXソフトウェアではなく、製品版コアライブラリ（core.zip）をダウンロード、ENGINEをcloneしてrun.pyを動かす手順をドキュメント化（READMEに追記）したいです。

Windowsでは、製品版VOICEVOXのパスを起動引数で指定することで（同梱されているPythonモジュールが認識されて）製品版コアライブラリを使うことができます。

一方Linuxでは、いまのところ製品版VOICEVOXが1ファイルにパッケージされたAppImage形式で配布されているため、同様の方法で製品版コアライブラリを使うことができない状態です（一応、AppImageを展開＝`---appimage-extract`すれば、今でもできると思います）。

（Dockerイメージにソースコードをマウントすれば製品版コアライブラリを使って開発ができると思いますが、これもドキュメント化されていないですね...）

Linuxでは、製品版コアライブラリ（libcore）やLibTorchの共有ライブラリを読み込むため、LD_LIBRARY_PATHを設定する必要があることを書く。WindowsでもPATHを通すことになりそう。

VOICEVOX COREリポジトリのmainブランチはONNX版になっているので、COREリポジトリの特定バージョンをcheckoutするように書く必要がありそう。

## VOICEVOXのバージョン

0.9.3

## OSの種類/ディストリ/バージョン

- Windows
- macOS
- Linux

## その他

- ref https://github.com/VOICEVOX/voicevox_engine/issues/121#issuecomment-984122870
    - ここでコメントしていた内容

**Comment by aoirint** [comment]
Linux想定したメモです。

コアパッケージは基本的には以下のドキュメントの手順でインストールできます（Python 3.8想定）。

- <https://github.com/VOICEVOX/voicevox_core/tree/42acc417bc3efb08009c669a7752c378698e5fb2#%E3%82%BD%E3%83%BC%E3%82%B9%E3%82%B3%E3%83%BC%E3%83%89%E3%81%8B%E3%82%89%E5%AE%9F%E8%A1%8C>

ただ、`setup.py install`でインストールすると、インストールしたパッケージを（自動で）削除する方法がないので不便です。関連するドキュメントすべてで、`pip install`（`pip3 install`）に書き換えたいなと思っています（ENGINEのDockerfileではそうしていて、不都合は起きないと思う）。

<https://github.com/VOICEVOX/voicevox_engine/blob/a451258c937113e4d244a643cbaea9d86b1fdcc1/Dockerfile#L252>

また、実際にはcore.zipの中身すべてを`example/python`に展開する必要はなくて、Windowsの場合は`*.lib`を生成するためにDLLをコピーする必要がありそうですが、Linuxの場合は`core.h`をコピーするだけで済むと思います（まあ動作に不都合はないので、便宜上そのままでもいいかも）。

---

ENGINE a451258c937113e4d244a643cbaea9d86b1fdcc1 では、[0.9.0のcore.zip](https://github.com/VOICEVOX/voicevox_core/releases/tag/0.9.0)を`~/local/voicevox_core-0.9.0`に展開した場合、coreパッケージインストール済みの環境で以下のように起動できます。

コアライブラリが`metas.json`や`*.bin`を読み込むため、`--voicelib_dir`の指定が必須です（おそらく`run.py`からの相対パスに`core.zip`をコピー展開しない限り）。同じ場所を指定していて混乱しそうですが、`voicelib_dir`にDLLやSOが存在している必要はないです。

```shell
LD_LIBRARY_PATH=~/local/voicevox_core-0.9.0 python3 run.py --voicelib_dir ~/local/voicevox_core-0.9.0
```

CPU版を使う場合、あらかじめ`core.zip`展開先の`libcore_cpu.so`を`libcore.so`にリネーム（置換）しておく必要があります。

<https://github.com/VOICEVOX/voicevox_engine/blob/a451258c937113e4d244a643cbaea9d86b1fdcc1/Dockerfile#L40>

---


Python 3.8をパッケージマネージャや公式インストーラでインストールした環境で、
Ubuntuでは、`python`/`pip`コマンドはPython 2.x、`python3`/`pip3`コマンドはPython 3.xを指していたと思います。
Windowsでは、`python`/`pip`コマンドはPython 3.xを指していて、`python3`コマンドは存在しないと思います（`pip3`はあったかも）。

ドキュメントで`python`や`pip`と記述していると、意図せずPython 2を使ってしまう場合がある（Python 2に依存するパッケージ e.g. VirtualBox が残っていてPython 2＝`python`コマンドを消せないことがある）と思いますが、Python 2はEOLになっているし、ここは開発者がわかっているという想定でもいいのかもしれないなと思って、あまり気にしていません。

**Comment by Hiroshiba** [comment]
コアライブラリ使用手順を書くの、良いと思います！！

とりあえず最も簡潔なドキュメントを書いておいて、様々なケースには別途markdownファイルにして`docs/`辺りに置くと良いのかなと思いました。
（様々なケースは時と場合によって変わりそうなので、別途ブログ記事を書いて頂くのもありなのかなとも感じました）

**Comment by qwerty2501** [comment]
LD_LIBRARY_PATHのくだりはcoreをimportではなくLoadLibraryで動的に読み込むようにしたらそもそも不要なのではないでしょうか。
使用するcoreを分けられるようにするという話があったような気がしたのでそれの結果しだいで手順変わるかもしれませんし、ドキュメントに記載するのは少し待ったほうが良いかもしれませんね

**Comment by Hiroshiba** [comment]
個人的にはデバッグに必要なことがたまにあるので、できれば今の実装に合う形でREADMEに記載しても良いかなと思いました！

**Comment by tarepan** [comment]
現在のREADMEには以下の記述があります：  

> #### 過去のバージョンのコアを使う
> ...  
> ##### 音声ライブラリを直接指定する
> VOICEVOX Core の zip ファイルを解凍したディレクトリを--voicelib_dir引数で指定  
> ...  
> ```bash
> python run.py --voicelib_dir="/path/to/voicevox_core" --runtime_dir="/path/to/libtorch_or_onnx
> ```

つまり関係者の尽力により「製品版コアライブラリをダウンロードしてrun.pyを動かす手順」は既にドキュメントへ追加済みです。  
@Hiroshiba  
よって本 issue は close 可能かと思います。

**Comment by Hiroshiba** [comment]
コメントありがとうございます！
確かに解決していそうな気がするのでcloseしたいと思います！
もし何かあればコメントしていただければ！
