### ISSUE TITLE
エンジンのlatestの自動ビルドがほしい

### ISSUE THREAD

**Issue by Hiroshiba** [VOICEVOX/voicevox_engine#241]
## 内容

最近エンジンのpreview版が必要になって、何度もpre-releaseタグを作っています。
https://github.com/VOICEVOX/voicevox_engine/releases

いつかなにかのミスしそうでちょっと怖いです。
dockerは最新版のlatestビルドを作っているので、同じようにlatestのバイナリビルドもあると嬉しいのかなと思いました。
https://hub.docker.com/r/hiroshiba/voicevox_engine/tags

### Pros 良くなる点

手動更新から開放される。
常に最新のビルドが使える。

**Comment by aoirint** [comment]
latestにあたるバイナリビルド自体は、`master`ブランチのcommitによって作られるようになっているのかなと思いました！

- <https://github.com/VOICEVOX/voicevox_engine/actions/workflows/build.yml?query=branch%3Amaster>
- <https://github.com/VOICEVOX/voicevox_engine/actions/runs/1599264228>

プレビュー用途では、`release-*`ブランチでも同じようにバイナリが作られるようにするといいかもです。

- <https://github.com/VOICEVOX/voicevox_engine/actions/workflows/build.yml?query=branch%3Arelease-0.10>

バージョンを切れたほうがよさそうなので、正式リリースでないビルドでは、`0.10.preview.{手動バージョン}.{コミットID}`のような形で、自動ビルド時にバージョンを自動設定されるようとするといいのかもと思いました。

ただちょっとプレビュー（プレリリース）の運用がよく分かっていないですが、プレリリースのためにコミットを`release-*`に取り込むと、その変更を実際にそのバージョンでリリースするかわからない、というのがあるかもと感じました。

プレビューのためのブランチを作るか、`master`ブランチでプレビュービルドを作るようにすると対策できるのかなと思いました。

それから、わかりやすいところに最新版へのリンクを置いておけるとよさそうです。

...ということを書こうとしましたが、もう #242 が作られていました！

**Comment by Hiroshiba** [comment]
> プレビューのためのブランチを作るか、masterブランチでプレビュービルドを作るようにすると対策できるのかなと思いました。

ちょっと考えたのですが、後者が良いかなと感じました。
前者でのほうが見た目がきれいそうなのですが、`VERSION.txt`の更新が大変なのと、どれをそのブランチにマージすべきかの管理が大変そうというデメリットを感じました。
であれば最初からmaterブランチで、タイミングを見てpreviewリリースを作るのが、ニーズも満たしつつ運用が楽なのかなと感じた次第です。
（VERSION.txtは雑に、未更新で運用することになりますが･･･）

プレビュー版・latest版に関してリリース戦略の課題をまとめるとこんな感じになりそうでしょうか。

* プレビュー版（人力で作る版）
  * ブランチは作るのか　→　作らない
  * tagの付け方はどうするか　→　`0.10.preview.{手動バージョン}.{コミットID}`？
  * VERSION.txtはどうするか
  * どう操作したらプレビュー版が作られるようにするか
    * 今のところは`0.10.preview.バージョン`tagを手動で作成
* latest版
  * 作成されるタイミングはいつか　→　masterが更新されたとき
  * 上書き更新をどう実現するか

プレビュー版のtagの付け方は、日付使うと簡単に完全自動にできるかもです。
ffmpegをビルドし続けている謎のリポジトリはそんな感じの運用に見えました。
https://github.com/BtbN/FFmpeg-Builds/releases

latest版は、ずっとlatestタグで良いかなと感じました。

**Comment by Hiroshiba** [comment]
雑にnightlyビルドでも良いかもと思って調べてみたところ、それっぽいgithub actionsがありました。
https://github.com/WebFreak001/deploy-nightly

１日１回実行されているものなのか、release tagを付けられて実行されたものなのかの区別はgithub.event_nameでできそうでした。
https://stackoverflow.com/a/70282170

**Comment by Hiroshiba** [comment]
こちら取り組もうかなと思っています！
エディタ側にもあった↓を真似る形を考えてます。

- https://github.com/VOICEVOX/voicevox/pull/1484

（エディタ側で便利だったのでエンジン側も適用したい）
