### ISSUE TITLE
onnx版のコアライブラリに対応する

### ISSUE THREAD

**Issue by Hiroshiba** [VOICEVOX/voicevox_engine#245]
## 内容

コアがonnx化され、previewビルドができまました。
https://github.com/VOICEVOX/voicevox_core/releases/tag/0.10.preview.0
このビルドを用いてエンジンで同じことができるようにすることを目指したissueです。

ディスク容量の大幅削減や、推論の高速化など、ユーザーにとって大きなメリットが提供できるはずです。
ぜひ注力したいので、どなたかアサインできると嬉しいです･･･！

### 実現方法

できそうなら、7z分割をせずにreleasesアップロードする部分おｍ対応してしまっても良いかも。

## その他

https://github.com/VOICEVOX/voicevox_engine/issues/69 の続きタスクです。

**Comment by Hiroshiba** [comment]
もしよければ @aoirint さんが最適人かなと思ったのですが、いかがでしょう･･･？ 👀

**Comment by aoirint** [comment]
取り組んでみます。

**Comment by aoirint** [comment]
ONNX版コアでは、いくつか対応プラットフォームが増えていますが、まずは既存のENGINEの対応プラットフォームのみ対応しようと思っています。

- Windows x64
- Linux x64
- macOS x64

ENGINEの依存関係はいろいろあるので、対応プラットフォームを増やすには、それらの解決やビルドが必要になる可能性があります。

個人的にはENGINEをLinux armhfに対応させてもいいかなと思っていますが、依存関係のメンテナンス負荷が大きくなる可能性があるので、ENGINEについてはOrganizationとして対応しなくてもいいのかなと思っています（簡単にできそうだったら別でPRするかもですが）。

**Comment by Hiroshiba** [comment]
取り組みありがとうございます！！

たしかに、armhfはコアとしての用途が主だと思うのでエンジン作成はしなくても良いかもと感じました！

**Comment by Hiroshiba** [comment]
もしかしてもう完了でしょうか・・・？
とりあえずこのissueの意図は今までエンジンができていたことをonnxでもできるようにすることだったので、armhfは別対応ということにしてcloseしてしまっても良いかもと感じました。

**Comment by aoirint** [comment]
このIssueは完了と思います。
#264 があるのでエディタ側の自動ビルドではチェックできていませんが、エンジン側の自動ビルドのONNX対応は終わっているので、Closeしてしまってよさそうです。

**Comment by Hiroshiba** [comment]
了解です！！ありがとうございます、リリースが楽しみですね…！！
