### ISSUE TITLE
対応デバイス（CPU/GPU）がわかるAPIエンドポイントを作る

### ISSUE THREAD

**Issue by Hiroshiba** [VOICEVOX/voicevox_engine#246]
## 内容

エディタ側で、CPU/GPU判定が必要なissueがあります。
こちら用にエンドポイントを用意するタスクです。

### 実現方法

今までコアにそのエンドポイントがなかったから実現できなかったのですが、onnx化に伴って取得できるAPIが増えたので実現可能になりました。

こちらのタスクが先になりそうです。

- https://github.com/VOICEVOX/voicevox_engine/issues/245

**Comment by takana-v** [comment]
#254 とコンフリクトしそうですので、#254 がマージされ次第取り組みたいと思います。

## 関連Issue
- https://github.com/VOICEVOX/voicevox/issues/298
- https://github.com/VOICEVOX/voicevox/issues/479

**Comment by Hiroshiba** [comment]
承知しました、ありがとうございます･･･！
