### ISSUE TITLE
デフォルトでキャスト名を正しく読めない

### ISSUE THREAD

**Issue by nmori** [VOICEVOX/voicevox_engine#259]
## 内容
現在つかえるキャストの名前を適切に読めていないため、形態素辞書の更新をするのがよいと思います。

特に今後キャストが増えるにあたり、商標を持つキャラクターも出てくると予想されますし、
自己紹介を読み上げるたびに、読み文章修正をする必要がある点はユーザ体験がよくない可能性があります。

そのため、デフォルト状態で正しく名前を読めることは、今後重要度を増してくるかと考えます。

現状）
　雨晴はう→あまはらしわう
　波音リツ→なみおんりつ

### Pros 良くなる点
・キャストの名前をユーザが意識しなくても正しく読めるようになる
・ユーザが読み訂正などをしなくてすむようになる（ユーザ体験の向上）

### Cons 悪くなる点
・独自の形態素辞書となるため、管理点が1つ増える可能性がある

### 実現方法
・OpenJtalk のMeCab辞書を追記加工してコンパイル、その辞書を採用する

## VOICEVOXのバージョン
～0.9.4

## OSの種類/ディストリ/バージョン
当方で確認でいている範囲で。他のディストリビューションでも同様であると想定される。
- [X] Windows
- [ ] macOS
- [ ] Linux

**Comment by Hiroshiba** [comment]
こちらのプルリクエストの内容が近そうでしょうか？👀

- https://github.com/VOICEVOX/voicevox_engine/pull/234

**Comment by nmori** [comment]
コメントありがとうございます。
ご提示いただいたもので近いかとおもいますが、下記の点が気になります。

今回の「キャスト名を正ししく読む」という点の方策として
方策案１）ユーザー辞書のデフォルト定義に追加しておく
方策案２）システム辞書に追加する
の２つがありそうです。

補正したい読みやキャストの数がすくなく、一般的なユーザの行動として
「辞書は加筆していくことが多い」と仮定すれば、（１）がよい気はします。

半面、「ユーザーが辞書を入れ替えて使うケース」などでは
毎回作成するファイルにキャスト名を入れておかなければならないのも
少し使い勝手がわるいかもしれません。その場合は（２）が方策になるかとおもいます。

＜この場合の実装方法＞
（１）で実現なら→ #234 実装後、デフォルト辞書に文字列を追加で完了
（２）で実現なら→システム辞書に形態素追加＆コンパイル、取り込み

**Comment by Hiroshiba** [comment]
おお、なるほどです！！
OpenJTalkを実はしっかり知らないのですが、システム辞書に追加というのはどうすれば良いかご存知だったりしますか･･･？👀

**Comment by nmori** [comment]
OpenJTalkの中身をいじったことはないのですが、おそらく
[システム辞書ファイル](https://github.com/r9y9/open_jtalk/blob/957229334996d2c9d9fcb73cdb3f4d9c15bcdd57/src/mecab-naist-jdic/naist-jdic.csv)に追記後、Makeで生成される辞書を採用すれば（２）を実現できそうです。

**Comment by Hiroshiba** [comment]
なるほどです！！

もしくはユーザーが作った辞書をコンパイルするときにこちらが用意した辞書を足しちゃう、という手もありそうだなと感じました。
システム辞書のコンパイルの大変さによって取る手が変わりそうです。

**Comment by nmori** [comment]
システム辞書の環境を作るのは少しだけ苦労しそうです。
（手元でためしたのですが、ちょっとうまく作れていません）

MeCab公式ガイド(https://www.gavo.t.u-tokyo.ac.jp/~mine/japanese/nlp+slp/NAIST-JDIC_manual.pdf) には、コマンドをいくつか実行すれば実現できると書いてあるので、環境構築ができればそこまでハードルはないかもしれません。

逆に、毎回このような点で引っかかる可能性があれば、ご提案いただいている
「ユーザ辞書に毎回アドオンしてコンパイルをとおしてしまう」という手が
スマートかもしれません。

**Comment by Hiroshiba** [comment]
なるほどです！！

とりあえず一旦はユーザー辞書にVOICEVOX辞書を常に足す設計にしておいて、余裕が出てきたらVOICEVOX辞書をシステム辞書に足すという感じが良いかなと思いました。
@takana-v どうでしょう 👀

**Comment by takana-v** [comment]
#234 ではcsvをコンパイルしたものを読み込んでいますが、別csvをマージしてコンパイルして読み込むのも可能かと思います。
また、システム辞書の入れ替えはやろうと思えば可能ですがちょっと大変な気がします。
ですのでそちらの方針で良いと思います。

現在 #234 のユーザー辞書には雨晴さんの分が入っていないほか、単語のコストが0であまり完成度が高くありません。
もしよろしければ私のブランチに向けてPRしていただければ大変助かります。@nmori

**Comment by takana-v** [comment]
#234 にてキャスト名を正しく読めるようになりましたのでcloseしました。
システム辞書への追加については別でIssueもしくはPRを立てていただければと思います。
