### ISSUE TITLE
mypyの設定を有効化する

### ISSUE THREAD

**Issue by qwerty2501** [VOICEVOX/voicevox_engine#263]
## 内容
TODOの掘り起こしです
https://github.com/VOICEVOX/voicevox_engine/pull/30 で行われたlint設定でmypyがとりあえず無効化されてたのでエラー部分も直して有効化する

### 実現方法

pysenの設定で mypyの有効化~及び  "strict" modeに変更する~

**Comment by Hiroshiba** [comment]
mypyは結構理不尽と言うか、pythonの良さを消している部分もあるので、適用は賛否両論ありそうです。
今はどうか知りませんが、例えば`def __init__`の返り値に`None`を指定しないとエラーみたいなのがあった気がします。

が、たしかに型の補助はあったほうがコーディングも楽になるし、ミスにも気付けるので良いかもと感じました。
todoとまではいきませんが、一旦検討しても良さそうだと思います。

**Comment by qwerty2501** [comment]
やるにしてもまずはmypyの有効化のみのほうがよさそうですね。

**Comment by Hiroshiba** [comment]
こちらのタスクですが、mypyテストがあればよりミスに気づきやすくなると思うのでちょっと優先度上げた方が良い気がしました。
例えば↓のプルリクで修正されたミスはmypyで指摘されました。

- https://github.com/VOICEVOX/voicevox_engine/pull/922

個人的には`no-untyped-def`を無効化しつつ、他の若干直感的じゃない設定を無効化して導入したいです。

**Comment by sabonerune** [comment]
mypyの設定はpysenが支配しているようで`setup.cfg`を書き換えても反映されないようです。
現在の`entry`が最も緩い設定のようでこれ以上緩めるならプラグインを書く必要があるかもしれません。

https://github.com/pfnet/pysen?tab=readme-ov-file#frequently-asked-questions
>Q. How do I change specific settings for linter X?
>A. We prioritize convention over configuration. However you can always create your own plugin. See: [Create a plugin to customize pysen](https://github.com/pfnet/pysen?tab=readme-ov-file#create-a-plugin-to-customize-pysen)

もしくはpysenの設定を無効にしたまま独自に設定をして直接mypyを実行するとか?

**Comment by Hiroshiba** [comment]
@sabonerune コメントありがとうございます！！！

な～るほどです。
調べてみた感じpysenをメンテナンスしているpfnetのリポジトリでもpysenが使われていて、見た感じ`-> None`もちゃんと書かれてました。
だったらまあ僕たちも従って良い気がしました！！！

ということで、特に設定なしのまま導入する方向で･･･！！
