### ISSUE TITLE
開発者向けドキュメント: 利用可能なライブラリライセンス

### ISSUE THREAD

**Issue by tarepan** [VOICEVOX/voicevox_engine#265]
## 概要
外部ライブラリ選定にあたり、利用可能ライセンスのリストが必要.  
現状では検討がほぼなされていない.  
リストアップおよびREADMEへの記載を要望.  

## 内容
外部ライブラリの選定（例: #135）にあたり、外部ライブラリのライセンス検討が必要です.  
VOICEVOXライセンスが *LGPL v3* or *個別ライセンス* であるため、GPL等、利用不可のライブラリが出てきます.  
以下の3つのfeatureにより、この問題を解決できると考えます.  

- 個別ライセンスの概要開示
- VOICEVOXで利用可能なライブラリライセンスの線引き明示
- READMEへの記載

個別ライセンスの要件によって利用可能範囲が全く異なります. 例えば、外部ライブラリの著作権表記を不要にする必要があるならMITライセンスは利用できません.  
個別ライセンスの概要を開示することで、そこの検討が可能になると考えます.  

### Pros 良くなる点

- ライブラリ導入時に都度ライセンス確認が不要

### Cons

- 個別ライセンスの中身がぼんやりと見える

### 実現方法
1. LGPLと個別ライセンスの要件をリストアップ
2. メジャーライセンス（GPL, LGPL, Apache License, MIT, BSD 3-clause?）と比較、線引き確定
3. README記載

## VOICEVOXのバージョン
all  

## OSの種類/ディストリ/バージョン
all

## Notes
過去のissue等で触れられているのはおそらく以下のみです.  

https://github.com/VOICEVOX/voicevox/issues/219#issuecomment-927917044

**Comment by Hiroshiba** [comment]
個人ライセンスですが、製品版のコアライブラリが作れれば（≒コアライブラリーのソースコードの公開義務がなければ）大丈夫です。
例としてGPL・LGPLだと、GPLは利用不可、LGPLはエディタとエンジンでは利用可・コアでは利用不可となりそうです。

MITやApache LicenseやBSDはおそらくどこでも利用できそうです。
あとPython Licenseとかもあるのですがこれも大丈夫です。
たまにライセンスが無いものがあって、それは要注意になりそうです。

**Comment by tarepan** [comment]
「VVCoreビルド時にリンクして一体化しても、Core部のコード非公開OK」が要件、と認識しました.  
この場合、Hihoさんの言う通り  

- MIT/Apache/BSD-3: OK
- LGPL: Coreと分離されてるEditor/EngineではOK、CoreはNG
- GPL: 全部に公開が必要なのでNG

で間違いないと思います.  

今後の開発者向けにPRを建てたいと思います.  
README `ユーザー辞書の更新について` の下あたりがいいかと思います.  
どうでしょうか?

**Comment by Hiroshiba** [comment]
共通ではありますが、コミッターの方の目に入る場所に書いておきたいので各々のREADMEに書くのがいいのかなと感じました！
書く場所はその辺りが良いと思います！
