### ISSUE TITLE
削除: 音量適用時の計算量軽減

### ISSUE THREAD

**Issue by tarepan** [VOICEVOX/voicevox_engine#267]
## 概要
現実装では音量調節時に不要な計算をif文でスキップ.  
だが実パフォーマンスでは改善がほぼなく、今後の機能追加のブロックになりうる.  
削除を提案.  

## 内容
現実装では `SynthesisEngine.synthesis` での音量適用時に「`*1.0` は無意味なのでif文でスキップ」をしています.  

https://github.com/VOICEVOX/voicevox_engine/blob/c935cf2585358bf7fc217389d63e5032885a516c/voicevox_engine/synthesis_engine/synthesis_engine.py#L463-L466

パフォーマンス計測をしたところ、この計算での負荷は0.05**ミリ**秒以下でした.  
今後の機能拡張（例: #135）を見据えて、このif文を削除することを提案します.  

### Pros 良くなる点
- より良い見通し: 不要なif文の削除
- 容易な機能拡張: if文を考慮して新機能を設計する必要がなくなる

### Cons 悪くなる点
- パフォーマンスの低下、ただし0.05ミリ秒以下

### 実現方法
if文の削除（1行）

## VOICEVOXのバージョン
latest

## OSの種類/ディストリ/バージョン
all

## その他
パフォーマンステストコード:

```python
import time
from random import random
from statistics import mean

import numpy as np


# Fake inputs
len_input = 5 * 24000
i = np.array([random() for _ in range(0,len_input)])
gain = 1.0

# Repeated test
n_test = 100
latencies_msec = []
for _ in range(0, n_test):
    t_start = time.perf_counter()

    i *= gain

    t_end = time.perf_counter()
    latencies_msec.append((t_end - t_start) * 1000)

print(f"{round(mean(latencies_msec), 3)} msec")
!lscpu | sed '13!d'
!lscpu | sed '4!d'
# 0.045 msec @ Google Colab CPU instance, Intel(R) Xeon(R) CPU @ 2.20GHz 2 core
```

**Comment by takana-v** [comment]
個人的には #135 の実装時に削除すれば良いかと思いましたが、PRを作られるのであればapproveしたいと思います。
（小さい変更ですので、直接PRを作ってそこで議論してもいいかなと思いました）
