### ISSUE TITLE
venvフォルダ等をgitignoredする

### ISSUE THREAD

**Issue by tarepan** [VOICEVOX/voicevox_engine#269]
## 不具合の内容
`.venv`ディレクトリがgitignoredされず、gitでトラックされる.  

### 現象・ログ
gitのadd対象一覧に`.venv`以下のファイルが表示される.  

### 再現手順
1. GitHub Codespacesにて本プロジェクトを起動
2. venv構築完了まで待機
3. gitタブ確認

### 期待動作
`.venv`以下がgitignoredされる

## VOICEVOXのバージョン
master c935cf2585358bf7fc217389d63e5032885a516c

## OSの種類/ディストリ/バージョン
- [x] Linux: Ubuntu 20.04.3 LTS  

Windows/macOS環境未確認

## 推定原因
`.gitignore`に`.venv`が指定されていない.  

https://github.com/VOICEVOX/voicevox_engine/blob/c935cf2585358bf7fc217389d63e5032885a516c/.gitignore#L13-L14

## 修正
gihub公式では`.gitignore` に `.venv` を採用.  

https://github.com/github/gitignore/blob/96d68766538413194aabd55e3622734cd501e715/Global/VirtualEnv.gitignore#L11

上記環境にて`.venv`追加でバグ消滅を確認済み  

## Notes
draft PRを添付します.

**Comment by takana-v** [comment]
基本的に過去のPRを見る限り、個人の環境で必要な物のignoreは各個人で行う、という方針のようです。
（個人でのignoreは https://github.com/VOICEVOX/voicevox_engine/pull/243#issuecomment-997866273 を参照してください）
一旦前例に従ってcloseしますが、問題があればコメントもしくは再オープンをお願いします。

- https://github.com/VOICEVOX/voicevox_engine/pull/243
- https://github.com/VOICEVOX/voicevox_engine/pull/138

**Comment by tarepan** [comment]
他issueへの案内ありがとうございます.  

現在の`.gitignore`ではvenvに関わるディレクトリを既にignoreしています.  

https://github.com/VOICEVOX/voicevox_engine/blob/c935cf2585358bf7fc217389d63e5032885a516c/.gitignore#L3
https://github.com/VOICEVOX/voicevox_engine/blob/c935cf2585358bf7fc217389d63e5032885a516c/.gitignore#L13-L14

これらに基づいてvenvはデフォルト環境なのかな？（なのでバグか？）と推測しました.  
環境は個人で、という方針でしたら、逆にこれらを消すPRを建てた方が良いでしょうか?

**Comment by takana-v** [comment]
私はvenvのフォルダ名は`venv`で問題ない（バグではない）と考えています。
（私は`python -m venv venv`で環境を作って開発しています）
現在のgitignoreを外すと既存の開発者さんに迷惑がかかりそうなので避けたいと思います。

（方針について）
VOICEVOXがOrg化する前はヒホさん1人でメンテナンスされており、方針＝ヒホさんの考え、となっていました。
しかし、Org化して複数のレビュアーがレビューするようになってからは各個人の考えの元レビューしています。
ですのでちょっと「方針」という言葉には語弊があったかもしれません。
正確には「私が推測した、ヒホさんが恐らく取るであろう対応」となっています。

**Comment by tarepan** [comment]
状況理解しました. ご丁寧にありがとうございます!

**Comment by Hiroshiba** [comment]
こちら、結構issueもらうので、まあgitignoreにいろんなのがいっぱいあっても別にいいかなという気持ちになりました。
置き換えるとしたらこちらでしょうか。 https://github.com/github/gitignore/blob/main/Python.gitignore

**Comment by tarepan** [comment]
GitHub公式のgitignoreを最初に導入するのが現行のベストプラクティスだと考えます.  
なのでhihoさんコメントのリンクから、環境周りの部分を移植するのが良いと思います.  

`# PEP 582` と `#Environments`、約10行の移植になります.  
lockファイルは今後導入がありうるということで、それ周りは移植しないのが妥当だと思います.  

@takana-v さん、discussionおよび実装検討ということで、issue reopenしていただければ幸いです.

**Comment by takana-v** [comment]
lockに関しては、その後pip-toolsによるライブラリのバージョン固定が導入されました。
ですのでpipenvが導入される可能性は少ないかなと思います。

**Comment by tarepan** [comment]
そうなるとGitHub公式に従い、追加で

- `Pipfile.lock`: for pipenv
- `poetry.lock`: for poetry

をgitignoreできそうです.  
これらもignoreしてよいでしょうか?

**Comment by Hiroshiba** [comment]
lockもignoreで良いと思います！
