### ISSUE TITLE
疑問文フラグをAccentPhraseModelに持たせるように仕様変更する

### ISSUE THREAD

**Issue by Hiroshiba** [VOICEVOX/voicevox_engine#272]
## 内容

疑問文フラグは現状Modelに持たせておらず、？があったときに母音を足して語尾を上げたMorasを返すようになっています。
このままだと、エディタ側でアクセントを変更したときにどうしても音高がリセットされてしまいます。

- https://github.com/VOICEVOX/voicevox/issues/632

ということで、AccentPhraseに疑問文フラグをもたせ、強制的に毎回語尾を上げるようにする処理をエンジン側に追加することにしようかなと思いました。

### Pros 良くなる点

操作が直感的になる

### Cons 悪くなる点

エディタ側に？を表示するUIが必要

### 実現方法

AccentPhraseにisinterrogativeをもたせる。
デフォルト値をfalseにしておけば、以前のバージョン用で作られているサードパーティでも問題なく動くはず。
（できれば、Modelに初期値をもたせた状態で、その値が存在しないクエリを投げたときにデフォルト値がセットされるかを確かめたい）

## その他

@qwerty2501 さん、どうでしょう・・・？

**Comment by qwerty2501** [comment]
> 強制的に毎回語尾を上げるようにする処理をエンジン側に追加することにしようかなと思いました。

今でも強制的に語尾を上げるようにしてますが、これは語尾 `だけ` を上げるようにするということでいいんですかね？

**Comment by Hiroshiba** [comment]
> 語尾のmora だけ

そちらの認識です！
音高が決定してから、moraを足してそこだけ音高を変えるのが良いかなと思っています。

もし違和感あるようでしたら僕が気づけていないかもなので、教えて頂けると！

**Comment by qwerty2501** [comment]
多分大丈夫だと思います

**Comment by qwerty2501** [comment]
ちょっと実装してて気づいたのですが、最後の文字のpitchが0だった場合って母音付け足さないほうがいいのではないでしょうか？例えばッの場合？がつくと発音的にはッッになりますし、付け足されたもののpitchが0ではなくなるのでおかしくなりそうです

**Comment by Hiroshiba** [comment]
確かに、「っ」は反復しないほうが良いのかなと感じました。
ただまあ別に反復させても音声はほぼ変わらないと思うので、反復するかしないかはコードが簡単な方で良いかもです。

･･･あ！！
「〜です」の「す」も（無声化しているため）pitchが0なのですが、こっちは「っ」とは別で、更に強制的に有声化したほうが良いかもです。
例えばよくある日本語だと、「〜だそうです」の「す」は「う」を発音しないためpitch=0ですが、「〜だそうです？」の「す」は「う」を発音するためpitch!=0になります。

このとき「す」の高さをどう決めれば良いのか全然わかりませんね･･･
更に１つ前のモーラのpitchをコピーするのが良いのかなと思うのですが、もし可能だったらそちらも実装するとよりそれっぽい疑問文になると思います。

「〜です」のモーラが`de``sU`、ピッチが`de`=x・`sU`=0だったとき、`sU`を`su`にしてピッチをxにし、さらに`u`を足してピッチをx+0.3（0.2でしたっけ）にする感じです。

あとから色々言っちゃって申し訳ないです･･･。

**Comment by qwerty2501** [comment]
「す」について末尾に「す」が来た場合は無声化されないのでは？
https://github.com/VOICEVOX/voicevox_engine/blob/master/test/test_synthesis_engine_base.py#L247
「これはありますか」のように「す」のあとに何か文字がある場合は無声化されてるように見えます
https://github.com/VOICEVOX/voicevox_engine/blob/master/test/test_synthesis_engine_base.py#L92
なので「す」については特に考慮しなくてよさそうですが文脈次第では末尾に「す」が来ても無声化されるのでしょうか？

「す」以外にも無声化されてるものがありそうですが、前の前の文字のpitchをそのまま使うのは場合によっては不自然になるかもしれません。
仮対応であらゆる文章の調整がんばるのもキリがないというのもあります。
また「っ」の場合だとmora追加しませんが、これはエディタ側でaccent phraseが疑問形だった場合他のaccent phraseとは違う実装にしなければならないと思います。
これをpitch=0の文字ごとに対応しなければならないとなるとエンジン、エディタともに実装が複雑になりバグの温床になりそうです。
わりきってpitch=0の場合はmoraを追加しないという実装のみにするか、もしくはエディタ側がちょっと複雑になりそうなので実装の際の負荷を考えるとpitch=0の場合はpitch=0のmoraを追加するのみとしたほうが良いかもしれません。

**Comment by qwerty2501** [comment]
「です」の場合は「す」が無声化されますね

**Comment by qwerty2501** [comment]
いや、「です？」にするとOpenJtalkだと無声化されないかもです

**Comment by Hiroshiba** [comment]
仰るとおり、「～です」系は最後が無声化されることが多いです･･･！

OpenJTalkは疑問文にしたとき有声化されていますが、これは今回だと必ずしも使えるわけではないかなと考えています。
が、たしかにユースケース考えると、語尾の有声・無声はOpenJTalkに任せるのも良いかもと感じました。

処理の流れは　テキスト入力→OpenJTalk→音素・音高→ユーザー操作→音声合成→再生　だと思います。
この「ユーザー操作」で最後の音の有声・無声が切り替えられるので、厳密にはOpenJTalkの出力を信じているとユーザーの意図に反してしまうことがあるかもと考えてました。

ただそれはかなりレアケースなので、最後が無声（pitch=0）の場合は何もしないでも良いかもと思いました。
もしそういうユースケースが出たら、pitch=0のときの処理を考えても良いかもです･･･！

**Comment by Hiroshiba** [comment]
> interrogative mora

一瞬名案だと感じたのですが、moraだとlengthをもつ必要があるのですが、interrogative moraがどういうlengthを持つべきかがパッと最適解がわかりませんでした。
まあ将来的にはinterrogative mora実装になるかもですが、一旦フラグにしておくのが良いのかなと思いました！

**Comment by qwerty2501** [comment]
OKです。ということは実装はこのままで良さそうなので #273 はこれでレビューできる状態になってるはずです

> まあ将来的にはinterrogative mora実装になるかもですが、一旦フラグにしておくのが良いのかなと思いました！

この辺は将来実際に検討してみないとなんともですが、フラグと専用mora両方もつことになるかもしれません。「っ」つきの疑問文で疑問符表示したいときはフラグも必要になるかと

**Comment by Hiroshiba** [comment]
こちらのissueはもう目標がなくなってしまった（API ModelもEngine Modelもおなじになった）ので、閉じちゃっても大丈夫そうでしょうか👀 @qwerty2501

**Comment by qwerty2501** [comment]
https://github.com/VOICEVOX/voicevox_engine/pull/273
このissueがmergeされてるので完了で大丈夫だと思います

**Comment by Hiroshiba** [comment]
了解です、ありがとうございます…！

**Comment by Hiroshiba** [comment]
こちらのissueですが、

> 疑問文フラグは現状Modelに持たせておらず、？があったときに母音を足して語尾を上げたMorasを返すようになっています。

この課題が実はまだ解決できていなかったことに気づきました。
これはたぶん現状のデータフローが

テキスト入力→OpenJTalk→音素・音高**→擬似疑問文化→**ユーザー操作→音声合成→再生

となっているのが原因で、こうすれば解決になりそうです。

テキスト入力→OpenJTalk→音素・音高→ユーザー操作**→擬似疑問文化→**音声合成→再生

ソースコードを読んだ感じ、adjustするタイミングをsyntesis APIの開始時に移せば問題を解決できそうです。
が、テスト周りを変更する必要等がありそうで、自分はリリース準備のためにちょっと手が動かせずにいます。

@qwerty2501 さん、お願いできたりしますか･･･？👀

**Comment by Yosshi999** [comment]
↑やります

**Comment by Hiroshiba** [comment]
ありがとうございます！！
たぶん https://github.com/VOICEVOX/voicevox_engine/issues/309 のissueはこちらの不具合依存なので、本リリースまでにバージョンアップしておきたいなと感じました･･･！

**Comment by qwerty2501** [comment]
すみません。今気づきました。
担当される方がすでにいらっしゃるようなので、お手数をおかけしますがよろしくおねがいします。

**Comment by Hiroshiba** [comment]
解決したのでcloseします！
https://github.com/VOICEVOX/voicevox_engine/releases/tag/0.10.2 で解決されたはず
