### ISSUE TITLE
dockerで雨晴はうが存在しない?

### ISSUE THREAD

**Issue by kuroneko6423** [VOICEVOX/voicevox_engine#277]
## 不具合の内容

docker pull hiroshiba/voicevox_engine:cpu-ubuntu20.04-latest
をしたのですがなぜか声が 
”あまあま四国めたん, ノーマル四国めたん, セクシー四国めたん, ツンツン四国めたん, あまあまずんだもん, ノーマルずんだもん, セクシーずんだもん, ツンツンずんだもん, ノーマル春日部つむぎ, ノーマル波音リツ”
は、おり"雨晴はう"がボイスに存在しません。
これはバグでしょうか？

### 打ったコマンド

docker pull hiroshiba/voicevox_engine:cpu-ubuntu20.04-latest
docker run -d -it -p '127.0.0.1:50021:50021' hiroshiba/voicevox_engine:cpu-ubuntu20.04-latest

### 期待動作

雨晴はう以外はすべて認識、動作しました。

## VOICEVOXのバージョン

最新?

## OSの種類/ディストリ/バージョン

- [ ] Windows
- [ ] macOS
- [x] Linux  UbuntuServer 20.04LTS

## その他

voicevoxをDiscordの読み上げbotとして使わせていただいてます。ありがとうございます。
Botコード https://github.com/KuronekoServer/VOICEVOX-TTSbot/

**Comment by y-chan** [comment]
現状のLatestは新しいコア(機械学習ライブラリであるLibtorchの利用を廃止し、軽量なONNX Runtimeへ移行する)のテストビルドとなっており、雨晴はうが含まれません。
`docker pull hiroshiba/voicevox_engine:cpu-ubuntu20.04-0.9.5`コマンドをご利用ください。
解決されたようでしたら、Issueをcloseしていただきますようお願いします。
