### ISSUE TITLE
Dockerイメージ自動ビルド: 製品版のspeaker_infoを取り込むようにする

### ISSUE THREAD

**Issue by aoirint** [VOICEVOX/voicevox_engine#278]
## 内容

#180 でバイナリビルドは製品版リソースが同梱されるようになりましたが、Dockerイメージではコアを除いてダミーが使われています。

エンジンをDockerイメージ`Hiroshiba/voicevox_engine`で起動した状態でエディタを起動した場合に、コアは製品版が使われますが、立ち絵やアイコン、音声ライブラリのライセンスなどにダミーが表示されます。

### Pros 良くなる点

- コアとspeaker_infoの話者情報の不一致が解消される

### 実現方法

`Dockerfile`または`build-docker.yml`で https://github.com/VOICEVOX/voicevox_resource を`speaker_info/`に展開する。

ホスト側のspeaker_infoディレクトリを使用するか、VOICEVOX/voicevox_resourceを使用するか、分岐できるようにするといいかも。

## VOICEVOXのバージョン

0.9.5

## OSの種類/ディストリ/バージョン

- Windows
- macOS
- Linux

**Comment by Hiroshiba** [comment]
これたしかcloseで良かったはずです！
どこかで直したはず･･･。
