### ISSUE TITLE
リファクタ: gitignore標準化

### ISSUE THREAD

**Issue by tarepan** [VOICEVOX/voicevox_engine#280]
## 内容
(discussed in #271)  

現在のgitignoreはVOICEVOX独自の内容です.  
GitHub公式のPython用gitignoreに追従すれば、ベストプラクティスを踏襲し、かつ今後の更新が楽になります.  
gitignoreの置き換えを提案します.  

### Pros 良くなる点
- 標準的Pythonプロジェクトとの一致
- ベストプラクティス更新への追従性↑

### 実現方法
1. 現行とGitHub公式のdiff
2. 影響検討
3. 置き換え

## VOICEVOXのバージョン
all

## OSの種類/ディストリ/バージョン
all

**Comment by tarepan** [comment]
## Diff
GitHub公式にないVV独自属性は以下になります.  

- `*.dist`
- `*.build`
- `.venv-release`
- `/licenses.json`
- `/build`: 類似したGitHub公式属性 - `build/`
- `/cache`: 類似したGitHub公式属性 - `.cache`

おそらくビルド周りの属性です.  
詳しい方のコメントがいただければ幸いです.  
ある程度情報が集まり次第、上記属性をGitHub公式に足したものをPRにしたいと考えています.

**Comment by Hiroshiba** [comment]
`*.dist`と`*.build`と`/build`と`/cache`はnuitkaが出すディレクトリです。
`licenses.json`は`generate_licenses.py`の生成物です。
↑これらはgitignoreに足しても良さそうに感じました。

`.venv-release`は昔１人でメンテしてたときの名残なので不要っぽいです。
