### ISSUE TITLE
音声の前の無音を長くする機能を削除する

### ISSUE THREAD

**Issue by Oyaki122** [VOICEVOX/voicevox_engine#281]
## 内容

#128 と同様の機能が VOICEVOX/voicevox_core#58 でコア側に実装されたため、エンジン側の処理を削除する必要があります

**Comment by Hiroshiba** [comment]
issue作成ありがとうございます！
二重に無音を長くしてしまうと生成速度に影響が出るので早めに対処したく、優先度を中にしてみました。
