### ISSUE TITLE
CPUを半分程度までしか使用しない

### ISSUE THREAD

**Issue by AsPulse** [VOICEVOX/voicevox_engine#282]
## 質問の内容
DockerでVoicevox-Engineを実行した際、CPU使用率を半分までしか使用しません。
### 経緯
4CoreのCPUを搭載するLinux上で動いている~~Kubernetes上に~~ **(追記: Kubernetesを使用せず、直接docker runした場合でも同じ現象が発生しました。)**、
voicevox_engineのDockerイメージをデプロイしたところ、
CPU使用率が200%までしか使われませんでした。（Kubernetesから何も制限はかけておりません。）

- 切り分けのために行ったこと①
CPU負荷をかけるイメージ([progrium:stress](https://hub.docker.com/r/progrium/stress/))を同じ状況でデプロイさせたところ、
400%まで使用率が使われました。

- 切り分けのために行ったこと②
16CoreのCPUを搭載するWindows(別サーバー)のDockerで同じイメージをrunしても、
CPU使用率は800%までしか使われませんでした。

- 切り分けのために行ったこと③（20:27 追記）
4Core の CPUを搭載したサーバーに、Dockerの「使用率制限300%まで ( cpu-quota=300000 )」をかけたとしても、
200%までを使っていました。
もし、Dockerの使用率制限を基準に行っていたら150%までしか使わなそうなので、
搭載されているコア数が基準になっているのかなと思います。

## VOICEVOXのバージョン
[aoirint/voicevox_engine:cpu-ubuntu20.04-latest](https://hub.docker.com/r/aoirint/voicevox_engine)
GET /version の結果: `version 0.10.preview.2`

## OSの種類/ディストリ/バージョン

- [x] Windows
- [ ] macOS
- [x] Linux

Linux: 
```
OS:
Linux version 5.4.0-90-generic (buildd@lgw01-amd64-054) (gcc version 9.3.0 (Ubuntu 9.3.0-17ubuntu1~20.04)) #101-Ubuntu SMP Fri Oct 15 20:00:55 UTC 2021

CPU:
4 Core
Intel(R) Core(TM) i5-3230M CPU @ 2.60GHz
```

Windows:
```
OS:
Windows 11 Home OSビルド 22523.1000

CPU:
16 Core
Intel(R) Core(TM) i9-9900K CPU @ 3.60Ghz
```
## その他
使用率確認のために実行したコマンド
```
docker container stats [コンテナID]
```

**Comment by aoirint** [comment]
設定ですべてのCPUコアを100%使用することができてもよさそうだなと思いました。

対応するコミットIDはおそらくこちら: <https://github.com/VOICEVOX/voicevox_engine/tree/3b29b38bab246018cb51f27484b0243c702a3bce>

コアがONNX Runtimeで動作するようになったバージョンです。

CPU使用率については、コアのarmhf版作成のときに、ONNX Runtimeが通常CPUを100%使わない挙動になっていそうなことが触れられていました。

- <https://github.com/VOICEVOX/voicevox_core/issues/40#issuecomment-968369167>
- <https://github.com/VOICEVOX/voicevox_core/pull/41#pullrequestreview-807327751>
- <https://github.com/VOICEVOX/voicevox_core/pull/41#issuecomment-971617570>

ちょっと調べてみましたが、対応にはコア側の変更が必要そうです。

現在のVOICEVOXエンジンは、基本的にVOICEVOXエディタに同梱して動作させることを想定していると思うので、デフォルトでフルパワーで動かしてしまうと、デスクトップ環境などの処理にリソースを回せずに、OSの動作が不安定になるのかなと思いました。

エンジンを専用サーバや、リソース制限された環境で動かす場合には、フルパワーで動かすことができるとよさそうです。

- <https://github.com/VOICEVOX/voicevox_core/blob/25b7c866435443d3be39a9301e14024d2a0878ac/core/src/core.cpp#L118>

コア側でONNX Runtime使用時に動作設定ができそうでした。

現在は特別な設定をしていないので、安定動作のためにONNX RuntimeのデフォルトではCPUを50%までしか使わないようになっているのかもと思いました。

OpenMPを有効化したONNX Runtimeビルドでは、環境変数`OMP_NUM_THREADS`でスレッド数を変更できましたが、armhf向け以外で使用している公式のONNX RuntimeビルドはOpenMPが無効化されているので、使えなさそうです。

- <https://github.com/microsoft/onnxruntime/issues/3713#issuecomment-620140390>

コア側で、モデルのSessionを作成する前に、`Ort::SessionOptions`にオプションを設定することでスレッド数の指定ができそうでした。

コアのinitializeインタフェースがONNX Runtime専用に変わりそうなので、任意のオプションを辞書形式で受け付けられるようにできないかなと思いました。
`OMP_NUM_THREADS`のように、環境変数で指定するようにする方法もあるのかもです。

```cpp
Ort::SessionOptions session_options;
session_options.SetIntraOpNumThreads(intra_op_num_threads);
session_options.SetInterOpNumThreads(inter_op_num_threads);
```

ちなみに、VOICEVOXのリリースと対応したバージョンが切られた公式のDockerイメージリポジトリはこちらです：

- <https://hub.docker.com/r/hiroshiba/voicevox_engine>

**Comment by AsPulse** [comment]
ありがとうございます！

限られたサーバー資源だと、aoirintさんの仰るようにフルパワーが使えると大変ありがたいです！
私のようにKubernetes/Dockerから利用している場合は、環境変数で指定できる便利だと思います。

Dockerのイメージリポジトリの件なのですが、知りませんでした...！ご指摘ありがとうございます。

私は春日部つむぎ/ノーマル (SpeakerId: 8) を使用していたのですが、
最初Docker Hubを検索した時、公式がどれかわからず...。[hiroshiba:voicevox_engine](https://hub.docker.com/r/hiroshiba/voicevox_engine)の方では、
```
これは「四国めたん」「ずんだもん」の VOICEVOX 音声合成エンジンです。
```
と記載されており、「春日部つむぎ」は搭載されていないのかな...と思いました。
もし、そちらでも「春日部つむぎ」や「波音リツ」など他のライブラリも使用できるようでしたら、
それも併記して頂けるとわかりやすいと思います！


<details>
  <summary>以下余談です:</summary>
私は、Discordと呼ばれるチャットツールのBot（DiscordはAPIを公式に提供しており、プログラミングで拡張機能のようなものを追加することが認められています）開発者で、「投稿されたメッセージを通話で読み上げる」という機能をVOICEVOX_ENGINEを用いて開発させて頂いております。
（フリーで使うことができる既存の音声合成エンジンの中でかなりかわいい声なので、使って頂いてる方からも非常に高評価を頂いております...!!本当にありがとうございます！）

このような状況だと、「投稿されたメッセージ→すぐ音声合成→通話に流す」ということが求められています。
現在はメッセージの投稿（日本語100文字）から発声までに20秒程度を要しており、これの解決が課題となっているのです...。

</details>

**Comment by AsPulse** [comment]
Core側にもIssueを開かせて頂きました。

**Comment by Hiroshiba** [comment]
> もし、そちらでも「春日部つむぎ」や「波音リツ」など他のライブラリも使用できるようでしたら、
> それも併記して頂けるとわかりやすいと思います！

利用できるはずです！
バージョンによって使用できるキャラクターが異なってきて混乱のもとなってしまいそうだったので、キャラクター名に関する記述をREADMEから省くことにしました。
言って頂けないと気づけませんでした、提案ありがとうございます！

CPU利用率の決定方法は先にコアの対応が必要そうですが、もしそれが実装されたのであれば何らかの方法でエンジン起動（run.py）のパラメータにすると良いのかなと思いました！

**Comment by Oyaki122** [comment]
コア側での対応は終了しました
コアのinitialize関数の引数に設定項目が追加されています

今後はエンジン側での対応をお願いします

**Comment by Hiroshiba** [comment]
@AsPulse さん

もしよかったらコード書いてみませんか？👀

こんな感じでパラメータを受け取って、
https://github.com/VOICEVOX/voicevox_engine/blob/5496881aa2cf6a7fe2b13f52dd555fdee5ce5910/run.py#L490-L496

initialize関数に渡せばOKなはずです。
https://github.com/VOICEVOX/voicevox_engine/blob/6a1a951471350febc1d62b1edcb64c566f1aaaea/voicevox_engine/synthesis_engine/make_synthesis_engine.py#L50

開発にはこちらの新しいコアを使う必要があります。
https://github.com/VOICEVOX/voicevox_core/releases/tag/0.10.preview.2

新しいコアを使うにはrun.pyに`--voicelib_dir`を指定して起動すれば良いのですが、もしかしたらうまく起動しないかもしれません。
その際はこちらのissueが参考になるかもです。

- https://github.com/VOICEVOX/voicevox_engine/issues/236

**Comment by AsPulse** [comment]
ありがとうございます！（時間的に）今日の17時ころからになりますが、書いてみます！

**Comment by Hiroshiba** [comment]
おー、ではよろしくお願いします！！
わからないことあれば聞いていただければ…！

**Comment by AsPulse** [comment]
少し気になったのですが...
- https://github.com/VOICEVOX/voicevox_core/releases/tag/0.10.preview.2
このリリースには、下のコミットが含まれていないと思うのですが大丈夫でしょうか...？
- https://github.com/VOICEVOX/voicevox_core/commit/5db2faef093071a534738849c164282f32e83048

**Comment by Hiroshiba** [comment]
あ…大丈夫じゃないですね、後ほど作り直します。
（ご指摘ありがとうございます！）

**Comment by Hiroshiba** [comment]
cpu_num_threadsがあるpreview版を作ってみました！
https://github.com/VOICEVOX/voicevox_core/releases/tag/0.10.preview.3

**Comment by AsPulse** [comment]
皆様本当にありがとうございました...！！
できたビルドを確認してみて、治っているようでしたらこのIssueをクローズさせていただきたいと思いますので、もうしばらくお待ち頂けると嬉しいです

**Comment by AsPulse** [comment]
確認しました、確かに使用率は上がったのですが、
合成そのものにかかる時間がむしろ遅くなっていますね...これは別の原因があるのでしょうか...

**Comment by AsPulse** [comment]
イメージ: [`hiroshiba/voicevox_engine:cpu-ubuntu20.04-0.10.preview.11`](https://hub.docker.com/layers/hiroshiba/voicevox_engine/cpu-ubuntu20.04-0.10.preview.11/images/sha256-72a4692189f08d3674c91d292f6b0d24ed0a2549127611e39a006f8e1e0d23c1)
環境: 4Core CPU搭載の Linux
指定方法: VV_CPU_NUM_THREADS環境変数を指定
調査方法: 日本国憲法50文字を、それぞれ5回ずつ読み上げさせ、所要時間を計測する
<details>
<summary>今回使用した文章</summary>

```
日本国民は正当に選挙された国会における代表者を通じて行動しわれらとわれらの子孫のために諸国民との協和
```
</details>


| スレッド数 (`VV_CPU_NUM_THREADS`) | 平均所要時間(ms) | 標準偏差 |
| ------------- | ------------- | ------------- |
| 3 | 12291.8  | 134.3 |
| 2 | 11123.6  | 121.9 |
| 1 | 18471.6  | 134.9 |


1スレッドの場合は、想像通り2スレッドの場合の二倍ほどの時間がかかっているのですが、
3スレッドの場合は2スレッドの場合よりも少し遅くなっているという結果でした。

**Comment by Hiroshiba** [comment]
なるほど！！！初期値のスレッド数にチューニングされている感じなのかなぁ。

ちょっとissueを漁ってみると、ベンチマークでthread数を指定できるようになっていました。
もしかしたらどこかにベンチマーク結果があるかもです。
https://github.com/microsoft/onnxruntime/pull/5390

**Comment by AsPulse** [comment]
CPUをフルで使うという目的は達成できたので、一旦クローズした後、
「スレッド数に見合った性能が発揮されていない」というIssueを再び建てる感じで大丈夫でしょうか...？

**Comment by Hiroshiba** [comment]
気になりましたらそうして頂けると…！

（ただ、dockerを経由していることとか、そもそも別タスクで何か動いてるかもとか、いろんな要因が考えられるのもあって解決はなかなか難しいかもと感じました。）

**Comment by AsPulse** [comment]
わかりました...！
私にできることはデータを集めることくらいなので、
いろいろな条件でやって少しでも原因の切り分けに協力できたらな、と思っています！

改めてありがとうございました！！！！
