### ISSUE TITLE
ユーザー辞書機能のAPIの仕様の決定

### ISSUE THREAD

**Issue by takana-v** [VOICEVOX/voicevox_engine#284]
## 内容
#234 にて、OpenJTalkのユーザー辞書機能が使えるようになりました。
現在の仕様ではあらかじめコンパイルされた辞書を読み込むだけですが、エディタ側で任意の言葉を登録できると便利です。
本Issueはエディタ側との通信に使用するAPIについて仕様を固めたい、という目的で作成しました。

### Pros 良くなる点
ユーザー辞書機能の実現

### Cons 悪くなる点
エディタ側のUIを考えるのが結構大変かも

### 実現方法
/user_dict
- GET ... 辞書一覧の取得
- PUT ... 単語の追加
- DELETE ... 単語の削除
という感じになるでしょうか。

### 検討すべき点
- 品詞を固定するかユーザーに委ねるか
- コストは0にするか自動推定にするかユーザーに委ねるか
- アクセント結合規則はC1で固定してよいか

### 辞書に関する詳細
辞書の形式は以下の通りです。
`表層形,左文脈ID,右文脈ID,コスト,品詞,品詞細分類1,品詞細分類2,品詞細分類3,活用型,活用形,原形,読み,発音,アクセント型/モーラ数,アクセント結合規則`

以下は現在の実装の辞書です。
https://github.com/VOICEVOX/voicevox_engine/blob/73e32877dab4b235e07d38a52a5433fb975960f8/user-dic.csv

以下はOpenJTalkの辞書です。
https://github.com/r9y9/open_jtalk/blob/957229334996d2c9d9fcb73cdb3f4d9c15bcdd57/src/mecab-naist-jdic/naist-jdic.csv

Mecabの物ですが、ユーザ辞書の作り方です。
https://taku910.github.io/mecab/dic.html

文脈IDは以下から参照できます。
https://github.com/r9y9/open_jtalk/blob/957229334996d2c9d9fcb73cdb3f4d9c15bcdd57/src/mecab-naist-jdic/_left-id.def

アクセント結合規則は以下のPDFの23ページが分かりやすいです。
https://ccd.ninjal.ac.jp/unidic/UNIDIC_manual.pdf

品詞（文脈ID）を決めるのがユーザー側からすると、少し面倒かもしれません。
しかし、文脈IDが誤ったものになると、形態素解析の結果が誤ったものになる確率が上がってしまいます。
（文脈IDは空でも大丈夫なはずですが、品詞などは必須です。）

コストが空の場合は自動コスト推定の結果になるはずです。（未確認）
しかし、自動推定の結果次第では、きちんと反映されない場合があります。
コストを0にするとほぼ確実に反映されますが、意図しない読み方になる場合があります。
（例：「六花」をコスト0で「リッカ」と登録→「六花亭」が「リッカチン」と読まれる）

## VOICEVOXのバージョン
0.10.0かその次までに実装できればベスト

**Comment by Hiroshiba** [comment]
> 実現方法

ちょっとAPIの設計をどうすればいいか若干わからないのですが、「単語の修正」もあったほうが良いのかなぁと少しだけ思いました。DELETEしてから単語を追加しても一緒なのですが、DELETEだけ成功して追加に失敗することを考えると、あったほうが良いのかなぁとか。
やるとしたらPUTに単語id（か単語を一意に決められる何か）を設定していれば修正に、無指定なら追加にするとかでしょうか。

> 検討すべき点

難しいところですが、エディタをどうするかは置いといて、APIとしては（メンテが容易な範囲で）可能な限り全部の正しい値を受け取れるようにして、ユーザーに委ねることができる感じが良さそうに思います。
一旦こんな感じでどうでしょう。

> 品詞を固定するかユーザーに委ねるか

openjtalkで設定できる品詞を全部選べるようにする感じをイメージしています。
品詞細分類は･･･まあ実装が難しくなければ全部登録可能にしておいても良いのかなと思いました。openjtalkの既存の辞書から一覧をとってくるイメージでいます。

品詞の一覧を返すAPIが別であると便利そうだなとおもいました。
（それとは別に、頻出の品詞一覧を返すAPIがあってもいいかなと思いましたが、それを使うのはたぶんVOICEVOXエディタくらいかもなので、一旦なくて良いかもです。）

> コストは0にするか自動推定にするかユーザーに委ねるか

自動推定は実装が大変そうなので、APIとしてはユーザーに委ねられるようにするのが良さそうに感じました。
といっても0~10000オーバーのコストで何を設定すれば良いのか難しいので、別で優先度みたいなのを設定可能にする別口があっても良いかもと思いました。
例えば、0~100で優先度を指定でき、既存辞書でのコスト全部のパーセンタイル値にマッピングされる感じを想像しています。

> アクセント結合規則はC1で固定してよいか

むずかしいですね･･･
エディタをどうするか置いといて、API側はいろいろ指定できるようにしても良いかもと思いました。

**Comment by Hiroshiba** [comment]
ユーザー辞書機能の追加はなかなか要望を頂くのでぜひ進めたいですね！！
https://twitter.com/roku10shi/status/1484475504727973889

こちらのプルリクエストもちょくちょく進めていきたいところですが、どんなAPIにすると良さそうでしょうか･･･？

**Comment by takana-v** [comment]
とりあえず以下の感じで考えています。

実装する機能
- コストの決定
- モーラ数の算出
- 半角アルファベットの修正
- 各種値の検証
  - 品詞が有効か
  - 読み/発音がカタカナか
  - アクセント型がモーラ数を超えてないか
  - アクセント結合規則
- 辞書の保存
  - jsonなどでユーザー辞書を保存
    - 過去のものと重複しないように単語IDを割り振る
  - dicファイルは再利用するようにする

エンジンに渡すもの
- 表層形
- コストのパーセンタイル値
- 品詞
- 読み
- 発音
- アクセント型
- アクセント結合規則

エンジン内部で持つもの

key: 
- left-id.defの品詞

value:
- コストのパーセンタイル
- 検証に必要な情報
  - 取りうるアクセント結合規則（接頭詞P/助詞・助動詞F/普通名詞・接尾詞C/＊）
  - アクセント型が＊を許すか（モーラも＊になる）

本当はopenjtalk側に検証を任せたいところですが、適当なファイルで試したところセグフォしてインタプリタごと落ちたのでエンジン側で可能な限り値を検証する必要がありそうです。
（もしくはopenjtalk側で正しくエラーに対処できるようにする）

**Comment by Hiroshiba** [comment]
まとめありがとうございます！
完成品のイメージが湧いてくるとても良いまとめに感じました！！

以前、エンジン側はopenjtalkが受け取れる値は全部カバーできてると嬉しいみたいなコメントをしましたが、 @.takana-v さんのまとめをみた感じ、全部カバーしようとすると流石に時間がかかっちゃうかも？と思いました。

一旦最小限の実装にするというのはどうでしょう。
最小限の実装はこんな感じかなぁと思いました･･･！

### 実装する機能

- 品詞は名詞固定
- 読みは無しで発音のみ（ボイボでは発音だけ使っているので）
- アクセント結合規則も固定
- コストは固定（程よく使う単語、「カップラーメン」くらいの適当なコストでどうでしょう）
- モーラ数の算出
- 半角アルファベットの修正
- 各種値の検証
  - 発音がカタカナか
  - アクセント型がモーラ数を超えてないか
- 辞書の保存
  - jsonなどでユーザー辞書を保存
    - 過去のものと重複しないように単語IDを割り振る
  - dicファイルは再利用するようにする

### エンジンに渡すもの
- 表層形
- 発音
- アクセント型

### エンジン内部で持つもの

一旦無し

**Comment by Hiroshiba** [comment]
ちょっと工程がどんな感じになるか考えてみました。
これ１つ１つに対しPRがあるという粒度です。

- [ ] 単語登録＆辞書に追加＆コンパイル
  - 名詞のみで、発音・表層系・アクセント型のみ 
- [ ] 単語の上書き＆消去
- [ ] 品詞ごとのコストのパーセンタイル値作成コード＆パーセンタイル値データ追加
- [ ] 名詞でのコストのパーセンタイル値を追加
- [ ] 名詞以外のわかりやすい品詞を追加（動詞・形容詞とか。可能なら語尾も）
- [ ] アクセント結合規則・読みの追加
- [ ] 検証に必要な情報の作成コードを追加
- [ ] 名詞以外の品詞を追加

仰々しく書いているので多く見えますが、ユーザーがほしいのは上５つくらいなのかもです。
見た目よりはmustなとこは少なめかも？

エディタ側にもタスクが発生するはずなので、voicevox_projectの方にissue作ってみます！

**Comment by takana-v** [comment]
ユーザー辞書機能がおおむね完成したので、こちらのIssueはcloseします。

**Comment by Hiroshiba** [comment]
素晴らしいことだと思います！！！👏
