### ISSUE TITLE
APIドキュメントを自動生成する

### ISSUE THREAD

**Issue by Hiroshiba** [VOICEVOX/voicevox_engine#304]
## 内容

今APIドキュメントは適当にリリースのタイミングで更新しています。
たぶんバージョンごとやlatestなど、いろんなAPIドキュメントがあると便利だと思います。
とくにlatestのドキュメントは更新が大変なので、自動生成にしたいかもです。

### Pros 良くなる点

最新のドキュメントを読める

### 実現方法

Github Actionsで別ブランチにドキュメント.htmlを作成し、github pagesでそちらを参照するようにする、とかどうでしょう。

**Comment by Issei0804-ie** [comment]
こんにちは，こちらの issue にチャレンジしてみようと思い少し実験してみました．


現状，下記のコマンド操作で   API ドキュメントの自動生成 &  github pages に自動アップロード  を行うことができます．

```
$ python -m pip install -r requirements-test.txt 
$ python make_docs.py

# 初回だけ下記の空ブランチ作成のコマンドを実行
$ git checkout --orphan gh-pages

# 2回目以降は下記のコマンドを実行
$ git worktree add --track -b gh-pages gh-pages-temp origin/gh-pages 

# 私の環境だとなぜか cp が cp -i に ailias されてたので \ が必要でした．
$ \cp -f docs/api/index.html gh-pages-temp/index.html
$ cd gh-pages-branch 
$ git add index.html
$ git commit -m"update docs"
$ git push origin gh-pages 
```

空ブランチを作成する作業を CI に入れる方法が今のところ思いつかないので，ここは手作業でやってもらったほうがいいのかなぁと思います．

何か改善できそうな箇所があればご指摘下さい :pray:


ちなみに， GitHub Actions の設定はこのコメントを Hiroshiba さんに確認してもらってから書き始めます．


下記に実験したリポジトリと pages のリンクを貼っておきます．

- [リポジトリがここ](https://github.com/Issei0804-ie/voicevox_engine/tree/gh-pages)
- [pagesの URL](https://issei0804-ie.github.io/voicevox_engine/) 


よろしくおねがいします!!!!

**Comment by Hiroshiba** [comment]
@Issei0804-ie さん
コメントありがとうございます！　ぜひお願いしたいです！

提案されたコードの感じ、良さそうに感じました！
もしかしたら既存のgithub actionを借用すると更に綺麗に書けるのかも？
[peaceiris/actions-gh-pages](https://github.com/peaceiris/actions-gh-pages)

空のブランチは必要とあらば作成したいと思います。
プルリクエスト、お待ちしています！

**Comment by Issei0804-ie** [comment]
@Hiroshiba さん
返信ありがとうございます:crab: 

また，既存の github action を紹介して頂きありがとうございます！

恐らくそれを使用したほうが  綺麗に書けそう & メンテナンスも楽になりそう  なので，
使用を前提に github actions の設定を書いてみます．

もし，空ブランチの作成が必要であればコメントするので，その時はよろしくお願いします :pray:

**Comment by Hiroshiba** [comment]
承知しました！　ぜひよろしくおねがいします！

**Comment by Issei0804-ie** [comment]
@Hiroshiba さん

CI が終わっていたので、[デプロイ先](https://voicevox.github.io/voicevox_engine/)を確認したのですが、404 が返ってきました。


merge した後に Pages の設定を行う必要があるのですが、もし忘れていたら設定をお願いします!!

設定の方法: https://github.com/VOICEVOX/voicevox_engine/pull/364

**Comment by Hiroshiba** [comment]
@Issei0804-ie ご連絡ありがとうございます！設定してみたのでしばらくあとに反映されると思います･･･！

**Comment by Issei0804-ie** [comment]
設定ありがとうございます、見えました!!
