### ISSUE TITLE
作業ディレクトリに影響されないようにする

### ISSUE THREAD

**Issue by takana-v** [VOICEVOX/voicevox_engine#307]
## 内容

現在、作業ディレクトリがvoicevox_engine直下でないと動かないことがあります。
以下はその例ですが、未発見のものがあるかもしれません。
- `/speaker_info`
- ユーザ辞書機能（#305 で修正済）

### Pros 良くなる点

これらを修正すると、外部のプログラムから呼び出した場合でも正常に動くようになります。

### Cons 悪くなる点

なし

### 実現方法

まずは作業ディレクトリに影響される可能性が高い機能を探す必要がありそうです。

## VOICEVOXのバージョン

0.10.0

**Comment by Hiroshiba** [comment]
issueありがとうございます！

データを放り込むディレクトリ（assetとか？）を作って、
FileManagerクラスかモジュールを作って、
わかりやすいメソッド（get_asset_pathとか）を持たせるといいのかなと思いました。

**Comment by takana-v** [comment]
https://github.com/VOICEVOX/voicevox_engine/pull/301 がマージされればutilityにエンジンのルートフォルダを取得する関数が追加されます。
それを使うのが楽かもしれません。
