### ISSUE TITLE
docker GPUが落ちる

### ISSUE THREAD

**Issue by kuroneko6423** [VOICEVOX/voicevox_engine#308]
## 質問の内容

dockerでGPU版を起動しようとしてるのですがすぐに落ちてしまいます。cudaは入れています。

## VOICEVOXのバージョン

0.9.5

## OSの種類/ディストリ/バージョン

- [ ] Windows
- [ ] macOS
- [ x ] Linux

UbuntuServer 20.04 LTS

## その他

どうしたらGPU版が起動しますか？
GPUはGeForce GTX 670２枚です。

**Comment by takana-v** [comment]
https://github.com/VOICEVOX/voicevox_engine#gpu

こちらの手順で起動が可能です。
問題が発生する場合は、ログ等の情報提供をお願いします。

（私のwindowsのdocker環境（GPU）では起動、音声合成に問題はありませんでした）

**Comment by kuroneko6423** [comment]
失礼ながらUbuntuでdockerのログを確認するにはどうすればいいでしょうか？
調べた方法でも
root@KuronekoServer-Server2:~# docker logs voicevox_engine:nvidia-ubuntu20.04-0.9.5
Error: No such container: voicevox_engine:nvidia-ubuntu20.04-0.9.5
になってしまって...

**Comment by takana-v** [comment]
docker run時に`--rm`オプションを外してお試しください。
また、バージョン0.9.5をお使いのようですのでlatestあるいは0.10.1の使用をおすすめします。

----
GeForce GTX 670とのことですので、GPUのメモリ不足が考えられます。
同様に、PC本体のメモリが不足していることも考えられます。
そのような場合はCPU版の使用、あるいはGPUやメモリなどの換装を検討してください。

（メモリ不足時のエラー例）
```
Traceback (most recent call last):
  File "./run.py", line 565, in <module>
    synthesis_engines = make_synthesis_engines(
  File "/opt/voicevox_engine/voicevox_engine/synthesis_engine/make_synthesis_engines.py", line 75, in make_synthesis_engines
    core = CoreWrapper(use_gpu, core_dir, cpu_num_threads)
  File "/opt/voicevox_engine/voicevox_engine/synthesis_engine/core_wrapper.py", line 169, in __init__
    raise Exception(self.core.last_error_message().decode("utf-8"))
Exception: ONNX raise exception: std::bad_alloc
```

**Comment by kuroneko6423** [comment]
root@KuronekoServer-Server2:~# docker run  --gpus all -p '127.0.0.1:50021:50021' hiroshiba/voicevox_engine:nvidia-ubuntu20.04-0.9.5
docker: Error response from daemon: could not select device driver "" with capabilities: [[gpu]].
ERRO[0001] error waiting for container: context canceled

**Comment by takana-v** [comment]
当該エラーで[検索すると](https://www.google.com/search?q=Error+response+from+daemon%3A+could+not+select+device+driver+%22%22+with+capabilities%3A+%5B%5Bgpu%5D%5D.)一般的なDockerのエラーのようです。
VOICEVOX engine側の問題ではないためcloseします。
もしDockerでのGPUの使用が難しいようであればCPU版、もしくはlinux向けバイナリの使用を検討してください。
