### ISSUE TITLE
途中に？を置くと別の箇所が間延びすることがある

### ISSUE THREAD

**Issue by Hiroshiba** [VOICEVOX/voicevox_engine#318]
## 不具合の内容

[こちらの方](https://twitter.com/CeT8XbNOlin6yUi/status/1487362088041586690)の報告の通り、擬似疑問文をONにした状態で「でも？再生数伸びてないよね」という音声を生成すると、後ろの「再生数」の最後が間延びします。
バグっぽい挙動なのですが、原因わかる方いたら報告頂けるととても助かります。

### 再現手順

「でも？再生数伸びてないよね」で再生

### 期待動作

途中に？がないときと同じ読み方がされる

## VOICEVOXのバージョン

0.10.2

## その他

この辺りの変更が問題になってるかも

- https://github.com/VOICEVOX/voicevox_engine/pull/314
- https://github.com/VOICEVOX/voicevox_engine/pull/313

修正されたらhotfixを入れるつもりです！

**Comment by takana-v** [comment]
ちょっと検証してみたいと思います。

**Comment by takana-v** [comment]
pyopenjtalk側の問題のようです。
full_context_labelを見てみると、「でも」「再生数」まで疑問文と判定されているみたいです。
（f3が1になっている）
```
sil:xx
d:1
e:1
m:1
o:1
pau:xx
s:1
a:1
i:1
s:1
e:1
e:1
s:1
u:1
u:1
n:0
o:0
b:0
i:0
t:0
e:0
n:0
a:0
i:0
y:0
o:0
n:0
e:0
sil:xx
```

仕様として許容するか、pyopenjtalk以外の手段で疑問文を判定するか、どちらが良さそうでしょうか？
@Hiroshiba

**Comment by Hiroshiba** [comment]
おおお。。不具合の原因箇所が思ったよりどうしようもなさそうですね。。

と思ったのですが、手元でopenjtalkをそのまま叩いた感じ、正しい位置だけに疑問文フラグが立っているかも･･･？
かなりお手数おかけしてしまうのですが、openjtalkをそのまま実行してみて試して頂くことってできますか 👀 
たしかopenjtalkのCLIコマンドを`-ot [ファイル名].txt`引数付きで実行するとlogファイルからフルコンテキストラベルが手に入るのですが、こちらは正しいものが出ている気がしたので伺ってみた次第です。

openjtalkのlogファイルを見るコマンドやフルコンテキストラベルを抽出するコードはこちらが参考になるかもです。
https://github.com/Hiroshiba/openjtalk-label-getter/blob/5e55da14bdda6386dae63ddb67853c65a550df9a/openjtalk_label_getter/__init__.py#L96-L111

手元の環境のopen_jtalkはバージョン`1.10`でした。

･･･まあ原因究明はさておき、一旦は仕様としてしまうのが妥当かなーと感じました･･･！

**Comment by takana-v** [comment]
確かにaptで入れたopen_jtalkでは正しい位置ですね...（1.10）
pyopenjtalkの辞書を指定しても同じでした。

pyopenjtalk側で問題が発生しているみたいですね。
（さっきの結果は`pyopenjtalk.extract_fullcontext`のもの）
ちょっと原因究明は大変そうです...

**Comment by Hiroshiba** [comment]
なるほどです、ありがとうございます！！

ということは、このままのアーキテクチャで行くならpyopenjtalk側を変える必要がある感じで
すね･･･
今持っている知識で、見る必要がありそうな箇所をメモしてみます。

pyopenjtalkは開発者の方が自分でopenjtalkをforkしたものが利用されています。
https://github.com/VOICEVOX/pyopenjtalk/tree/de0aafc16ec762a159c1ddfcb92488053f49191c/lib
なのでこのforkされているopenjtalk内に問題がある可能性があります。

もしくは、pyopenjtalk内でopenjtalkの処理を模倣？している箇所があるのですが、ここの処理が間違っている可能性もありそうです。
https://github.com/VOICEVOX/pyopenjtalk/blob/de0aafc16ec762a159c1ddfcb92488053f49191c/pyopenjtalk/openjtalk.pyx#L162-L178

解決のために取れる手段は２つありそうです。
１つはpyopenjtalkを改修することです。openjtalkのロジックを見る必要があり、なかなか大変だと思います。
２つ目はopen_jtalkのCLIコマンドをラップすることです。正直音素やアクセントを得るだけならこちらのほうがずっと簡単だと思うのですが、将来的に見据えているユーザー辞書を更新するう部分を対応するのが大変かもしれません。
mecabのCLIコマンドに辞書の作成があると楽かもなのですが･･･

とりあえずpyopenjtalk側にissue立てても良いかもと思いました。

**Comment by takana-v** [comment]
pyopenjtalkが依存しているopen_jtalkを更新すると改善しました。
open_jtalkの更新で解決する場合のタスクは以下の通りです。

- [ ] open_jtalkの更新
  - https://github.com/VOICEVOX/open_jtalk/pull/1
- [ ] pyopenjtalkの依存関係更新
- [ ] vveの依存関係更新
- [ ] vveのライセンス情報更新

**Comment by Yosshi999** [comment]
と思ったら↑のPRで解決してますね

これまでのNJD_print

```
でも,接続詞,*,*,*,*,*,でも,デモ,デモ,1/2,*,-1
？,フィラー,*,*,*,*,*,？,？,？,4/0,*,0
再生,名詞,サ変接続,*,*,*,*,再生,サイセイ,サイセー,0/4,C2,1
数,名詞,接尾,一般,*,*,*,数,スウ,スー,1/2,C3,1
伸び,動詞,自立,*,*,一段,連用形,伸びる,ノビ,ノビ,3/2,*,0
て,動詞,非自立,*,*,一段,未然形,てる,テ,テ,1/1,*,1
ない,助動詞,*,*,*,特殊・ナイ,基本形,ない,ナイ,ナイ,1/2,動詞%F3@0/形容詞%F2@1,1
よ,助詞,終助詞,*,*,*,*,よ,ヨ,ヨ,0/1,名詞%F1/動詞%F1/形容詞%F1,1
ね,助詞,終助詞,*,*,*,*,ね,ネ,ネ,1/1,動詞%F1/名詞%F1/形容詞%F1,1
```

1.11のNJD_print

```
でも,接続詞,*,*,*,*,*,でも,デモ,デモ,1/2,*,-1
？,記号,一般,*,*,*,*,？,？,？,0/0,*,0
再生,名詞,サ変接続,*,*,*,*,再生,サイセイ,サイセー,4/4,C2,0
数,名詞,接尾,一般,*,*,*,数,スウ,スー,1/2,C3,1
伸び,動詞,自立,*,*,一段,連用形,伸びる,ノビ,ノビ,3/2,*,0
て,動詞,非自立,*,*,一段,未然形,てる,テ,テ,1/1,*,1
ない,助動詞,*,*,*,特殊・ナイ,基本形,ない,ナイ,ナイ,1/2,動詞%F3@0/形容詞%F2@1,1
よ,助詞,終助詞,*,*,*,*,よ,ヨ,ヨ,0/1,名詞%F1/動詞%F1/形容詞%F1,1
ね,助詞,終助詞,*,*,*,*,ね,ネ,ネ,1/1,動詞%F1/名詞%F1/形容詞%F1,1
```

**Comment by takana-v** [comment]
個人的にはopenjtalkのバージョンと辞書のバージョンの不一致が気になっています。
openjtalkのバージョンは1.10ですが、pyopenjtalkが使う辞書は1.11のものです。
1.11でunidicの追加、一部パラメータの変更が入っています。
（タイミングが被ってしまいました...）

1.10のopenjtalkと1.11のopenjtalkを使った際の差分です。
```
NJD_print(self.njd)の結果
1.11
？,記号,一般,*,*,*,*,？,？,？,0/0,*,0
1.10
？,フィラー,*,*,*,*,*,？,？,？,4/0,*,0
JPCommon_print(self.jpcommon)の結果
1.11
？,記号,*,*,0,0
？,感動詞,*,*,4,0
```

**Comment by Hiroshiba** [comment]
修正作業が完了しました！　調査本当にありがとうございます！！！

エンジンのバージョンを上げ、releasesを作成しました。
https://github.com/VOICEVOX/voicevox_engine/releases/tag/0.10.4

ビルドされたら次はエディタ側をビルドし、問題なさそうであればリリースしたいと思います！
