### ISSUE TITLE
コアのctypes実装の修正など

### ISSUE THREAD

**Issue by takana-v** [VOICEVOX/voicevox_engine#323]
## 内容

現在のctypes実装ではファイル名に基づいたファイル探索を行っていますが、0.10の製品版に対応していません。
これを修正します。

- dllの場所がフォルダ直下からcore/lib以下に移動
  - `--voicevox_dir`の修正
  - binファイルとdllの場所が違う可能性を考慮する必要が生じた
- dllの名前にアーキテクチャ名が含まれず`core.dll`のまま
  - dllの名前でのコアの種類の判別が不可能になった

### 実現方法

`voicebin_dir`（仮称）を作り、binファイル群の場所を指定するようにする
`voicebin_dir`からmetas.jsonを読み込み、バージョンを確認する

できれば同時にこのリファクタリングも行いたいです。
https://github.com/VOICEVOX/voicevox_engine/pull/254#discussion_r789713612

## その他

他の人と被らないようにするためのIssueです。

**Comment by Hiroshiba** [comment]
issue化ありがとうございます！

> voicebin_dir

こちら、役割的には`voicelib_dirs`と同じなのかなと思ったのですがどうでしょう👀

https://github.com/VOICEVOX/voicevox_engine/blob/c7cda72cbb38c84958d40aa078b86e5787e9a958/voicevox_engine/synthesis_engine/make_synthesis_engines.py#L26-L27

**Comment by takana-v** [comment]
現状では`voicelib_dirs`に「`core.dll`の場所」と「`*.bin`の場所」の2つの意味があります。
（initializeの時に後者の意味で使っています）

これまではそれでも問題ありませんでしたが、0.10でdllとbinの場所が分かれたので、「`*.bin`の場所」を示す、`voicebin_dir`を作りたいと思っています。
（もう少しいい名前があればそれにしたいです）

**Comment by Hiroshiba** [comment]
なるほどです！！！
バージョン0.10のエンジンパッケージは理由があってcore/lib/core.dllにあるんですね！！

https://github.com/VOICEVOX/voicevox_engine/blob/release-0.10/.github/workflows/build.yml#L759-L761

今のmasterだと、バージョン0.10をvoicevox_dirに与えるとうまく動かないから、`voicebin_dir`を追加して修正する、という認識であっていますか👀

であれば、今のmasterはバージョン0.10のエンジンをvoicevox_dirで指定できない、という仕様にしてしまう手もあるかなと思いました。
というのも、現状のディレクトリ構成は結構複雑で、これ以上増やすとメンテナンスコストが上がってしまう一方、0.11に上がればおそらく不要になってしまうためです。

今のmasterで0.11プレビュー版をビルドし、それをvoicevox_dirに指定してもらうことで問題を迂回できるのであればそうしたいのですが、どうでしょうか👀

**Comment by takana-v** [comment]
それで問題ないかと思います。
タスクはこのような感じでしょうか。
とりあえずこのIssueはcloseしておきます。

- [ ] 0.11プレビュー版をビルド
- [ ] 0.10では動かない旨をIssueでピン止め

**Comment by Hiroshiba** [comment]
0.10で動かない件はREADMEに書く手も良いかもです。

0.11のプレビュー版をビルドし始めてみました！
https://github.com/VOICEVOX/voicevox_engine/releases/tag/0.11.preview-0
