### ISSUE TITLE
アーキテクチャを考慮した共有ライブラリのロードをする

### ISSUE THREAD

**Issue by HyodaKazuaki** [VOICEVOX/voicevox_engine#324]
## 内容

https://github.com/VOICEVOX/voicevox_engine/issues/322#issuecomment-1038100126 にあるように、VOICEVOXエンジンはアーキテクチャを考慮して共有ライブラリをロードする機構がありません。
このIssueでは、この機能を実装することを提案します。

### Pros 良くなる点

x86_64以外のアーキテクチャ(aarch64など)で共有ライブラリをロードすることができるようになる。

### Cons 悪くなる点

実現方法に記載するように、アーキテクチャの情報は`platform`ライブラリを使って取得します。
しかし、これで得られる値はコンピュータによって様々です。
例えば、64bitのIntel/AMD CPUでは、`x86_64` / `x64` / `AMD64`などの値が返ってきます。
そのため、これらを網羅しなければならないのですが、`platform`ライブラリのドキュメントには記載がありません。
https://docs.python.org/ja/3/library/platform.html#platform.machine
これにより、対応しているアーキテクチャを持ったコンピュータが弾かれてしまい、利用できない可能性があります。

### 実現方法

Pythonの`platform`ライブラリを利用します。
以下の各関数で行われているOS判定に加えて、アーキテクチャの判定を行います。
https://github.com/VOICEVOX/voicevox_engine/blob/c7cda72cbb38c84958d40aa078b86e5787e9a958/voicevox_engine/synthesis_engine/core_wrapper.py#L11-L33
https://github.com/VOICEVOX/voicevox_engine/blob/c7cda72cbb38c84958d40aa078b86e5787e9a958/voicevox_engine/synthesis_engine/core_wrapper.py#L36-L56
https://github.com/VOICEVOX/voicevox_engine/blob/c7cda72cbb38c84958d40aa078b86e5787e9a958/voicevox_engine/synthesis_engine/core_wrapper.py#L59-L109

## その他

#322 を実現するために必要なIssueです。
私(@HyodaKazuaki )が担当します。

コードを確認していた所、`onnxruntime`をバックエンドに利用する場合にGPUフラグが動作していないように思えました。
https://github.com/VOICEVOX/voicevox_engine/blob/c7cda72cbb38c84958d40aa078b86e5787e9a958/voicevox_engine/synthesis_engine/core_wrapper.py#L65-L80
これは正常な仕様でしょうか？

**Comment by y-chan** [comment]
個人的に、ライブラリのロードに際してアーキテクチャを考慮する必要はないと思っています。
というのも、基本的に(MacのUniversal Binaryのような例外を除いて)ビルドする際はアーキテクチャごとにビルドしますし、開発の際もアーキテクチャは基本固定されます。
開発の手順を楽にするために、各アーキテクチャごとに対応したコードを書くよりも、開発時・ビルド時に各自がバイナリの名前を固定した名前(`core.dll`など)に変更するように指定・READMEなどで指示する方が楽なのではないかと思いました。
ただでさえ現状のcore wrapperはif文が多く、ネストされているのに、これ以上アーキテクチャごとのコードを増やすとなると可読性・保守性が落ちることは目に見えているのではないでしょうか...

あくまで個人的な意見ですし、私の見識が狭いだけかもしれないですが、コメントしておきます。

その他のonnxruntimeを利用する際のコードは単純にミスな気がします...

**Comment by HyodaKazuaki** [comment]
> 開発の手順を楽にするために、各アーキテクチャごとに対応したコードを書くよりも、開発時・ビルド時に各自がバイナリの名前を固定した名前(core.dllなど)に変更するように指定・READMEなどで指示する方が楽(今後のことも考えた保守性が高い)なのではないかと思いました。

確かに、そちらのほうが良さそうです。
`run.py`に与えている実行時引数`--voicelib_dir`を`--voicelib_path`に変更して直接共有ライブラリを指定する形でしょうか。

> その他のonnxruntimeを利用する際のコードは単純にミスな気がします...

わかりました。
では、このIssueに対するPRで対応したいと思います。

> P.S. 私自身アーキテクチャを分ける目的がいまいち見えていない気がしたのですが、aarch64などでは現状書かれているlibtorchやonnxruntimeのライブラリ以外に何か必要ということでしょうか....?(だとしたら話は変わってくると思います)

このIssueで取り上げている問題は、VOICEVOX Coreのファイル名が`core_wrapper.py`にハードコードされているために、aarch64などの環境下で適切なVOICEVOX Coreをロードできないという点です。
目的は、この問題を解決するために以下のいずれかの手をとることで、この問題を解決することです。
* アーキテクチャを考慮してVOICEVOX Coreをロードするようにする
    このIssueで最初に提案した方法です。
* `--voicelib_path`などでライブラリを直接指定してロードするようにする
    @y-chan に提案していただいた方法です。

ですので、この他にライブラリが必要というわけではありません。

**Comment by PickledChair** [comment]
@HyodaKazuaki 

> コードを確認していた所、onnxruntimeをバックエンドに利用する場合にGPUフラグが動作していないように思えました。
> これは正常な仕様でしょうか？

ご質問ありがとうございます。私は実装者ではないのですが、この部分の変更が行われた PR のレビューに参加していたので、このコードの意図がある程度わかっているつもりで解答させていただきます（もしかしたら考え違いがあるかもしれないので、その場合はコードの正しい意図をどなたかご教示いただけると幸いです）。

この部分のコードは一応正常に動作するという認識です（ただし、状況を整理するうちに、改善の余地がありそうだと思えてきました）。

不自然なコードに見えるのは、おそらくこの部分のコードが「GPU を使用するかどうか」を切り替えるものではなく、「GPU 対応の core を使用するかどうか」を決定するコードであることに起因していると思われます（GPU 対応の core でも CPU モードを使うことができるので、GPU を使用するかどうかと GPU 対応の core を使用するかどうかは異なった問題になります）。また、 `run.py` の起動オプション `--voicelib_dir` に渡すパスとして

- VOIEVOX ENGINE のパス
- https://github.com/VOICEVOX/voicevox_core/releases で配布されている core のパス

の両方を利用可能にしていることも、このコードの意図の分かりにくさの一因となっているように思います。

## `onnxruntime` 版の core を読み込む場合

#254 で Python の ctypes モジュールを用いて core を読み込むように変更された際、エンジン内蔵の core（この PR 時点では `onnxruntime` 版に移行済み）として https://github.com/VOICEVOX/voicevox_core/releases からダウンロードしたものをリネームせずに VOICEVOX アプリケーションへ同梱し、用いるようになりました（`build.yml` で指定された `voicevox_core_dll_name` をそのまま用いています）。

https://github.com/VOICEVOX/voicevox_engine/blob/c7cda72cbb38c84958d40aa078b86e5787e9a958/.github/workflows/build.yml#L360-L383

https://github.com/VOICEVOX/voicevox_engine/blob/c7cda72cbb38c84958d40aa078b86e5787e9a958/.github/workflows/build.yml#L657

このことから、`use_gpu` フラグを用いなくても core のファイル名からその core が GPU 対応版であるかどうかが判別できます。`core_gpu_x64_nvidia.dll` の読み込みが失敗すれば、代わりに CPU 版の core が存在すると仮定して `core_cpu_x64.dll` を読み込もうとします。その後、以下の `self.core.initialize(".", use_gpu, cpu_num_threads)` の実行で GPU を使用するかどうかを core に伝えています（CPU 版のコア使用時に `use_gpu` が `True` だった場合は `False` が返ると思いますが）：

https://github.com/VOICEVOX/voicevox_engine/blob/c7cda72cbb38c84958d40aa078b86e5787e9a958/voicevox_engine/synthesis_engine/core_wrapper.py#L165

https://github.com/VOICEVOX/voicevox_core/releases で配布されている core を使用する場合でも、core の名前が ENGINE 内蔵版と同じであるため、必要な処理は共通になります。

## `libtorch` 版の core を読み込む場合

`libtorch` 版の場合は少し複雑で、`--voicelib_dir` オプションに渡すパスが VOIEVOX ENGINE のパスであるか、あるいは  https://github.com/VOICEVOX/voicevox_core/releases で配布されている core のパスであるかで、core の名前が違うということに注意しなければなりません。

#254 がマージされる以前は、以下に示すように、VOICEVOX ENGINE に同梱される core は GPU 版・CPU 版ともに `core.dll` にリネームされるようになっていました。：

https://github.com/VOICEVOX/voicevox_engine/blob/cc6836a19f8ee27a733612c46fa9fcdda99c0734/.github/workflows/build.yml#L399-L422

https://github.com/VOICEVOX/voicevox_engine/blob/cc6836a19f8ee27a733612c46fa9fcdda99c0734/.github/workflows/build.yml#L673

つまり、ENGINE 同梱の core を読み込む場合は `use_gpu` フラグを使用する必要はなく、一律に `core.dll` を読み込むようにすれば良いということになります。逆に言えば、ENGINE 同梱の core は initialize するまではそれが GPU 対応版であるかどうかを判断することが不可能です。

一方、https://github.com/VOICEVOX/voicevox_core/releases で配布されている core はリネーム前であるため、GPU 版の core は `core.dll`、CPU 版の core は `core_cpu.dll` という名前になっています。ここで、ENGINE 同梱の core を読み込む時のように一律に `core.dll` をまず読み込む、ということにすると、CPU 版の core である `core_cpu.dll` を使用する手段がなくなってしまいます。そこで、`use_gpu` フラグが `False` であるときは、優先的に `core_cpu.dll` を読み込むようにする、ということにして、これを通して CPU 版の core を使用できるようにしていると考えられます。その上で、実際に GPU を使用するかどうかは `onnxruntime` 版 core を使用するときと同様に `self.core.initialize(".", use_gpu)` で指定します。

## 改善の余地がありそうな点

以下の２点が考えられます：

- `libtorch` 版 core を読み込む処理で、`use_gpu` が `False` である時に `core_cpu.dll` をまず読み込むようにする、という意図がコードから伝わりづらい
- `load_core` 関数の `use_gpu` という引数の名称・役割が紛らわしい

### １点目について

直観的には `use_gpu` フラグが `True` である時に `core.dll` を読み込む、という処理が強調されているように見えます。繰り返しになってしまいますが、おそらくこの部分のコードの本来の意図は `use_gpu` が `False` である時にまず `core_cpu.dll` を読み込むことによって、https://github.com/VOICEVOX/voicevox_core/releases で配布されている core の CPU 版の方を利用可能にする、ということだと思われます。したがって、そちらの処理の方が強調されるべきだと思われました。

### ２点目について

`load_core` 関数は GPU を使用するかどうかに関わっていません。GPU 対応版 core を使用するかどうかを担っています。したがって、`use_gpu` という引数名は紛らわしいものであり、役割も「優先的に `core_cpu.dll` を読み込むかどうか判断する」という、名前からは想像しづらいものです。`use_cpu_core` などという引数に変えると同時に、「優先的に `core_cpu.dll` を読み込むかどうか判断する」という処理は `load_core` 関数の外部に出してしまった方が意図が分かりやすくなるかも、と感じました（改善策についてはもっと良い案があるかもしれません）。

**Comment by PickledChair** [comment]
すみません、自分の文章を読み返して気づいたのですが、`onnxruntime` 版では逆に https://github.com/VOICEVOX/voicevox_core/releases で配布されている core の使用時に `core_cpu_x64.dll` を使用する手段がないですね……。ご指摘の通り、確かにこの部分にもフラグを持たせる必要がありそうです（あるいは指定されたパスに GPU 対応版 core が存在している場合はそちらのみを読み込むようにし、CPU 版は読み込まないようにする、という仕様にするのも１つの手かもしれません）。

一方、`load_core` 関数の `use_gpu` という引数名・役割が紛らわしいかもしれない、という考えはそのままなので、上のコメントは覚え書きとしてそのまま残しておきたいと思います。

**Comment by y-chan** [comment]
あー、なるほど...!
すみません、私自身がctypesを用いた旧コアのロードが可能なエンジンの仕様をうまく把握できていなかったようです...
確かに、ファイル名でGPU依存/非依存を区別しているのであれば、アーキテクチャを考慮した共有ライブラリのロードが必要になりますね...

ただ、コードの煩雑さ的にこれを実装するのはやはり保守性の問題を避けられないと思うので、どこか妥協点を探したいところです(個人的にはハードコードされるのは`libcore.dll`や`libcore.so/.dylib`といった汎用名だけにし、ユーザーにはその名前変えてもらうといった対応に変える・もしくは HyodaKazuaki さんの言うように引数でパスを指定するようにすれば、Issueとして挙げられている問題は解決しそうだと思いました)。

旧コアロードのモチベーションとして、releasesやVOICEVOXディレクトリをそのまま使用したいという点があるのかなと思います。
例えば、スクリプトで旧コアを導入する等を前提とすることで、旧コア導入を簡単化しつつ、Engineのコードの保守性を上げられそうな気はしますが、今度はそのスクリプトを保守しなければならなかったり、そのスクリプトのユーザーサポートが必要だったりと、大きくコストがかかる気がします。

最初に提案されている通り、エンジン自体をアーキテクチャを考慮した形に変更するのが一番楽なんですかね...(私にもわかりません...)

**Comment by PickledChair** [comment]
@HyodaKazuaki @y-chan これまでの意見や提案をまとめると、考慮すべき事項が大きく分けて３つありそうでした：

- アーキテクチャ（`x86_64`/`aarch64` 等）を考慮した共有ライブラリのロード
- GPU依存/非依存を考慮した共有ライブラリのロード
- ユーザーの使い勝手を考慮（旧コア導入を容易にする）

このうち最初の２つをどう整理・実現するかはっきりさせることが重要そうです。３つ目の使い勝手も最終的に外してはならない要素ですが、最初の２つの整理なしには議論できなさそうな気がします。

個人的には、アーキテクチャ・GPU依存/非依存をユーザーが明示的に指定して起動できる仕組みを最初に作り、その後に、明示的指定がない場合に暗黙的にロードすべきコアを選択する仕組みを作る方法が一番堅実だと感じます（後者が「使い勝手」を担う部分です）。

条件を明示的に指定して起動する仕組みを実装するにあたっては、`libtorch` 版と `onnxruntime` 版の VOICEVOX CORE/ENGINE の差異を吸収する必要があります（これに関して、知っている範囲の知識で私も協力できそうです）。これが実装できれば、ロードすべきコアの暗黙的・自動的解決の実装前に、ある程度仕様のあいまいさが排除されて助かる気がしています。

**Comment by Hiroshiba** [comment]
なるほどです！

> --voicelib_pathなどでライブラリを直接指定してロードするようにする

たしか`voicelib_dir`の役割はdll＋必要なバイナリの場所指定で、`voicelib_path`にするとバイナリの場所を指定する引数も必要になってややこしくなるかもです（認識違うかも）

> アーキテクチャ・GPU依存/非依存をユーザーが明示的に指定して起動できる仕組み

引数にあるuse_gpuは[コアの引数に指定する](https://github.com/VOICEVOX/voicevox_core/blob/d042fe54f693393a347917377328648d675577ac/core/src/core.h#L25)ものでもあります。
アーキテクチャは一意なので、platformで自動判定が良いように感じました！
（仮にエディタで使う際は結局platformで自動判別が必要になるので）

> アーキテクチャを考慮してVOICEVOX Coreをロードするようにする

なので、こちらが良いのかなと思いました。
見逃し等あればご指摘お願いします･･･！

---

結構ややこしい課題だなぁと感じました。

「明示的に指定」「platformで自動判定」の他にも、「コア配布パッケージを良い感じにする」手もあると思います。
良い感じとは、環境ごとにコア配布パッケージを分ける形です（過去のコア配布パッケージも含め）。

明示的に指定はエンジン的には綺麗ですが、結局エディタ側に複雑性が移るだけなるかもと思いました。

となると自動判定か配布パッケージの改善ですが、正直保守を考えると自動判定が一番楽なのかなと感じました。
配布パッケージは過去バージョンのマイグレーションが大変で、やるならマイグレーション用のリポジトリを用意することになり、なかなか大変そうです。

**Comment by HyodaKazuaki** [comment]
> > アーキテクチャを考慮してVOICEVOX Coreをロードするようにする
> 
> なので、こちらが良いのかなと思いました。
> 見逃し等あればご指摘お願いします･･･！

コアの複雑さをフロントエンドまで持ち込む必要はないので、エンジンあたりで処理してしまうのがいいかと思います。

ところで1つ疑問なのですが、GPUで**も**利用可能なコア(ここではGPUコアと呼びます)をロードし、失敗した場合にCPUで利用可能なコア(ここではCPUコアと呼びます)をロードする仕様はなぜ存在しているのでしょうか？
VOICEVOXの製品として利用する場合、内部にはGPUコアかCPUコアのいずれかしか入っておらず、`core_wrapper.py`で切り替える必要性がないように感じます。
また、VOICEVOXエンジン単体で利用する場合、利用者がGPUコアかCPUコアのいずれかを用意すれば良いのではないでしょうか。

("たられば"で申し訳ないのですが)コアを`core.zip`でまとめて配布するのではなく、onnxruntimeのようにOS/アーキテクチャごとに配布することができていれば、`core_wrapper.py`はOS判定(dllなのかsoなのかdylibなのか判定するため)だけで済んだのかなと思います。
例えばこの方法に変更する場合、VOICEVOX CoreのReleaseを変更する必要がありますが、それぞれのRelease tagが打たれているコミットでビルドし、ReleaseのAssetsに追加することは難しいでしょうか...?

**Comment by takana-v** [comment]
> GPUでも利用可能なコア(ここではGPUコアと呼びます)をロードし、失敗した場合にCPUで利用可能なコア(ここではCPUコアと呼びます)をロードする仕様はなぜ存在しているのでしょうか？

core.zipを解凍したものを`--voicelib_dir`に指定した時に、GPUコアを優先的に使用するためだったと思います。
GPUコアを使った場合、`/supported_devices`でCPU、GPU両方使えることが分かりますが、CPUコアを使った場合はGPUが使えない、という結果が返ってきます。
それが「PCの環境的にGPUを使えない」のか「GPUは使えるけどCPUコアを使っているから使えない扱いになっている」のかが分からなくなってしまうため、GPUコアを優先的に読み込む仕様にしたはずです。
