### ISSUE TITLE
mock版エンジンがフォールバックにならないようにもできるようにする

### ISSUE THREAD

**Issue by Hiroshiba** [VOICEVOX/voicevox_engine#325]
## 内容

onnxruntimeがimportできなかったとき、エラー無くmock版エンジンにフォールバックします。
この挙動は混乱の原因となっていたりします。

- https://github.com/VOICEVOX/voicevox/issues/701

### Pros 良くなる点

エラーと気づかずに実行してしまうことを防げる

### 実現方法

↓のいずれか

* mock版エンジンでフォールバックしないようにするオプション
* もしくはmock版でエンジンで起動するオプション（コアが起動しなかったらエラーになる）
* もしくはmock版にフォールバックするオプション（コアが起動しなかったらエラーになる）

個人的にはフォールバックしてほしい機会があまりなさそうなので、コアがなければエラーが良いと思っています

## VOICEVOXのバージョン

0.10.4

## その他

別のhotfixがあったときに一緒にhotfixに含めたいと思います。
バージョン0.11が出る前であれば`release-0.10`ブランチに向けてプルリクエストを送ってください。

**Comment by takana-v** [comment]
現在のmasterは`--enable_mock`を付けないとエラーで落ちるようになっているはずです。
（release-0.10には含まれていません）
同名の引数を追加し、make_synthesis_engineを、エンジン作成時にエラーかつ`--enable_mock` がTrueの場合のみMockを使用するように変更すると良いかと思います。

**Comment by Hiroshiba** [comment]
おっと、なるほどです！
release-0.11になると自動解決するけど、0.10のhotfixには入らないという形になりそうですね･･･
とりあえずcloseで良さそうなので、closeしたいと思います！

（docstringは修正するプルリクエスト投げておきました！）
