### ISSUE TITLE
ユーザー辞書をエンジンごとに分けるべきか

### ISSUE THREAD

**Issue by takana-v** [VOICEVOX/voicevox_engine#339]
## 内容

現在のユーザー辞書の設計では、ユーザー辞書の保存先フォルダをエンジンごとに変える必要があります。
そのため、複数エンジンで同じユーザー辞書を使いまわすことができません。
同じユーザー辞書を使いまわせるようにするべきかを含めて議論したいです。

- https://github.com/VOICEVOX/voicevox_project/issues/6

#### Pros 良くなる点
実装が分かりやすい
#### Cons 悪くなる点
複数エンジンで同じ単語登録をしたい場合に手間
#### Pros 良くなる点
ユーザーがエンジンごとに単語を登録する必要がなくなる
#### Cons 悪くなる点
pyopenjtalkを使う処理を行う前に辞書を確認し、必要に応じて再コンパイルする必要がある
（他のエンジンで変更した内容は手動で反映させる必要があるため）
#### 実現方法
user_dictをクラス化してlatestのUserDictオブジェクトを持っておく
ユーザ辞書ファイルがopenjtalkによって排他制御されるので一時ファイルを使うようにする

### その他
案1を採用する場合、外部エンジンで変更漏れが起こる可能性があります。
その場合は@.shirowanisanなどに連絡しておいた方が良いかもと思いました。

**Comment by Hiroshiba** [comment]
全エンジンに同じ辞書登録エンドポイントがあるのであれば、`案1. エンジンごとにユーザー辞書を分ける`を採用しつつエディタ側で全部に登録していく方法もあるのかなと思いました。
この方法であれば、openjtalkを使わないエンジンが仮にあったとしても動くかもです。

この方法だと同期が大変ですが、import/export機能を作ればエディタ側から全エンジンの辞書をそこそこ簡単に同期できるかもです。
もしくはプラグインエンジンの起動時に、VOICEVOXエンジンの辞書をexportして自身にimportする、みたいな設計もあるかもです。

辞書ファイルを共通で使うのは危険な気がしています。（もちろん利便性とトレードオフですが）
例えばどれか１つのプラグインエンジンの辞書作成機能が壊れていたりしたら、全部のエンジンに影響が出そうです。

**Comment by takana-v** [comment]
> プラグインエンジンの起動時に、VOICEVOXエンジンの辞書をexportして自身にimportする

すべてのエンジンの辞書を同期しようとすると、既存のデータをいったん全削除する必要がありますね...
`/import_user_dict`に既存の辞書を破棄する、といった引数を実装してもいいかなと思います。

ただ、エディタ外部からプラグインエンジンにワード追加・変更があった場合、それを上書きしてしまう恐れがありますね。
そこら辺をどうするかは要検討だと思います。

**Comment by Hiroshiba** [comment]
たしかに、完全に同期だと消す必要がありますが、事故りそうですね…。
辞書読み込みに失敗して単語登録がない状態を同期して全滅、みたいな。さすがにそれは無いか…。

そもそも別エンジンだけ単語登録されてる機会は珍しそうですし、とりあえず安パイ側に倒して、余計なものはdeleteせず残すのも良いのかもと感じました。
今のimportの実装は、同じのがあれば上書き、無ければ足す、余計なものはdeleteせず残すって感じでしょうか👀

**Comment by takana-v** [comment]
> 今のimportの実装は、同じのがあれば上書き、無ければ足す、余計なものはdeleteせず残すって感じでしょうか

そうですね。（override=Trueの場合）
override=Falseの場合は同じのがあっても上書きせず前のを残すようになります。

エンジン側で追加の実装が不要そうであれば、このIssueはcloseして結論をVVPの方にメモしたいと思います。
- https://github.com/VOICEVOX/voicevox_project/issues/2

**Comment by Hiroshiba** [comment]
なるほど、上書きするかも選べるんでした！！便利だ。
（全然関係ないけど、overrideよりoverwriteのが一般的かもと今気づきました･･･！）

個人的には安全方向に倒して、辞書の同期＝「同じのがあれば上書き、無ければ足す、余計なものはdelete」とするのが良いかなと思いました。
それは今のimport/exportで可能なので、新たな実装は不要になっていると思います！
設計の勝利！

**Comment by Hiroshiba** [comment]
メモですが、↑の最後の結論コメント、「同じのがあれば上書き、無ければ足す、余計なものはdeleteせず残す」だと思われます。コピー範囲が間違っていそう。
