### ISSUE TITLE
規約同意前にAPIが機能してしまう

### ISSUE THREAD

**Issue by nmori** [VOICEVOX/voicevox_engine#353]
## 不具合の内容
規約に同意する前にAPIをコールすることで機能を利用できてしまう。

エディタ環境に関してのみの利用規約であれば問題ないと思われるが
おそらく意図と異なるとおもわれるためレポートする

### 現象・ログ

規約に同意していなくても、APIをたたけば音声が発話で出来てしまう

### 再現手順

①セットアップ後、規約質問画面を出す
②その状態でAPIをコールする

### 期待動作

①規約に同意してから、engineを起動する
②規約に同意していない状態では engine を起動しても生成処理をしない

## VOICEVOXのバージョン

0.11.2

## OSの種類/ディストリ/バージョン
（すくなくともWindowsではこの現象がおきています）
- [X] Windows
- [ ] macOS
- [ ] Linux

## その他

・さしあたってエディタ側では、エンジンを起動する処理よりも前に
　同意チェックを織り込むことがよいかと思われます。
・engine側には、同意を意味する設定変数もしくは引数があるとよさそうです。
・以前の議論より「起動することで同意とみなす」はあまりよくないとのことでしたので
　回避ルートをなくすほうが良いかと思いました。

**Comment by Hiroshiba** [comment]
issueありがとうございます！

インストール時に表示するのが一番良い気がしました。

とりあえず、同意ボタン前にエンジンが起動できるのは誤解を生みそうなのと、起動ロジックを変えるのは大変なのとそれなりの効果があるのか微妙なので、「次へ」ボタンに変えて暫定対処にできればと思います！

**Comment by nmori** [comment]
そうですね、「同意するまでしか使われないロジック」なので
「がっつり変更するには割に合わない」かもしれません。

そういう意味ではエディタはインストーラ表示にしたうえで
「次へ」にするのが最小工数で済みそうです。
（エンジン自体はインストール時点で同意が得られている形）

仕組みを変えられるタイミングがあるとしたら、
・同意したかどうかの情報は、エディタ側ではなくエンジン側が情報をもつ
・同意していないかぎり、生成命令は実行されない
となるのがよさそうです

（たとえば、将来的にエンジンを組み込んだ製品やdockerイメージができたとしても、
　同意するまで動かない…みたいなことが実現できるかとおもいます）

**Comment by tarepan** [comment]
本 issue の究極の目的は「ユーザーが規約を遵守した使い方をする」かと思います。  
しかしユーザーの利用法には手出し出来ないため、次善の策として本 issue の規約同意システムが提案されたと理解しました。  

ここで問題となるのは目的と「ユーザーが同意チェックを付ける」の間にはかなり距離があることです。  
ユーザーと規約の関係は以下のように整理できます：  

- ① 規約を知らない
- ② 規約の存在を知っている
- ③ 規約を読んだ
- ④ 規約を理解した
- ⑤ 規約の遵守を約束する
- ⑥ 規約を遵守している

目的は⑥の実現ですが、本 issue の規約同意システムができるのは「①→② の促進」に留まると考えます。  
「面倒だからとりあえず同意チェックするか」というユーザーがそれなりにいるとすれば、全員を②の段階とするのも厳しそうです。  

規約を読んでもらわない（③）と遵守も何も無いため、本 issue の規約同意システムの実効的な意義には限界があると感じます。  
かといってより厳密な仕組みを目指し、例えば「規約スクロール」をエディタでなくエンジンに組み込む場合、サーバーでの利用に支障をきたします。  
規約遵守はシステムでなく性善説に基づくのも1つのプラグマティックなやり方かと思います。  

@Hiroshiba  
本 issue での提案法に理論上の限界がある点、本 issue が立ってからの約2年間で解決策が出てきていない点を考慮すると、本 issue は一旦 close が良いと考えます。別の方向性ありそうでしょうか？

**Comment by Hiroshiba** [comment]
@tarepan ありがとうござます！

おっしゃる通りで、利用規約を守る人の数が最大化されると嬉しそうです。
起動の流れを変えれば確かに API を利用するけど規約を知らない人を少なくできるかもしれません。
ただ起動直後に出てくる利用規約画面を見ずにすぐに API利用アプリを使う方はまあそんなに多くないだろうなと想像できます。

それに比べて実装コストはまあまあ高そうです。
と言ってもまあ、合意しました API を作って状態を管理して実行できる API を制御すればいいだけではありそうです。
@nmori さんのおっしゃる通りこの機能は結構便利そうではありますが、破壊的変更になってしまうのでなかなか覚悟は必要かもです。

他にもエディターの方を、利用規約合意後にエンジンを起動するよう、起動シーケンスを変更する手はあるかもです。
まあエディターの起動シーケンスはすごくややこしいことになっているのでこうするのはかなり難しいのですが、エンジンの破壊的変更をする必要がないのでどちらかというとこちらの方が妥当なのかなと思いました。

とりあえずこのissueはクローズする形が良いかなと･･･！
