### ISSUE TITLE
エンジンの機能リストAPIの検討

### ISSUE THREAD

**Issue by takana-v** [VOICEVOX/voicevox_engine#362]
## 内容

- https://github.com/VOICEVOX/voicevox_project/issues/2

こちらのプロジェクトに関するIssueです。
エンジンによっては一部値が無効なものであったり、一部APIが非対応だったりする可能性があります。
そこで、どの機能が有効であるかの情報をエディタ側に提供するAPIを作成します。

SynthesisEngineクラスに情報を持たせるのがいいのかなと思います。

### 機能リストの一覧
勝手に私が考えた機能リストの一覧です。

- AdjustableMora: bool
  - イントネーション欄非表示
  - 音素長調整欄非表示
  - 再生位置追従オフ
  - labファイル書き出しオフ
- AdjustableSpeedScale: bool
  - 話速調整欄非表示
- AdjustablePitchScale: bool
  - 音高調整欄非表示
- AdjustableIntonationScale: bool
  - 抑揚調整欄非表示
- InterrogativeUpspeak: bool
  - 疑似疑問文対応オフ
- DefaultSamplingRate: int
  - 設定画面のデフォルト周波数で使用

もっと良さそうな命名や機能漏れがあったら指摘をお願いします。

**Comment by Hiroshiba** [comment]
CPU/GPUフラグ切り替えに対応しているかどうかも合ったほうが良いかもです･･･！

**Comment by sevenc-nanashi** [comment]
（横からごめんなさい）
殆どがbool値のため、`supported_features`に`list[str]`を持たせる手もありだと思いました。（`DefaultSamplingRate`は別として）
```json
"supported_features": [
  "mora_adjust", "speed_scale", "pitch_scale", ...
]
```のような。

**Comment by Hiroshiba** [comment]
エンジンの機能リストですが、こんな感じの仕様を考えました。

  - engine_manifest.jsonに機能情報を追加する
    - featuresキーに`{ FeatureKey(str): { type: "bool", default: True, name: "機能の名称", description: "機能の簡単な説明" } }`の情報を持たせる
  - エンジン側で↑をロードしてAPI経由で返せるようにする
    - サーバー型のエンジンでも機能リストを取れるようにするため

こちらにも書いてます https://github.com/VOICEVOX/voicevox_project/issues/2#issuecomment-1228687094

@takana-v こんな感じでどうでしょう（型とか意見あれば！！）

**Comment by takana-v** [comment]
これで良いと思います。
