### ISSUE TITLE
README.md に記載されている API ドキュメントのリンクが切れている

### ISSUE THREAD

**Issue by Issei0804-ie** [VOICEVOX/voicevox_engine#368]
## 不具合の内容

#304 , #364  で API ドキュメントのリンクが予期せず変更されてしまいました．

旧: https://voicevox.github.io/voicevox_engine/api/
新: https://voicevox.github.io/voicevox_engine/

そのため，README.md から API ドキュメントのリンクを踏むと 404 が返されてしまいます．

### 現象・ログ

- API ドキュメントのリンクを踏むと 404 が返されてしまう．

### 再現手順

API ドキュメントをご参照下さい。 をクリックする．

![image](https://user-images.githubusercontent.com/52270000/158367644-ab840234-8174-4193-91f1-0167ca858090.png)

### 期待動作

404 ではなく API ドキュメントが返ってくる．

## その他

API ドキュメントを参照している箇所は二箇所あるっぽいです．

```
$ find ./ -type f -print0 | xargs -0 grep https://voicevox.github.io/voicevox_engine/api                                                           ✔  3.8.10  
./README.md:[API ドキュメント](https://voicevox.github.io/voicevox_engine/api/)をご参照ください。
./README.md:[API ドキュメント](https://voicevox.github.io/voicevox_engine/api/)（実体は`docs/api/index.html`）の内容を更新します。
```

**Comment by Hiroshiba** [comment]
issue作成ありがとうございます！！
おっしゃるとおり、一旦READMEを修正し、その後`/api`になるように修正できると嬉しいです！！

**Comment by Issei0804-ie** [comment]
お返事 & PR の承認ありがとうございます!!

fork先で `/api` になるように修正できたので，もう一度 PR 送ります．

この issue とは関係無い話ですが，上手く sub-direcotry を管理すれば release ごとに API ドキュメントを作成して公開，みたいなこともできそうだなぁーと思いました．もう少し考えをまとめて issue を作成してみます!!

**Comment by Hiroshiba** [comment]
> 上手く sub-direcotry を管理すれば release ごとに API ドキュメントを作成して公開

バージョンごとにAPIを用意できると嬉しいので、すごく良いと思います！！
もしよかったらぜひ･･･！
