### ISSUE TITLE
異なるバージョンのAPIドキュメントを閲覧できるようにしたい

### ISSUE THREAD

**Issue by Issei0804-ie** [VOICEVOX/voicevox_engine#375]
## 内容

GitHub Pages を使用して API ドキュメントを公開しているが latest版しか公開できていない．
バージョンごとの API ドキュメントも公開できると，より便利であるので公開方法の検討を行いたい．

### Pros 良くなる点

- 異なるバージョンの API ドキュメントを閲覧できる

### Cons 悪くなる点

- 特になし

### 実現方法

公開方法については，gh-pages ブランチに下記のようにディレクトリを配置すると良い．

```
.(gh-pages)
└── api
    ├── 0.10
    │   └── index.html
    ├── 0.11
    │   └── index.html
    ├── 0.5
    │   └── index.html
    ├── 0.6
    │   └── index.html
    ├── 0.7
    │   └── index.html
    ├── 0.8
    │   └── index.html
    ├── 0.9
    │   └── index.html
    └── index.html
```

過去のバージョンは手作業で commit & push するほうが良いと思われる．
今後のバージョンについては GitHub Actions を用いて自動化したい．

## その他

 API ドキュメントからバージョンを切り替えて表示できるようにしたいのですが良い方法が思いつきません....

**Comment by Hiroshiba** [comment]
Issue作成ありがとうございます！
とても良いと思います･･･！

**Comment by Hiroshiba** [comment]
たしかに、そのエンジンのドキュメントを読めば良いかもですね！
迂回策があるのと、手動でやる場合メンテコストがまあまあかかるので、クローズの方向で良さそうに感じました。

まぁこれは大体のライブラリも同条件で、そのバージョンのドキュメントを読めば良いのですが、過去バージョンのドキュメントも案内されてるあたり、ネット上で過去のも参照できるのは意味のあることなんだろうなとも思います。
チャレンジしたい方がいらっしゃったらissueを再オープンしてください！
