### ISSUE TITLE
Failing to start engine on Linux

### ISSUE THREAD

**Issue by Patchethium** [VOICEVOX/voicevox_engine#377]
## 不具合の内容

Attempting to start the engine on Linux often, let's say, 3 times in 4 attempts, causes a `std::bad_alloc` exception and ends the process. The other attempts just run normally or (rarely) cause a memory leak and freeze the whole computer.

### 現象・ログ

Full log:
```
$ python /home/.../voicevox_engine/run.py --voicevox_dir /home/.../engine
Warning: cpu_num_threads is set to 0. ( The library leaves the decision to the synthesis runtime )
Traceback (most recent call last):
  File "/home/.../voicevox_engine/run.py", line 860, in <module>
    synthesis_engines = make_synthesis_engines(
  File "/home/.../voicevox_engine/voicevox_engine/synthesis_engine/make_synthesis_engines.py", line 72, in make_synthesis_engines
    core = CoreWrapper(use_gpu, core_dir, cpu_num_threads)
  File "/home/.../voicevox_engine/voicevox_engine/synthesis_engine/core_wrapper.py", line 355, in __init__
    raise Exception(self.core.last_error_message().decode("utf-8"))
Exception: ONNX raise exception: std::bad_alloc
```

### 再現手順

Start the engine following README

### 期待動作

Engine always runs without throwing exceptions

## VOICEVOXのバージョン

latest `master` branch

## OSの種類/ディストリ/バージョン

Linux Mint 20.1 x86_64

- [ ] Windows
- [ ] macOS
- [x] Linux

## その他

I also use arch btw

**Comment by Hiroshiba** [comment]
issue作成ありがとうございます！
Thanks for creating the issue!

`std::bad_alloc`･･･ おそらく初めての報告例です。
ちなみに、お使いのPCのメモリ量はいくつでしょう？
`std::bad_alloc`... This is probably the first reported case.
By the way, how much memory does your PC have?

**Comment by Patchethium** [comment]
It's roughly 16 GB.

**Comment by Hiroshiba** [comment]
I see... enough memory...
We are waiting for a solution or another person's report.

**Comment by Patchethium** [comment]
Oh I forgot this issue, the new version doesn't cause this problem anymore. Although I don't know what fixed this but I think it's safe to close now.
