### ISSUE TITLE
Docker cpuモードで「九州そら」最新化が欲しいです。

### ISSUE THREAD

**Issue by LeeYunwhan** [VOICEVOX/voicevox_engine#379]
## 質問の内容

https://hub.docker.com/r/hiroshiba/voicevox_engine で、

hiroshiba/voicevox_engine:cpu-ubuntu20.04-latestをImageとして使いましたが、
/speakersで確認しても現在最新版の「九州そら」は探すことができません。

## VOICEVOXのバージョン
0.11.1

**Comment by Hiroshiba** [comment]
@LeeYunwhan 
Issue作成ありがとうございます！

speakersで得られないのは、こちらが原因だと思われます。
https://github.com/VOICEVOX/voicevox_engine/issues/278

実はspeakersには現れませんが、音声合成話者としては実装されています。
speaker_idに、「ひまり」のspeaker_idより大きな値を指定してみてください。

Issueの原因が #278 と同じなので、一旦クローズします。

**Comment by takana-v** [comment]
最新版Dockerイメージはこちらが正しいです。
https://hub.docker.com/r/voicevox/voicevox_engine/tags

詳しくはリンク先のIssueを参照してください。
- https://github.com/VOICEVOX/voicevox_engine/issues/361

**Comment by LeeYunwhan** [comment]
**言われた通りにやって見ましたが、できませんでした。😢**

![soraDekinai](https://user-images.githubusercontent.com/82069313/159681334-deb7bc4e-665f-42df-b162-b1cc0c6aa4f1.png)

[resource](https://github.com/VOICEVOX/voicevox_resource)にある「九州そら」のuuidを参考してJsonデータが読み込められるのかも確認しましたが、できませんでした。

**Comment by takana-v** [comment]
現在masterブランチにバージョン0.11.4の変更が取り込まれていないため問題が発生しているようです。
修正するプルリクエストを作成しておきましたので、マージされれば改善すると思います。

- https://github.com/VOICEVOX/voicevox_engine/pull/381

**Comment by yunwhanlee** [comment]
ありがとうございます！

**Comment by LeeYunwhan** [comment]
ありがとうございます！
