### ISSUE TITLE
voicevox engineが異常終了する

### ISSUE THREAD

**Issue by anyworks** [VOICEVOX/voicevox_engine#384]
## 不具合の内容

voicevox engineが異常終了する

### 現象・ログ

voicevox_engine_1  | WARNING: JPCommonLabel_insert_word() in jpcommon_label.c: First mora should not be short pause.
voicevox_engine_1  | *** stack smashing detected ***: terminated
docker_voicevox_engine_1 exited with code 139

### 再現手順

voicevox-engineのaudio_queryAPIのパラメータ"text"に値として、JSON文字列を与える
例）```/audio_query?speaker=1&text=${JSON_STRING}```

audio_queryが出力したJSONを誤って指定したら発生しました。(2回中２回再現）

### 期待動作

変換処理のエラー判別がなんらかの方法で可能

## VOICEVOXのバージョン

0.11.4

## OSの種類/ディストリ/バージョン

- [x] Windows
- [ ] macOS
- [ ] Linux

Windows 10 Pro 64bit (19044.1586)

## その他

楽しく使わせてもらってます。ありがとうございます。
環境としては、Windows10 上でのdocker環境起動です。
#377の方が言っている、std::bad_allocエラーにも出くわしましたが、今回のエラーはその原因とは関係無いようです。参考まで。

**Comment by takana-v** [comment]
長すぎる文字列が渡されたせいでクラッシュしたと思われます。
原因はここら辺だと思います。

https://github.com/VOICEVOX/pyopenjtalk/blob/a85521a0a0f298f08d9e9b24987b3c77eb4aaff5/pyopenjtalk/openjtalk.pyx#L167

この2つの関数の引数である`text`の長さが一定以上だった場合、エラーを返すようにすると改善すると思います。
https://github.com/VOICEVOX/pyopenjtalk/blob/a85521a0a0f298f08d9e9b24987b3c77eb4aaff5/pyopenjtalk/__init__.py#L85
https://github.com/VOICEVOX/pyopenjtalk/blob/a85521a0a0f298f08d9e9b24987b3c77eb4aaff5/pyopenjtalk/__init__.py#L160
```python
# 値は適当です
if len(text) > 200:
    raise ValueError("入力の文字列が長すぎます。")
```
こうすることで`audio_query`APIのパラメータ`text`に値として、JSON文字列（長い文字列）を与えた場合には500エラー(Internal Server Error)が返ってくるようになります。
できればエディタによるエンジン再起動を防ぐため400番台のエラーを返すようにしたいですが、現在のエディタでは長い文字列を入力した場合に警告が出るようになっているので、とりあえず500エラーでもいいかと思います。

Cython周りはちょっと自信が無いため、他の方にも意見を伺いたいです。

**Comment by Hiroshiba** [comment]
同じく、文章が長すぎることが原因なエラーかなと思いました。
もしそうであれば、メモリ使用量がぐんぐん上がっているはずです。
実行中のメモリ使用量を見てみていただいてもよろしいでしょうか･･･？👀 @anyworks

**Comment by anyworks** [comment]
JSON自体は問題とされていないようなので、全角ひらがな３０００文字のテキストを用いてテストした結果
興味深い挙動に遭遇しました。

1回目リクエスト結果ログ
```
voicevox_engine_1  | WARNING:  Invalid HTTP request received.
voicevox_engine_1  | Traceback (most recent call last):
voicevox_engine_1  |   File "/home/user/.local/lib/python3.8/site-packages/uvicorn/protocols/http/h11_impl.py", line 136, in handle_events
voicevox_engine_1  |     event = self.conn.next_event()
voicevox_engine_1  |   File "/home/user/.local/lib/python3.8/site-packages/h11/_connection.py", line 432, in next_event
voicevox_engine_1  |     raise RemoteProtocolError(
voicevox_engine_1  | h11._util.RemoteProtocolError: Receive buffer too long
```

実行後サーバ状態 => 稼動

２回目リクエスト結果ログ（同じテキスト）
```
voicevox_engine_1  | *** stack smashing detected ***: terminated
```

実行後サーバ状態 => 異常終了

ちなみに、メモリ使用量はこの時点では微々たるものでした。

ただ、このテスト中docker落ちる→docker再起動を繰り返しているうちに、voicevox-engineがメモリだけを永遠に食いつぶして起動しないという事象にも遭遇しました。(Vmmem.exeが延々とメモリ消費している状態になる）
結果、物理メモリが足りなくなり、プロセスは起動する事なく以下コードで終了しました。。（物理メモリは３２GB)

```
voicevox_engine_1  | + exec gosu user /opt/python/bin/python3 ./run.py --use_gpu --voicelib_dir /opt/voicevox_core/ --runtime_dir /opt/onnxruntime/lib --host 0.0.0.0
voicevox_engine_1  | Warning: cpu_num_threads is set to 0. ( The library leaves the decision to the synthesis runtime )
docker_voicevox_engine_1 exited with code 137
```

**Comment by Hiroshiba** [comment]
なるほどです！！

文字数が多くてメモリを食いつぶしてしまう感じなんですね！
なぜか１回目は異常終了しないとの調査もありがとうございます。

@takana-v さんの仰るように、メモリオーバーで異常終了しないように、文字数が多かったらエラーを返すというのはどうでしょう。

思いつく最長の日本語はじゅげむなのですが、どうやら140文字程度らしいです。
https://detail.chiebukuro.yahoo.co.jp/qa/question_detail/q1313105563
それが３回くらい入る、500文字を超えたときにエラーを返す、とか。

@anyworks さん、プルリクエスト作成に挑戦してみませんか･･･？👀

**Comment by Hiroshiba** [comment]
おー！調査ありがとうございます！！
プルリクエスト、ぜひ…！！

**Comment by anyworks** [comment]
なるほどです。文字コードの問題でしたか。ありがとうございます＆お騒がせしました。
疑問も解消したのでちょっとトライしてみようと思います。
