### ISSUE TITLE
辞書の登録・更新において優先度はpriority単位であるのに、user_dictで取得できる一覧はcost単位である

### ISSUE THREAD

**Issue by y-chan** [VOICEVOX/voicevox_engine#390]
## 不具合の内容

題の通り
これによりエディタ側で、登録した単語が現在どの優先度なのかがわからない状態になっている

### 期待動作

user_dict APIにおいてもpriority単位での優先度が取得できるようになる

## その他

CSVファイルの形式等を変えることも検討しましたが、既存のユーザー辞書に対して影響が及んでしまい、互換性を消し飛ばすことになりかねないため、エンジン内部に`cost2priority`機構を用意し、APIだけに破壊的変更を加えるのがきれいに収まりそうだと思いました(現状ユーザー辞書機能を外部から触っていてかつcostの数値を参照していることはまあないと思うので、影響範囲の少ないところをいじるといった形になります)
その方向で修正を進めます。

**Comment by Hiroshiba** [comment]
提案頂いた方法で良いのかなと思いました･･･！

将来priorityとcostの対応関係は代わり得るので、ユーザーが設定したpriorityが勝手に変わっているように感じるかもしれません。なのでpriroityに保存すべきとも思います。
が、仰る通り今のユーザーが作った辞書が読めなくなってしまう問題があります。
変換器を作るのが一番良さそうな気もしますが、まあpriorityの変更（openjtalkの辞書の破壊的な更新）の頻度は高くなさそうだなぁという判断です！
