### ISSUE TITLE
CORSの範囲を制限し、無関係なリクエストを弾く

### ISSUE THREAD

**Issue by ts-klassen** [VOICEVOX/voicevox_engine#392]
## 内容
``` Access-Control-Allow-Origin: * ``` は変えたほうが良いかもしれない（要議論）
ヒホさんとTwitterのDMで話した内容を詳しく書きます。

### 現状
VOICEVOXエンジンとエディタのオリジンが違うため、JavaScriptでのリクエストはCORS上の問題が発生する。現在、エンジン側のヘッダで ``` Access-Control-Allow-Origin: * ``` と返すことで異なるオリジンからのリクエストを許可している。

### 変更すべき点
現状ではapp以外からのJavaScriptリクエストも許可してしまうため、``` Access-Control-Allow-Origin: app://. ``` に書き換えるべきである。（要検証）

### app以外からも許可している現状の問題点
VOICEVOXを起動した状態で悪意のあるサイトを開くと、知らぬ間にVOICEVOXエンジンへリクエストが飛ぶ可能性がある。

#### 再現方法
VOICEVOX0.11.4をLinuxで起動した。（ ``` $ /path/to/VOICEVOX0.11.4/run ``` ）
google chromeで https://voicevox.su-shiki.com/su-shikiapis/localtests/ にアクセスし、InspectのNetworkを開きリロードした。
送信ボタンを押した。
送信に成功し、 ``` /path/to/VOICEVOX0.11.4/run ``` の標準出力に ``` 127.0.0.1:37768 - "POST /synthesis?speaker=1&enable_interrogative_upspeak=true HTTP/1.1" 200 OK ``` と出力された。

### 原理
そもそもCORSはブラウザの自主規制である。chromium系であれば起動時のオプションに ``` --disable-web-security ``` とつければ無効化できる他、JavaScriptを介さないリクエストや、ブラウザを使わないリクエスト（curlなど）に対し何ら効果を発揮しない。しかし、Electronがchromiumをベースにしているため、web-securityを無効化しない限り別オリジンへJavaScriptリクエストを出せないのである。
#### 実演
すべてのオリジンを許可するv1apiと、同一オリジンのみ許可するv2apiを用意した。
v1api; https://api.su-shiki.com/v1/localtests/
v2api; https://api.su-shiki.com/v2/localtests/
無論、ブラウザやcurlで直接アクセスすることを妨げるものではない。しかし、別オリジン（ホストが違うなど。スキームやポート番号が違っても別オリジンである。）のJavaScriptでリクエストを飛ばすとブラウザが止めてくれるはずである。
v1api; https://voicevox.su-shiki.com/su-shikiapis/localtests/v1api.html
v2api; https://voicevox.su-shiki.com/su-shikiapis/localtests/v2api.html

### VOICEVOXエンジンとエディタは別オリジンである
エンジンが ``` http://127.0.0.1:50021 ``` であるのに対し、エディタは ``` app://. ``` であるため、レスポンスヘッダで ``` Access-Control-Allow-Origin ``` を正しく返さなければならない。

### Access-Control-Allow-Originを変える
``` Access-Control-Allow-Origin: app://. ``` を返すと良いだろう。（要検証。本当に弊害がないか。）

### app以外からの利用
例えばブラウザの拡張機能としてVOICEVOXを利用するなど、JavaScriptでリクエストする場合、 ``` Access-Control-Allow-Origin: * ``` とせざるを得ないこともある。

### Pros 良くなる点
利用者の意図しない形で、第三者にVOICEVOXエンジンへリクエストや任意の文字列を送信される可能性を減らせる。

### Cons 悪くなる点
ユーザーの利用目的や連携先（外部ホスト）に応じて、セキュリティー設定を利用者自身が変更する必要がある。

## 検証時のVOICEVOXバージョン

0.11.4

## 検証時のOSの種類/ディストリ/バージョン

- [ ] Windows
- [ ] macOS
- [x] Linux

``` Linux inty 5.15.0-27-generic #28-Ubuntu SMP Thu Apr 14 04:55:28 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux ```

``` Linux kali 5.15.0-kali3-amd64 #1 SMP Debian 5.15.15-2kali1 (2022-01-31) x86_64 GNU/Linux ```

**Comment by Hiroshiba** [comment]
ありがとうございます！！

VOICEVOXを起動している場合、ブラウザからリクエストを飛ばしたり情報を取得できたりするのはセキュリティ的に良くないとずっと思っており、これを防ぐ方法を探りたいなと考えています。

そもそもちゃんと知らないのですが、`Access-Control-Allow-Origin`を設定すると、悪意のあるwebサイトからlocalhostに対してアクセスしても情報が取得ができなくなる感じでしょうか。それともリクエストを飛ばすこともできなくなる感じでしょうか。

あとVOICEVOXエディタからのリクエストはちゃんと受け付けられるようにする方法があればぜひ知りたいです。。

ご存じの方がいらっしゃったらぜひコメントいただけると嬉しいです。

**Comment by ts-klassen** [comment]
誤解がありました。VOICEVOXエディタもブラウザ同様```Origin:```は```http;//127.0.0.1```ではじまると思っていましたが、ネットワークを監視した結果、```Origin: app://.```と返していることがわかりました。

未検証ですが、```Access-Control-Allow-Origin: *```を```Access-Control-Allow-Origin: app://.```にしても引き続きエディタからアクセスできると思います。

ユーザーが必要に応じて```Access-Control-Allow-Origin: *```と```Access-Control-Allow-Origin: app://.```を切り替えられるようにするのが良いかもしれません。（セキュリティー設定の一種として）

**Comment by ts-klassen** [comment]
質問に答えていませんでした。

ブラウザは、本命のリクエスト（POSTメソッドなど）の前にVOICEVOXエンジンにプリフライトリクエスト（OPTIONSメソッド）を送ります。そのレスポンスの```Access-Control-Allow-Origin```を見て本命のリクエストを送ったり自粛したりします。
これは、VOICEVOXエンジンが飛んできたリクエストを拒否しているわけでありません。ブラウザ側の自粛なので、ブラウザのセキュリティー設定で無効化することもできます。

「リクエストを飛ばすこともできなくなる」というより、「リクエストを自粛するようになる」という認識で良いと思います。

**Comment by Hiroshiba** [comment]
まとめとご教示ありがとうございます！！

CORSの仕組みを使えば、`Access-Control-Allow-Origin: app://.`を設定することでブラウザにレスポンスを返さないようにできる一方、リクエストを受け付けないようにするのは難しいのかなと感じました。
また、サードパーティアプリが利用するHTTPリクエストライブラリから手軽に通信できなくなりそうな気もしました。

POSTリクエストを受け付けないようにする場合は、プリフライトリクエストの仕組みを使うことで防止もできそうだということも理解できました！
ただ、synthesisみたいに全てJSONリクエストにする必要があったり、主要なブラウザの仕様をちゃんと把握したりする必要がありそうで、少し手間かもと感じました。

---

問題を整理すると、３点考えることがありそうです。

1. 悪意のあるサイトにレスポンスを返さないようにできるか
2. 悪意のあるサイトからリクエストを無視できるか
3. サードパーティーアプリから簡単に利用できるか

いろいろ考えたのですが、「Originがhttp/httpsなら無視する処理をサーバー側に持たせる」のが良いのかもと思いました。
ブラウザ経由（http/httpsプロトコル）なら弾くというブラックリスト方式を取る感じです。
まだ試していませんが、おそらくFastAPI内でリクエストを送ってきたOriginを知る方法はある･･･はず。

サードパーティーが利用するHTTPリクエストライブラリが、Originをhttpとして送信している可能性もあるかもしれません。
Originがhttp://localhostやhttp://127.0.0.1、もしくはサーバー側のと同じになっているものは通してもいいかも？

あと、http/https以外に、悪意のあるサイトからlocalhostに対してリクエストを飛ばせる仕組みがあるかもと懸念しています。例えば`git://`とか･･･（適当なたとえです）。
そういうのがあった場合はこのブラックリスト方式は無力そうです。

**Comment by ts-klassen** [comment]
> あと、http/https以外に、悪意のあるサイトからlocalhostに対してリクエストを飛ばせる仕組みがあるかもと懸念しています。例えばgit://とか･･･（適当なたとえです）。
そういうのがあった場合はこのブラックリスト方式は無力そうです。

これはイタチごっこの予感がしますね！！

一つ突破する方法を思いつきました。FireFoxでは対策済みでしたが、Google ChromeではOriginを偽装できるかもしれません。

これはGoogle Chromeの脆弱性かもしれないので、この場で手法を公開することは差し控えさせていただきます。（TwitterのDMで送ります。）

この場合、Originはnullを返します。

http, httpsに加え、nullもブラックリストに入れると対策できます。弊害として、ブラウザで開いたローカルのHTMLファイルもエンジンにリクエストを出せなくなります。（fileメソッドのOriginはnullを返します。）

**Comment by ts-klassen** [comment]
> Originが http://localhost/ や http://127.0.0.1/ 、もしくはサーバー側のと同じになっているものは通してもいいかも？

Originが http://localhost や http://127.0.0.1 とそのポート番号違い（http://127.0.0.1:50021 など）の場合は許可して問題ないと思います。（サーバーと同じOriginとはhttp://127.0.0.1:50021 のことです。許可しないとhttp://127.0.0.1:50021/docs  のJavaScriptが機能しなくなります。）
加えて、http://127.0.0.1 からhttp://127.255.255.254 も許可して問題ないと思います。（これらはすべてループバックアドレスです。許可する必要があるかは分かりませんが。）

トリッキーなケースとして、自身のローカルIP（例えば http://192.168.10.102 ）も許可して問題ないでしょう。（同様に、許可する必要があるかは分かりませんが。）ただし、その他のローカルIPは許可すべきではありません。（正直、全部不許可でいいと思います。）

また、Originを渡さないリクエストも許可して良いと思います。（Originを渡さないのと```Origin: null```は別物です。後者はnullというOriginを渡しています。そうです。nullは立派なOriginなのです。なんと```Access-Control-Allow-Origin: null```でnullだけ許可できほどに。さて、Originを渡さないリクエストに話を戻しますが、）例えば、Google Chromeでhttp://127.0.0.1:50021/docs にアクセスしたとき、ブラウザはOriginを渡しません。（JavaScriptのリクエストではないので当然です。）一見危険に見えるかもしれませんが、（バックドアが仕掛けられていたり、ポートフォワーディングでもしていない限り）http://127.0.0.1:50021 にOriginを渡さずリクエストを飛ばせるのはユーザー（人間とは限らない）が実行したプログラムだけです。

#### 敗者復活戦
ブラウザの拡張機能としてWEBページの読み上げをする場合、どのようなOriginを渡すか分かりません。（未定義という意味ではなく、私が知らないということです。）なんとなくhttps:// かchrome-extension:// など独自のメソッドを返す気がします。無論、そんなメソッドは発見次第即ブラックリスト行きです。しかし、利用者の明示的な許可があれば通しても良いでしょう。例えばVOICEVOXエンジンで固有の（予測困難な）トークンを発行し、そのトークンを利用者がコピペできるようにします。そして、ブラックリスト入りしたOriginたちはトークンを渡さないとリクエストを拒否されます。（あるいは無視されます。）したがって、ブラックリスト入りしたOriginを渡すアプリは利用者にVOICEVOXトークンを求める必要があり、利用者はトークンをコピペするかどうかで明示的な許可を与えることができます。

**Comment by Hiroshiba** [comment]
詳細にありがとうございます！
`Origin: null`など、全く知らない概念があって目からウロコでした。

方針としては、まずレスポンスを返さないようにするのを優先的に直すことを考えると良いのかなと思いました。（辞書などに含まれるかもしれない個人情報を守るのが一番大事だと考えています。）
こちらは、VOICEVOXエディタのみを通す`Access-Control-Allow-Origin`を用意して解決する方法で進められればと思います。

VOICEVOXエディタがappプロトコルなのは[ここのコード](https://github.com/VOICEVOX/voicevox/blob/9f8cf045732e3e9db19cd09642414c0e2236f438/src/background.ts#L781-L782)によるものな気がします。
voiecvoxプロトコルなどに変えられるとおしゃれかもです。よくわかってませんが、こっちも変えないといけないかも･･･？
https://nklayman.github.io/vue-cli-plugin-electron-builder/guide/configuration.html#changing-the-file-loading-protocol

この影響は @ts-klassen さんの仰る通り、ブラウザを介するサードパーティーアプリが動かなくなるかもしれません。
たしかゆかりねっとはブラウザを介する仕組みで、かつユーザーも多いので一番影響があるかもしれません。
とりあえず簡単に迂回できるよう、エンジン側にCORSを無効にするオプションを用意しつつ、しっかりアナウンスしようと思います。

CORSを設定できたら、リクエストを弾く（処理をキャンセルする）のを進めるのが良いのかなと思いました。
こちらは、VOICEVOXエディタからのリクエスト・`http[s]://localhost:*`・`http[s]://127.0.0.1:*`・Origin無しだけを通すホワイトリスト形式を考えています。

予測できる影響は、先ほど同様ブラウザを介するサードパーティーアプリだけですが、予想外の影響があるかもしれないので、こちらの方法はCORS設定ができたあと慎重に行いたいです。

**Comment by Hiroshiba** [comment]
@ts-klassen さん、もしよかったらCORS設定を導入するプルリクエスト作成に挑戦してみませんか･･･？👀
このあたり知識がないと難しいのと、エンジン周りのことが詳しい方におまかせできると心強く、お伺いしてみた次第です。

もしわからないこと等がありましたらなんでも聞いて頂けますと幸いです！
どうでしょう･･･？

**Comment by ts-klassen** [comment]
挑戦してみます。

**Comment by Hiroshiba** [comment]
おー！！ぜひ…！！
python等でわからない点などあればなんでも聞いていただければ！

**Comment by Hiroshiba** [comment]
いったんこちらのタスクをまとめてみます。

- [ ] `app://`以外のCORSを無効にする（`Access-Control-Allow-Origin: app://.`）
- [ ] `Access-Control-Allow-Origin`の値を変えられるオプションを用意する
- [ ] 無関係なリクエストを弾くor 実行をキャンセルする（VOICEVOXエディタからのリクエスト・http[s]://localhost:*・http[s]://127.0.0.1:*・Origin無しだけを通す）
- [ ] ユーザーに案内する

**Comment by ts-klassen** [comment]
すみません、放置してました。
取り掛かります。編集範囲はrun.pyだけだと思います。

**Comment by masinc** [comment]
@Hiroshiba さん
TwitterのDMにて、ご連絡させていただきました。

> 無関係なリクエストを弾くor 実行をキャンセルする（VOICEVOXエディタからのリクエスト・http[s]://localhost:・http[s]://127.0.0.1:・Origin無しだけを通す）

localhostや127.0.0.1ですが、もし本番用途で不要あれば、開発環境限定の環境変数などで許可対応するのがよいかと思いましたがいかがでしょうか。

PRの件ですが、エンジン側についてはともかくエディタ側(特にVue, CSS)の知見が少ないため、全ての対応は難しいと考えています。協力できる範囲であればご相談ください！

**Comment by Hiroshiba** [comment]
@ts-klassen さん
おお、ありがとうございます！！　不明な点あればなんでもお聞きください！！

**Comment by Hiroshiba** [comment]
@masinc さん
丁寧にDMで教えてくださってありがとうございました！

> localhostや127.0.0.1ですが、もし本番用途で不要あれば、開発環境限定の環境変数などで許可対応するのがよいかと思いましたがいかがでしょうか。

VOICEVOXエディタにとってはlocalhostなどは不要なのですが、エンジンだけ使いたいサードパーティアプリではそうでもないのかなーと思っています。
なので本番用途（ビルド済みエンジン）でも環境変数あるいは実行引数で指定して許可できると良いのかなと思っています。

なんとなくですが、指定なしだった場合は「VOICEVOXエディタからのリクエスト・`http[s]://localhost:*`・`http[s]://127.0.0.1:*`・Origin無し」を通し、指定した場合は指定したものだけ通す、とかが良いのかなぁと想像しています。

> PRの件ですが、エンジン側についてはともかくエディタ側(特にVue, CSS)の知見が少ないため、全ての対応は難しいと考えています。協力できる範囲であればご相談ください！

お言葉ありがたいです！
@ts-klassen さんからPR頂いたらレビューをお願いさせていただくかもしれません。その際はぜひ･･･！

**Comment by masinc** [comment]
@Hiroshiba さん

> なので本番用途（ビルド済みエンジン）でも環境変数あるいは実行引数で指定して許可できると良いのかなと思っています。

はい、私もほぼ同様の実装を想定していました。

> なんとなくですが、指定なしだった場合は「VOICEVOXエディタからのリクエスト・http[s]://localhost:*・http[s]://127.0.0.1:*・Origin無し」を通し、指定した場合は指定したものだけ通す、とかが良いのかなぁと想像しています。

なるほど。既存のサードパーティアプリがどのようなものが存在するのかわかっていないのですが、Webブラウザエンジン経由でHTTP通信するアプリ以外は基本的には問題無いと思われますので、オプションでの指定のみで十分対応できるのかと考えていました。
また、指定の有無に関わらず、VOICEVOXエディタとOrigin無しについては無条件許可で良いかと思っています。Webブラウザ上のアプリと違って、ローカルにて実行されているアプリなら任意のリクエストヘッダの設定ができますので。

**Comment by Hiroshiba** [comment]
@masinc さん
[CORS設定まわりのプルリクエスト](https://github.com/VOICEVOX/voicevox_engine/pull/494)についてレビュー頂けると心強いです･･･！

**Comment by Hiroshiba** [comment]
こちらのissueですが、`無関係なリクエストを弾くor 実行をキャンセルする`までの議論を分断したくないので、そこもissueに含む形にタイトルを修正させていただこうと思います 🙏

**Comment by Hiroshiba** [comment]
もしよければ `無関係なリクエストを弾くor 実行をキャンセルする`もPRお願いできると嬉しいです･･･！
（PR内容が被らないようにするために、このissueで宣言するか、空のDraft PRを作成していただければと！）

**Comment by ts-klassen** [comment]
作業に入る前に、現状のおさらいです。

CORSを設定した時点で、情報をJavaScriptに抜き取られないようにするという目標は達成しました。

Originでリクエストを弾く処理をつけようという方針になった理由に、プリフライトリクエストを飛ばさないタイプのリクエストが脅威たりうると考えたからです。

まず、Originでリクエストを弾く処理でGETリクエストは防げません。（今気づいた。どうしよう…）
例）↓ここをクリック
http://localhost:50021/is_initialized_speaker?speaker=0&core_version=0.13.2

一方、POSTなどは対策できそうです。
現状、ブラウザがプリフライトリクエストを送らない限り、VOICEVOXを起動した状態で次のようなボタンを押すとCPUリソースが食われます。
https://voicevox.su-shiki.com/su-shikiapis/localtests/form_post.html

試しにVOICEVOXの代わりにnetcatを50021ポートで待機させると、
<details><summary>Bashコマンド「netcat -l 50021」の結果</summary>
```
netcat -l 50021
POST /initialize_speaker?speaker=0 HTTP/1.1
Host: localhost:50021
Connection: keep-alive
Content-Length: 0
Cache-Control: max-age=0
sec-ch-ua: "Google Chrome";v="105", "Not)A;Brand";v="8", "Chromium";v="105"
sec-ch-ua-mobile: ?0
sec-ch-ua-platform: "Linux"
Upgrade-Insecure-Requests: 1
Origin: null
Content-Type: application/x-www-form-urlencoded
User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/105.0.0.0 Safari/537.36
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9
Sec-Fetch-Site: cross-site
Sec-Fetch-Mode: navigate
Sec-Fetch-User: ?1
Sec-Fetch-Dest: document
Accept-Encoding: gzip, deflate, br
Accept-Language: en-US,en;q=0.9
```
</details>

のように```Origin: null```を返しながらも有効なPOSTリクエストを出していることがわかります。
（面白いことに、```https://voicevox.su-shiki.com```に設置したトラップなのにOriginはnullです。）

本質的にはクロスサイトリクエストフォージェリ（CSRF）対策みたいなものだと思いますが、トークンを発行するような破壊的変更は避けたいです。
そこで、許可されていないOriginを渡すリクエストは弾くという方針を考えています。

もっと良い方法があれば是非！

**Comment by Hiroshiba** [comment]
まとめありがとうございます！
仰る通り、`許可されていないOriginを渡すリクエストは弾く`というのが筋が良いのかなと感じました！

ちょっと認識が食い違っているのかもなのですが、この場合でもGETリクエストは防げない（弾けない）感じでしょうか 👀

**Comment by masinc** [comment]
> まず、Originでリクエストを弾く処理でGETリクエストは防げません。（今気づいた。どうしよう…）

API実装気を付けないとDoSできちゃいますね。。

> 本質的にはクロスサイトリクエストフォージェリ（CSRF）対策みたいなものだと思いますが、トークンを発行するような破壊的変更は避けたいです。
> そこで、許可されていないOriginを渡すリクエストは弾くという方針を考えています。

私もこの方針には同意見ですが、トークンを利用しないとミドルウェアなどでの一元的なCSRF対策は厳しそうと思いました。
あまり自信ないですが、GETメソッドのCSRF緩和策を取るとしたらこんな感じでしょうか。

* 初回を除きレスポンスをキャッシュした結果を返す。(リクエスト毎にCPU/メモリ/IO等のリソースをほぼ利用しない)
* ↑が難しい場合、連続リクエストに対しての何かしらの対策をする。両方できるとより良い。


>ちょっと認識が食い違っているのかもなのですが、この場合でもGETリクエストは防げない（弾けない）感じでしょうか 👀

ブラウザの GET リクエストは Originヘッダを送ってこない様々なパターンがあり、それを正確に対応するのは厳しそうです。この記事がわかりやすいかもです。
[CORSの仕様はなぜ複雑なのか - CORSが使われないとき](https://zenn.dev/qnighy/articles/6ff23c47018380#cors%E3%81%8C%E4%BD%BF%E3%82%8F%E3%82%8C%E3%81%AA%E3%81%84%E3%81%A8%E3%81%8D)

**Comment by Hiroshiba** [comment]
@masinc さんありがとうございます！！
なるほど、ブラウザがGETリクエストはいろんなのがあるんですね･････。存じませんでした。

キャッシュと連続リクエスト対策、ありだと感じました。
実装コストもあると思うので必須ではなく、とりあえずOrigin制限しつつ、余力があるなら別のPRで対応とかもありなのかなと思いました！

**Comment by Hiroshiba** [comment]
CORS設定を取り込んだリリースを作ってみました。7zを展開したらexeが出てきます。ちゃんと弾かれるはず･･･？
https://github.com/VOICEVOX/voicevox_engine/releases/tag/0.14.0-preview.1

**Comment by ts-klassen** [comment]
取り掛かります。

**Comment by Hiroshiba** [comment]
おお！！よろしくお願いします･･･！

**Comment by Hiroshiba** [comment]
今回の仕様変更の影響をユーザーの方に案内をしたいのですが、ちょっと複雑な段取りを取ろうと思います。

```
先に自分 @hiho_karuta のツイッターで該当ツールが無いか聞く
↓
該当ツール開発者の方に事前に連絡する
（chrome拡張が２つ見つかったのでその方には連絡したい）
（あとゆかりねっと）
↓
「セキュリティアプデしたためサードパーティツールに影響があります。開発者の方はこちらをご確認ください。」
＆影響があるサードパーティツールなど一覧の画像添付
で公式ツイート
```

というのも、これらの要件を満たしたいためです。

・愉快犯を防ぎたい（ので詳細を伏せる）
・ブラウザを介するサードパーティツールに影響があると気づける
・大多数のユーザーには影響がない
・WEB版VOICEVOXは影響ないことがわかる（ユーザー数が多く不安になる方がいらっしゃりそう）

また、普段機能追加PRをマージしたときはツイッターでPRリンク付きツイートをさせていただいている（[例](https://mobile.twitter.com/voicevox_pj/status/1582044314750050304)）のですが、もしツイートすると愉快犯が現れてしまうかもと考えています。
そのため、PRを出していただいた @ts-klassen さんには申し訳ないのですが、今回はPRリンク付きツイートをしない方針を取らせていただきたいと考えています。
申し訳ないですが、ご理解いただけますと幸いです 🙇🙇

**Comment by Hiroshiba** [comment]
サードパーティアプリ開発者の方向けに案内する予定のissueを作成しました。もし語弊などあればご指摘頂けると嬉しいです･･･！

- https://github.com/VOICEVOX/voicevox_engine/issues/509

**Comment by Hiroshiba** [comment]
情報ありがとうございます！！
迂回策はいくつか思いつくので案内issue側に列挙してみたいと思います。
その辺りどうしていくのが良いか含めて開発者の方に聞いてみたいと思います。

**Comment by aoirint** [comment]
https://github.com/VOICEVOX/voicevox_engine/issues/392#issuecomment-1308005214

ブラウザ拡張についてですが、Google Chrome 101+（>=の意。[Chrome 101は2022-04リリース](https://chromereleases.googleblog.com/2022/04/stable-channel-update-for-desktop_26.html)。2022-12-04時点の最新の安定版はChrome 108）およびManifest V3で、`declarativeNetRequest`という機能によって、Originヘッダを削除する形で対応できるかもしれません。

`declarativeNetRequest`を使用するには、`manifest.json`の`permissions`に`declarativeNetRequestWithHostAccess`という項目（Chrome 96+）を追加する必要があります。ちなみにFirefoxで現行のManifest V2では、`webRequest.onBeforeSendHeaders`という機能で同じことができると思います（ただしChromeは、2022年1月からManifest V2の非推奨化プロセスに入っており、2024年1月に廃止する予定です）。

- chrome.declarativeNetRequestのドキュメント: <https://developer.chrome.com/docs/extensions/reference/declarativeNetRequest/>
- Google ChromeのManifest V2 廃止スケジュール: <https://developer.chrome.com/docs/extensions/mv3/mv2-sunset/>

またCORSについては、`manifest.json`の`host_permissions`に`http://127.0.0.1:50021/*`を含めることで、ブラウザ拡張機能の特権としてCORSを回避できます。CORSを無視するため、VOICEVOX ENGINEの起動引数`--cors_policy_mode`は影響しません。

- <https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json/host_permissions>

> [XMLHttpRequest](https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest) and [fetch](https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API) access to those origins without cross-origin restrictions (though not for requests from content scripts, as was the case in Manifest V2).

具体的な実装例を置いておきます。

`manifest.json`の`service_worker`に指定したJavaScriptファイルで、以下の処理を実行すると、実行した拡張機能によるVOICEVOX ENGINE `http://127.0.0.1:50021`宛のHTTPリクエストから、Originヘッダを削除できます。`initiatorDomains`（Chrome 101+）は、書き換えるHTTPリクエストの送信元を拡張機能自身のみに絞ることを意図しています（拡張機能自身以外が送信したHTTPリクエストのOriginを削除しないようにするため）。

```js
// license: CC0
chrome.declarativeNetRequest.updateDynamicRules({
  removeRuleIds: [1],
  addRules: [
    {
      id: 1,
      priority: 1,
      action: {
        type: 'modifyHeaders',
        requestHeaders: [
          { 'header': 'Origin', 'operation': 'remove' },
        ],
      },
      condition: {
        urlFilter: '127.0.0.1:50021/*',
        initiatorDomains: [chrome.runtime.id], // chrome-extension://{extension_id}
      },
    },
  ],
})
```

**Comment by Hiroshiba** [comment]
なるほど！！chrome拡張側のコード変更でCORS回避できるんですね！！盲点でした。

拡張機能開発者の目線だと、ユーザーにCORSの設定をしてもらわなくて済むのでこちらの方が好まれそうですね。
「CORSの設定方法」みたいなドキュメントを用意して、そこで↑のコメントをちょっと言及してあげると良いかもですね。

いろんな需要があると思う（普通にwebページからリクエスト飛ばしたいとか）ので、CORSを設定する方法も提供できると嬉しいのかなと思いました！

**Comment by Hiroshiba** [comment]
- https://github.com/VOICEVOX/voicevox_engine/issues/522

が解決されたので案内を進めていきたいと思います！

discordで聞いた感じだと、chrome系アプリの他には影響ない感じでした。
たぶんゆかりねっと周りも大丈夫です。

他に影響ありそうなシステムがないかを僕の個人アカウントからツイートして公募中です。
https://twitter.com/hiho_karuta/status/1610074942703558656

ちょっと時間たってからVOICEVOX公式から案内したいと思います！

**Comment by Hiroshiba** [comment]
こちら確か案内も済ませて、特に問題なく完了した記憶があります。
のでクローズします。実装やディスカッションとても心強かったです、ありがとうございます！！
