### ISSUE TITLE
Nuitkaのバージョンを上げる

### ISSUE THREAD

**Issue by takana-v** [VOICEVOX/voicevox_engine#393]
## 内容

題の通り
`0.6.17.4`から`0.7.7`辺りのバージョンまで上げたいと考えています。

#### APIと内部処理用のmodelの分離

- #256

上のPRで実装されましたが、不具合が原因でリバートすることになりました。
-  https://github.com/VOICEVOX/voicevox_engine/pull/266

最近のnuitkaのリリースノートを見ると、以下のような文がありました。
https://nuitka.net/doc/Changelog.html#nuitka-release-0-7
```
Compiled types of Nuitka now inherit from uncompiled types.
This should allow easier and more complete compatibility, making even code in extension modules that uses PyObject_IsInstance work, e.g. pydanctic.
```
nuitkaをアップデートすることで #256 を再度適用することができるようになるかもしれません。

#### M1対応への準備

恐らくバージョン0.8台でuniversalビルドに対応すると思われます。
バージョンが4つも飛ぶと、かなり大きな修正が必要そうなので0.7台に上げておきたいです。

#### ビルド時の処理の簡潔化

様々な不具合の修正が入っており、独自に行っている処理が不要になる可能性があります。

#### 軽量化・高速化

アップデートで様々な最適化が行われているため、軽量化、高速化するかもしれません。

### Cons 悪くなる点

ビルド環境が大きく変わることになるので、不具合が発生する可能性があります。
（特にmacOS環境）

### 実現方法

build.yml、Dockerfileなどの修正

## OSの種類/ディストリ/バージョン

- [x] Windows
- [x] macOS
- [x] Linux

## その他

- 0.6.18.x
- 0.6.19.x
- 0.7.x

の3つの大きなアップデートを乗り越える必要があるので、結構大変かもしれません。
（0.7からNuitkaのバージョン命名規則が変わり、4桁から3桁になっています。）

**Comment by Hiroshiba** [comment]
issue作成ありがとうございます！！
ぜひお願いします･･･！

（これはただのアイデアですが、nuitka以外のライブラリのバージョンはできるだけ変えないほうがデバッグしやすいかもと思いました。
少し手間そうですが、`requirements.in`にかかれているnuitka以外のライブラリは、今使っているもので固定しておくといろいろ簡単かもと感じました。）

**Comment by Hiroshiba** [comment]
なんとなく確認したのですが、今もう0.9まで進んでるんですね･･･。

**Comment by takana-v** [comment]
0.9.2で試したのですが、MacOSでScipyのビルドが通らないので断念しています。
ちなみにuniversalビルドは対応してないみたいです。

**Comment by Hiroshiba** [comment]
なるほどです！！お試し情報とても助かります！！
scipyのバージョン上げたり、macでrequirements.txt作ったりしないといけないのかなぁ･･･そんな簡単じゃない気もするなぁ･･･。

**Comment by Hiroshiba** [comment]
こちらですが、pyinstallerへの移行を行ったので問題が迂回されました。
@takana-v さん、ありがとうございました！！
