### ISSUE TITLE
ビルド周りをコア 0.12.0-preview.3に対応する

### ISSUE THREAD

**Issue by Hiroshiba** [VOICEVOX/voicevox_engine#396]
## 内容

コアが0.12.0-preview.2に上がったタイミングで、アーキテクチャごとにzipファイルが分かれるようになりました。

- https://github.com/VOICEVOX/voicevox_core/releases/tag/0.12.0-preview.2

この分かれたzipにエンジンのビルドを追いつかせるのがこのissueの目的です。

### Pros 良くなる点

アプデ出来るようになる

### 実現方法

大きな差分は以下の３つになりそうです

* ライブラリにバイナリが同梱されている
* zipファイルが分かれている
* ライブラリにアーキテクチャ名が含まれていない

build.ymlやbuild-docker.ymlの変更が必要だと思われます。

## VOICEVOXのバージョン

0.?.0

**Comment by Hiroshiba** [comment]
@PickledChair さんにお願いさせていただきました！！よろしくお願いします･･･！

**Comment by PickledChair** [comment]
今気づいたのですが、[0.12.0-preview.2](https://github.com/VOICEVOX/voicevox_core/releases/tag/0.12.0-preview.2) と [0.12.0-preview.3](https://github.com/VOICEVOX/voicevox_core/releases/tag/0.12.0-preview.3) で zip ファイルの構造が変わっている (https://github.com/VOICEVOX/voicevox_core/pull/117) ので、0.12.0-preview.2 に対応させたあと、0.12.0-preview.3 以降に対応させるために再びビルド手順を微修正することになりそうです。

**Comment by Hiroshiba** [comment]
おっと、なるほどです！
issueタイトルは.2になっていますが、いきなり.3対応でも全く問題ないです…！

**Comment by PickledChair** [comment]
> いきなり.3対応でも全く問題ないです…！

わかりました！ ちなみに、0.12.0-preview.3 のコアを今のエンジンで読み込むと、遅延ロードの仕組みが加わった関係でモデルのロードがされず、音声の生成ができないことを確認しています。とりあえず `initialize` 関数の第３引数 `load_all_models` に `True` を渡すだけで解決するのですが、一応 PR を分けて、先にこの引数変更の対応をしてからビルドの方に取り組みたいと思います。

**Comment by Hiroshiba** [comment]
ありがとうございます！
coreに関しても助かります。
