### ISSUE TITLE
起動コマンドの引数の紹介をする

### ISSUE THREAD

**Issue by Hiroshiba** [VOICEVOX/voicevox_engine#411]
## 内容

起動コマンド引数を、READMEでもAPIドキュメントでも案内していないので、GPUを使う方法がわからないようになっています。
問い合わせ例 https://twitter.com/AUu6Jh4PMBWnRfb/status/1528979245166301184

READMEかAPIドキュメントで引数の案内ができると嬉しそうです。

### Pros 良くなる点

わかりやすい

### Cons 悪くなる点

メンテが少し大変

### 実現方法

READMEかAPIドキュメント、あるいは両方に書き足す

**Comment by HyodaKazuaki** [comment]
起動コマンドの引数というのは以下の部分でしょうか？
https://github.com/VOICEVOX/voicevox_engine/blob/master/run.py#L789-L805

ArgumentParserは`help`引数を付けてあげることで`help`コマンド用のメッセージを出せるので、これで対応するのはいかがでしょうか。
`help`引数のメリットは、基本的に`run.py`の実装がそのまま説明になるので実装とかけ離れづらいことが挙げられます。
`README.md`に「引数は`python run.py --help`で確認してください。」と一言添えるだけで良くなると思われます。

```python
import argparse

if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="プログラムの説明")
    parser.add_argument("--use_gpu", action="store_true", help="このコマンドの説明(この引数をつけるとGPUを有効化します etc.)")

    args = parser.parse_args()
    // 以降必要な処理
```

これを挿入すると、起動コマンドに`--help`引数をつけてもらえれば引数がわかるので便利になるかと思います。

```
$ python run.py --help
usage: run.py [-h] [--use_gpu]

プログラムの説明

optional arguments:
  -h, --help  show this help message and exit
  --use_gpu   このコマンドの説明(この引数をつけるとGPUを有効化します etc.)
```

**Comment by Hiroshiba** [comment]
良いですね！！READMEに反映するメンテナンスコストがかからないのが嬉しいです･･･！！

**Comment by HyodaKazuaki** [comment]
では提案した実装をPRしてみます

**Comment by Hiroshiba** [comment]
ありがとうございます！！
