### ISSUE TITLE
ファイルを上書きしてバージョンを更新すると、cpuモードで起動しなくなる

### ISSUE THREAD

**Issue by manju-summoner** [VOICEVOX/voicevox_engine#417]
## 不具合の内容
voicevox_engine 0.11.4(windows-cpu)を保存しているフォルダにvoicevox_engine 0.12.0(windows-cpu)を上書き保存すると、cpuモードで起動できなくなりました。

zip形式で配布されているVOICEVOX CPU版を、0.11.4から0.12.1へファイルを上書きして更新した場合にも同様の症状が発生します。
インストーラー版では0.11.4から0.12.1へ更新しても問題なく動作しました。

### 現象・ログ
```
D:\...\windows-cpu>run.exe
Warning: cpu_num_threads is set to 0. ( The library leaves the decision to the synthesis runtime )
Traceback (most recent call last):
  File "D:\...\windows-cpu\run.py", line 773, in <module>
  File "D:\...\windows-cpu\voicevox_engine\synthesis_engine\make_synthesis_engines.py", line 74, in make_synthesis_engines
  File "D:\...\windows-cpu\voicevox_engine\synthesis_engine\core_wrapper.py", line 420, in __init__
Exception: This library is CPU version. GPU is not supported.
```

### 再現手順
1. voicevox_engine 0.11.4(windows-cpu)をダウンロードし、展開する（以下フォルダA）
2. voicevox_engine 0.12.0(windows-cpu)をダウンロードし、展開する（以下フォルダB）
3. フォルダB内のファイルをフォルダAにコピーし、上書き保存する
4. フォルダA内のrun.exeを起動する
5. Exception: This library is CPU version. GPU is not supported.と表示され、CPUモードで起動しなくなる

### 期待動作
ファイルを上書きしてバージョンを更新した場合でもcpuモードで起動する

## VOICEVOXのバージョン
- voicevox_engine cpu版を、0.11.4から0.12.0へファイルを上書きしてバージョンを更新
- voicevox_engine cpu版を、0.10.4から0.12.0へファイルを上書きしてバージョンを更新
- zip形式で配布されているVOICEVOX cpu版を、0.11.4から0.12.1へ、ファイルを上書きしてバージョンを更新

## OSの種類/ディストリ/バージョン

- [x] Windows 11 Pro 22H2 22621.1
- [ ] macOS
- [ ] Linux

**Comment by takana-v** [comment]
現在、コアのバージョンをコアと同じディレクトリにあるファイルの存在有無で判別しています。
上書きした場合は最新バージョンで削除されたファイルが残存するため、古いバージョンのコアであると誤認してエラーが発生したと思われます。
- #385 

他の方法でバージョンを判別できれば改善できますが、ちょっと方法が思いつかないです...

**Comment by manju-summoner** [comment]
なるほど。
現状の判定処理的にも今後のサポートコスト的にも置き換えを前提とする方が良さそうですね。
READMEへの記載があれば問題ないと思います！
