### ISSUE TITLE
OSError: [WinError 1]　書き込み権限が無いときにresolveがエラーになる

### ISSUE THREAD

**Issue by arigayas** [VOICEVOX/voicevox_engine#419]
https://github.com/VOICEVOX/voicevox/issues/824 のコピーissueです。

## 不具合の内容

自分の環境で起動しないとツイートしました。
https://twitter.com/arigayas/status/1531456337825402880

zip版を展開してvoicevox.exe をダブルクリックで起動しても「音声合成エンジンエラー」というダイアログが表示された後は「データ準備中」のままになってしまい使用できません。
![image](https://user-images.githubusercontent.com/11251874/171084185-90df62fb-7547-4584-8252-6b5c5eeef954.png)
![image](https://user-images.githubusercontent.com/11251874/171084200-8987e3a8-55dd-42ba-a83f-4f51fa1e7f40.png)

### 現象・ログ
エラーログです。
[20220531_104942_error.log](https://github.com/VOICEVOX/voicevox/files/8801653/20220531_104942_error.log)

エラーログのエラーメッセージが文字化けしているとヒホ（ヒロシバ）さんにTwitterにて伝えたらリプライで コマンドプロンプトにてrun.exe を実行したスクリーンショットです。
OSError: [WinError 1] ファンクションが間違っています。: '.'　と表示されていました。
![image](https://user-images.githubusercontent.com/11251874/171084170-dfc1f5c2-2976-4d1a-8d52-809da9597cb4.png)

### 再現手順

1. RAMディスク作成ツールは ImDisk Virtual Disk Driver　を使用しました。
![image](https://user-images.githubusercontent.com/11251874/171088411-dfdae75c-d832-4e19-b441-7cd20bc687a4.png)

2. Rドライブ(RAMディスクで4GB確保している) にvoicevox-windows-cpu-0.12.0 をダウンロードします。
3. voicevox-windows-cpu-0.12.0 を展開します。
4. R:\voicevox-windows-cpu-0.12.0\VOICEVOX 内の voicevox.exe をダブルクリックで起動します。

### 期待動作

問題無く起動して初回起動時の画面（キャラクター選択画面）が表示される。

## VOICEVOXのバージョン

0.12.0 Pre-release

## OSの種類/使用ソフトなど
*   Windows 10 Pro 64bit 21H2 (10.0.10586)
*   Ryzen 5 3600 + Radeon RX 6600 + 64GB
*   7-zip 21.07(x64)
*   ImDisk Virtual Disk Driver　

## その他

RドライブにダウンロードしたzipをCドライブに展開したら問題無く起動しました。

Rドライブに展開したVOICEVOX 内のフォルダやファイルたちのプロパティのセキュリティタブのアクセス許可を見ると
「フルコントロール」、「変更」、「読み取りと実行」、「読み取り」、「書き込み」、「特殊なアクセス許可」と並んでいて
Usersには読み取りと実行、読み取りの2つだけにチェックマークが入っていました。
これが原因かと思いRドライブ自体に フルコントロールにチェックマークを入れる作業をして
そこにダウンロードしたzipを別フォルダ名で展開しVOICEVOX の起動を試みても起動しませんでした。

issueタイトルに行き着いたのは最後の部分のファイルのプロパティを見比べてアレ？と思ったからです。
それでもRドライブでの起動ができなかったのは腑に落ちないですが。

**Comment by Hiroshiba** [comment]
issue作成ありがとうございます！

ここでresolveするのができていないっぽく思います。
https://github.com/VOICEVOX/voicevox_engine/blob/02e0fe2fafc36f6e7d5567371f420f00e75dec26/voicevox_engine/utility/engine_root.py#L17

こちらのエラーに関して、twitterにてコメントを頂いていました。
https://twitter.com/sabonerune/status/1532196351546892291

たしかにpython側に何かしらのバグがあるのかもしれません。
https://github.com/python/cpython/issues/76023

となると、解決は結構難しいのと、ケースがかなりレアだと思われるので、「RAM上に展開するのを避けていただく」というのを迂回作として案内するのが良いのかなと感じました。
いかがでしょうか？👀

**Comment by takana-v** [comment]
（コメントするタイミングが被ってしまいました...）

ImDisk Virtual Disk Driverを使用していることが原因になっていると思われます。
`Path.resolve()`でOSErrorが発生していますが、この関数ではこのエラーは発生しないはずです。
（本来は`FileNotFoundError`もしくは`RuntimeError`のみが発生するはずです）
つまり、Pythonが想定していないエラーが発生したことになります。
ソースを見たところ、恐らくWin32APIのCreateFileW関数を叩いたときに意図しないエラーが発生したと思われます。
https://github.com/python/cpython/blob/3.11/Modules/posixmodule.c#L4342

VOICEVOX側でこの問題を解決することは難しいと思います。（Python3.11.0b3でも未修正です）
私も @Hiroshiba さんと同じく、「RAM上への展開を避ける」を迂回策として案内するのが良いかと思います。

**Comment by arigayas** [comment]
了解しました。
もし可能ならエラーメッセージが増えたら分かりやすくなってうれしいと思いましたが、
このレアケースに対応する為の開発コストを考えると天秤が釣り合わないですし、私が気をつければ良いだけなので、
以後ダウンロードしたファイルはHDDのドライブに展開するようにいたします。
お騒がせしました。

**Comment by Hiroshiba** [comment]
同じ問題が起こった人がここに辿り着けば自己解決できたり、twitterで見かけた場合も案内しやすくなったはずなので、今回の議論は十分な効果を発揮してくれると思います！
ありがとうございました！

**Comment by Hiroshiba** [comment]
こちら別の方も問題を報告されていました。
https://twitter.com/shinohito/status/1623887727484862465

discordにて簡単に直せる方法が見つかったので転記しておきます！ （thx @sabonerune @takana-v ！）

> %TEMP%ではなくエンジンの設定ディレクトリ内に一時ファイル用のディレクトリ作ってしまうとか?

> それもありかもですね
dirオプションで設定できそう
https://docs.python.org/ja/3/library/tempfile.html#tempfile.TemporaryFile

> hoge.dic.tmp みたいに、後ろに.tmpつけて同じディレクトリに保存するとかもあるなと思いました。

優先度的にはかなり低そうですが、結構簡単に解決できそうなのでopenにしたいと思います。

**Comment by sabonerune** [comment]
>%TEMP%ではなくエンジンの設定ディレクトリ内に一時ファイル用のディレクトリ作る

というアプローチは`engine_root`下のファイルパスを`resolve`しているためこのissueのVOICEVOXをRAMディスク上に配置したというケースには対応できませんね。

このアプローチで解消するのは%TEMP%をRAMディスクに変更した場合ですね。

**Comment by Hiroshiba** [comment]
なるほどです。ここのことですよね。
https://github.com/VOICEVOX/voicevox_engine/blob/65bc9f00fa22ba9053f2fa3fe5b8a57d61140292/voicevox_engine/utility/path_utility.py#L17

ここ、resolveがそもそも要らない気がちょっとしました。もともと絶対パスが返ってそう･･･？

**Comment by Hiroshiba** [comment]
たぶんこちらで解決すると思うので、closeします！

- https://github.com/VOICEVOX/voicevox_engine/pull/629

次のバージョン0.14.Xや、0.15で実装される見込みです。
