### ISSUE TITLE
DirectML版で複数リクエストが同時に来ると落ちる

### ISSUE THREAD

**Issue by Hiroshiba** [VOICEVOX/voicevox_engine#427]
## 不具合の内容

エンジンがおそらくリクエストに対して並列処理できる形になっています。
DirectML版はどうやら同時リクエストで落ちるらしく、エディタ側にエラーが返ります。

- https://github.com/VOICEVOX/voicevox/issues/843

### 現象・ログ

落ちる

### 再現手順

エディタ側から音声を複数書き出しする

### 期待動作

落ちない

## その他

DirectML版ではなくCPU版であっても、数百のリクエストが来たらおそらくメモリが溢れてエラーになります。
サーバーの並列数を制御できるようにし、デフォルト値を１にするのが丸いかなと思いました。

**Comment by takana-v** [comment]
調査したところ、exe化したエンジンの出力では、
```
（省略）
File "C:\Users\takana\DOWNLO~1\WINDOW~3\voicevox_engine\synthesis_engine\core_wrapper.py", line 486, in decode_forward
OSError: exception: access violation reading 0x0000000000000000
_executor.cc:346 onnxruntime::SequentialExecutor::Execute] Non-zero status code returned while running Concat node. Name:'Concat_2' Status Message: D:\a\_work\1\s\onnxruntime\core\providers\dml\DmlExecutionProvider\src\MLOperatorAuthorImpl.cpp(1758)\onnxruntime.dll!00007FF8BF56DE04: (caller: 00007FF8BF96F080) Exception(4) tid(820) 887A0005 GPU デバイス イン スタンスが中断されています。GetDeviceRemovedReason を使用して適切なアクションを確認してください。
```
pythonでの実行（faulthandlerを有効にした状態）では、`0xc0000374 (STATUS_HEAP_CORRUPTION)`で落ちました。

----

run.pyのsynthesis関数をコルーチン関数(async def)に書き換えることで改善しました。
デフォルトでは恐らくスレッドプールで実行されるので並列処理されますが、コルーチン関数の場合は単一のイベントループで処理されます。
synthesis関数ではawaitしないので、一度処理が走ったら処理が終わるまでロックされることになり、エラーが出ないのかなと思います。
（asyncioの理解が完全ではないので誤っているかもしれません）
https://fastapi.tiangolo.com/ja/async/#path-operation

もし別の方法（fastapiの設定で並列数を指定するなど）があればそちらを採用したいです。
この方法を採用する場合は別の問題が起きないかきちんとチェックする必要がありそうです。

**Comment by sevenc-nanashi** [comment]
https://www.uvicorn.org/settings/
fastapiの設定ではlimit_concurrencyが使えそうです。

**Comment by sevenc-nanashi** [comment]
が、他の並列で動かしたいところ（画像読み込みとか）にも影響するので、`async def`にするのが1番だと思います。

**Comment by Hiroshiba** [comment]
コメントありがとうございます！！とても参考になります。
並列数１にしちゃえばいいかなと思っていたのですが、たしかに画像を返すレスポンスなどが直列になってしまうのは避けたいなと思いました！！

asyncio、僕もよくわかってないんですよね･･･。
動くからヨシの方針で実装しちゃって良いかも？
もしよかったらぜひプルリクエスト頂けると！！！
