### ISSUE TITLE
サポートしているデバイスを返すAPIを作る

### ISSUE THREAD

**Issue by Hiroshiba** [VOICEVOX/voicevox_engine#449]
## 内容

エンジンがGPU対応しているかどうか、アプリ側から検知するすべがありません。
このissueはそれを可能にするissueです。

エディタのこちらのissueに関連しています。

- https://github.com/VOICEVOX/voicevox/issues/298

### Pros 良くなる点

エディタ側でGPUモードに切り替えられないことがわかるようになる。

### Cons 悪くなる点

APIが１個増える（問題はなし）

### 実現方法

ちなみに、すでにコアにはその機能があります

- https://github.com/VOICEVOX/voicevox_core/issues/16

**Comment by y-chan** [comment]
#299 で解決しているのではないでしょうか...:eyes:

**Comment by Hiroshiba** [comment]
あれ、ほんとですね！！　ありがとうございます･･･！
