### ISSUE TITLE
コードフォーマットをコミット時に自動で行う

### ISSUE THREAD

**Issue by y-chan** [VOICEVOX/voicevox_engine#45]
READMEに書かれているコードフォーマットコマンド(`pysen run format lint`)を自動で実行するようにしたいです。
git hooksとpre-commitを使えばうまい具合にできると思いますが、ちゃんと調べ切れていません。

ただ、これができるようになればGitHub Actionsで気づいて修正、といった二度手間が減ると思うので、できれば追加すべきと考えます。

**Comment by Hiroshiba** [comment]
初学者の方にも優しそうなので、良いと思いました。

**Comment by y-chan** [comment]
大丈夫ですー!

**Comment by isnot** [comment]
[voicevox#54](https://github.com/Hiroshiba/voicevox/pull/54) が、意図としては近しい内容のようです。
参考になるのではないかと思います。

**Comment by qwerty2501** [comment]
Python,pysenについて無知なので間違っていたら指摘お願いします。

規模が大きくなってファイル数が増えると処理時間が増えて結構ストレスになるため、pre-commit(git hooksのイベント)時に行う処理はステージ済みのファイルのみに対象を絞るようにしたほうが望ましいでしょう。
しかしながら、pysenについては全てのpythonファイルを対象にしてそうなのであまり相性はよくなさそうです。少なくともpre-commit(git hooksのイベント)時にlintを行うのは避けたほうが良いでしょう。

そのため現状を維持しつつ[pre-commit](https://pre-commit.com/) (git hooks管理ツール)を活用し`PR出したあとにlint errorを指摘されて修正` といったことを避けてレビュワーの負荷を減らすには、pre-commit(git hooksのイベント)時に `pysen run format lint` を実行するのではなく、pre-commit時に `pysen run format` ,  pre-push時に `pysen run lint` を実行するのが妥協案として無難に感じました。 `pysen run lint`  だけでフォーマット済みかどうかまで確認してくれるかわからないのでちょっと不安ですが。

先任者様のPRでフォーマットを行ったあとの再ステージが厳しいとのことでペンディングしたようですが、 pre-push時に `pysen run lint` を実行するようにすればすぐにできてある程度効果は得られるかと思います。

@Hiroshiba 
リポジトリをまたがってメンテされてる方がいらっしゃるのでgit hooksの管理方法( [husky](https://github.com/typicode/husky) を使うか、pre-commit(git hooks管理ツール)を使うか、あるいは特にツールを導入せずにgit hooksを共有するだけにするか)をVOICEVOXプロジェクトとして統一するべきか一度検討していただけますでしょうか？
統一するメリットとしては各リポジトリのgit hooks管理に関する学習コストをある程度下げる効果があると思います。反面デメリットとして例えば全てのリポジトリでhuskyを使って各リポジトリのgit hooksを管理するとなった場合engineリポジトリで本来不要なnodejsを導入する必要があります。
これについてどちらにするべきか私では判断できないので一度統一するのかしないのかオーナー様の方針を表明していただけますでしょうか？

**Comment by Hiroshiba** [comment]
> これについてどちらにするべきか私では判断できないので一度統一するのかしないのかオーナー様の方針を表明していただけますでしょうか？

提案ありがとうございます！
初学者のコミッターの方の負担が最も軽くなるようにするのが良いのかなと思います。
なので、nodejsのインストールをお願いしなくても良いような方法だと嬉しいです。

なのでそのリポジトリの言語に合わせてツールを導入するか、`ツールを導入せずにgit hooksを共有するだけにする`のが良いかなと思いました。
ただhooksを生で書くよりは、前者のほうがメンテナンス性が高いのかなと（なんとなく）思っている感じです！

**Comment by qwerty2501** [comment]
返信ありがとうございます。
となるとpre-commitにしちゃう感じでいいですかね？
とりあえずPR作ってしまうので、なんかまずかったらrejectしてください

**Comment by Hiroshiba** [comment]
フォーマットを自動で行うわけではないですが、commit時にlintが走るようになったのでcloseで良さそうです。
