### ISSUE TITLE
辞書ファイルのエクスポート・バックアップ方法を案内する

### ISSUE THREAD

**Issue by Hiroshiba** [VOICEVOX/voicevox_engine#453]
## 内容

辞書ファイルのバックアップ方法について問い合わせがありました。
https://twitter.com/gocha765/status/1563352363498217473

ファイルの場所を、READMEや、エディタのQ&Aで案内できると良さそう。

### Pros 良くなる点

バックアップや、PCの移行ができる

**Comment by sevenc-nanashi** [comment]
エクスポート/インポートにしても良さそう…？

**Comment by Hiroshiba** [comment]
それが一番良いと思います！
（このissueはreadmeに書くだけで済むので比較的簡単です）

**Comment by Hiroshiba** [comment]
それが一番良いと思います！
（このissueはreadmeに書くだけで済むので比較的簡単です）

**Comment by Hiroshiba** [comment]
追加で要望の声を頂きました。
https://twitter.com/nicogorivv/status/1603656354249392128

今だったらGUIで実装import/export実装も面白そうです。
https://github.com/VOICEVOX/voicevox_engine/issues/522

**Comment by Hiroshiba** [comment]
辞書ファイルインポート・エクスポートのニーズをよく聞くので、別途issueを作成してみました。

- https://github.com/VOICEVOX/voicevox_engine/issues/656

**Comment by tarepan** [comment]
#656 でのGUI実装完了を確認しました。  

VOICEVOX ENGINE `README.md` へのGUI操作案内ドキュメントを追加したいと思います。  
これにより「辞書ファイルのエクスポート・バックアップ方法を案内する」が達成可能です。  
@Hiroshiba  
着手しても良いでしょうか？

**Comment by Hiroshiba** [comment]
@tarepan あ、ぜひぜひ！！！
