### ISSUE TITLE
キャラクター（スタイルID）ごとにどのコアバージョンが利用可能かの一覧を返す

### ISSUE THREAD

**Issue by Hiroshiba** [VOICEVOX/voicevox_engine#455]
## 内容

エンジンは複数バージョンの音声ライブラリを持つことができます。

- https://github.com/VOICEVOX/voicevox_engine/pull/300

が、どのバージョンが利用できるかの一覧がないため、エディタ側に選択UIを実装できないことに気づきました。
このissueはその機能を実装できると完了になります。

### 実現方法

SpeakerInfo辺りに持たせる･･･？

## その他

関連

- https://github.com/VOICEVOX/voicevox_engine/issues/454
- https://github.com/VOICEVOX/voicevox/issues/324

（近い将来に全キャラのイントネーションが若干変わる可能性が若干あって、そのタイミングで必須になりそうに感じています）

**Comment by Hiroshiba** [comment]
実装を再確認していたのですが、すでにコアバージョンの一覧を取得する機能が実装済みでした！

https://github.com/VOICEVOX/voicevox_engine/blob/8057ee439767c9bfe14f323bb20f8391006d6bfd/run.py#L497-L502

こちらのAPIの仕様を変える形で実装できそう？

**Comment by Hiroshiba** [comment]
検証ありがとうございます！！

エンジンを使う側としては個々のスタイルからだけで情報が取れるのがあっても便利かもですが、全部返してもレスポンスが重くないのであればそちらで代替するのはかなり現実的なのかなと思いました！
プロダクトが成長してきてキャラが10000人とかになってきたら話は別かもです…！

**Comment by tarepan** [comment]
現在主流のユースケースは「VOICEVOX (editor) 経由」や「ENGINE Docker」です。  
これらはデフォルトだと単一コアバージョンのみを含んでいるため、`for core_version in core_version_res.json():` が 1 ループのみで終了します。  
なのでレスポンス速度に影響が出るのは `GET /speakers` が極端に遅い場合、つまりご指摘の `キャラが10000人` くらい極端なケースのみと考えます。  

現時点では「代替手段の動作が検証され、十分に機能した」という結論が得られたと認識しました。  
よって本 issue は NoGo で close とします。
