### ISSUE TITLE
ユーザーディレクトリに過去のコアライブラリを配置する場合のドキュメントを追加する

### ISSUE THREAD

**Issue by Hiroshiba** [VOICEVOX/voicevox_engine#459]
## 内容

こちらのタスクで、ユーザーディレクトリに過去のコアライブラリを配置できるようになりましたが、ユーザーへの案内がまだできていません。

- https://github.com/VOICEVOX/voicevox_engine/issues/457
- https://github.com/VOICEVOX/voicevox_engine/pull/458

### Pros 良くなる点

ネットに情報があるようになる

### 実現方法

ドキュメントへの案内と、使い方での案内があると良さそう？

**Comment by tarepan** [comment]
着手します。
