### ISSUE TITLE
jsonフィールドのcaseを揃えたほうが良いのではないか

### ISSUE THREAD

**Issue by qwerty2501** [VOICEVOX/voicevox_engine#460]
## 内容
現状APIで使われているjsonのフィールド名がcamelCaseとsnake_caseとで別れている
これはフィールド名に一貫性がないためcamelCaseかsnake_caseに揃えたほうが良いのではないか

### Pros 良くなる点

フィールド名に一貫性が持てる

### Cons 悪くなる点

破壊的変更になるため既存ユーザーに影響が出る

### 実現方法

voicevox_engine/model.pyに定義されている型のフィールド名をsnake_case、ないしはcamelCaseに統一する

### 関連 issue

https://github.com/VOICEVOX/voicevox_core/pull/261

**Comment by Hiroshiba** [comment]
issue作成ありがとうございます！！

なんとなくですが、返り値はjsonなので、jsっぽくcamelCaseで統一できればと思っています！

**Comment by qwerty2501** [comment]
https://github.com/VOICEVOX/voicevox_core/pull/261 で metas.jsonはすでにsnake_caseなのでそれにあわせるのであればsnake_caseのほうが良いのでは？となりました。coreの内容と合わせるのであればこっちもsnake_caseにするべき？

**Comment by tarepan** [comment]
@Hiroshiba  
2024年現在の視点（ポスト・マルチエンジン）で見ると、本 issue の提案は VOICEVOX API の破壊的変更です。  
マルチエンジンの意義を考えると、v1.0 でさえ実装するか悩ましいレベルに見えます。  
本 issue 提案は Go/NoGo どちらの方向性でしょうか？

**Comment by Hiroshiba** [comment]
やるやらはさておき、こちらのissueを短期間でクリアするのは難しいと思います。
↓のissueに集約されたということにして、このissueはcloseで良いかなと！

- https://github.com/VOICEVOX/voicevox_project/issues/18#issue-1451870920
