### ISSUE TITLE
AArch64版の追加を！

### ISSUE THREAD

**Issue by AlphaIru** [VOICEVOX/voicevox_engine#466]
## 内容

Aarch64 （通称Arm64）のバイナリーを追加してください！

### Pros 良くなる点

RaspberryPiなどで動くようになる

### Cons 悪くなる点

無い、作業が大変になるぐらい…？

### 実現方法

そこの所はあまり詳しくないのです…（CMake？

## VOICEVOXのバージョン

0.13.0

## OSの種類/ディストリ/バージョン

- [ ] Windows
- [ ] macOS
- [x] Linux

**Comment by Hiroshiba** [comment]
こちらと被っていそうなのでcloseします

- https://github.com/VOICEVOX/voicevox_engine/issues/322
