### ISSUE TITLE
開発版と製品版でユーザー辞書のディレクトリを変更できるようにする

### ISSUE THREAD

**Issue by sabonerune** [VOICEVOX/voicevox_engine#472]
## 内容

現状ユーザー辞書は開発版と製品版で同じディレクトリを利用しています。
そのため開発版で行った辞書の操作が製品版にも反映されてしまいます。
これでは不便なので変更できるようにするべきだと思います。

### Pros 良くなる点

開発しやすくなる。

### Cons 悪くなる点

ないはず。

### 実現方法

`user_dict`側では辞書のファイルパスが指定ができるはずなので`generate_app`で辞書ディレクトリを指定できるようにすればいい？
実行時に切り替えるいい方法が思いつかない。(起動コマンドで指定？)

## その他

現状はあまり問題になりませんが`run.py`のテストの障害になると思います。
- #230

**Comment by Hiroshiba** [comment]
issue作成ありがとうございます！！

> 実行時に切り替えるいい方法が思いつかない。(起動コマンドで指定？)

こちらですが、Nuitka/Pyinstallerでコンパイル済みのときは製品版、そうじゃないときは開発版にするのはどうでしょう。
そのif判定はこちらに実装例がありそうです！

https://github.com/VOICEVOX/voicevox_engine/blob/52d5c3836941fbd5862bcc58522a3b8e51e275d5/voicevox_engine/utility/path_utility.py#L10-L16

**Comment by sabonerune** [comment]
では取り掛かってみるとします。

**Comment by sabonerune** [comment]
`path_utility`確認して気づいたのですが開発版と製品版の保存場所を切り替えるだけなら`get_save_dir()`を切り替えてしまうのがいいような気がしました。
https://github.com/VOICEVOX/voicevox_engine/blob/440b463770ac5be1e8573575ad4c1d4367a1b70c/voicevox_engine/utility/path_utility.py#L24-L28

ただ、テストという点では`generate_app()`の引数でもユーザー辞書のディレクトリを指定できる方がいいような気もしますが。

**Comment by Hiroshiba** [comment]
ありがとうございます！！！

`get_save_dir()`を切り替えるというのは、例えば開発版だったら`Path(user_data_dir("voicevox-engine-dev"))`を返し、製品版だったら`Path(user_data_dir("voicevox-engine"))`を返す、というような感じでしょうか。
でしたら、たしかエディタがそうなっているので、エンジン側も合わせてそうするのが良さそうに思います。

引数で指定可能にする機能は、その機能がどうしても必要になってから実装を考えるのが良いのかなと思いました！

**Comment by sabonerune** [comment]
分かりました。そのようにしていきます。
