### ISSUE TITLE
もち子さんで二文字かつ最後が「ん」ならバグる

### ISSUE THREAD

**Issue by kinoko0518** [VOICEVOX/voicevox_engine#477]
## 不具合の内容

もち子さんで二文字かつ最後が「ん」ならバグります。

### 再現手順

もち子さんを選択した状態でたとえば「ぱん」と入力して生成します。
エディターでも生成したwavでもバグってます

## VOICEVOXのバージョン

12.5、13.1

## OSの種類/ディストリ/バージョン

- [x] Windows
- [ ] macOS
- [ ] Linux

Windows 10 Home 21H2

**Comment by Hiroshiba** [comment]
バグではなく仕様になります。
迂回策ですが、最初に「あああああ、」などを付けると良い感じになったりします。
