### ISSUE TITLE
ビルド済みエンジンがRust版コアを使うように変更する

### ISSUE THREAD

**Issue by PickledChair** [VOICEVOX/voicevox_engine#481]
## 内容

Rust 版コアには現行のリリース版コア（C++ 版）の互換 API が追加されたため (https://github.com/VOICEVOX/voicevox_core/pull/279) 、 #454 の作業を行わなくてもエンジンが Rust 版コアを使うことができるようになっています（コアの名前が `core` から `voicevox_core` に変わったことについても #471 で対応済みです）。

ビルド時に用いるコアについて、いくつかの変更に注意しつつ Rust 版コアに差し替える作業を行うと、Rust 版コアを用いたビルド済みエンジンをリリースすることができるようになります。 https://github.com/VOICEVOX/voicevox_core/issues/213 の作業の一環として、この作業を行っていきたいと考えています。

### Pros 良くなる点

- Rust 版コアに移行できる

### Cons 悪くなる点

- おそらくないです

### 実現方法

大雑把には以下のような作業があると考えました。

- [x] コアのリポジトリ側で現時点の機能を持つ Rust 版コアのプレビュー版リリースが行われるのを待つ
  - 以下の２つが達成されていることを期待している：
    - エンジン向けの互換 API が実装されている
    - リリースのアセットとしてダウンロードスクリプトがアップロードされている
- [ ] Docker ビルドを Rust 版コアに対応させる
  - コアの関連ファイルをダウンロードスクリプトで取ってくるようにする
  - コア名の変更に対応
- [ ] build.yml を Rust 版コアに対応させる
  - コアの関連ファイルをダウンロードスクリプトで取ってくるようにする
  - コア名の変更に対応

ただし「その他」で後述しますが、PyInstaller ビルドの作業との間で優先度をどうするかによって、作業の進め方が変わると思います。

## VOICEVOXのバージョン

0.14.0 のリリースに組み込まれることを目指す

## OSの種類/ディストリ/バージョン

- [x] Windows
- [x] macOS
- [x] Linux

## その他

エンジンのビルドツールを Nuitka から PyInstaller に移行する作業 #439 を優先させる場合は、そちらを先に進めて pyinstaller ブランチを master にマージしてから作業するのが良いかもしれません（PyInstaller ビルドの作業で残っているのは Docker ビルドの対応だと思います）。

両者が並行して進められるとややこしくなると考えられるため、どちらかを優先させる必要がありそうです。

**Comment by Hiroshiba** [comment]
pyinstaller側先に進めたいかもですね！
あるいはdocker版は一時的に置いておいてmainにマージしちゃうか、pyinstallerブランチから作業する手もあるかもです。（両方ちょっと微妙かもですが…）

pyinstaller側でちょっと聞いてみます。

**Comment by Hiroshiba** [comment]
pyinstaller側が完了したので（ thx @y-chan 🎉 ）rust版対応とかも進められそうですね･･･！！！

マストではないですが、なんとなくVOICEVOXバージョン0.14.0に間に合うと良いのかなとちょっと思ってます。
014.0は早くて12月中旬とかになりそうです。（各ボイボ系エディタとの連携が必要なのでたぶん遅れます）

もしよければ進めていけると･･････！！！
