### ISSUE TITLE
異なるサンプリングレートの音声も結合できるようにする

### ISSUE THREAD

**Issue by Hiroshiba** [VOICEVOX/voicevox_engine#486]
## 内容

エディタ側で複数エンジン対応が進められています。

- https://github.com/VOICEVOX/voicevox_project/issues/2

エンジン側のデフォルトのサンプリングレートを使う設定が可能なのですが、その場合エンジンごとにサンプリングレートが異なるため、音声結合の下記の部分で失敗します。

https://github.com/VOICEVOX/voicevox_engine/blob/0097d71a7745165dc547824bc2caa20081261ee4/voicevox_engine/utility/connect_base64_waves.py#L32-L33

このエラーを出なくするのがこのissueの目的です

### Pros 良くなる点

複数エンジン対応しても音声結合でエラーが出ない

### 実現方法

サンプリングレートも含んだ音声ファイルが渡ってきているので、一番サンプリングレートが大きい音声のサンプリングレートにリサンプリングしちゃう手が良さそう。

## その他

- https://github.com/VOICEVOX/voicevox_project/issues/2

**Comment by sabonerune** [comment]
自分がやってみます。

**Comment by Hiroshiba** [comment]
ありがとうございます！！ぜひお願いします！！
