### ISSUE TITLE
「SYNC_USER_DICT」用のAPIを作成する

### ISSUE THREAD

**Issue by Hiroshiba** [VOICEVOX/voicevox_engine#493]
## 内容

[エディタ側のマルチエンジン対応](https://github.com/VOICEVOX/voicevox_project/issues/2)で、辞書周りをどう設計するかという話がありました。

他のエンジンには同じ単語が別IDで登録されていたり、あるエンジンには登録されていて他のエンジンに登録されていない単語があったりと不便なので、それらをまとめるものが作られました。

- https://github.com/VOICEVOX/voicevox/pull/980

こちらのSYNC関数は、もしかしたらエンジン側にあったほうが適切なのかなと思ってissueを作成しました。

### Pros 良くなる点

* サードパーティアプリからも需要があるかも？
* そっちのほうが何度もリクエストしないので処理が早い

### Cons 悪くなる点

* APIを実装する必要がある

### 実現方法

エディタ側のSYNC_USER_DICT関数をエンジン側に実装する感じを考えています。
同じ単語が別IDで登録されていた場合は、もとから登録されていた方を消すという感じです。

**Comment by tarepan** [comment]
本 issue に関して、アイデアが提示され意義・必要性・設計は議論中との認識です。  

@Hiroshiba  
2024年3月現在でも上記の新 API は有用そう、という認識でしょうか？  

その場合、issue は open から 1年以上経過しており、「有用だしどちらかといえば賛成なのですが、手が回らずかつすぐに手を回せる人もいないというタスク」のように見受けられます。  
ロードマップ #1106 への登録と一旦 close が1つの方向性として有り得そうですが、どうでしょうか？

**Comment by Hiroshiba** [comment]
確認ありがとうございます！

この機能は「あった方が良い」より優先度がだいぶ低いかもと感じました！
エディタ以外から需要が発生せず、かつエディタ側でもすでに解決されているためです。
温度感を言葉にすると「あっても良いかもだけどなくても良い」くらいでしょうか。

ということでcloseしたいと思います！
