### ISSUE TITLE
upload-docs の CI が落ちるようになった

### ISSUE THREAD

**Issue by PickledChair** [VOICEVOX/voicevox_engine#499]
## 不具合の内容

[エンジンの API ドキュメント](https://voicevox.github.io/voicevox_engine/api/)は [upload-docs](https://github.com/VOICEVOX/voicevox_engine/blob/50a8e9a04601831e12c21d33b2f24febc9a5c7e3/.github/workflows/upload-gh-pages.yml) という Actions で生成・ GitHub Pages へのデプロイを行っていますが、 #494 の変更により失敗するようになりました。

### 現象・ログ

https://github.com/VOICEVOX/voicevox_engine/actions/runs/3359878760/jobs/5568393592#logs

上記のログより、`make_docs.py` のエラーメッセージを以下に抜粋します：

```
Traceback (most recent call last):
  File "make_docs.py", line 9, in <module>
    app = run.generate_app(
  File "/home/runner/work/voicevox_engine/voicevox_engine/run.py", line 115, in generate_app
    if args.cors_policy_mode == "localapps":
NameError: name 'args' is not defined
```

### 再現手順

master への push によって https://github.com/VOICEVOX/voicevox_engine/blob/50a8e9a04601831e12c21d33b2f24febc9a5c7e3/.github/workflows/upload-gh-pages.yml を走らせる

### 期待動作

API ドキュメントの更新が正常に行われるようになる

## VOICEVOXのバージョン

latest（開発版）

## その他

原因は、`run.py` の `generate_app` 関数内でグローバル変数 `args` にアクセスしていることです（以下の箇所）：

https://github.com/VOICEVOX/voicevox_engine/blob/50a8e9a04601831e12c21d33b2f24febc9a5c7e3/run.py#L113-L124

このグローバル変数 `args` は `if __name__ == "__main__":` であるときだけ定義されています（以下の箇所）：

https://github.com/VOICEVOX/voicevox_engine/blob/50a8e9a04601831e12c21d33b2f24febc9a5c7e3/run.py#L930

一方、`make_docs.py` では `import run` して `generate_app` 関数を呼び出している（以下の箇所）ため、`if __name__ == "__main__":` の処理が走らず、`args` 変数が定義されないため `NameError` が発生します：

https://github.com/VOICEVOX/voicevox_engine/blob/50a8e9a04601831e12c21d33b2f24febc9a5c7e3/make_docs.py#L7-L12

修正案としては、`generate_app` 関数の定義の直前にグローバル変数 `cors_policy_mode` と `allow_origin` を定義して初期値を指定し、`if __name__ == "__main__":` 内の処理で `args` の値を元にそれらの値を再設定する、というものが考えられます。

あるいは、`generate_app` 関数の引数として定義した方が良いのかもしれません（グローバル変数を安易に作ると問題の温床になるかもしれないため）。

**Comment by Hiroshiba** [comment]
issue作成ありがとうございます！
まあ解決はagrsを使わないようにすれば可能そうですね。とりあえず動くようにして、別issueでargsをglobal変数にしない方法を考えても良いのかなと思いました。

（仰る通りgenerate_appを分ける方針が良い気がしています）

**Comment by Hiroshiba** [comment]
PR作成してみました！！
