### ISSUE TITLE
run.pyのgenerate_appなどの関数を分離していく

### ISSUE THREAD

**Issue by Hiroshiba** [VOICEVOX/voicevox_engine#501]
## 内容

`run.py`が複雑化し、テストもない状態でメンテナンスが難しくなりつつあります。

例

- https://github.com/VOICEVOX/voicevox_engine/pull/500

メンテナンス性を挙げるためにも、run.pyにあるいろんな関数を分離させて解体していくのがこのissueの目的です。

## その他

関連

- https://github.com/VOICEVOX/voicevox_engine/issues/499
- https://github.com/VOICEVOX/voicevox_engine/pull/500
- https://github.com/VOICEVOX/voicevox_engine/issues/119

**Comment by tarepan** [comment]
> run.pyにあるいろんな関数を分離

@Hiroshiba  
こちらの意図は

- `run.py` 以外のファイル/モジュールへ分離
- `run.py` の巨大 `generate_app()` 関数を更に小さな関数へ分解する（あくまで `run.py` 内に留める）

のどちらでしょうか？

**Comment by Hiroshiba** [comment]
@tarepan たしかにどちらかわからないですね…！

「メンテナンス生を上げるため」とあるので、読みやすくリファクタリングされていればどちらでも良さそうです。
ただまぁ関数が多いので、ファイル分けするのが妥当なのかなと感じます！

**Comment by tarepan** [comment]
2024年3月現在の `run.py` を調査した。  
その結果、これまでのリファクタリングによりほぼ分割・切り出しが完了していることが確認された。  
積極的に切り出しする意味があるのは FIXME がついた以下の1箇所のみ：

https://github.com/VOICEVOX/voicevox_engine/blob/1968353a95d5b93ee27dab8f610b957a9c3edfd3/run.py#L877-L878

現状で別ファイル/モジュールに移植できるのは 30 行程度の `set_output_log_utf8()` 関数のみであった。  
これだけのためにモジュールを用意するのは過剰であると考える。  

@Hiroshiba  
本 issue は役割を果たしたと考えます（close 可能？）

**Comment by Hiroshiba** [comment]
あ、肝心のgenerate_appの切り出しがまだかもです！
とはいえ切り出しの要不要は要議論かもですね…。
run.pyは1500行くらいあるので、なにかしらの切り出しちゃったほうが良いと思ってます。

これはこのissueの範疇じゃなさそうですが、1番やった方が良さそうなのはgenerate_app自体の切り崩しかもです。
API用の関数を辞書や音声合成やプリセットなどの概念に分けてファイル定義するみたいな。

タスクを整理して別のissueでまとめ直すか、generate_appがしかるべき場所（どこ…？）に移動すればこのissueはcloseで良いと思います！

**Comment by tarepan** [comment]
> generate_appの切り出し  

私の理解が合っていないような気がするので、認識合わせさせてください。   

`generate_app()` は 1250 行の巨大関数ですが、そのほぼ全行が `app` への API 追加 (例: `@app.post()`) です。  
`generate_app()` を分割する場合、`app` 変数を引き回し、サブ関数内で `@app.post()` により API 追加する、という方向性で認識合っているでしょうか？

**Comment by Hiroshiba** [comment]
どういう構成が最適かは僕もわかってないのですが、app渡すのはテストが少し大変かもですね。
公式ドキュメント読むに、appを渡すのではなくrouterを返してもらう形にすると上手く書けるかも…？
https://fastapi.tiangolo.com/ja/tutorial/bigger-applications/

**Comment by tarepan** [comment]
着手しています。
