### ISSUE TITLE
エンジンデプロイ時にcoreのダウンロードスクリプトを使用するようにする

### ISSUE THREAD

**Issue by qwerty2501** [VOICEVOX/voicevox_engine#514]
## 内容
エンジンデプロイ時に行われているダウンロード処理をcoreのダウンロードスクリプトで行うようにする

### Pros 良くなる点

- stepの簡略化によるメンテナンス性向上
- coreで参照するdriverなどのバージョンが変更されてもengine側でdriverのバージョン指定を変更する必要がなくなる
- ダウンロード処理速度の向上(現状sh版スクリプトのみ非同期でダウンロード行っているので早い。powershell版も実装は面倒だが将来的に非同期化することによって早くできるかも)
- 必要なものだけダウンロードするためデプロイ時間の短縮になる。特にcudaについてはかなりの短縮が見込める

### Cons 悪くなる点

単純に実装するのが面倒

### 実現方法

build.ymlの変更

**Comment by Hiroshiba** [comment]
issue作成ありがとうございます！
ビルド時間の短縮になるのは盲点でした。この点はメンテナ的にはモチベーション的にありに感じました。

**Comment by qwerty2501** [comment]
ダウンロードスクリプトでデプロイするようにするためにはcpu archをスクリプトの引数として受け取れるようにしないといけなさそうです

**Comment by Hiroshiba** [comment]
#709 に調査結果なども含めて議論している場所があるので、そちらに移ります🙇
