### ISSUE TITLE
エンジン側でいろいろ設定できるGUIを提供する

### ISSUE THREAD

**Issue by Hiroshiba** [VOICEVOX/voicevox_engine#522]
## 内容

サードパーティアプリでエンジンだけを利用するという機会がそこそこ増えています。
エンジン単体でエンジンを設定できるGUIがあると便利そうです。

直近でCORS設定のために需要が増すと感じており、優先度を高めに設定しています。

- https://github.com/VOICEVOX/voicevox_engine/issues/509

### Pros 良くなる点

エンジン単体で設定できたりする

### 実現方法

[Streamlit](https://streamlit.io/)が便利だと思います。
ブラウザでGUIを表示できるのでお手軽です。

## その他

ついでに簡単な音声合成ができるとデバッグなどにも便利かも？

**Comment by takana-v** [comment]
Streamlitの実行には、`streamlit run xxx.py` を実行する必要があり、ビルド周りが大変そうです。
（不可能ではないですが、run.exeでボイボエンジンとstreamlitの両方を起動させようとすると、大きな変更が必要になりそうです）

現状、GUIの実装方法は大きく分けて2種類あります。
- 設定用exeファイルを提供する
  - wxPythonなどを使用？
  - ボイボがインストールされるパスを案内する必要がある
- 設定webページを返す
  - fastapiのappを2つ同時並行で動かす？
  - bootstrap（とjinja2）の利用

どちらの方法で進めるかは要検討です。

**Comment by Hiroshiba** [comment]
まとめありがとうございます！！
（`Streamlit`、静的HTMLをレンダリングできないのは個人的に予想外でした）

ユーザー目線で考えると、パスを探す必要がない「設定webページを返す」方が良いだろうなと思いました！
もし簡単に実装できるなら（開発者目線で）「設定用exeファイルを提供する」も良いかもと思いました！

**Comment by Hiroshiba** [comment]
wxPython・bootstrap+htmlどちらが良いかを考えていたのですが、どちらも一長一短だなという感じです。
前者はwxPythonの知識が必要になってきますが、pythonのみで書けるのでフォーマッターなどの導入がいりません。
後者はHTML+jsを生で書く煩わしさがありますが、webコーディングは一般的なので必要な知識が少なくてすみます。

とにかくGUIが提供されていることが一番大事だと思うのでう、実装はどの方針でも良いのかなと思いました！
もし取り組んでくださる方がいらっしゃったらアサインさせて頂きたいのでご連絡ください･･･！

**Comment by My-MC** [comment]
横から失礼します。

PythonはGILが使わているため複数のウェブサービスを動かそうとするとレスポンスなどが遅くなる可能性があります。
そのためFastAPIのhtmlresponseとjinjaのテンプレートエンジンを使ってWebGUIを実装するのがいいかと思います。この場合ですと、新しくappを作成する必要もなくなり、エンドポイントを追加するだけで実装できます。

**Comment by Hiroshiba** [comment]
プロセスを分けたらGILを無視できるので、その点は気にしなくて大丈夫だと思います！
WebGUIを実装して専用のエンドポイント追加するという方針はありだと思います！

**Comment by My-MC** [comment]
私はいまこのissueに取り組もうと思っているのですがひとつ相談があります。

設定の保存はファイルで行う必要があると思うのですが、どのファイル形式が良いでしょうか。具体的には以下のような形式があります

- iniファイル 標準モジュールconfigpaserで実装可能
- yamlファイル PyYAMLで実装可能
- json 標準モジュールjsonで実装可能
- toml tomlで実装可能

このように簡単にあげたものだけでも、様々な形式があり、VOICEVOXにはどれが相応しいでしょうか。

**Comment by Hiroshiba** [comment]
ありがとうございます！！
yamlでお願いします！理由は[プリセットをyamlで管理しているため](https://github.com/VOICEVOX/voicevox_engine/blob/fa30e5940586af810042322cb201bd2883a876b8/voicevox_engine/preset/PresetLoader.py#L39)です。

**Comment by My-MC** [comment]
すみませんもう一つ質問があります。

このissueはCORSの設定をWebGUIから設定できるようにするということから作成されたと思うのですが、設定できるものは[run,py](https://github.com/VOICEVOX/voicevox_engine/blob/master/run.py)を実行するときのコマンドライン引数で指定できるものでよろしいでしょうか。

**Comment by Hiroshiba** [comment]
そうですね！！
CORSに関連するのは`cors_policy_mode`と`allow_origin`で、特にほしいのは`allow_origin`です！

**Comment by Hiroshiba** [comment]
あ、こちらcloseしたほうが良さそうですね！
@My-MC さん、ありがとうございました！！！
