### ISSUE TITLE
フレーム単位のピッチ・音素入力が可能なQueryを作る

### ISSUE THREAD

**Issue by Hiroshiba** [VOICEVOX/voicevox_engine#528]
## 内容

ピッチ・音素（特にピッチ）をフレーム単位で入力・出力できるフォーマットを用意したいです。

- ref
  - https://github.com/VOICEVOX/voicevox/issues/1048

ビブラートのようなものを実現する際にも必要になると思います。

### Pros 良くなる点

表現の幅が広がる

### Cons 悪くなる点

どういうQueryModelにするかが難しい

### 実現方法

`AudioQuery`にOptionalな`frame_level`要素を持たせて、その下に構造を持たせる？

```json
{
  "frame_level": {
    "pitch": {
      "array": [0, 0, 0.5, 0.5, 0.5, ...],
      "rate": 200
    },
    "phoneme": {
      "array": ["pau", "pau", "pau", "a", "a", ...],
      "rate": 100
    }
  }
}
```

## その他

ここでいう「フレーム」は「一定時間で区切った区間」みたいな意味で、例えば200Hzだと0.005秒ごとにピッチの値がある感じです。

↑細かい単位

* サンプル単位
  * 一番細かい単位。音声波形がこれ。
  * VOICEVOXだとサンプリングレートは24000Hz。
* フレーム単位
  * 次に細かい単位。データによって時間幅は様々。
  * WORLDのピッチだとフレームレートは200Hz、Juliusの音素アライメントでの音素だと100Hz。
* モーラ単位
  * 音１個。日本語だと子音＋母音の単位。
  * 0.1~0.2秒くらい。話者や音によって長さは様々
* 音素単位
  * 子音とか母音とかの単位。
  * 短いと0.03秒とかになる。

↓荒い単位

**Comment by tarepan** [comment]
`TTSEngine.frame_synthsize_wave()` で実装された、という認識は合っているでしょうか？  
https://github.com/VOICEVOX/voicevox_engine/blob/ef122413041aa8896ccc218a3de5f7ccdb58dd3a/voicevox_engine/tts_pipeline/tts_engine.py#L561

**Comment by Hiroshiba** [comment]
たしかに、実装されたということになりそうです！　（コメント助かります！！）
