### ISSUE TITLE
リリースするvvppや7zをVOICEVOX ENGINEだとわかるようにする

### ISSUE THREAD

**Issue by Hiroshiba** [VOICEVOX/voicevox_engine#533]
## 内容

現状、リリースしているファイルの名称は`os-device.ext`になっています。
vvppが特にそうなのですが、なんのファイルかわからないので、prefixとして`voicevox_engine`などと付けたいです。

いろいろ付属するタスクはあるのですが、このissueはエンジン側のbuild.ymlが変わり次第closeにしたいと思います。

### Pros 良くなる点

わかりやすくなる。

### Cons 悪くなる点

エンジンのダウンローダーを作っているサードパーティアプリやエディタ側に修正が必要

### 実現方法

artifact_nameというのがあるので、ここに全部`voicevox_engine`とつけると良さそう。
https://github.com/VOICEVOX/voicevox_engine/blob/b28601b7d3e6ea4d3ad01a8366b1992a9661c579/.github/workflows/build.yml#L42

より正確にするなら、`package_name="voicevox_engine-$artifact_name"`などと別変数に入れるほうがより良さそう。

## その他

付属タスクメモ

- [ ] エディタの方に対応が必要だというissueをたてる
- [ ] サードパーティアプリ開発者の方に連絡する

**Comment by Hiroshiba** [comment]
メモですが、7zの中身のディレクトリ名は以前のartifact_nameと同一になっていそうでした。
`voicevox_engine-windows-cpu-0.14.0-preview.8.7z`を展開 → `windows-cpu`ディレクトリができる

`voicevox_engine-windows-cpu-0.14.0-preview.8`ディレクトリが出来上がるのが自然そうですが、まあ別に良いかなと思いました！

**Comment by sarisia** [comment]
ダウンロードしたファイルを処理する側 (editor) と、こちらのコード変更の量が少なくなるかな〜と思い、最後の圧縮のステップだけで名前を変更するようにしたのですが、もしかしたらそんなに労力変わらなかったかもしれないですね…💦

**Comment by Hiroshiba** [comment]
配慮ありがとうございます、実際エディタ側の変更もかんたんだったと思います！！
めっっっっっっっっっっっちゃ気が向いたら修正しても良いかも･････････？くらいの気持ちです！！

**Comment by Hiroshiba** [comment]
変えようかなと思ったのですが、またエディタ側も調整が必要になっちゃうので、まあいつか修正するという感じでいいかなと思いました！
忘れないように↓のタスクに追加しておきました！

- https://github.com/VOICEVOX/voicevox_project/issues/18
