### ISSUE TITLE
提案：スタイル毎に立ち絵を設定出来るようにする機能

### ISSUE THREAD

**Issue by sevenc-nanashi** [VOICEVOX/voicevox_engine#539]
## 内容

現在のVoicevox Engineの仕様では、1キャラクターにつき1つの立ち絵しか設定できません。
同一キャラに複数の立ち絵（＝スタイル毎の立ち絵）を設定できるようにする、という提案です。

### Pros 良くなる点

- 同じキャラの別の姿（例：櫻歌ミコの第一形態/第二形態、後鬼の人間/ぬいぐるみver）で立ち絵を変えることが出来る
- キャラクターの表情を豊かにすることが出来るようになる（例：ツンツンずんだもん）

### Cons 悪くなる点

（なし？）

### 実現方法

StyleInfoにOptionalな`portrait`キーを生やす？

## VOICEVOXのバージョン

（なし）

## OSの種類/ディストリ/バージョン

（全体）

## その他

（なし）

**Comment by Hiroshiba** [comment]
issue作成ありがとうございます！！

影響範囲としてはエンジン側のコード周り・ビルド周りと、あとエディタの表示部分という感じでしょうか。
需要の声は頂いているので、ぜひ実装したいです！！

**Comment by sabonerune** [comment]
少し前に思いつきで作ってみたものがあるのでPR出してみます。
