### ISSUE TITLE
Dockerfileでバージョン無指定のpip-licensesがライセンス不明のprettytableライブラリをインストールしてライセンスエラーになる

### ISSUE THREAD

**Issue by Hiroshiba** [VOICEVOX/voicevox_engine#544]
## 不具合の内容

Dockerfileでバージョン無指定のpip-licensesがライセンス不明のprettytableライブラリをインストールしてライセンスエラーになっていました。

### 現象・ログ

https://github.com/VOICEVOX/voicevox_engine/actions/runs/3789004082/jobs/6442342036

## OSの種類/ディストリ/バージョン

Linux

## その他

releasel-0.13でバージョンを固定する応急処置をしたいと思います。
それが解決するまでは優先度高にし、終わり次第優先度中くらいにしたいと思います。

どう処理するのが正しいでしょうか･･･？

**Comment by aoirint** [comment]
CIに必要なPythonパッケージは`requirements-dev.txt`に含まれていますが、Dockerfileの`runtime-env`ではバイナリビルドをしないので、ソースコードから実行するときに必要なパッケージだけをインストールするために、`requirements.txt`の方を使っています。

pip-licensesは`requirements-dev.txt`にしか含まれていないので、Dockerfileは独自にpip-licensesをインストールするようになっていて、バージョン無指定になっていましたね...

2か月前にpip-licensesに入った変更で、新しくprettytableパッケージ (BSD 3-Clause License)に依存するようになったみたいです。

- <https://github.com/raimon49/pip-licenses/blob/118478395fff23c62310265d1714c96d83589f47/requirements.in>
- <https://pypi.org/project/prettytable/>

少なくとももともとバージョン固定しておきたかったですが、かといってライブラリバージョンを管理する場所が分散するのも避けたいですね...

coreやONNX Runtimeと同様に、Dockerfileに`licenses.json`を生成するための`compile-python-env`ベースのステージを追加して、`requirements-dev.txt`からパッケージをインストール、`licenses.json`を生成して、`runtime-env`ステージにコピーするのがいいのかなと思います。

変更時の注意で、Dockerfile内のバイナリビルドでは`requirements-dev.txt`から改めて`licenses.json`を生成するようになっているので、こちらも変更してしまうとPyInstaller化のコミットとコンフリクト起こしそうですね（release-0.13にも変更を入れる場合）。

**Comment by Hiroshiba** [comment]
ライセンスを生成するための環境を作る、良いと思いました！！
たぶんこの方法だと、PyInstallerのライセンスが混じっちゃう問題も解決できそうだなと思いました！

- https://github.com/VOICEVOX/voicevox_engine/issues/549
-

**Comment by Hiroshiba** [comment]
あれ、ちょっと考えてみたのですが、`requirements-dev.txt`をインストールするとdevにしかないPyInstallerなども含まれちゃいますね･･･。
もしPoetryで管理するなら、devとtest以外にlicense環境を作って、そこに`pip-license`を加える感じでしょうか。
あるいはバニラの環境に`pip-license`を加えるか、なんなら今のDockerfile内みたくビルド時に書くとかもありかもですね･･･。

**Comment by Hiroshiba** [comment]
あ！いや、globalのpythonに`pip install requirements-dev.txt`してしまって、仮想環境を作って`pip install requirements.txt`すれば、globalの`pip-license`を使って仮想環境のライブラリのライセンス一覧が作れる･･･？

**Comment by Hiroshiba** [comment]
こちらrelease0.14に合わせて解決しちゃおうと思います。

- https://github.com/VOICEVOX/voicevox_engine/pull/574

↑でrequierements-license.txtを作りました。
これをインストールすれば問題なさそうです！
