### ISSUE TITLE
manifest_versionの更新忘れを防ぐ方法を考えたい

### ISSUE THREAD

**Issue by Hiroshiba** [VOICEVOX/voicevox_engine#547]
## 内容

`engine_manifest.json`にmanifest_version項目がありますが、これを上げ忘れるのが結構ありそうな気がしています。
できれば予防する手段を講じたいです。

### Pros 良くなる点

予防できる

### 実現方法

マニフェストファイルの型が変わってないことのテストを書く？

**Comment by sevenc-nanashi** [comment]
ちなみに、このmanifest_versionってどういう用途なんでしょう？
APIの仕様のバージョン、とかなら数値のほうが管理しやすいと思います

**Comment by Hiroshiba** [comment]
ですです、APIの仕様、正確にはマニフェストファイルのschemaのバージョンを意図してます。
https://github.com/VOICEVOX/voicevox_engine/blob/0c2c72869e38e5ba9379dac97f319b60295e1fc9/voicevox_engine/engine_manifest/EngineManifest.py#L47

数値でも良いのですが、基本的にリリースタイミングでアップデートしたほうが混乱がないだろうと思っていて、スキーマが変わるたびにインクリメントという運用にはしていない感じです。
（VOICEVOXのプロジェクトファイルのバージョンと同じ運用です。）

まあどちらにせよ更新忘れは起こり得ちゃいそうですね･･･

**Comment by tarepan** [comment]
> スキーマが変わるたびにインクリメントという運用にはしていない  

この運用の場合、テストでは防げないと思います。  

この運用をするにはまず「スキーマ更新済み・バージョン未更新」を test pass させ、バージョンアップ時に「スキーマ更新済み・バージョン未更新」を test failed させる必要があります。  
つまり同じ条件のテストをある時は通し、ある時はコケさせる必要があり、test更新無しでは困難に見えます。  
「バージョン更新時にテスト更新を忘れないこと」と申し送りするのであれば、「バージョン更新時にバージョン番号更新を忘れないこと」と申し送りするのと等価です。  

なので、バージョンアップ手順書に「manifestのバージョン番号更新を忘れないこと」と書くのが妥当な防止策に感じます。

**Comment by Hiroshiba** [comment]
@tarepan コメントありがとうございます！

こちら方法に関して完全には思いついてないのですが、想定と完全一致するテスト（スナップショットテスト）を書いて、そこに「更新する場合はマニフェストのバージョンも上げるか検討すること」みたいなコメントを書いておくと結構予防できるかもとか思っています。
まあレビュワー側は気づけないのですが･･･。

バージョンアップ手順書に書くのが妥当そうな気がしました 😇

**Comment by tarepan** [comment]
> バージョンアップ手順書に書くのが妥当そう  

👍  

project側 に [PR](https://github.com/VOICEVOX/voicevox_project/pull/46) を作成しました。  
本PR merge 後、close 可能です。
