### ISSUE TITLE
PyInstaller版エンジンのリリースに含まれるライセンスにPyInstallerのGPLライセンス文が含まれる

### ISSUE THREAD

**Issue by sabonerune** [VOICEVOX/voicevox_engine#549]
## 不具合の内容

PyInstaller版の`licenses.json`と`dependency_licenses.json`にPyInstaller本体のGPLライセンスの条文が含まれています。
PyInstallerによって生成されたプログラムにはライセンスを適用する必要がありません。
GPLのライセンス文が含まれることでVOICEVOX全体がGPLを適用する必要があると誤認させるリスクもあるため削除するべきです。

### 期待動作

PyInstallerのライセンス文が取り除かれる

## VOICEVOXのバージョン

[0.14.0-preview.2](https://github.com/VOICEVOX/voicevox_engine/releases/tag/0.14.0-preview.2) 以降

## その他

PyInstallerのFAQ
https://github.com/pyinstaller/pyinstaller/wiki/FAQ#license

**Comment by Hiroshiba** [comment]
Issue作成ありがとうございます！
ライセンス生成時は、requirements-dev.txtをインストールしてから依存するライブラリを網羅しているのですが、その関係でビルドのためのツールが入ってしまっていると思われます。

おそらく↓で提案されている、ライセンス一覧を作る専用の環境を作るのが良い解決策なのかなと思いました！

- https://github.com/VOICEVOX/voicevox_engine/issues/544

**Comment by Hiroshiba** [comment]
試したところ、globalのpythonにpip install requirements-dev.txtしてしまって、仮想環境を作ってpip install requirements.txtすれば、globalのpip-licenseを使って仮想環境のライブラリの一覧を作れるっぽいことがわかりました。
ちょっとやってみたいと思います！

**Comment by Hiroshiba** [comment]
↑完全に勘違いでした･･･。
Poetryにlicense groupを作ることで対応してみます。
