### ISSUE TITLE
`np.round`を用いているところを`np.ceil`に置き換えたい

### ISSUE THREAD

**Issue by y-chan** [VOICEVOX/voicevox_engine#552]
## 内容

Pythonの`round`関数は、単に四捨五入をするわけではなく、[偶数丸め](https://note.nkmk.me/python-round-decimal-quantize/#:~:text=source%3A%20round_test.py-,round()%E3%81%AF%E4%B8%80%E8%88%AC%E7%9A%84%E3%81%AA%E5%9B%9B%E6%8D%A8%E4%BA%94%E5%85%A5%E3%81%A7%E3%81%AF%E3%81%AA%E3%81%8F%E3%80%81%E5%81%B6%E6%95%B0%E3%81%B8%E3%81%AE%E4%B8%B8%E3%82%81,-Python3%E3%81%A7%E3%81%AE)をしています。これは、他の言語と異なる挙動であり、他の言語でエンジンを実装する際などに、影響を及ぼすことがあります。この挙動は、もちろん`np.round`にも引き継がれています。
なので、大体どの言語でも仕様が同じである`np.ceil`(無条件に切り上げ)もしくは`np.floor`(無条件切り捨て)に変える方がよいのではないかと思いました。

もしくは、可能であるなら、他の言語と同じ挙動をする`round`関数を独自に作るのもいいかもと思いました。

### Pros 良くなる点

Python独自の仕様に悩まされることがなくなるかも？

### Cons 悪くなる点

今までと生成される音の長さが変わる

### 実現方法

書き換える

**Comment by Hiroshiba** [comment]
調べてみるとなかなか面白い議論だなと思いました！

まず規格ですが、IEEEでは四捨五入ではなく偶数丸め

**Comment by qryxip** [comment]
Python以外で偶数丸めを表現することは普通にできそうです。CPythonの実装でどうやって偶数丸めにしているのか調べたところ、単にこうやっているだけだったようなので、これをそのままやれば模倣できると思います。
https://github.com/python/cpython/blob/3.11/Objects/floatobject.c#L1089-L1094

実際試してみたところ、x86_64のWindows, macOS, Linux上にて`np.round`と一致するらしいことを確かめました。
コード: https://github.com/qryxip/test-rust-roundeven/blob/98a6946a4b7c9763478466ae0e346df2d8cf4306/src/main.rs
Actions: https://github.com/qryxip/test-rust-roundeven/actions/runs/3806760340/jobs/6475847019

あと[rust-lang/libm](https://github.com/rust-lang/libm)というライブラリの[`libm::rint`](https://docs.rs/libm/0.2/libm/fn.rint.html)は、偶数丸めの挙動をするみたいです。
(なぜ↓の実装でそうなるか理解しきれていませんが)
https://github.com/rust-lang/libm/blob/0.2.6/src/math/rint.rs#L10-L14

**Comment by y-chan** [comment]
なるほど。
色々考えてみて、エディタ上での再生位置追従機能と実際の音声がうまく噛み合ってるのは四捨五入をしているからだろうというところはあって、`ceil`or`floor`を使うのは望ましくないことに気づきました。
また、numpyで効率的に四捨五入するのは、numpyの実装を独自に書き換えるぐらい大胆なことをしないと厳しいかなと思いました。

なので、ここはもうこの挙動のあり方を受け入れて、`round`の挙動が単なる四捨五入ではないということを、参照情報や他言語向けの実装向けの情報を含めてコメントに書く程度にとどめておくのがよいのかな...?と思いました。
これであれば、今までのエンジンに対して破壊的変更を加えることなく、他言語と異なる挙動をすることをコードを読む人に伝えられるかなと...!

どうでしょうか....!

**Comment by tarepan** [comment]
> roundの挙動が単なる四捨五入ではないということを、参照情報や他言語向けの実装向けの情報を含めてコメントに書く  

こちらの方針で着手します。
