### ISSUE TITLE
未初期化の speaker に対してリクエストを連続で送信すると, リクエスト数に比例してレスポンス時間が伸びる

### ISSUE THREAD

**Issue by sarisia** [VOICEVOX/voicevox_engine#554]
## 不具合の内容

前提: voicevox_engine の HTTP API を直接利用しています (エディタを利用していません).

未初期化の speaker (GET `/is_initialized_speaker` のレスポンスが `false`) に対し, speaker の初期化が必要なリクエスト
(POST `/audio_query`, POST `/synthesis` など) を連続で送信すると, 送信したリクエストの数に比例して, レスポンスにかかる時間が伸びていきます.

### 現象・ログ

リクエスト (POST `/audio_query`) を (連続で) 行い, レスポンスにかかる時間を計測します.

**リクエストを1つ送信**

この場合, レスポンスは約10秒で返ってきます.

```
POST http://localhost:50021/audio_query?speaker=20&text=%E3%83%86%E3%82%B9%E3%83%88 start: 2022-12-31 12:00:34.628012
POST http://localhost:50021/audio_query?speaker=20&text=%E3%83%86%E3%82%B9%E3%83%88 end: 2022-12-31 12:00:44.588634 (elapsed 0:00:09.960622)
```

**リクエストを5つ連続で送信**

この場合, 最初のリクエストのレスポンスは **約50秒後に** 返ってきます.
その後の連続したリクエスト (2-5個目) は, 最初のリクエストのレスポンス後にすぐに返ってきます.

```
POST http://localhost:50021/audio_query?speaker=20&text=%E3%83%86%E3%82%B9%E3%83%88 start: 2022-12-31 12:02:37.517616
POST http://localhost:50021/audio_query?speaker=20&text=%E3%83%86%E3%82%B9%E3%83%88 start: 2022-12-31 12:02:37.893750
POST http://localhost:50021/audio_query?speaker=20&text=%E3%83%86%E3%82%B9%E3%83%88 start: 2022-12-31 12:02:38.318484
POST http://localhost:50021/audio_query?speaker=20&text=%E3%83%86%E3%82%B9%E3%83%88 start: 2022-12-31 12:02:38.706374
POST http://localhost:50021/audio_query?speaker=20&text=%E3%83%86%E3%82%B9%E3%83%88 start: 2022-12-31 12:02:39.150189
POST http://localhost:50021/audio_query?speaker=20&text=%E3%83%86%E3%82%B9%E3%83%88 end: 2022-12-31 12:03:27.249951 (elapsed 0:00:49.732335)
POST http://localhost:50021/audio_query?speaker=20&text=%E3%83%86%E3%82%B9%E3%83%88 end: 2022-12-31 12:03:27.253010 (elapsed 0:00:49.359260)
POST http://localhost:50021/audio_query?speaker=20&text=%E3%83%86%E3%82%B9%E3%83%88 end: 2022-12-31 12:03:27.254628 (elapsed 0:00:48.936144)
POST http://localhost:50021/audio_query?speaker=20&text=%E3%83%86%E3%82%B9%E3%83%88 end: 2022-12-31 12:03:27.258922 (elapsed 0:00:48.552548)
POST http://localhost:50021/audio_query?speaker=20&text=%E3%83%86%E3%82%B9%E3%83%88 end: 2022-12-31 12:03:27.259091 (elapsed 0:00:48.108902)
```

### 再現手順

エンジンを起動し, HTTP API に対し POST `/audio_query` リクエストを連続して送信し, レスポンスにかかる時間を計測する.

```http
POST http://localhost:50021/audio_query?speaker=20&text=テスト
POST http://localhost:50021/audio_query?speaker=20&text=テスト
POST http://localhost:50021/audio_query?speaker=20&text=テスト
POST http://localhost:50021/audio_query?speaker=20&text=テスト
POST http://localhost:50021/audio_query?speaker=20&text=テスト
```

### 期待動作

未初期化の speaker に対して連続でリクエストを送信しても, 初期化時間が伸びるべきではありません.
具体的には, リクエストを5つ複数送信した際, 最初のレスポンスは10秒程度 (つまり, リクエストを1つのみ送信した場合と同程度の時間) で返ってくるべきです.

## VOICEVOXのバージョン

0.13.3

**0.14.0-preview.5 では発生しません.**

## OSの種類/ディストリ/バージョン

- [ ] Windows
- [ ] macOS
- [x] Linux

```
Distributor ID: Debian
Description:    Debian GNU/Linux 11 (bullseye)
Release:        11
Codename:       bullseye
```

## その他

- 原因は, 不適切な排他ロックによって初期化が複数回行われているためです:

 
 https://github.com/VOICEVOX/voicevox_engine/blob/cfc5ff1fb23d8fc25b8d81fb1c732da69f2ebc26/voicevox_engine/synthesis_engine/synthesis_engine.py#L185-L204

  - 複数のリクエストが `_lazy_init()` に到達した際, `initialize_speaker_synthesis()` は直列化されますが, `is_initialized_speaker_synthesis()` は即時に実行されます. よって, 複数リクエストの回数分, 複数回初期化が実行されます.

- v0.14.0-preview.5 では発生しませんでした. どうやら新しいコアで初期化が非常に高速になった (v0.13系は10秒前後 → v0.14系は0.5秒前後) ために, 問題とならなくなったようです. エンジン側の挙動に変わりはなく, 複数回初期化が行われていると考えられます.

**Comment by sarisia** [comment]
手元で修正していますので, PR を作成します.

**Comment by Hiroshiba** [comment]
あーー、なるほどです！！

> v0.14.0-preview.5 では発生しませんでした. どうやら新しいコアで初期化が非常に高速になった

あ、もしかしたら、LinuxのCUDA版お使いだったりしますか 👀
（[0.14系のLinux CUDA版がどうやら正常に動作しないっぽいという報告を頂いている](https://github.com/VOICEVOX/voicevox_engine/issues/513#issuecomment-1368256060)ので、初期化に何らかの問題があってすごく早く終わってるのかもと思った次第です）

**Comment by sarisia** [comment]
> https://github.com/VOICEVOX/voicevox_engine/issues/554#issuecomment-1368485343
> あ、もしかしたら、LinuxのCUDA版お使いだったりしますか 👀
> （[0.14系のLinux CUDA版がどうやら正常に動作しないっぽいという報告を頂いている](https://github.com/VOICEVOX/voicevox_engine/issues/513#issuecomment-1368256060)ので、初期化に何らかの問題があってすごく早く終わってるのかもと思った次第です）

いえ, 0.13.3 も 0.14.0-preview.5 も, いずれも Linux CPU 版 (GitHub の release ページからダウンロードしたもの) を利用しています.

どちらのバージョンも, `/audio_query` -> `/synthesis` で, 正常に再生できる音声が得られるところまでテストしています.
今, 再度追試したのですが, 0.14.0-preview5 はやはり滅茶苦茶初期化が高速 (0.5秒程度) なのですが, 正常に再生できる音声が得られていますね (春日部つむぎ ノーマル, もち子さん ノーマルでテスト済み).

**Comment by Hiroshiba** [comment]
おーーーなるほどです！！
ご確認いただきありがとうございます！！！
（思い当たる節がなかったのでお聞きした感じだったのですが、おそらく0.14でRust化した関係で暗号周りの処理が変わって高速化したのかもです。気づけてよかったです！）
