### ISSUE TITLE
CPUモードとGPUモードに精度の違いはあるでしょうか。

### ISSUE THREAD

**Issue by 2ji3150** [VOICEVOX/voicevox_engine#558]
## 質問の内容
気のせいかもしれませんが、何度聞き比べても僅かGPU動作モードのほうが高精度に感じます。
そういったことはあり得ますか。

## VOICEVOXのバージョン

0.13.4

## OSの種類/ディストリ/バージョン

- [x] Windows
- [ ] macOS
- [ ] Linux

### 環境
* CPU: AMD Ryzen R7 5800X
* GPU: RTX3060TI
* RAM: 32GB
* OS: Windows 11

**Comment by Hiroshiba** [comment]
issue作成ありがとうございます！

微小な差がある可能性があります。
差がないように作っているつもりなのですが、以前CPU版・GPU版で計算結果がずれていたことがあったので、もしかしたらまだどこかで微妙に異なっているかもしれません。
もしご興味あればAudacityなどで波形やスペクトログラムを見比べてみて、どのあたりに差があったかご報告頂けるとうれしいです！
どこあたりで計算結果がずれてるのかのヒントや、その深刻度を見積もれるかもしれません。

いったんissueの内容にはお答えできたと思うのでcloseします。
もし追加で聞きたいことがあればコメントあるいは別issueをどうぞ！

**Comment by 2ji3150** [comment]
書き出し結果だと、checksumで比較したbit by bit完全一致です。
プレビューの時だけ違いを感じることになるかもしくは、本当にプラシーボ効果か何かです。
お騒がせしてすみません。


![image](https://user-images.githubusercontent.com/12687881/210285065-de744e3e-de60-4582-9fcd-d6ad47457870.png)

**Comment by Hiroshiba** [comment]
あ、書き出し結果はキャッシュが効いている可能性が高いかもです！
一度voicevox.exeを落とすとキャッシュが消えます。

おそらくCPU版は２回書き出しても同じ結果だと思うのですが、GPU版は変わっているかもしれません。
