### ISSUE TITLE
テスト, ライセンスチェック (test.yml ワークフロー) を macOS でも実行する

### ISSUE THREAD

**Issue by sarisia** [VOICEVOX/voicevox_engine#560]
## 内容

GitHub Actions での `test.yml` ワークフローで, push や pull request に対する自動テストが行われていますが,
Ubuntu と Windows でのみ実行されており, macOS で実行されないようになっています.

各 OS での挙動差異によるバグの防止, 及び macOS-only な依存関係のライセンスチェックのために,
macOS でも `test.yml` を実行したほうが良いかと思います.

### Pros 良くなる点

- macOS のみで発生するバグを早期に検出できる
- macOS のみで利用される依存関係のライセンスチェックが実施できる

### 実現方法

`test.yml` には macOS の matrix 行が存在しているため, コメントアウトして動作を確認しつつ,
通るまで修正を行うのが良いかと思いました.

## VOICEVOXのバージョン

0.?.0

## OSの種類/ディストリ/バージョン

- [ ] Windows
- [ ] macOS
- [ ] Linux

## その他

macOS については, この workflow ファイルが追加された当初から (#30) ずっとコメントアウト状態
なのですが, どなたか経緯をご存知でしょうか…？

**Comment by Hiroshiba** [comment]
issue作成ありがとうございます！良いと思います！！

> どなたか経緯をご存知でしょうか

詳しくおぼえていないのですが、OS独自の問題がないテストはなるべく重複を避けてGithub Actionsに負荷をかけすぎないのを意識していたかもしれません。
pythonやフォーマッターのテストはそれでも良さそうですが、ライセンスやビルドのテストは（軽そうであれば毎回）macでも行ったほうが良いのかなと思いました！！
