### ISSUE TITLE
docker版もGithub Actionsで実行テストする

### ISSUE THREAD

**Issue by Hiroshiba** [VOICEVOX/voicevox_engine#564]
## 内容

docker版以外はビルド後に動作チェックしているのですが、docker版はされていません。

- https://github.com/VOICEVOX/voicevox_engine/issues/176

docker版もimage作成後に自動で起動＆疎通できるかチェックできると良いかもです。

### Pros 良くなる点

エラーに気づけるようになる

## その他

こちらのPRで気づきました

- https://github.com/VOICEVOX/voicevox_engine/pull/562

**Comment by K-shir0** [comment]
やってみます

**Comment by Hiroshiba** [comment]
おお！！　ありがとうございます！！
