### ISSUE TITLE
プリセットファイルのパスを起動引数および環境変数で変更できるようにしたい

### ISSUE THREAD

**Issue by aoirint** [VOICEVOX/voicevox_engine#570]
## 内容

T/O

### Pros 良くなる点

Dockerイメージで設定ファイル・プリセットファイルを永続化しやすくなる

**Comment by Hiroshiba** [comment]
issue作成ありがとうございます！！

たしかに、docker利用時の設定ファイルの永続化はちゃんと考えないとですね！
書かれている通りファイルパス指定が可能なのが良さそう。
