### ISSUE TITLE
エンジンごとのデフォルト辞書も同期できるようにする

### ISSUE THREAD

**Issue by takana-v** [VOICEVOX/voicevox_engine#575]
## 内容

現在の仕様では、それぞれのエンジンのデフォルト辞書にそれぞれのオリジナルキャラの読みが登録されています。
よって、エンジンを跨ぐとキャラの名前が読めない、ということが発生するかもしれません。
これを解決したいです。

### Pros 良くなる点

エンジンを跨いでもキャラクターの名前を正しく読める

### 実現方法

- `DefaultDictCSVLoader`みたいなクラスを実装
- `--additional_default_dict_csv`引数を追加
- エンジン起動時にLoaderを作成し、`generate_app`に渡す

## VOICEVOXのバージョン

0.?.0

## OSの種類/ディストリ/バージョン

- [ ] Windows
- [ ] macOS
- [ ] Linux

## その他

もう少し良い実装案が出るかもしれないので「要議論」をつけておきます。

**Comment by Hiroshiba** [comment]
Issueありがとうございます！！間違いなく課題だなと思いました！

実現方法に書かれていることって、誰かが全エンジンのdefault csvを結合して、それを引数で指定する…みたいな感じでしょうか👀

**Comment by takana-v** [comment]
自分の中では、全エンジンの`default.csv`のパスをエンジンに渡し、エンジン側でcsvを読み込んで結合するイメージでした。
（`--additional_default_dict_csv`は複数取れるようにする）
ただこれはエディタ側で処理しても問題ないと思います。

また、エンジンのデフォルト辞書の場所はengine_manifestに書くのが良いかなと思います。

**Comment by Hiroshiba** [comment]
なるほどです！
エンジン側の実装は素直なのですが、エディタ側から見ると引数の指定と全エンジン再起動が必要になりそうです。
特に全エンジン再起動はUX的に謎の待機が発生するのでもったいないな～と感じました。

アイデアとしては、`additional_default_dict_csv`に該当するものをこの前できたsetting.yamlに保存するようにし、設定APIを介して制御するのも良いかもと思いました！
パスをAPIで指定するのは若干危険な気と、なんか設計的にイマイチな気もしますが。。。

あるいはユーザー辞書をimport/exportできるのと同じようにして、デフォルト辞書csvもimport/export可能にするのもありかもと思いました。
こっちのが仕様が揃うので、仮に将来変更するとしても簡単かもです。

**Comment by tarepan** [comment]
本 issue に関して、必要性があると判断され設計は議論中との認識です。

@Hiroshiba
2024年3月現在でも上記のデフォルト辞書同期機能は有用そう、という認識でしょうか？

その場合、本 issue は最終議論から 1年以上経過しており、「有用だしどちらかといえば賛成なのですが、手が回らずかつすぐに手を回せる人もいないというタスク」のように見受けられます。
ロードマップ https://github.com/VOICEVOX/voicevox_engine/issues/1106 への登録と一旦 close が1つの方向性として有り得そうですが、どうでしょうか？

**Comment by Hiroshiba** [comment]
@tarepan 取り上げありがとうございます！

マルチエンジン実装から1年が経って状況が結構見えてきたので重要度を再考した感じだと、

* 設計の難度が割と高い（実装に時間がかかる）こと
* 需要がそこまで大きくないだろうということ
* 迂回策がかなり簡単なこと（エディターで辞書登録すればいい）

から、重要度は高くないかもと感じました！
ロードマップ #1106 に登録するか、需要が発生するまで実装を見送るかどちらかかなと思っていてちょっと迷ってます。

まーーーー需要の声を聞くまでクローズでも良いかも･･･？
