### ISSUE TITLE
辞書単語登録時にスペースがあっても登録できてしまう

### ISSUE THREAD

**Issue by Hiroshiba** [VOICEVOX/voicevox_engine#576]
## 不具合の内容

スペース付きのを登録して反映されないと不具合報告されている方がいらっしゃいました。
https://twitter.com/quokkaChannel/status/1615279752788717569

音声認識結果というコーナーケースですが、まあエラーを出してもいいかなと思いました。

### 再現手順

スペース付きで単語登録

### 期待動作

エラーが出る

## その他

そもそもOpenJTalk的にスペース付きはどういう扱いになってるんだろう･･･？

**Comment by sabonerune** [comment]
naist-jdicにスペース付きのデータが含まれていますね。
ぱっと確認したところスペースが全角化されていないことが原因の予感がします。

**Comment by Hiroshiba** [comment]
あーなるほどです！となるとこっちを変えたほうが良いかもですね。
https://github.com/VOICEVOX/voicevox/blob/4a84ac75f9e19468a33d221bfdcde484d66501d1/src/components/DictionaryManageDialog.vue#L384-L389

ありがとうございます、エディタ側にissueを作ろうと思います！！
