### ISSUE TITLE
Windowsのプレビュー版のCUDA版が動作しない

### ISSUE THREAD

**Issue by y-chan** [VOICEVOX/voicevox_engine#592]
## 不具合の内容

題の通り、CUDAのバージョンアップをしたことで、必要な動的ライブラリ(`zlibwapi.dll`)が不足してしまい、音声合成に失敗します。
Windowsにおいては、DirectML版があるため、替えが利く状況ではあるものの、現在 #502 のような問題があり、完全に代替を果たせる状況ではないため、CUDA版の需要はあるものと思われます。
次のバージョンでDirectMLへ完全に移行する(=CUDAのサポートをやめ、 #502 を解決する)か、それが間に合わない場合は`zlibwapi.dll`をビルド時に組み込んでCUDA版の配布を行うことが必要かと思います。

### 現象・ログ

![!image](https://cdn.discordapp.com/attachments/1016973645056327740/1068043410155503646/image.png)
![!image](https://cdn.discordapp.com/attachments/1016973645056327740/1068034816760619068/image.png)

### 再現手順

現在配布されているCUDA版のエンジンを実行する

### 期待動作

CUDA版でも音声合成ができる

## VOICEVOXのバージョン

0.14.0-preview.x

## OSの種類/ディストリ/バージョン

- [x] Windows
- [ ] macOS
- [ ] Linux

## その他

多分 DirectML版に完全に移行できる方が好ましいと思います

**Comment by Hiroshiba** [comment]
issue作成ありがとうございます！！

もうすぐ0.14のリリースですが、zlibwapi.dllの同梱は必須タスクではないと考えています。
だだCUDA版じゃないと困る方はいらっしゃると思います。
その方には見かけ次第、バックアップとしてzlibwapi.dllをダウンロードしてVOICEVOXのディレクトリに保存して頂くのを案内しようかなと思います！

（https://docs.nvidia.com/deeplearning/cudnn/install-guide/index.html#install-zlib-windows の`ZLIB DLL`でzlibwapi.dllをダウンロードできそうなんですが、僕の環境だとなぜかダウンロードされませんでした。。）

**Comment by y-chan** [comment]
案内を書くことと、ビルドコードを少し書き加えることと、どちらの作業負荷が大きいか、時間がかかるかということを考えたときに、ビルドコードを書き加える方が作業負荷が少なく済むと思ったのですが、どうでしょうか？(レビューが必要という点では、人員は必要かもしれませんが、大きな変更にはならないはずです。)
少なくとも0.14に間に合わないような大きな変更ではないです。

もしくは、DirectMLへの移行を完全なものとすることでクローズするというのも良いと思います(その場合は、PRをマージせずにクローズすればいいかなと思いました)

> `ZLIB DLL`でzlibwapi.dllをダウンロードできそうなんですが、僕の環境だとなぜかダウンロードされませんでした

私もただリンクをクリックするだけではダウンロードできなくて、右クリックして`リンク先を保存`とすることでダウンロードできました。

**Comment by Hiroshiba** [comment]
どちらかというと作業を遅延にできることが嬉しい感じです。
リリース前の今は時間がないけど、リリース後にリプライで案内するのはできるので･･･ 😇 
（もちろん、僕が作ってActionsでビルドして成果物を確認してという時間が取れないだけなので、誰かが作ってくださればもちろんマージしたいです！！）

> 右クリックしてリンク先を保存とすることでダウンロードできました。

なるほど。。。。。助かりました！！！！！
