### ISSUE TITLE
Voicevox engineのapiラッパー(Python製)をREADMEかなんかに乗せてほしいです

### ISSUE THREAD

**Issue by tuna2134** [VOICEVOX/voicevox_engine#593]
独自でvoicevox engineのapiラッパーを作りました(完全ではありません)
一応動作はでき、今後全部カバーするので、READMEに乗っけてください

ソースコード
https://github.com/tuna2134/voicevox-client

**Comment by Hiroshiba** [comment]
文脈はこの辺りのツイートですね！
https://twitter.com/fdc_tuna2134/status/1618500548503957504

別のOSSライブラリに関して指図するのは変かもですが、お互いの得になることを期待して２点だけコメントさせて頂きます！

１点目はユーザーへの案内の追加です。
READMEを見たユーザーがそのライブラリは何ができて何ができないのかわかるようになっているとユーザーに優しいのかなと思いました。
具体的にいうと、VOICEVOXを別途ダウンロードして起動する必要があるとかです！

２点目はほんとにただのコメントなのですが、今の形だとpip installすると、パッケージ名「voicevox」としてインストールされるかと思います。
これはパッケージ名「voicevox-client」になるようにして頂けると、将来的な衝突を避けられるかもです！

**Comment by tuna2134** [comment]
> 文脈はこの辺りのツイートですね！ https://twitter.com/fdc_tuna2134/status/1618500548503957504
> 
> 別のOSSライブラリに関して指図するのは変かもですが、お互いの得になることを期待して２点だけコメントさせて頂きます！
> 
> １点目はユーザーへの案内の追加です。 READMEを見たユーザーがそのライブラリは何ができて何ができないのかわかるようになっているとユーザーに優しいのかなと思いました。 具体的にいうと、VOICEVOXを別途ダウンロードして起動する必要があるとかです！
> 
> ２点目はほんとにただのコメントなのですが、今の形だとpip installすると、パッケージ名「voicevox」としてインストールされるかと思います。 これはパッケージ名「voicevox-client」になるようにして頂けると、将来的な衝突を避けられるかもです！

一点目は改善するよう頑張りますが、2点目は
```py
import voicevox_client
``` ってことでしょうか？

**Comment by tuna2134** [comment]
あと、voicevoxを使うのやめて
```sh
pip install voicevox-client
```
に移行しました

**Comment by Hiroshiba** [comment]
> 一点目は改善するよう頑張りますが、2点目は
import voicevox_client
ってことでしょうか？

ですね！
