### ISSUE TITLE
DirectMLでGPUがほとんど使用されない

### ISSUE THREAD

**Issue by 0kq-github** [VOICEVOX/voicevox_engine#612]
### 現象・ログ
DirectML版で生成を行った際GPUがほとんど使われずCPUに負荷がかかっており、生成が明らかに遅くなる

### 再現手順
DirectML版で音声生成を行う (エディタ有無 どちらでも確認)

### 期待動作
0.13.3等と同様にGPUで処理されること

## VOICEVOXのバージョン

0.14.1

## OSの種類/ディストリ/バージョン

- [x] Windows
- [ ] macOS
- [ ] Linux

OS: Windows 10 Pro 64bit
GPU: Tesla P40 (RTX3070Tiでも同様の現象を確認)
RAM: 32GB

## その他
nvidia-smiで確認するとCPUモードと違いプロセスの一覧に表示され、使用率が10~20%程度上昇している

**Comment by Hiroshiba** [comment]
おっと、本当ですね！！！
ご報告ありがとうございます。
僕のPCでの検証結果です。

```bash
set -eux

# TTSして見る関数
function tts() {
    text="$1"
    echo -n "$text" >text.txt

    curl -s \
        -X POST \
        "localhost:50021/audio_query?speaker=1" \
        --get --data-urlencode text@text.txt \
        >query.json

    curl -s \
        -H "Content-Type: application/json" \
        -X POST \
        -d @query.json \
        "localhost:50021/synthesis?speaker=1" \
        >audio.wav
}

# 起動
ここを書き換える
# ./run.exe &
# ./run.exe --use_gpu &

sleep 10

# とりあえず１回実行
tts "こんにちは"

# 時間測定
time for i in $(seq 1 10); do
    tts "テスト音声です、テスト音声です、テスト音声です"
done

# 停止
kill %1
```

```bash
0.13 GPU
real    0m1.849s
user    0m0.060s
sys     0m0.120s

0.13 CPU
real    0m12.008s
user    0m0.105s
sys     0m0.105s

0.14 GPU
real    0m8.140s
user    0m0.060s
sys     0m0.195s

0.14 CPU
real    0m11.669s
user    0m0.091s
sys     0m0.166s
```

**Comment by Hiroshiba** [comment]
環境によっては相当課題になりそうなので優先度を最高に設定します。
（共有です！ @y-chan ）

原因はエンジン側でDirectMLのフラグを用意したこと、あるいはRustコアがなぜか遅いということが考えられそうです。
後者のほうが調査しやすいのでちょっと試してみようと思います！

**Comment by 0kq-github** [comment]
0.14.2で試したところGPUがちゃんと使われて高速に処理できました

**Comment by Hiroshiba** [comment]
おお！！よかったです！！
現象のご報告とても助かりました、また何かあれば気軽にissueを建てて頂ければ･･･！！
