### ISSUE TITLE
話者ID・スタイルIDのマイグレーションAPI

### ISSUE THREAD

**Issue by sevenc-nanashi** [VOICEVOX/voicevox_engine#619]
## 内容

現在、話者IDの変更などのマイグレーションはエディタで行っています。この話者IDの変更情報をエンジン側に持たせた方が便利だと思いました。

### Pros 良くなる点

マルチエンジン時に、エディタに話者変更情報を伝えられる

### Cons 悪くなる点

（なし？）

### 実現方法

```ts
type SingleMigrationInfo = {
  // 変更前のStyleId
  before: number

  // 変更後のStyleId
  after: number
}

// これをGET /migration_infoで渡す
type MigrationInfo = Record<
  // バージョン（MyCoeiroinkのようにエンジンのバージョンを変えたくない場合を考えると、AudioCellごとにバージョンを持たせるべき？）
  string,

  SingleMigrationInfo[]
>
```

## VOICEVOXのバージョン

（関係なし）

## OSの種類/ディストリ/バージョン

（関係なし）

**Comment by Hiroshiba** [comment]
話者IDだけでなく、スタイルIDもマイグレーションの需要が生じるかもと思いました！

マイグレーション情報保存は話者ごとのmetas.json（[例](https://github.com/VOICEVOX/voicevox_engine/blob/da60a0cc43cdc48759d53a7b8f5b4006d33a89df/speaker_info/35b2c544-660e-401e-b503-0e14c635303a/metas.json)）に、
マイグレーション情報は話者の情報なので `/speaker_info` APIで返すのが良いのかなと。

エディタ側のマイグレーション処理をどうしようか難しいですね･･･。
影響があるのはプロジェクトファイルとデフォルトスタイルと並び替えかなと。
プロジェクトファイルはプロジェクト読み込み時にマイグレーションかけるのが一番いいのかなと思いました。
後者２つのマイグレーションはエンジン起動前なので･･･。うーん。うーん。。ｗ
`speaker_info`の情報をファイルから得られるようにする･･･････？いやー･･･エンジン起動後にマイグレーションかなぁ･･･。

あと、マイグレーション処理はエディタだけでなくエンジン側にも持たせた方が良いと思います！
合成APIなどで過去の話者ID・スタイルIDが来ても正しく生成できるようにする感じです。
マルチエンジン考えると、エンジンが勝手にアップデートし、エディタがマイグレーションに対応していない場合でもちゃんと動く必要があるので、これは必須な気がします。

ちょっとなかなか大変ですね。。
@shirowanisan さんとか @y-chan さんとか考えられたことあったりされますか･･･？

**Comment by y-chan** [comment]
私の場合は、そもそもマイグレーションが必要なようにコードを書いていないので、特に考えたことがないですね...
今まで、styleIdの変更があったのはごく一例(初期の初期にあった四国めたん・ずんだもんのスタイル)程度で、基本的にstyleIdや話者IDを変更する必要がないと思っていました。
ただ、マルチエンジン化に伴って、他のエンジンと話者ID(Speaker UUIDのことであってますよね...?)を合わせるような事例は発生したので、検討はすべきかなと思いました。

`/migration_info`を返すとすれば、過去のエンジンバージョン値を取ってあげる必要があるかもですね。
たとえば、スタイルIDに関しては、現状だとエンジン内で重複が許されないので、そこら辺の問題も同時に考える必要があるからです。
合わせて、エンジンのバージョンをプロジェクトファイルに埋め込むとかっていう改変も必要かも...(これめちゃめちゃ大変なのでは....?)

> マイグレーション処理はエディタだけでなくエンジン側にも
> 合成APIなどで過去の話者ID・スタイルIDが来ても正しく生成できるようにする感じ

これは確かに必要かなと思いました。
先にも挙げた、エンジン内での重複問題を考慮しなければいけなさそうです。
API叩くときにエンジンのバージョンを指定するとか...?

**Comment by tarepan** [comment]
本 issue に関して、スコープの議論中との認識です。

@Hiroshiba
2024年3月現在、上記機能群は有用そう、という認識でしょうか？

その場合、本 issue は最終議論から 1年以上経過しており、「有用だしどちらかといえば賛成なのですが、手が回らずかつすぐに手を回せる人もいないというタスク」のように見受けられます。
ロードマップ https://github.com/VOICEVOX/voicevox_engine/issues/1106 への登録と一旦 close が1つの方向性として有り得そうですが、どうでしょうか？

**Comment by Hiroshiba** [comment]
コメントありがとうございます！

優先度感が難しいとこですが、一旦特に何もせずcloseで良いかなと感じました。
あると便利な場面もありそうですが、需要が発生してから実装でも良いかなぁと…。
（忙しくて設計を考えてる時間が取れなそう、ってのもありますが…）

とりあえずcloseさせていただきます！
ロードマップに登録すべきかは要議論かもなので、ご意見あれば🙇
