### ISSUE TITLE
Mac M1ではDockerが動作しない

### ISSUE THREAD

**Issue by paulm17** [VOICEVOX/voicevox_engine#633]
mac m1 arm releaseのビルドをお願いします。

現在のdockerイメージはlinux/amdとして動作しており、wavファイルをビルドするエンドポイントが動作しない。

ソースからビルドしようとしましたが、あまりにも多くの問題にぶつかったので、あきらめました。

このTTSを作ってくれてありがとうございます。 私の日本語の勉強に使うのが楽しみです。

**Comment by Hiroshiba** [comment]
なるほど、とても良いアイデアですね！
ぜひGithub Actionsでビルドに挑戦してみてください！

VOCIEVOXはこちらでdocker buildしています。ここにARM用のビルドを追加できると思います。
https://github.com/VOICEVOX/voicevox_engine/blob/eee7f4a771c9e181ce58dd38a7ebe9e1ccb596dd/.github/workflows/build-docker.yml

Github Actionsはリポジトリをforkしたあと「Actions」から実行可能です。
プルリクエストお待ちしています！

---

Well, that's a very good idea!
You should try building it with Github Actions!

We have a docker build for VOCIEVOX here. I think you can add a build for ARM here.
https://github.com/VOICEVOX/voicevox_engine/blob/eee7f4a771c9e181ce58dd38a7ebe9e1ccb596dd/.github/workflows/build-docker.yml

Github Actions can be run from "Actions" after you fork the repository.
I'm waiting for your pull request!

**Comment by Hiroshiba** [comment]
@paulm17 ARM64 version is built and distributed. You can try it if you like!

- https://github.com/VOICEVOX/voicevox_engine/issues/644

**Comment by Hiroshiba** [comment]
@paulm17 Thanks a lot!
