### ISSUE TITLE
どのプロセスによってポートが塞がれているかをエラーログに出す

### ISSUE THREAD

**Issue by Hiroshiba** [VOICEVOX/voicevox_engine#634]
## 内容

50021番ポートが偶然使われていた場合、なぜかわからないけど起動しないという形になります。
もし前のプロセスがなぜか生き残ってるなどであればPC再起動で解決しますが、そうじゃない場合は現状詰みます。

どのプロセスが専有しているのかをエラーログに出してさえいれば何かアクティブサポートができるかもしれません。
ポート50021が塞がれているか確認し、塞がれている場合はプロセスの情報をエラーログに出したいです。

前例: https://twitter.com/hiho_karuta/status/1635568169896267776

### Pros 良くなる点

原因がわかる

### 実現方法

psutilが使えそう？
https://stackoverflow.com/questions/2987168/how-to-obtain-ports-that-a-process-in-listening-on

**Comment by tarepan** [comment]
2024年3月現在、エディタ側での対応等により、前提条件が変わっている感があります。  

@Hiroshiba  
2024年3月現在でもこちらの issue は実装の方向性でしょうか？

**Comment by Hiroshiba** [comment]
確かにエディター側は衝突を回避するようになったのでほとんど問題は解決したかもですね！
サードパーティー開発している場合にエラーの原因を究明するのに便利かもですが、こういう機能をあまり見かけたことがないのでそこまで重要じゃないかもです。

役割を終えたと判断してクローズしたいと思います！
もし他の方で希望があればコメントください 🙏
