### ISSUE TITLE
違いについて

### ISSUE THREAD

**Issue by tuna2134** [VOICEVOX/voicevox_engine#636]
## 質問の内容

Audio queryを作成するときに指定する`speaker`, 合成するときの`speaker`の違いを教えてください

**Comment by sevenc-nanashi** [comment]
話者によって音高・長さが異なります。
/audio_queryのspeakerは音高・長さの推論に使う話者を指定し、
/synthesisのspeakerはAudioQuery→wavの生成に使う話者を指定します。（という認識）

例えば、/audio_queryに四国めたん、/synthesisにずんだもんを指定するとめたんのイントネーションで話すずんだもんができるはずです。

**Comment by y-chan** [comment]
@.sevenc-nanashi さん対応ありがとうございます！おっしゃっていることで間違い無いです！

少し詳細に書くと、`audio_query` APIを叩くときと、`synthesis` APIを叩くときで、それぞれ話者を指定することができるだけで、意味的な違いはありません。
`audio_query` APIで得られたAudioQueryには話者固有のイントネーションや音の長さといった話し方の特徴を含むことになるものの、`speaker`に相当する情報が含まれていないので、`synthesis` APIを叩く時にも指定する必要があるという感じになっています。
なので、例に上がっている通り、`audio_query` APIと`synthesis` APIでそれぞれ別の話者を指定することも可能です。

以上が回答となります、ご質問が解決したようでしたら、Issueをcloseしていただけると...!
逆にまだ疑問に思うことがありましたが、返信いただければ...!

**Comment by tuna2134** [comment]
つまりaudio_queryとsynthesisのspeakerは同じにしてもいいって認識で大丈夫ってことですよね？

**Comment by y-chan** [comment]
そうですね、同一話者を指定すれば、最も自然な音声合成ができますね！

**Comment by tuna2134** [comment]
ありがとうございます
