### ISSUE TITLE
latest release権限をGithub Actionsから剥奪したい

### ISSUE THREAD

**Issue by Hiroshiba** [VOICEVOX/voicevox_engine#637]
## 内容

エディタ側で、バージョン999.999.999のソフトウェアがリリースされてしまうというミスがありました。

- https://github.com/VOICEVOX/voicevox/issues/1260

このときは特に問題が発生しませんでしたが、例えばエンジンの場合だとVOICEVOXリポジトリのlatestを信用して最新のをダウンロードする、みたいな機構を組み込んでいるアプリもあるかもしれません。
もしそこで変なバージョンのエンジンがダウンロードされると迷惑がかかってしまうので、防止したいです。

そもそもGithub Actionsからlatest releaseの権限を剥奪し、pre releaseしかできないようにすればとても安全になりそうです。

### Pros 良くなる点

Github Actionsのバグによるミスをなくせる。

### 実現方法

GITHUB_TOKENのパーミッションの設定方法などがあれば知りたいです。

### その他

エディタの方のisssue

- https://github.com/VOICEVOX/voicevox/issues/1263

**Comment by tarepan** [comment]
## メモ
[`ncipollo/release-action@v1`](https://github.com/ncipollo/release-action) で Release を生成。

**Comment by tarepan** [comment]
GitHub のドキュメントを確認しましたが、権限（workflow `permissions` 属性、ghトークンAuthZ範囲設定）による latest release のみ不許可はなさそうでした。  
latest も prerelease もあくまで「フラグの1つ」といった扱いのようです。

**Comment by Hiroshiba** [comment]
@tarepan ありがとうございます！！

なるほどです。となるとこのissueの達成はほぼ不可能とみなせそうですね･･･。

そもそも`pre rerelase: true`を必ずつけるようにし、問題がなければlatest化するとかのフローを取ると良いかもと思いました。
（今だとpre releaseかどうかを選べるのでバグが発生しうる）
まあpre release: trueを付け忘れる可能性はあるのですが･･･。

問題の解決は困難で、代替策も思いつかないので、このissueはcloseが良さそうに思いました。
ということでcloseします！
