### ISSUE TITLE
Docker イメージ ubuntu22 サポート追加

### ISSUE THREAD

**Issue by K-shir0** [VOICEVOX/voicevox_engine#660]
## 内容

- Docker イメージ ubuntu22 サポート追加
  - ubuntu22 のサポートの話が出た
    - #650

### Pros 良くなる点

- LTS なので 2025 年移行もサポート可能になる
- ubuntu22 ベースのイメージを使いたい人が使える

### Cons 悪くなる点

なし

### 実現方法

1. `.github/workflows/build-docker.yml` に ubuntu22 と名のついたタグを追加
2. `.github/workflows/release-test-docker.yml` に ubuntu22 と名のついたタグを追加
3. 既存の `cpu` や `nvidia` は最新の ubuntu 22 に移行する

## VOICEVOXのバージョン

0.14.3

## OSの種類/ディストリ/バージョン

- [ ] Windows
- [ ] macOS
- [x] Linux

**Comment by Hiroshiba** [comment]
issue作成ありがとうございます！！
サポート追加していきたいですね･･･１

**Comment by aoirint** [comment]
こちら、CUDA 11.6でUbuntu 22.04のDockerイメージ（ベースイメージ）が提供されていないので、
Ubuntu 22.04のベースイメージが提供されているCUDA 11.7以上に更新する必要がありそうです。

CUDAが提供されているコンテナレジストリ:

- https://hub.docker.com/r/nvidia/cuda
- https://catalog.ngc.nvidia.com/orgs/nvidia/containers/cuda

CUDAバージョンとNVIDIAドライババージョンの互換性表:

- https://docs.nvidia.com/cuda/cuda-toolkit-release-notes/index.html
> Table 2. CUDA Toolkit and Minimum Required Driver Version for CUDA Minor Version Compatibility

**Comment by Hiroshiba** [comment]
あーなるほどです！
自前でCUDA環境作るのはやったことあるのですが、結構メンテするのは大変だったのでなるべく避けたいかもです。

今出てる最新のonnxruntimeはCUDA 11.6ですが、なんとなく11.7上でも動く気がします！

**Comment by aoirint** [comment]
Ubuntu 22.04ベースイメージ対応の障害になりそうだった以下の点が解消されました。

- Python 3.8 から 3.11 に更新 #662 
- CUDA 11.6 から 11.8 に更新 #695

@K-shir0 
以前より対応を進めやすくなったと思います。ご興味ありますか...? 👀

**Comment by K-shir0** [comment]
@aoirint ありがとうございます。時間があるので対応しようと思います！！

**Comment by aoirint** [comment]
こちら、Ubuntu 20.04のサポートが2025年4月に切れるので、引き継ごうと思っています。
