### ISSUE TITLE
自作iosアプリから自宅のwindowsのvoicevox apiを使って音声合成結果を高速に受け取る方法

### ISSUE THREAD

**Issue by aistudy111** [VOICEVOX/voicevox_engine#665]
## 質問の内容
同一のネットワークにあるiosからwindowsへ接続を行っています。
以下のコードで音声合成をするコードをswiftで書いて走られると、"こんにちは"が再生されるのに1分ほどかかりました。
データの受け取りが完了するのに異常に時間がかかっている様なのですが、同一PCからpythonでapiを使ってwav fileを再生する場合は数秒で終わります。高速にiosからwavデータのレスポンスを受け取る方法があれば教えていただきたいです。

```swift
// ステップ2: synthesis へのリクエスト
AF.upload(jsonData, to: synthesisUrl, method: .post, headers: ["Content-Type": "application/json", "accept": "audio/wav"]).response { response in
                        switch response.result {
                        case .success(let data):
                            let audioUrl = FileManager.default.urls(for: .documentDirectory, in: .userDomainMask).first!.appendingPathComponent("audio.wav")
```

## VOICEVOXのバージョン

0.14.4

## OSの種類/ディストリ/バージョン

- [x ] Windows
- [ ] macOS
- [ ] Linux
*   Windows 10 Pro 64bit CPU 13990 Intel chip GPU RTX3090　                            
  補足:
Alamofireを使ってもURLrequestを使っても処理速度は変わらなかったです。

**Comment by Hiroshiba** [comment]
同一PCからだと早いのであればサーバー接続の問題なので、VOICEVOXに関係のない質問となりそうです。
お力になれなそうなのでcloseします。

ちなみにVOICEVOXのdiscordサーバーもあったりします。
自分はサーバー周りに詳しくないのでわからないのですが、どなたか助けてくださるかもしれません。
https://discord.gg/WMwWetrzuh
