### ISSUE TITLE
devcontainerで環境構築

### ISSUE THREAD

**Issue by tuna2134** [VOICEVOX/voicevox_engine#680]
## 内容

devcontainerは開発する際の環境構築を楽にするためのもので、それを使いたい

### Pros 良くなる点

環境を揃えれる
環境を構築簡単にできる

### Cons 悪くなる点

今の所見当たりません

### 実現方法

devcontainerのconfigを追加する

## OSの種類/ディストリ/バージョン

- [ ] Windows
- [ ] macOS
- [ ] Linux

**Comment by Hiroshiba** [comment]
OSSとして`devcontainer`をメンテナンスするのはちょっと違うように思いました。
色んな人がいろんな環境を持っているので、全部盛りになってしまいそうです。

一旦closeさせていただきますが、もし他に同じ環境を使われている方がいて、かつOSSとしてサポートすると良さそうな場合はコメントください！
