### ISSUE TITLE
リファクタ案： スクリプトはscriptsフォルダにまとめる

### ISSUE THREAD

**Issue by misogihagi** [VOICEVOX/voicevox_engine#688]
## 内容

* generate_licenses.py
* get_cost_candidates.py
* make_docs.py

を/scriptsに移動させる

あわよくば

* run.py

も移動させる

### Pros 良くなる点

ルートフォルダにあるファイルが少なくなり見通しが良くなる

### Cons 悪くなる点

動かなくなるかも…

**Comment by Hiroshiba** [comment]
確かにルートディレクトリ直下のファイルが散らばっているのはちょっと気になっていました！

run.pyはルートにあった方が初学者の方に分かりやすいかなと思いました。
Pythonのライブラリ参照とディレクトリ構造の関係はかなりややこしいので･･･。

scriptsディレクトリでもいいかもしれませんが、これらは開発段階で役に立つスクリプト群なのでとりあえずbuild_utilディレクトリでも良いかも･･･？
