### ISSUE TITLE
推論エンジンにONNXを採用し、サイズ削減とモデルポータビリティを向上させる

### ISSUE THREAD

**Issue by yamachu** [VOICEVOX/voicevox_engine#69]
## 内容

現在特徴量からwave形式のfloat列を推論する `each_cpp_forwarder` にはTorchが使用されている。
TorchScriptを使っているためポータビリティが良く、PythonでもC++でも使用できるみたいなメリットを享受できている。

しかしTorchLibrary自体のサイズが非常に大きく、VOICEVOX ENGINEをフルビルドし動作させるためのランタイムを同梱すると4GBを超える非常に大きなものとなっている。
バージョンアップの度に4GB以上のダウンロードが行われるのは体験的に好ましくないだろう。

そこでRuntimeのサイズが小さく同等レベルのポータビリティを備えるONNXを使用することを提案する。

### Pros 良くなる点

- Runtimeが小さいため、バンドルサイズが削減できる
  - Torch単体で1GBを超えるが、ONNXは100MBを超えない
  - GPUでの推論のためにはCudaのランタイムが必要であるためその分のランタイムを同梱する必要があるが、現在のTorchが依存しているものよりは少なくなると予想される
- ポータビリティが更に担保される
  - 多くの言語バインディングが存在し、each_cpp_forearderが存在しなくてもモデル単体を提供して多くの言語、プラットフォーム上で推論を行うことが可能
  - Webブラウザ上で推論を行うためのライブラリも提供が開始され、VOICEVOXの更なる展開が望める（？）

### Cons 悪くなる点

- CPP側で実装している箇所の大幅な書き換え（？）
  - どう実装されているのかわかっていないので想像で語っています

### 実現方法

- TorchScriptでモデルを保存する際にtorch.onnx.exportで出力する
  -  しかしONNXで実装されていないOperatorが存在した場合正常に出力できないなどあるので、ここで詰まることがあるかもしれません

## VOICEVOXのバージョン

0.4.1

## OSの種類/ディストリ/バージョン

*   Others

## その他

大分古いバージョンでの作業例ですが

https://github.com/yamachu/nnmnkwii/commit/7add37f201411b337532b81e4b79d8f1ea2d51d6

オレオレAutogradを作った場合こんな感じでONNXにする時にどう変換してほしいか書く必要があるものもあります（yukarin_s_forwarderとかsaとかその辺りがどう実装されているのかわからないので、単純にexportするだけで上手くいくかもしれません）。

もしかしたらEngineよりもCoreの方が適しているIssueかもしれませんね…

**Comment by Hiroshiba** [comment]
Issueありがとうございます。coreリポジトリしっかりしたらそちらに移しても良いかもですね！

容量が大きいことは、VOICEVOXが抱えてる大きめの問題の１つなのでぜひ解決したいところです・・・
内部でTransformer系のモデルを使っているので、そこの変換がサクッとできるかで難度がかわるかもしれません。

そういえばいつになるか未定ですが、JVSデータセットなどで学習したモデルと推論に必要なコードを公開しようかと考えているのですが、（やるやらないは置いておいて）他に必要になりそうなコードがあれば教えて頂ければ！

**Comment by yamachu** [comment]
> JVSデータセットなどで学習したモデルと推論に必要なコードを公開しようかと考えているのですが

首を長くしてお待ちしております:tada:

推論までのコード（例えばloadして、こんな形式のパラメータを入力して…）みたいのが分かると、モデルをloadしてから再度onnxでexportみたいので変換できるのかなぁ…とか思っています（トライしてみないとわからないところではありますが）。

他に必要そうなコードは今のところ思いつかないので、もしも公開されたらこのIssueにもリンクなどをいただけると嬉しいです（Coreとかその辺りのリポジトリもウォッチ予定なので見つけ次第tryしてみますが）。

**Comment by Hiroshiba** [comment]
了解しました！　いつになるかわかりませんが、なるべく早く公開したいと思います 🙏

**Comment by Hiroshiba** [comment]
とりあえず、推論だけはできるコードを書き出してみました・・・！
https://github.com/Hiroshiba/vv_core_inference

ただ、ネットワーク構造は、依存ライブラリを全てインストールしてコードジャンプを駆使しないと追えないようになってしまっています。

**Comment by yamachu** [comment]
ご連絡ありがとうございます！
早速コードを眺めて移植できないか検討中です

https://github.com/Hiroshiba/vv_core_inference/blob/3b9ad87b2d015513dd50c62c531e67b3124d5eea/vv_core_inference/make_yukarin_sosoa_forwarder.py#L7
https://github.com/Hiroshiba/espnet_pytorch_library
この辺りでespnetから呼んでいるtacotron2ラッパーがONNX化出来るかが鍵に見えますね………

Issueを見る感じONNX化のために何もしないぐらいのスタンスを持っていたのでもしかしたら腕力が必要かもしれませんが、トライしてみます

**Comment by chihayuki** [comment]
ONNXを採用するならばpytorchでなくonnxruntime のような推論エンジンを採用をしたほうが良いかもしれません
理由としては onnxruntime は DirectML をサポートしているためCUDAに比べて遅いですが intel,nvidia,AMDなどのどのGPUを同一のバイナリで利用することができます
Windows環境ならばOSの機能を利用する無駄なライブラリを同梱しなくてすむ容量も少なくなるかと思います

**Comment by Hiroshiba** [comment]
DirectML、初めて知りました！良いですね！！
もともとコア（ディープラーニングのforward部分）は秘匿化する必要がある関係でC++実装を目指してため、c++用のonnx runtimeを用いることになりそうです。
推論用のコードとサンプルモデルは２つ前のコメントにて公開中なので、もしよかったらコンバートに挑戦してみてください・・・！

**Comment by Yosshi999** [comment]
これ今どうなってますか？ちょっとやってみたいんですが

**Comment by Yosshi999** [comment]
Forwarderクラスを多少いじっても大丈夫ですか？
具体的にはWrapperYukarin*** に渡すときにbatchsizeを1に限定し、

https://github.com/Hiroshiba/vv_core_inference/blob/fa19e1d7a4fd6af463dcbbbcf9d1571b7353aae9/vv_core_inference/forwarder.py#L138-L145

ここらへんの`newaxis`を削除したいです

**Comment by Hiroshiba** [comment]
> ヤバそう

なるほどです！
参考になるかもなので僕の考えも載せてみます。

numpy.finfoは埋め込みで問題ないと思います！

peの置き換えに関しては、5000固定でも問題ないかもです。確か１秒で約100サンプルなので、５０秒ほどまでサポートできそうです。
想定より大きい物が来たら動的生成、というロジックが一番かっこいい思います！！

**Comment by Yosshi999** [comment]
onnx生成が出来れば次は https://github.com/Hiroshiba/voicevox_core でcore.cppの実装ですかね？
newaxisがいくらか消えましたがメモリ配置は変わっていないので、pythonとpython-C++のインターフェースは変更ないかもしれません（可読性という意味ではpythonのforwarderは変更したほうがいいかもしれない）
暗号化はさっぱりなのでおまかせします

**Comment by Hiroshiba** [comment]
リポジトリ間の横断が必要なため、別途リポジトリ横断用のissueにしてみました。

- https://github.com/VOICEVOX/voicevox_project/issues/4

**Comment by Hiroshiba** [comment]
製品版VOICEVOX COREの、onnxモデルが入ったリリースを作ってみました！！！大変おまたせしました。
https://github.com/VOICEVOX/voicevox_core/releases/tag/0.10.preview.0

この変更により、エンジン側でできることは２つほどあります。

１つ目が、7z分割をやめて、単体のファイルとしてreleasesを作ることです。これはユーザーにエンジンを配布しやすくなるので、ぜひやりたいと思っています。

２つ目は、CPU/GPU判定です。coreが対応しているデバイスを列挙するAPIが生えたので、エンジン側はそれをバイパスすることでソフトウェア側に伝えることができます。ソフトウェア側のこのissueを解決できるはずです。

- https://github.com/VOICEVOX/voicevox/issues/298

それぞれのissueを作成しつつ、作成したonnx版コアに問題が合った場合はissueを作成するとして、このissueはcloseしたいと思います。
本当に長い時間がかかりましたが、ここからの仕上げも大事なはずです。onnx版リリースまで頑張りましょう･････！！
