### ISSUE TITLE
辞書のimportがあるならexportもあればよいのではないでしょうか

### ISSUE THREAD

**Issue by misogihagi** [VOICEVOX/voicevox_engine#714]
## 内容

下記にも関連しますが、
https://github.com/VOICEVOX/voicevox_engine/issues/656

/import_user_dictがあるなら/export_user_dictもあってもよいのではないかと思いました。
/user_dictがそれの気はしますが…

### Pros 良くなる点

APIとして美しくなる

### Cons 悪くなる点

無駄なリソースが増える

**Comment by Hiroshiba** [comment]
仰るとおり`user_dict`がそれですね！
APIが必要だというissueであれば既存なのでclose、手段が必要だというissueであれば #656 と被っているのでcloseします！
なにか別の問題やコメントがあれば続けてください 🙏
