### ISSUE TITLE
API 関数の docstring を FastAPI 型で置き換え

### ISSUE THREAD

**Issue by Hiroshiba** [VOICEVOX/voicevox_engine#719]
元題名: 「numpyスタイルのドキュメントで書くとAPIドキュメントがとても読みづらくなるのを直す」

## 内容

numpyスタイルで書いたドキュメントはコード内では読みやすいですが、
![image](https://github.com/VOICEVOX/voicevox_engine/assets/4987327/fec988f7-528b-417e-b8f1-b0ce816faad7)

APIドキュメントではこのようになってしまいます。
![image](https://github.com/VOICEVOX/voicevox_engine/assets/4987327/3f9d0bf4-eb70-4f86-979b-072409bce2d3)

どちらでも読みやすいようにできれば良さそうです。

### Pros 良くなる点

読みやすくなる

### 実現方法

パラメータは[これと同様](https://github.com/VOICEVOX/voicevox_engine/blob/9b04dc9f5ac0b12561843343a002562f82f5353b/run.py#L391)にQueryにラップしてドキュメントを書くしかない･･･？

**Comment by sevenc-nanashi** [comment]
https://swagger.io/docs/open-source-tools/swagger-ui/usage/installation/#:~:text=the%20Configuration%20documentation.-,unpkg,-You%20can%20embed

GitHub PagesのAPIドキュメントをSwagger UIにするのも手だと思います。

**Comment by tarepan** [comment]
API は ENGINE 内部から呼ばれない（= コードエディタによる docstring 読み取りがほぼ無い）ため、API 関数にフォーマルな docstring を付ける意義自体が少なそうです。  
となると docstring を捨て、`Query` でラップして関数定義に含ませるのが合理的だと考えます。

**Comment by Hiroshiba** [comment]
おっしゃる通りですね！
必要であればQuery側に書くのが最善な気がしました！！
