### ISSUE TITLE
「AquesTalkライクな記法」や「kana」をドメイン用語「AquesTalk風記法」に統一する

### ISSUE THREAD

**Issue by Hiroshiba** [VOICEVOX/voicevox_engine#720]
## 内容

VOICEVOXの音声合成は、テキストからではなくアクセント箇所も指定したカタカナ+記号で表すような記法もサポートしています。
これはいわゆるAquesTalkの記法と似ているのですが、一部ちょっとだけ異なっています。
そのためこの記法の呼び方をどうしようかでずっと迷ってて、ドキュメントなどでもいろんな言葉で表れています。

コアの方で「AquesTalk風記法」に統一しようという動きがあります。
https://github.com/VOICEVOX/voicevox_core/pull/532#discussion_r1271480971

エンジンの方でもこれに倣って統一しようかなと考えてます。

### Pros 良くなる点

呼び方で困ることがなくなる

### 実現方法

発見し次第置き換えていくだけ

## その他

呼び方を固定するという話なので破壊的変更といえば一応破壊的変更ですが、まあアナウンスもほとんどすることなくコソッとドキュメントを変えちゃう形でいいかなと思ってます。

- https://github.com/VOICEVOX/voicevox_engine/issues/108

**Comment by tarepan** [comment]
## 旧式記法リスト
- 「AquesTalk 記法」
- 「AquesTalkライクな記法」
-  「AquesTalkライクな読み仮名」
- 「kana」

## 旧式記述箇所リスト
- 「AquesTalk 記法」
  - README.md
- 「AquesTalkライクな記法」
  - `accent_phrases()` APIドキュメント
  - `validate_kana()` APIドキュメント
-  「AquesTalkライクな読み仮名」
  - `AudioQuery.kana` のField title
- 「kana」
  - 各種変数名（12個のファイルに146個の結果 by VSCode検索）

**Comment by Hiroshiba** [comment]
@tarepan リストアップありがとうございます！！

`kana`ですが、プログラム中に現れる時はこの表現が良いのかなとちょっと思いました。（逆にコード中にAquesTalkは現れないように）
というのもクエリパラメーターになってしまっているのと、あとドキュメントと違ってコード中は`kana`で統一されているので変えなくてもいいかなとちょっと思った次第です。
･･･コードをちゃんと読んでないので若干自信がないです。

ドキュメントやコメントは統一する、というのはどうでしょう･･･？

**Comment by tarepan** [comment]
> ドキュメントやコメントは統一する

👍  

着手します。
