### ISSUE TITLE
e2eテストの作成

### ISSUE THREAD

**Issue by stmtk1** [VOICEVOX/voicevox_engine#726]
## 内容
エディタのe2eテストは存在していますが、エンジンのe2eテストも欲しいと思ったので、イシューを作ってみました。

### Pros 良くなる点
- エディタ側のe2eテストが落ちたときに原因を特定しやすくなる。
- エンジン側のばぐを検出しやすくなる

### Cons 悪くなる点
なし

### 実現方法
pythonでいい感じのライブラリがあれば教えてください。

## VOICEVOXのバージョン

0.?.0

## OSの種類/ディストリ/バージョン

- [x] Windows
- [x] macOS
- [x] Linux

## その他
[関連issue](https://github.com/VOICEVOX/voicevox/issues/1508)

**Comment by sevenc-nanashi** [comment]
#230 ですかね？

**Comment by stmtk1** [comment]
そうですね。イシューかぶってたのでクローズします
