### ISSUE TITLE
ライブラリの脆弱性チェックを行う

### ISSUE THREAD

**Issue by stmtk1** [VOICEVOX/voicevox_engine#728]
## 内容
JavaScriptでいう`npm audit`のようにライブラリの脆弱性チェックを行う機構を導入する。

### Pros 良くなる点
- ライブラリの更新をするべきかどうかの判断材料が増える

### Cons 悪くなる点
- 依存ライブラリが増えそう

### 実現方法
[safety](https://github.com/pyupio/safety)というライブラリがあるのでこれを使えば良さそう。

## VOICEVOXのバージョン

0.?.0

## OSの種類/ディストリ/バージョン

- [ ] Windows
- [ ] macOS
- [ ] Linux

**Comment by Hiroshiba** [comment]
良さそうに感じました！！！

**Comment by tarepan** [comment]
## 設計
脆弱性チェックシステムは次の要素により構築できそうです：  

- チェッカー: `safety` (c.f. PR #733)
- 定期チェックシステム: CI by GitHub Actions

`safety` そのものの導入が可能であることが #733 にて検証済みです。  

## 現状
本 issue の実装者を募集しています。興味のある方は気軽にコメントください👍

**Comment by tarepan** [comment]
着手します。
