### ISSUE TITLE
soundfileの依存を外す

### ISSUE THREAD

**Issue by sabonerune** [VOICEVOX/voicevox_engine#731]
## 内容

音声ファイルの読み込みや書き出しにSoundFileが使用されています。
しかしSoundFileの音声エンコード機能は使われていないためScipyの機能で十分かもしれません。

### Pros 良くなる点

Linuxでlibsndfileのインストールが不要になる。
配布物のファイルサイズが小さくなる。

### Cons 悪くなる点

MP3等のファイル形式対応ができなくなる。
- #440

### 実現方法

soundfileを使用している部分を[Scipy.io](https://docs.scipy.org/doc/scipy/reference/io.html#module-scipy.io.wavfile)に置き換える

## OSの種類/ディストリ/バージョン

- [x] Windows
- [x] macOS
- [x] Linux

**Comment by Hiroshiba** [comment]
> Linuxでlibsndfileのインストールが不要になる。

これは結構大きいように感じました。
特にエディター側ではインストール時にこのファイルがないと再実行を求められる感じになっています。
https://github.com/VOICEVOX/voicevox/blob/1e6bce16bacb5c093b0b58f42c8df60fedebe59f/build/installer_linux.sh#L145

> MP3等のファイル形式対応ができなくなる。

こちらに関して、おそらくmp3だとさすがのVOICEVOXでも音質が下がる気がします。
どちらかというと非圧縮なflacとかのサポートなら必要そうかなと。
まあもしmp3が必要になっても、他のコーデックにも対応すべきだと思うので、soundfileではなくffmpegあたりに依存するのが良さそうに感じます。

この辺り @y-chan さん的の意見もちょっとお伺いしてみたいです 👀

**Comment by Hiroshiba** [comment]
@sabonerune なるほどです！！！！

確かに容量が数MB増えてしまうのはもったいない気はしないでもないですが、将来的に（mp3ではない）別コーデックの提供は結構あり得るかなと感じています。
それとscipyはどちらかというとついでの機能として音声ファイル出力機能がある形だと思うので、専門的なライブラリに任せておいた方が頼もしい気がしないでもないです。
（その代わり破壊的変更はいっぱいありそうですが･･･。）

外すべきか外さざるべきか、正直判断できないという考えになってきました。
依存外すべきだということに特に強い意見がなさそうであれば、一旦このissueのタイトルを「外すかどうか議論する」に変更するか、あるいはまた課題が再発するまでクローズしておくとかもありかもと思いました。

特にコメントがなければ大きな問題ではないと思うのでcloseの方向に倒そうかなと今のところ考えています。
逆にsoundfileをアップデートしてlibsndfileの依存を外すというのは大事だと思うので、そのissueは立てようかなと思います。

**Comment by Hiroshiba** [comment]
とても遅くなりすみません、issueを建てました･･･！

- https://github.com/VOICEVOX/voicevox_engine/issues/747
