### ISSUE TITLE
appdirsが非推奨になったためplatformdirsに移行する

### ISSUE THREAD

**Issue by sabonerune** [VOICEVOX/voicevox_engine#735]
## 内容

設定等の保存場所の取得に使っていた[appdirs](https://github.com/ActiveState/appdirs)が正式に開発が終了したため非推奨になりました。
移行先に[platformdirs](https://github.com/platformdirs/platformdirs)が案内されています。

### Pros 良くなる点

開発が継続されているためバグ修正等が受けられる。

### Cons 悪くなる点

保存場所に変更がないか確認が必要。

### 実現方法

パッケージを変更して修正する。

## OSの種類/ディストリ/バージョン

- [x] Windows
- [x] macOS
- [x] Linux

## その他

ぱっと見た限りでは名前の変更と取得できるディレクトリが増えたのだけで大きな変更はなさそう？
(UNIXでの変更について自分は理解できませんでした)
[Changelog](https://platformdirs.readthedocs.io/en/latest/changelog.html)

**Comment by Hiroshiba** [comment]
issue作成ありがとうございます！

> 保存場所に変更がないか確認が必要。

ここだけ気をつけておきつつ、いい感じのタイミングで移行するべきだと思います！

移行前に設定が保存されているパスのテストを書いてマージし、移行後もテストが通ることを再確認するのが一番良さそうに思います。
まあでもめんどくさいのでさっと変えて色々確認するでも問題ないかと！
