### ISSUE TITLE
「あっ」で /synthesis が Internal Server Error

### ISSUE THREAD

**Issue by oov** [VOICEVOX/voicevox_engine#75]
## 不具合の内容

VOICEVOX の GUI で `あっ` というセリフを読み上げようとすると、
音素は出るものの、試聴しようとすると `再生に失敗しました` のメッセージボックスが表示される。

### 現象・ログ

```
INFO:     127.0.0.1:64908 - "POST /synthesis?speaker=0 HTTP/1.1" 500 Internal Server Error
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "C:\Users\ANONYM~1\AppData\Local\Programs\voicevox\uvicorn\protocols\http\h11_impl.py", line 373, in run_asgi
  File "C:\Users\ANONYM~1\AppData\Local\Programs\voicevox\uvicorn\middleware\proxy_headers.py", line 75, in __call__
  File "C:\Users\ANONYM~1\AppData\Local\Programs\voicevox\fastapi\applications.py", line 208, in __call__
  File "C:\Users\ANONYM~1\AppData\Local\Programs\voicevox\starlette\applications.py", line 112, in __call__
  File "C:\Users\ANONYM~1\AppData\Local\Programs\voicevox\starlette\middleware\errors.py", line 181, in __call__
ValueError: repeats may not contain negative values.
```

### 再現手順

GUI でセリフとして「あっ」とだけ入力して試聴する。

### 期待動作

あっ

## VOICEVOXのバージョン

0.5.1

## OSの種類/ディストリ/バージョン

Windows 10 Home 64bit 21H1 19043.1165

## その他

私は陰キャなのでこれが読めないと困ることがあります。

**Comment by y-chan** [comment]
「あっ」のAudioQueryを見てみたところ、なんだかおかしいところを見つけました
```
[
    AccentPhrase(
        moras=[
            Mora(
                text='ア',
                consonant=None,
                consonant_length=None,
                vowel='a',
                vowel_length=0.10487611591815948,
                pitch=5.564767360687256
            ),
            Mora(
                text='ッ',
                consonant=None,
                consonant_length=None,
                vowel='cl',
                vowel_length=-0.0957988053560257,  #なぜかマイナス値
                pitch=0.0
            )
        ]
    )
]
```
これを強制的に絶対値を取るように変更してみたところ、音声合成時のエラーは出なくなりましたが、ちゃんと発音はされませんでした。
エラー原因はマイナス値であることはほぼ明らかな気がしますね....
因みにこの問題は四国めたんでしか発生しないようです(ずんだもんではAudioQueryの時点からマイナス値が出ることなく、音声合成時もやや変ではあるが問題なく発音される)

**Comment by Hiroshiba** [comment]
なるほど、これはおそらくコアライブラリの問題です。
長さの出力の値域は実数全体なので、機械学習のお気持ち次第では負の値も有り得そうです。

とりあえずなんらかの最小値を入れるのが良いと思いました。
・・・0.03秒くらい？

**Comment by oov** [comment]
時間の長さとしてマイナスの値を返してくること自体が利点になることがなさそうなので、
コア側で `yukarin_s_forwarder` がマイナスの値を `return` してこないようにしたほうが良さそうだと思います。
エンジン側で対応してしまうと、将来コアが公開されやがてエンジン部相当の別実装が現れたときに、それら各々の実装すべてでこの対応する必要が出てきそうだからです。
（勘違いだったらすみません）

**Comment by Hiroshiba** [comment]
たしかに！　仰るとおりです。　０以下の値が出力されないよう、コア部分で制限したいと思います。

**Comment by Hiroshiba** [comment]
現行のコアは負の値が取らないようになっていて、かつonnxコードもそうなるので、このissueは解決で良さそうです。

- https://github.com/VOICEVOX/voicevox_core/pull/47

ということでcloseします。
