### ISSUE TITLE
異なるバージョンのPoetryによる操作を防ぎたい

### ISSUE THREAD

**Issue by aoirint** [VOICEVOX/voicevox_engine#750]
## 内容

#710 に関連して、一応調べたのでメモとして残しておく、くらいのIssueです。

VOICEVOX ENGINEのライブラリ管理にはPoetryが使われており、
`poetry.lock`でPoetryのバージョンが固定されていますが、
開発者の環境やPoetryの使い方によって、異なるバージョンのPoetryが使われる場合があります。

この状況では、Poetryの更新で`poetry.lock`のフォーマットが変わった場合に、項目の削除やバージョン文字列の更新に伴い、`poetry.lock`に不要な差分が生じる問題が起きます。

不要な差分が生じないように、`poetry.lock`に固定されたバージョンと異なるバージョンのPoetryによる操作を防ぎたいです。

### Pros 良くなる点

- 不要な差分が生じなくなる

### Cons 悪くなる点

- おそらく手間が増える

### 実現方法

- 案1. ドキュメントにPoetryバージョンを追記する
- 案2. ドキュメントに最新のPoetryを使うように追記する
- 案3. ドキュメントで`poetry`コマンド実行時にPython仮想環境で実行するように案内する
- 案4. ドキュメントの`poetry`コマンドを`poetry run poetry`に置き換える
- 案5. プルリクエストのテンプレートにPoetryバージョンの確認項目を追加する
- 案6. `poetry.lock`について、生成したPoetryバージョンを検証するCIを追加する
- 案7.  Poetryのバージョンを固定するバージョン管理ツールがあれば導入する

## VOICEVOXのバージョン

0.15 開発版

### 発生する状況

VOICEVOX ENGINEリポジトリにおいて、システムにPoetryをインストールした上で`poetry install`を実行すると、
Poetryが作るPython仮想環境に、固定されたバージョンのPoetryがインストールされます。

ここで、Python仮想環境に入って（`poetry env use`または`.venv/bin/activate`または`poetry run poetry`）Poetryを操作すると、Python仮想環境内のPoetryが使用されます。
しかし、Python仮想環境に入らずにPoetryを操作すると、システムにインストールしたPoetry（PATHが通ったPoetry）が使用されます。

このとき、システムにインストールしたPoetryのバージョンと、VOICEVOX ENGINEが固定している（Python仮想環境内の）Poetryのバージョンとが異なる場合、固定されたバージョンのPoetryが使用されない問題が起きます。

### 発生例

例えば、以下のPRは番号順にマージされていますが、`poetry.lock`の内容はいずれもPoetry 1.6.1に固定されている一方で、
それぞれ異なるバージョンのPoetryで`poetry.lock`が更新され、不要な差分が生じています。

1. Poetry 1.6.0で更新: https://github.com/VOICEVOX/voicevox_engine/pull/727
2. Poetry 1.3またはそれ以前のPoetryで更新: https://github.com/VOICEVOX/voicevox_engine/pull/744
3. Poetry 1.6.1で更新: https://github.com/VOICEVOX/voicevox_engine/pull/749

#### Windows（Powershell）の場合

```powershell
(Invoke-WebRequest -Uri https://install.python-poetry.org -UseBasicParsing).Content | python3 - --version 1.6.1
(Invoke-WebRequest -Uri https://install.python-poetry.org -UseBasicParsing).Content | python3 - --version 1.5.1
(Invoke-WebRequest -Uri https://install.python-poetry.org -UseBasicParsing).Content | python3 - --version 1.3.2
```

#### Linux/macOSの場合

```shell
curl -sSL https://install.python-poetry.org | python3 - --version 1.6.1
curl -sSL https://install.python-poetry.org | python3 - --version 1.5.1
curl -sSL https://install.python-poetry.org | python3 - --version 1.3.2
```

## 関連Issue

- https://github.com/python-poetry/poetry/issues/3316

**Comment by Hiroshiba** [comment]
詳細なissueありがとうございます！！

いつか致命的な問題が発生してしまうかもしれないので、可能であれば対策したいですね！

人はどうしてもミスをしてしまうので、機械がミスを検知するのが良さそうに感じました。
実装難度の面も考えると

> 案6. poetry.lockについて、生成したPoetryバージョンを検証するCIを追加する

が妥当な感じがします。

今poetry周りだとreiquirements.txtが変わらないかどうかをチェックするCIはあったりします。
https://github.com/VOICEVOX/voicevox_engine/blob/10ac2f577abf7cc1619e8803617ca1374d9c6789/.github/workflows/test.yml#L42-L56

この辺りに追加で、[`poetry install`を実行した後にロックファイルが変更してしまっているかどうか検証する](https://chat.openai.com/share/4512d552-d074-476c-8b4b-95540d8b5481)とかがありなのかもと思いました！

**Comment by Hiroshiba** [comment]
- https://github.com/VOICEVOX/voicevox_core/pull/655

の実装を真似て↓のようにすると良さそうかもです！
```bash
          poetry lock --no-update
          git diff --exit-code
```

結構タスク的に簡単で、Github Actionsの練習にもなる気がするので、要議論を外して初心者歓迎タスクラベルをつけようかなと思います！
