### ISSUE TITLE
`run.py`の`__main__`実装を関数スコープにしたい

### ISSUE THREAD

**Issue by aoirint** [VOICEVOX/voicevox_engine#752]
## 内容

`run.py`の`__main__`の実装は、グローバルスコープになっています。

`run.py`の実装が意図しない変数を参照して不具合の原因になる可能性があるため、`main`関数を作成、実装を移動して、ローカルスコープにしたいです。

`__main__`内のグローバルスコープ変数に依存した、`__main__`外のコードがあれば、修正が必要です。

### Pros 良くなる点

- 意図しない変数参照による不具合を防げる
- `generate_app`を再利用しやすくなる

### 実現方法

- `run.py`に`def main() -> None`を追加する
- `__main__`の実装を`main()`関数に移動する
- `__main__`から`main()`関数を呼び出すようにする
- グローバルスコープ変数に依存したコードを修正する

## VOICEVOXのバージョン

0.15 開発版

### 関連Issue

- #501

**Comment by Hiroshiba** [comment]
良いと思います！

かなり多くの行動がグローバル変数に依存してそうな気がするので、実際やってみてちょっと難しそうだったら一旦引き返してちょこちょこ変更していくのもありかもとか思いました！
もし挑戦してくださるならじゃんじゃんプルリクエストいただけると･･･！！！
