### ISSUE TITLE
YAMLファイルの拡張子の表記揺れを統一したい

### ISSUE THREAD

**Issue by aoirint** [VOICEVOX/voicevox_engine#753]
## 内容

YAMLファイルの拡張子に揺れ（`.yaml`、`.yml`）があるので、リポジトリ内で統一したいです。

- `.pre-commit-config.yaml`
- `default_setting.yml`
- `setting.yml`
- `test/setting-test-load-1.yaml`
- `presets.yaml`
- `test/presets-test-1.yaml`

### Pros 良くなる点

- 新しくYAMLファイルを追加するときに命名に迷わなくなる
- 同じスキーマのファイルで表記揺れすることによる混乱が起きにくくなる
- 同じ書式のファイルで表記揺れすることによる混乱が起きにくくなる

### Cons 悪くなる点

- 後方互換性が失われる

### 実現方法

- どちらを採用するか決める
- コーディング規約を追加する

## VOICEVOXのバージョン

0.15 開発版

**Comment by Hiroshiba** [comment]
おっと･･･････これはつらいですね･････。

どちらに寄せるかですが、ユーザー側に影響があるものを優先したいです。
が、まあマイグレーション書けばいいので正直どっちでもと思いました。

前例を調べてたんですが、多く採用されているのはymlとのことでした。
https://github.com/kmuto/review/issues/244
（公式は.yaml派だけどマジョリティは.ymlっぽい）

開発でしか使わないファイルは問答無用で.ymlに書き換えちゃって良さそう。
.yamlになっていてユーザーに影響を与えるファイル（presets.yaml）は、`.yaml`のファイルがあればそちらを、なければ`.yml`を見るようにするのが良さそう？
まあそもそもこのファイルはエンジンを更新すると自動的に破棄されるので、もし実装が難しそうであれば破壊的に変更しちゃっても良いかもと思いました。

今後`.yaml`ファイルが生まれない方法としては･･･`find '*.yaml'`ですかね･･･････。

**Comment by tarepan** [comment]
2023-12-08現在:  

`$ find . -name '*.yaml'`:  

- ./.pre-commit-config.yaml
- ./presets.yaml
- ./test/setting-test-load-2.yaml
- ./test/setting-test-load-3.yaml
- ./test/presets-test-1.yaml
- ./test/presets-test-3.yaml
- ./test/presets-test-2.yaml
- ./test/presets-test-4.yaml
- ./test/setting-test-load-1.yaml

`$ find . -name '*.yml'`:  

- ./default_setting.yml
- ./.github/labeler.yml
- ./.github/workflows/build.yml
- ./.github/workflows/coverage-comment.yml
- ./.github/workflows/typos.yml
- ./.github/workflows/build-docker.yml
- ./.github/workflows/release-test.yml
- ./.github/workflows/labeler.yml
- ./.github/workflows/release-test-docker.yml
- ./.github/workflows/upload-gh-pages.yml
- ./.github/workflows/release_latest_dev.yml
- ./.github/workflows/test.yml

**Comment by tarepan** [comment]
`.pre-commit-config.yaml` → `.pre-commit-config.yml` に変更したところ、以下のエラーが発生しました：  

```
@tarepan ➜ /workspaces/voicevox_engine (refactor/yaml) $ git push origin refactor/yaml
No .pre-commit-config.yaml file was found
- To temporarily silence this, run `PRE_COMMIT_ALLOW_NO_CONFIG=1 git ...`
- To permanently silence this, install pre-commit with the --allow-missing-config option
- To uninstall pre-commit run `pre-commit uninstall`
error: failed to push some refs to 'https://github.com/tarepan/voicevox_engine'
```

公式ドキュメントは .yaml な設定ファイル名になっています：  

> Add a file called .pre-commit-config.yaml to the root of your project.  
> [pre-commit](https://pre-commit.com/)

どうも非サポートのようです。  
https://github.com/pre-commit/pre-commit/issues/702

となると、`.yml` への統一は不可能そうです。  
逆に `.yaml` に寄せる、あるいは統一を諦める、が残る選択肢かと思います。  
どちらの方針でしょうか？

**Comment by Hiroshiba** [comment]
@tarepan なるほどです！！
Github Actionsはなんとなく一旦ymlにしておきつつ、他はよほどのことがない限り`.yaml`統一が良いのかなと思いました！
`default_setting.yml`はマイグレーション特にせずに変更で良いかなと･･･！

**Comment by tarepan** [comment]
> Github Actionsは ... yml ... 他は ... .yaml統一

👍  

PR作成およびコーディング規約集 #799 更新に着手します。
