### ISSUE TITLE
起動時に「cannot load library 'libsndfile.so'」と出て終了する

### ISSUE THREAD

**Issue by mikan-megane** [VOICEVOX/voicevox_engine#770]
## 不具合の内容

arm64環境のdockerでコンテナの起動に失敗する

### 現象・ログ

```
Traceback (most recent call last):
File "/home/user/.local/lib/python3.11/site-packages/soundfile.py", line 161, in <module>
    import _soundfile_data  # ImportError if this doesn't exist
    ^^^^^^^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named '_soundfile_data'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "/home/user/.local/lib/python3.11/site-packages/soundfile.py", line 170, in <module>
    raise OSError('sndfile library not found using ctypes.util.find_library')
OSError: sndfile library not found using ctypes.util.find_library

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "/opt/voicevox_engine/./run.py", line 17, in <module>
    import soundfile
File "/home/user/.local/lib/python3.11/site-packages/soundfile.py", line 192, in <module>
    _snd = _ffi.dlopen(_explicit_libname)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
OSError: cannot load library 'libsndfile.so': libsndfile.so: cannot open shared object file: No such file or directory
```

### 再現手順

(arm64環境で)  
`docker run --rm voicevox/voicevox_engine:cpu-ubuntu20.04-latest`

## VOICEVOXのバージョン

[0.15.0-preview.8](https://github.com/VOICEVOX/voicevox_engine/releases/tag/0.15.0-preview.8) かな…

## OSの種類/ディストリ/バージョン

- [ ] Windows
- [ ] macOS
- [x] Linux

* Ubuntu 22.04.3 LTS
* aarch64

## その他

- #747 に関連している気がする
- amd64環境ではエラーなく起動することを確認

**Comment by Hiroshiba** [comment]
おっとなるほどです！！　ご報告ありがとうございます！！

仰るとおり #747 関連とみて考えています。手元にarm64 linuxマシンがないので試せませんが･･･。
python環境がある状態で`pip install soundfile==0.12.1`とするとlibsndfile.soも一緒に降ってくるはずなのですが、arm64環境でそれが来てないのではと思っています。
`python-soundfile`内に含まれていそうな`libsndfile.so`をつくる[`libsndfile-binaries`](https://github.com/bastibe/libsndfile-binaries/tree/f1655ba375f306c4b3b179e1fb603d71b50ce179)には`arm64`っぽいものも含まれていそうですが･･･。

とまだ未解決なのですがいったんコメントです！

**Comment by Hiroshiba** [comment]
原因はわかりましたが、さてどうしようかという感じでした。

pythonのwheelがある場合はビルド済みのlibsndfileを含める形になっていそうでしたが、arm64 linuxだけwheelが作られてないようでした。
https://pypi.org/project/soundfile/#files

linux arm64のwheelを作るプルリクが４月に開かれているとこまでわかりました。
https://github.com/bastibe/python-soundfile/pull/382

**Comment by aoirint** [comment]
https://github.com/bastibe/python-soundfile/pull/382 側にプルリクエストの修正策をコメントしてみました。進展なければプルリクエストを引き継ぎたい。

Forkレベルでは、aarch64向けのwheelが作れています（`bastibe/python-soundfile`リポジトリのテストは通過しました）。

- https://github.com/aoirint/python-soundfile/releases/tag/0.12.2.dev2%2Baoirint.addlinuxarm64

**Comment by Hiroshiba** [comment]
おおー！！！素晴らしいと思います！！
返信来ると嬉しいですね。

時間かかりそうなら一旦voicevox orgでビルドの仕組み作って管理したり、liux arm64だけaoirintさんのreleasesのwheelに依存したり、とかもありかも。
まあ特に急ぐ予定はないかなという気持ちです。

**Comment by mikan-megane** [comment]
arm64環境でテストし問題ない事を確認できました！
ありがとうございます。

ワークアラウンド対応との事なので、close判定はお任せいたします…

**Comment by Hiroshiba** [comment]
おお、良かったです！！！

こちら↓に続きのissueを作りました！このissue自体は解決したので、closeさせていただこうと思います！

- https://github.com/VOICEVOX/voicevox_engine/issues/839

@aoirint さん、 @sabonerune さんもありがとうございました！！
