### ISSUE TITLE
audio_queryを編集する方法のサンプルをREADMEに追加する

### ISSUE THREAD

**Issue by Hiroshiba** [VOICEVOX/voicevox_engine#775]
## 内容

VOICEVOXエンジンの音声合成はaudio_queryを叩いて得られたjsonをsynthesizeに投げることで実現されています。
この`audio_query`のパラメータを編集することで音声の速度や高さを変えられるのですが、その方法がREADMEに記載されていません。

このissueはREADMEに案内を追加できたら達成だと思います。

### Pros 良くなる点

出てくる音声を制御する方法がREADMEを読んだだけでわかるようになる

### 実現方法

`audio_query`を得たあと、音声の速度を変えてから`synthesize`に投げる例があると良さそう。
場所は`HTTP リクエストで音声合成するサンプルコード`の下あたりに追加とか？

**Comment by tarepan** [comment]
着手しました。
