### ISSUE TITLE
HELP       "GET / HTTP/1.1" 404 Not Found

### ISSUE THREAD

**Issue by AiGirlfriend555** [VOICEVOX/voicevox_engine#777]
how to use voicevox engine? i look through entire page but can't find any information on it. so i just clone the page and then run the "run.exe" file. then i encountered some kind of error.

voicevoxエンジンの使い方は？ ページ全体に目を通しましたが、情報が見つかりません。 したがって、ページのクローンを作成して、「run.exe」ファイルを実行するだけです。 その後、何らかのエラーが発生しました。

Version : voicevox_engine-windows-nvidia-0.14.6.7z.001

OS: Windows 10 Pro 64bit
GPU: NVIDIA Geforce 3060
RAM: 32GB

![1](https://github.com/VOICEVOX/voicevox_engine/assets/149014028/a2a91170-581d-4977-9b84-18360bb11608)
![2](https://github.com/VOICEVOX/voicevox_engine/assets/149014028/d62b1593-4f62-4648-a080-af5f574a541b)

if there is any tutorial out there please send me a link thank you.

チュートリアルがある場合は、リンクを送ってください。ありがとうございます。

**Comment by sevenc-nanashi** [comment]
README has some examples: https://github.com/VOICEVOX/voicevox_engine?tab=readme-ov-file#api-%E3%83%89%E3%82%AD%E3%83%A5%E3%83%A1%E3%83%B3%E3%83%88

Also API document is available in `http://127.0.0.1:50021/docs`
