### ISSUE TITLE
`GET /` にポータルページ

### ISSUE THREAD

**Issue by sevenc-nanashi** [VOICEVOX/voicevox_engine#778]
追記: https://github.com/VOICEVOX/voicevox_engine/issues/778#issuecomment-2002448117 に議論結果を集約しています。

## 内容

GET /を踏むと/docsに飛んだら優しいと思いました。

### Pros 良くなる点

優しくなる

### Cons 悪くなる点

ないはず？

### 実現方法

リダイレクトのレスポンスを返せば大丈夫だと思います。

## VOICEVOXのバージョン

0.?.0

## OSの種類/ディストリ/バージョン

- [x] Windows
- [x] macOS
- [x] Linux

## その他

（なし）

**Comment by Hiroshiba** [comment]
設定にアクセスしたい人もいるかもなので、案内ポータルを表示してあげるとかどうでしょう。
README（利用規約）も表示してあげるとより分かりやすいかも。

**Comment by tarepan** [comment]
- `GET /` → `GET /docs` リダイレクト
- `GET /` に新規ポータルページ

の 2 案が提案中と認識しました。  

@Hiroshiba  
本 issue はどちらの方向性を深めていく方針でしょうか？

**Comment by Hiroshiba** [comment]
コメントありがとうございます！

ホームをどう扱うかは現状完全に予測不可能で、リダイレクトさせると将来何か意味を持たせたくなった時に破壊的仕様変更になりそうだと気づきました。
まあさほど問題ないかもですが、逆にリダイレクトしなくてもさほど問題ないので…決定が難しいですね…。

何もしない・リダイレクトどちらでも良さそうで、その実装優先度も非常に低いという感じになりそうです。
PR来たらマージするけど、issue openで建てておくほどではないかなぁという気持ちです。
どっちでも良さそう…！

**Comment by Hiroshiba** [comment]
あ、いや、設定ページが生えたのでリダイレクトよりはポータルのが良いですね。
ポータルが良さそう！
「あった方が良いけどなくても良い」くらいの優先度になりそうです。

**Comment by tarepan** [comment]
## 現状整理 for Future
「`GET /` に新規ポータルページを作成」が望ましいと整理されています。  
ポータルページに設定ページ & API docs へのリンクを入れることで、GUI に馴染んだ ENGINE ユーザーによりフレンドリーな設計となりそうです。  
興味がある方のコントリビュートをお待ちしています！

**Comment by tarepan** [comment]
着手しました。
