### ISSUE TITLE
Refactor: BasePhonemeの単純化

### ISSUE THREAD

**Issue by tarepan** [VOICEVOX/voicevox_engine#779]
## 内容
現在の `BasePhoneme` は `voicevox_engine` 内で未使用な関数（テストのみ）を備えている。以下はそのリスト:   

- [`BasePhoneme.duration()`](https://github.com/VOICEVOX/voicevox_engine/blob/b768811688261d128b4253f755060bb5900abe06/voicevox_engine/acoustic_feature_extractor.py#L63)
- [`BasePhoneme.load_lab_list()`](https://github.com/VOICEVOX/voicevox_engine/blob/b768811688261d128b4253f755060bb5900abe06/voicevox_engine/acoustic_feature_extractor.py#L118)
-  [`BasePhoneme.save_lab_list()`](https://github.com/VOICEVOX/voicevox_engine/blob/b768811688261d128b4253f755060bb5900abe06/voicevox_engine/acoustic_feature_extractor.py#L139)

これら不使用関数の削除によるリファクタリングを提案します。  

### Pros 良くなる点
- コードの見通し改善

### Cons 悪くなる点
- 無し

### 実現方法
- 関数・テストの削除

## VOICEVOXのバージョン

0.14.10

## OSの種類/ディストリ/バージョン

- [x] Windows
- [x] macOS
- [x] Linux

**Comment by Hiroshiba** [comment]
@tarepan 削除が良いと思います！
もしよかったらプルリクエストを頂けますか？

**Comment by tarepan** [comment]
@Hiroshiba 👍

#780 解決後に着手します。
