### ISSUE TITLE
Refactor: `acoustic_feature_extractor.py` の単純化

### ISSUE THREAD

**Issue by tarepan** [VOICEVOX/voicevox_engine#780]
## 内容
現在の `acoustic_feature_extractor.py` は `voicevox_engine` 内で未使用なDict・クラス（テストのみ）を備えている。以下はそのリスト:

- `JvsPhoneme`
- `phoneme_type_to_class`

`JvsPhoneme` に関しては2年前にリファクタリング提案があり、以後進展無し（[the discussion](https://github.com/VOICEVOX/voicevox_engine/pull/153#discussion_r735872782)）。  
これら不使用Dict・クラスの削除によるリファクタリングを提案します。  

### Pros 良くなる点
- コードの見通し改善

### Cons 悪くなる点
- 無し

### 実現方法
- 関数・テストの削除

## VOICEVOXのバージョン

0.14.10

## OSの種類/ディストリ/バージョン

- [x] Windows
- [x] macOS
- [x] Linux

**Comment by Hiroshiba** [comment]
提案ありがとうございます！
削除で良いのかなと思いました！必要になったら再度追加すれば良いかなと。
@tarepan もしよかったらプルリクエスト頂けると！

**Comment by tarepan** [comment]
@Hiroshiba 👍
着手します。
