### ISSUE TITLE
Refactor: `BasePhoneme` の廃止

### ISSUE THREAD

**Issue by tarepan** [VOICEVOX/voicevox_engine#785]
## 内容
要望: `BasePhoneme` 基底クラスの廃止

現在の [`BasePhoneme`](https://github.com/VOICEVOX/voicevox_engine/blob/bad1209e250f7e1ebafaaf5ffb2f22e223fb85b2/voicevox_engine/acoustic_feature_extractor.py#L7) は `OjtPhoneme` のみに継承され、基底クラスとしての役割を持たない。  
2年前に[リファクタリング提案](https://github.com/VOICEVOX/voicevox_engine/pull/153#discussion_r735872782)があり、#779 で一部が解決。  
本リファクタリングによって `BasePhoneme` の利用中全機能を移管可能。  
よって `BasePhoneme` の廃止によるリファクタリングを提案します。  

### Pros 良くなる点
- コード見通し改善

### Cons 悪くなる点
- 無し

### 実現方法
- `BasePhoneme` から `OjtPhoneme` へのメソッド移管
- `BasePhoneme` と対応テストの削除

## VOICEVOXのバージョン

0.14.10

## OSの種類/ディストリ/バージョン

- [x] Windows
- [x] macOS
- [x] Linux

**Comment by Hiroshiba** [comment]
良いのかなと思いました！！
もし必要になったら作り直す感じで･･･！
