### ISSUE TITLE
Remove: `OjtPhoneme.convert()` の廃止

### ISSUE THREAD

**Issue by tarepan** [VOICEVOX/voicevox_engine#786]
## 内容
要望: `OjtPhoneme.convert()` の廃止  

[`OjtPhoneme.convert()`](https://github.com/VOICEVOX/voicevox_engine/blob/bad1209e250f7e1ebafaaf5ffb2f22e223fb85b2/voicevox_engine/acoustic_feature_extractor.py#L138) は音素表現の変換（`sil`→`pau`）を担う関数である。  
`__init__()` ではなく関数として用意されており、任意タイミングの変換が想定されている。  
しかし現在の実装では `OjtPhoneme` がインスタンス化される[唯一の箇所](https://github.com/VOICEVOX/voicevox_engine/blob/bad1209e250f7e1ebafaaf5ffb2f22e223fb85b2/voicevox_engine/synthesis_engine/synthesis_engine.py#L57) の直後で `.convert()` がコールされている。  
すなわち現在のユースケースであれば `__init__()` 内で処理できる。  

また現在の `_synthesis_impl` は `pau` 前提のコードであるため、`sil` にしておけるメリットは無いにも関わらず変換し忘れるデメリットのみが存在している。  

上記の理由より、`OjtPhoneme.convert()` の廃止を提案します。  

### Pros 良くなる点
- コード見通しの改善
- 将来的バグ埋め込みの回避

### Cons 悪くなる点
- （現在未利用の）柔軟性低下

### 実現方法
- `__init__` での `sil`-to-`pau` 変換実装
- `.convert()` の廃止

## VOICEVOXのバージョン

0.14.10

## OSの種類/ディストリ/バージョン

- [x] Windows
- [x] macOS
- [x] Linux

**Comment by Hiroshiba** [comment]
いいですね、消しちゃいましょう！！
