### ISSUE TITLE
Remove: `OjtPhoneme` 特殊Equal廃止

### ISSUE THREAD

**Issue by tarepan** [VOICEVOX/voicevox_engine#787]
## 内容
要望: `OjtPhoneme.__eq__()` の廃止

現在の [`OjtPhoneme`](https://github.com/VOICEVOX/voicevox_engine/blob/bad1209e250f7e1ebafaaf5ffb2f22e223fb85b2/voicevox_engine/acoustic_feature_extractor.py#L73) は built-in関数 `__eq__()` をオーバーライドし特殊なEqualチェックをおこなっている。  
`__eq__()` 内では `.start`/`.end` 属性に基づく判別をおこなっているが、この属性は現在使われていない（placeholder値が代入されるだけ）。また `voicevox_engine` 内でもこの特殊Equalを生かした操作は現在実装されていない。  

一方で特殊Equalは検索が不可能である。メソッドと異なり、`OjtPhoneme` のインスタンスがEqualチェックされている箇所を一発で検索することはできない（インスタンス名の自由度、 `==` や `in` など多数の演算子）。  
結果として `OjtPhoneme` 変更の影響範囲把握が著しく困難になり、リファクタリング含む変更を阻害している。  

上記の理由より、`OjtPhoneme.__eq__()` の廃止を提案します。  

（本issue/PRは影響しうる範囲が広く変更リスクが高いため、`OjtPhoneme.__eq__()` 廃止に焦点を絞り、廃止後のリファクタリングは別に行う予定です。）  

### Pros 良くなる点
- 複雑性の低減
- 変更容易性の向上

### Cons 悪くなる点
- （未使用の）機能性低下

### 実現方法
-  `OjtPhoneme.__eq__()` の削除

## VOICEVOXのバージョン

0.14.10

## OSの種類/ディストリ/バージョン
- [x] Windows
- [x] macOS
- [x] Linux

## その他
廃止の影響範囲確認が非常に煩雑かつ重要であるため、pull request時のコメントにて影響範囲一覧（と機能的影響がない証明）を付記する予定です。

**Comment by Hiroshiba** [comment]
提案ありがとうございます！

演算子のオーバーロードは確かに検索性が良くないので、結構な恩恵が受けられる時のみ実装するのが良いのかなと感じました！
明確な比較が必要な時は別途関数を定義したり、その都度プロパティの比較をした方が分かりやすいのかなと。
（この辺に関してベストプラクティスを探してみたのですが、特に資料は見つかりませんでした）

なので`__eq__`を廃止する方針が良いのかなと思いました！！

**Comment by tarepan** [comment]
👍  
#788 解決後に着手します。
