### ISSUE TITLE
Refactor: `split_mora()` の分割

### ISSUE THREAD

**Issue by tarepan** [VOICEVOX/voicevox_engine#792]
## 内容
要望: `split_mora()` 関数の二分割によるリファクタリング

モーラを音素に分割する `split_mora()` 関数は現在、以下の3箇所で利用されている。  

https://github.com/VOICEVOX/voicevox_engine/blob/38be022f5ecd9b2cc942881369a77a03531e2c3a/voicevox_engine/synthesis_engine/synthesis_engine.py#L191

https://github.com/VOICEVOX/voicevox_engine/blob/38be022f5ecd9b2cc942881369a77a03531e2c3a/voicevox_engine/synthesis_engine/synthesis_engine.py#L310

https://github.com/VOICEVOX/voicevox_engine/blob/38be022f5ecd9b2cc942881369a77a03531e2c3a/voicevox_engine/synthesis_engine/synthesis_engine.py#L435-L439

このように、2/3のユースケースでは `vowel_indexes_data` 返り値のみを利用している。  

`split_mora()` 内部では早期に `vowel_indexes_data` を計算しており、これを取り出すだけなら以後の全演算が不要である。  

https://github.com/VOICEVOX/voicevox_engine/blob/38be022f5ecd9b2cc942881369a77a03531e2c3a/voicevox_engine/synthesis_engine/synthesis_engine.py#L83-L86

また `split_mora()` という関数名から母音インデックス取り出しを想起することは難しい。  

上記の理由から母音インデックス取り出し関数の切り出しによるリファクタリングを提案します。  

### Pros 良くなる点
- 不要コード実行の排除による実行速度の向上
- 関数名変更による可読性の向上

### Cons 悪くなる点
- 無し

### 実現方法
- `_find_vowel_indexes()` 関数への機能切り出し

## VOICEVOXのバージョン
0.14.10

## OSの種類/ディストリ/バージョン
- [x] Windows
- [x] macOS
- [x] Linux

**Comment by Hiroshiba** [comment]
提案ありがとうございます！　方針として良いのかなと思いました！！

**Comment by tarepan** [comment]
👍  
#790 に依存しているため、当該PRマージ後に着手します。
