### ISSUE TITLE
Refactor: Coreロードの型付け・変数名

### ISSUE THREAD

**Issue by tarepan** [VOICEVOX/voicevox_engine#804]
## 内容
要望: Coreロード関連コードの型改善・変数名変更によるリファクタリング  

現在の [`core_wrapper.py`](https://github.com/VOICEVOX/voicevox_engine/blob/master/voicevox_engine/synthesis_engine/core_wrapper.py) は様々なversionのコアを読み込むための歴史的コードが積み重なっている。  
それらの多くが `Literal` 型で表現できる型を `str` 型で表現しており、可読性に改善の余地がある。  
また入れ子の関数が全て非ローカル関数（`_xxx()`）で命名されており、全体像の把握に手間がかかる。  

これらの問題を解決するために、Coreロード関連コードの型改善・変数名変更によるリファクタリングを提案します。  

### Pros 良くなる点
- 厳密な型（`str` → `Literal`）による安全性
- ローカル/非ローカル命名による見通し改善

### Cons 悪くなる点
- 無し

### 実現方法
- 型付け
- 変数名変更

## VOICEVOXのバージョン
0.14.10

## OSの種類/ディストリ/バージョン
- [x] Windows
- [x] macOS
- [x] Linux

## その他
先行して draft PR を作成しました（#805）。変更概要の理解にご利用ください。
  
着手承認後に正式PR化します。

**Comment by Hiroshiba** [comment]
良さそうに思いました！　理解の助けになるのでどんどん型付けしたいです。
正式PRにしていただければ…！

**Comment by tarepan** [comment]
着手しました。
