### ISSUE TITLE
Refactor: `.mutex` の `SynthesisEngine` → `CoreWrapper` 移植

### ISSUE THREAD

**Issue by tarepan** [VOICEVOX/voicevox_engine#809]
## 内容
要望: `.mutex` の `SynthesisEngine` → `CoreWrapper` 移植によるリファクタリング  

現在の `SynthesisEngine` は `.mutex` 属性を用いてマルチスレッディングを制御している。  
https://github.com/VOICEVOX/voicevox_engine/blob/dbb40f26288b40f06baec692a0b84b214620ce8c/voicevox_engine/synthesis_engine/synthesis_engine.py#L210

制御箇所は4箇所あり、全て `self.core.X()` すなわちCoreDLL呼び出しに関連した関数を制御している。  

https://github.com/VOICEVOX/voicevox_engine/blob/dbb40f26288b40f06baec692a0b84b214620ce8c/voicevox_engine/synthesis_engine/synthesis_engine.py#L227-L232
https://github.com/VOICEVOX/voicevox_engine/blob/dbb40f26288b40f06baec692a0b84b214620ce8c/voicevox_engine/synthesis_engine/synthesis_engine.py#L272-L273
https://github.com/VOICEVOX/voicevox_engine/blob/dbb40f26288b40f06baec692a0b84b214620ce8c/voicevox_engine/synthesis_engine/synthesis_engine.py#L409-L410
https://github.com/VOICEVOX/voicevox_engine/blob/dbb40f26288b40f06baec692a0b84b214620ce8c/voicevox_engine/synthesis_engine/synthesis_engine.py#L458-L459

このとき1つの `SynthesisEngine` インスタンスは1つの `CoreWrapper` と1:1対応している。  
ゆえに `.mutex` はそのどちらに持たせても問題ない。  
またマルチスレッディング制御はCoreの都合で必要とされているため、`CoreWrapper` 内で管理する方が直感的である。  
そしてCore管理機能を `CoreWrapper` 移すことで `SynthesisEngine` の役割がより明確になる。  

上記の理由より、`.mutex` の `SynthesisEngine` → `CoreWrapper` 移植によるリファクタリングを提案します。  

### Pros 良くなる点
- 機能的凝集による見通しの改善

### Cons 悪くなる点
- 無し

### 実現方法
- `.mutex` の移植

## VOICEVOXのバージョン
0.14.10

## OSの種類/ディストリ/バージョン
- [x] Windows
- [x] macOS
- [x] Linux

**Comment by Hiroshiba** [comment]
提案ありがとうございます！
言われてみれば同期処理にしたい対象はコアなので、CoreWrapperにある形の方が適切に感じました。
（なんで当時気づかなかったんだろう、くらいの気持ちです。）

- https://github.com/VOICEVOX/voicevox_engine/pull/428

**Comment by tarepan** [comment]
👍  
着手します。
