### ISSUE TITLE
AquesTalk風記法定義参照

### ISSUE THREAD

**Issue by tarepan** [VOICEVOX/voicevox_engine#816]
## 質問の内容
質問概要：**「AquesTalk風記法」の定義として参照すべき単一ソースはどこか**  

*AquesTalk風記法* は VOICEVOX で定義・利用される音声テキスト記法である。  
この記法は Frontend / Engine / Core に横断して利用されており、各所に記法に関する注釈が存在している。  
各注釈では「定義・詳細はこのリンクへ」という形式ではなく、各所で（その場に必要な）部分的説明がなされている。  

例:  
https://github.com/VOICEVOX/voicevox_engine/blob/16845ab63210c6e1e3e805ab673065798885c043/README.md?plain=1#L58-L61

https://github.com/VOICEVOX/voicevox/blob/37d52de4647b7e19bbac7d42cde06deb295c5050/src/openapi/apis/DefaultApi.ts#L826

これを踏まえて次の質問があります。  

- Q1. **「AquesTalk風記法」の定義文章はありますか？**
- Q2. **「記法詳細はこちら」に利用可能な、静的かつ安定的な参照先は存在しますか？**

## VOICEVOXのバージョン
0.14.10

## OSの種類/ディストリ/バージョン
- [x] Windows
- [x] macOS
- [x] Linux

## 関連issues
- #720

**Comment by Hiroshiba** [comment]
質問ありがとうございます！！

静的リンクはないと思われます。というより表記を完全にまとめた場所もないと思います･･･。なので

> Q1. 「AquesTalk風記法」の定義文章はありますか？
> Q2. 「記法詳細はこちら」に利用可能な、静的かつ安定的な参照先は存在しますか？

どちらも現状なさそうです。。

書くべきだと感じました。
一旦になってしまうかもですが、エンジンのREADMEに書くのが一番適してるのかなと思いました。
あるいはAPIドキュメント内に書けたらかっこよさそうですが、ちょっと詳しくない感じです！

**Comment by tarepan** [comment]
> どちらも現状なさそう  

把握しました。  

> 一旦になってしまうかもですが、エンジンのREADMEに書くのが一番適してるのかなと

ユーザー向けドキュメントとしてREADMEを（一旦）案内するのには賛成です。  

エンジニア向けに（例えばコードコメントとして）「詳細はココ見ろ」と書ける場所/リンクがあると有難いです。  
READMEだとREADME編集時の節名称変更等でURLが飛んでしまうのでちょっと不向きです。  

「AquesTalk風記法詳細」という issue で（一旦）管理するのはどうでしょうか？  
議論用ではなく、現行の口語的定義・仕様詳細・参照すべきコード指定などを周知するためのissue、という形です。  
GitHubのissueは静的（リンクが切れない）ので、サッと作って暫く使うのに向くと考えます。  
もしこれを採用するなら、メンテナさんが `voicevox_project` レポあたりに置くのが丸いと思います。

**Comment by Hiroshiba** [comment]
なるほどです！　とりあえずissueを作るのが丸いのかなと思いました！

`project`のissueはプロジェクトを作ることに使っているので、候補としてはエンジンのissue・`.github`のissue・新しくドキュメント用のリポジトリを作ってそこのissueあたりが検討対象になりそうかなと！
とりあえず需要が発生しているのがエンジンなのでここにissueを作り、将来移動が必要になったらtransfer issueするとかが良いのかなと思いました！

そしてすみません、定義文章はあげられているREADMEの箇所に書かれていました。。

https://github.com/VOICEVOX/voicevox_engine/blob/16845ab63210c6e1e3e805ab673065798885c043/README.md?plain=1#L58-L65

なのでこちらを転記したissueを作ることになりそうです。
（長いけどこのパーマネントリンクでもいいのかも？とちょっとだけ思いました）

**Comment by tarepan** [comment]
> 定義文章はあげられているREADMEの箇所に  

把握しました。  

> このパーマネントリンクでも

READMEに `### AquesTalk風記法` 独立節を作るのはどうでしょうか？  
現在はサンプルコード内の記述として混在しているため安定性が低いですが、独立節とすれば変更に強くなります。  
幸い #818 で記法正式名がfixしたため、節名称自体は暫く不変で安定になるはずです。

**Comment by Hiroshiba** [comment]
こちらに関してですが、特にどちらにしてもそう問題はないので、とりあえずREADMEに追記して、必要に応じてリンクする形で良いのかなと思いました！！
