### ISSUE TITLE
Refactor: `CoreWrapper` 責務範囲明確化とディレクトリ移動

### ISSUE THREAD

**Issue by tarepan** [VOICEVOX/voicevox_engine#825]
## 内容
要望: `CoreWrapper` 責務範囲の明確化とディレクトリ移動によるリファクタリング  

提案背景issues:  

- #823
- #824

現在の `CoreWrapper` は `voicevox_engine/synthesis_engine/core_wrapper.py` で定義されている。  
`/synthesis_engine` は音声合成に関わるサブモジュールであり、`CoreWrapper` の責務が合成関係であることを示唆する。  

しかし現在の `CoreWrapper` は実態として音声合成以外の機能（例: style load、supported device）も担っており、`CoreWrapper` の責務範囲は単なる合成でなく「Core機能一般の提供」に見える。  

このような背景から次の質問があります：
Q. 「`CoreWrapper` の責務範囲は "VOICEVOX CORE の機能一般をEngineへ提供する"」であるか否か

この質問がYESの場合、`synthesis_engine/core_wrapper.py` のディレクトリ変更によるリファクタリングを提案します。  

### その他
本 issue が解決したのち、`CoreWrapper` の責務タイプ（CoreDLLラッパ、Engine向けCoreマネジメント隠蔽）を別issueで議論できればと思います。  

### Pros 良くなる点
- 責務の明確化によるメンテ性向上
- 責務とモジュール構造の一致による見通し改善

### Cons 悪くなる点
- 無し

### 実現方法
- ディレクトリ変更

## VOICEVOXのバージョン
0.14.10

## OSの種類/ディストリ/バージョン
- [x] Windows
- [x] macOS
- [x] Linux

**Comment by Hiroshiba** [comment]
issue作成ありがとうございます！！

> Q. 「CoreWrapper の責務範囲は "VOICEVOX CORE の機能一般をEngineへ提供する"」であるか否か

そんな感じだと思います！　フロントだとAPIクライアントとかが近い概念かなと。
Engineへ提供するのはCoreWrapperの責務じゃないかもです（自信ないです。。）。
[VOICEVOX COREはコアと呼んでるっぽい](https://github.com/VOICEVOX/voicevox_engine#%E9%81%8E%E5%8E%BB%E3%81%AE%E3%83%90%E3%83%BC%E3%82%B8%E3%83%A7%E3%83%B3%E3%81%AE%E3%82%B3%E3%82%A2%E3%82%92%E4%BD%BF%E3%81%86)のと、まあよくあるAPIラッパーであることも添えて、説明は簡素にこんな感じでも良いかも･････？
`コアのラッパー。コアの関数を実行する。`

**Comment by tarepan** [comment]
> Engineへ提供するのはCoreWrapperの責務じゃないかもです  

Engineの存在に関わらず、コアをPythonから呼ぶための独立したラッパー、的なニュアンスで合ってるでしょうか？  
このニュアンスはしっくりきます。

**Comment by Hiroshiba** [comment]
> Engineの存在に関わらず、コアをPythonから呼ぶための独立したラッパー、的なニュアンスで合ってるでしょうか？ このニュアンスはしっくりきます。

そんな感じなのかなと･･･！！

**Comment by tarepan** [comment]
> そんな感じなのかなと･･･！！  

👍  
まとめると「`CoreWrapper` の責務範囲は "VOICEVOX CORE の関数を Pytnon から実行可能にする" である」ですね。  
丁寧にありがとうございました！  

これらの議論に基づいて、以下の新ディレクトリ構造へリファクタリングするPRを作成します：

- `voicevox_engine`
  - `core_wrapper` (ルート直下へ移動)
  - `synthesis_engine`
    - `synthesis_engine_base`
    - ...

## 依存PR一覧
以下のIssues/PRsに依存しているため、これら解決後に着手します：  

- #822
