### ISSUE TITLE
engine_rootのパスに関する問題

### ISSUE THREAD

**Issue by sabonerune** [VOICEVOX/voicevox_engine#828]
## 内容

engine_rootの取得コードは次のようになっています。
https://github.com/VOICEVOX/voicevox_engine/blob/92c8211b6882fc0e4ecdcb5a1dc7d60024a45e8a/voicevox_engine/utility/path_utility.py#L9-L17
しかしこのコードには以下の問題があります。

1. [PyInstallerのマニュアル](https://pyinstaller.org/en/stable/runtime-information.html)にはシンボリックリンクから起動した場合`sys.argv[0]`にはそのシンボリックリンクのパスが入る。(`sys.executable`を使うべき)
2. コンパイルされたコードにはバンドルしたファイルのパスと実行ファイルのパスの2種類のパスがあり、PyInstallerでは前者を`__file__`、後者を`sys.executable`で取得するべきである。

後者に関しては今まではOneDirモードなので`__file__`を使用したパスと`sys.executable`で取得したパスが同じであるため問題が起こりませんでした。

しかしPyInstaller v6では実行ファイルと`_internal`ディレクトリが作成されビルド時にバンドルされるデータは全て`_internal`に保存されるようになるため問題が発生します。
- ref: https://github.com/VOICEVOX/voicevox_engine/pull/765#issue-1943183173

### 実現方法

3つ選択肢があると思います
1. `engine_root`を実行ファイルのあるディレクトリと`_internal`のディレクトリ取得用の関数に分離する。
   - エンジンのディレクトリがとてもすっきりする
   - コードの変更量は多い
2. `engine_root`はそのままに、ファイルの方を実行ファイルのディレクトリに置くようにする。
   - ある程度すっきりする
   - 外部から参照されることを基本的に想定していないファイルが中途半端に露出する
3. `_internal`ディレクトリを生成しない(v5と同じ)設定でv6に更新する

## その他

開発用途(`--voicevox_dir`のため)一見`_internal`に置くべきに見える`speaker_info`やdll等を外に置くべきかもしれないことが若干気になる。

`_internal`のディレクトリ名は変更可能です。

Nuitkaは実行ファイルの場所は`sys.argv[0]`、バンドルしたファイルは`__file__`を使用して取得するように案内されています。
https://nuitka.net/doc/user-manual.html#standalone-finding-files

**Comment by Hiroshiba** [comment]
せっかくなので、調査したてで情報の整理がついているうちにPyinstallerのメジャーバージョンアップをしても良いかもとちょっと思いました。
もしご興味あれば、是非！！！

（ちょっとエンジンの0.15アップデートが近そうで、もしかしたら0.15からは外す、みたいな判断をさせていただくことになるかもしれませんが 🙇 ）

**Comment by Hiroshiba** [comment]
あ、共有ライブラリは実行ファイルと同じディレクトリに置いておかないとうまく起動しないかもですね！
`licenses.json`も目立った位置にあったほうが良いのでrootのが良いかなと思いました。
`speaker_info`は･･･まあ`--voicevox_dir`の関係上、共有ライブラリと同じとこのが嬉しい気がしますねぇ。

･･･VOICEVOX用のファイルは全部実行ディレクトリ直下（run.exeがあるとこ）に置いて、pyinstallerやpythonやpythonライブラリが必要とするものを`_internal`（か`engine_internal`）に配置するのもありな気がしてきました。
考えることを少なくできそうですが、どうでしょうか。（あまり深く考えずに提案しています）

**Comment by Hiroshiba** [comment]
ありがとうございます！！
