### ISSUE TITLE
Remove: `OjtPhoneme` 単純化

### ISSUE THREAD

**Issue by tarepan** [VOICEVOX/voicevox_engine#829]
## 内容
要望: `OjtPhoneme` クラス変数と一部テストの廃止による単純化

現在の `OjtPhoneme` は以下のクラス変数を持つ：  

- `phoneme_list`
- `num_phoneme`
- `space_phoneme`

これら3属性はコアへ渡される特徴量の形式を決定する属性であり、***決して***変更されてはならない。  
しかし現在の `OjtPhoneme` はこれら3属性をパブリッククラス変数として公開しており、意図しない変更によるバグが起きうる。  

よって、1点目として、`phoneme_list` / `num_phoneme` / `space_phoneme` のプライベート変数化を提案します。  

またこれら3属性に関わるテストが存在する。  
その一部は（決して変更されない）3属性の値をテストしている。  

この背景に基づいて次の質問があります：

Q: これら定数テストはどのような意図でしょうか？   
https://github.com/VOICEVOX/voicevox_engine/blob/f8d6acf0f96ff0a2bf80e4956f673234777a2496/test/test_acoustic_feature_extractor.py#L13-L18
https://github.com/VOICEVOX/voicevox_engine/blob/f8d6acf0f96ff0a2bf80e4956f673234777a2496/test/test_acoustic_feature_extractor.py#L20-L23

もし当初の意図が現在は自然と達成されているなら、これらテストの廃止による単純化を提案します。  

### Pros 良くなる点
- 潜在的バグ源の事前潰し
- テスト単純化によるメンテコスト低減

### Cons 悪くなる点
- 無し

### 実現方法
- `phoneme_list`: モジュール定数 `_PHONEME_LIST` に切り出し、`__init__()` 内でプライベート変数に紐付け
- `num_phoneme`: モジュール定数 `_NUM_PHONEME` に切り出し、`__init__()` 内でプライベート変数に紐付け
- `__init__()` 内の文字列化、変数として廃止

## VOICEVOXのバージョン
0.14.10

## OSの種類/ディストリ/バージョン
- [x] Windows
- [x] macOS
- [x] Linux

**Comment by Hiroshiba** [comment]
プライベート変数化、良いと思います！！

> Q: これら定数テストはどのような意図でしょうか？

これらの値が変わっても他の全てのテストは通るかもしれませんが、実際に音声合成しようとするとコアとの兼ね合いで正しく実行できないので、コード変更によりこれらの値が変わってないことを保証するテストなのかなと思いました！
テスト実装に明るくないので、このようなテストが一般的なのかどうかちょっと自信ないです･･･！

**Comment by tarepan** [comment]
> プライベート変数化、良いと思います！！

👍  

> コード変更によりこれらの値が変わってないことを保証するテスト  

開発者が `phoneme_list` 等の変更をcommitしていないことの保証ですね、なるほどです。  
であればテストには引き続き頑張ってもらう（廃止無し）方向でPRを作ります。  

## 依存PR一覧
以下のIssues/PRsに依存しているため、これら解決後に着手します：

- #822
