### ISSUE TITLE
Refactor: コアCDLL型付けの切り出し

### ISSUE THREAD

**Issue by tarepan** [VOICEVOX/voicevox_engine#842]
## 内容
要望: コアCDLL型付けの切り出しによるリファクタリング  

`CoreWrapper` は CDLL 型付け（引数・返り値型指定）をおこなっている。  
このコードはプリミティブであり、「メソッド1つに型をつける」という目的に10行ほどのコードが必要である。  
結果として `CoreWrapper` は煩雑化・肥大化している。  

よってメソッドごとに型付け関数を切り出すリファクタリングを提案します。  
PRを作成した (#843) ので可否判断材料にご利用ください。  

### Pros 良くなる点
- 単一メソッドに関する型付け集約による見通し改善
- `CoreWrapper` スリム化による見通し改善

### Cons 悪くなる点
- 無し

### 実現方法
- 関数に切り出し

## VOICEVOXのバージョン
0.14.10

## OSの種類/ディストリ/バージョン
- [x] Windows
- [x] macOS
- [x] Linux

**Comment by Hiroshiba** [comment]
なるほどです！　プルリクエストの方にコメントさせていただきました！！
