### ISSUE TITLE
話者メタ情報がエンジンとコアに跨がる理由

### ISSUE THREAD

**Issue by tarepan** [VOICEVOX/voicevox_engine#847]
## 質問の内容
概要: 話者メタ情報がエンジンとコアに分散している理由が知りたい

現在の `voicevox_engine` は `MetasStore` を通じて話者メタ情報（`Speaker` インスタンス）を管理している。  
`Speaker` は `EngineSpeaker` と `CoreSpeaker` からなり、前者の情報はエンジン内の `/speaker_info/{uuid}/metas.json` から、後者はコアDLLの `.metas()` から取得されている。  

https://github.com/VOICEVOX/voicevox_engine/blob/5d7562c51364e4672462f5110c4c87e1a8eaf145/voicevox_engine/metas/MetasStore.py#L21-L22

https://github.com/VOICEVOX/voicevox_engine/blob/5d7562c51364e4672462f5110c4c87e1a8eaf145/voicevox_engine/synthesis_engine/synthesis_engine.py#L389

現在の `EngineSpeaker` は「モーフィング許諾」メタ情報を、現在の `CoreSpeaker` は「話者/スタイルの名称とID」メタ情報を保持している。  
これらは一見するとどちらの情報もスタイル固有であり、エンジン**あるいは**コアに統一して持つことが可能に見える。  

このような背景から以下の質問があります：  

Q: ***話者メタ情報がエンジンとコアに分散している理由は何か***  

（歴史的経緯等色々有ると想像しています。）  

将来的に統一できれば `MetasStore` や関連設定ファイルの廃止（後方互換性用のみのメンテ）が可能であるため、理由を教えていただければ幸いです。  

## VOICEVOXのバージョン
0.14.10

## OSの種類/ディストリ/バージョン
- [x] Windows
- [x] macOS
- [x] Linux

**Comment by Hiroshiba** [comment]
質問ありがとうございます！！　この辺りドキュメントにまとめたいと思いつつ、まとめられてなかったです 🙇 

歴史的背景があるのもちろんなのですが、画像データなど重いファイルをコア側に持たせていないというのも主要因の１つです。
詳しくお答えします！

まず歴史的背景ですが、もともとエディター内とコア内のみに話者情報がありました。
コア側はID情報程度しか持ってなくて、それ以外のエディタ側にあり、やっぱコア側に移したいよねということで徐々に移動している最中です。

それでも情報が分かれている理由がいくつかありそうです。

* 画像データなどの重たいファイルをコア側に移すべきかどうかの判断を保留していた
	* この辺りは最近コア側のモデル＋話者情報（VVMファイル）を別ファイルにできるようになったので、そこに画像データを置くことが将来できるかもしれません
* モーフィング機能はコアにないのでエンジンが情報を持っている
* 単純に優先度がそこまで高くない関係で利用規約情報などが移行しきれてない
	* ちなみにコア側のREADMEに利用規約が書かれています（データ構造化されていない）

さらに聞きたいことがあれば何でも聞いてください･･･！

**Comment by tarepan** [comment]
とても丁寧にありがとうございます！  

「大きな流れとして話者メタ情報はコアへ移植されていってる。各要素にそれぞれ固有事情がある」ということですね。  

> モーフィング機能はコアにないのでエンジンが情報を持っている  

「声質の同一性保持権」に関する許諾情報っぽいので、機能有無に関わらず、音声モデル利用規約の一部とみなせそう。そうするとコア側が持つべき…？ とぼんやり思いました。  

メタ情報移植の実装するタイミングでより具体的な議論ができればと思います。  
ありがとうございました🙏
