### ISSUE TITLE
整理: `default_setting.yaml` の廃止

### ISSUE THREAD

**Issue by tarepan** [VOICEVOX/voicevox_engine#848]
## 内容
要望: `default_setting.yaml` の廃止によるリファクタリング  

`default_setting.yaml` はユーザー設定ファイルが存在しない場合のみにフォールバックとして読み込まれるファイルである。  

https://github.com/VOICEVOX/voicevox_engine/blob/5d7562c51364e4672462f5110c4c87e1a8eaf145/voicevox_engine/setting/SettingLoader.py#L17-L20

このフォールバックのためにビルド過程でファイルコピー等をおこなっており、メンテに配慮が必要である。  

https://github.com/VOICEVOX/voicevox_engine/blob/5d7562c51364e4672462f5110c4c87e1a8eaf145/Dockerfile#L230

フォールバック用の値は固定値であるため、コード内にハードコードすることでも同じ効果が得られる。  
`default_setting.yaml` として切り出しておくと「フォールバック挙動の変更」が可能にはなるが、この用途では（おそらく）利用されていない。  

よって、`default_setting.yaml` の廃止によるリファクタリングを提案します。  

### Pros 良くなる点
- ビルド過程の単純化によるメンテ性向上
- `SettingLoader` とデフォルト値の近接配置による見通しの改善

### Cons 悪くなる点
- （不使用の）柔軟性低下

### 実現方法
- `default_setting.yaml` の廃止
- `SettingLoader` におけるデフォルト値 `Setting` の用意

## VOICEVOXのバージョン
0.14.10

## OSの種類/ディストリ/バージョン
- [x] Windows
- [x] macOS
- [x] Linux

**Comment by Hiroshiba** [comment]
issue作成ありがとうございます！！

言われてみればデフォルト値をコードに書く流れで問題なさそうに感じました！
ビルドや起動コマンドは簡潔にしておきたいですね！

歴史を見てみた感じ、もともとsetting.ymlとしてユーザー保存の設定値をこのファイルで管理しようとしていたのを、ただのデフォルト値とするようになった雰囲気でした。
https://github.com/VOICEVOX/voicevox_engine/pull/531#discussion_r1056979818
導入目的から考えても、コード内に書いちゃう形で問題なさそうな気がします！

**Comment by tarepan** [comment]
👍  
着手します。
