### ISSUE TITLE
Refactor: AquesTalk風記法パーサーの文法規則コメント

### ISSUE THREAD

**Issue by tarepan** [VOICEVOX/voicevox_engine#850]
## 内容
(必要性議論済み: [#817 comments](https://github.com/VOICEVOX/voicevox_engine/pull/817#issuecomment-1848284590))  

要望: AquesTalk風記法パーサーのコードコメントにパース規則を追加してリファクタリング

AquesTalk風記法テキストはその文法規則に基づきパーサーによって処理される。  
パーサー実装のコードコメントに文法規則との対応付けがあれば、規則の実装としてのコードが見通しよくなる。  

よってAquesTalk風記法パーサーのコードコメントにパース規則を追加するリファクタリングを提案します。  

### Pros 良くなる点
- 規則-実装対応の明示によるコード見通しの改善

### Cons 悪くなる点
- 無し

### 実現方法
- コメントの追加

## VOICEVOXのバージョン
0.14.10

## OSの種類/ディストリ/バージョン
- [x] Windows
- [x] macOS
- [x] Linux

**Comment by Hiroshiba** [comment]
読みやすくなるのであれば良いのかなと思いました！！
