### ISSUE TITLE
Add: 「音声合成クエリ」相当のドメイン用語定義

### ISSUE THREAD

**Issue by tarepan** [VOICEVOX/voicevox_engine#853]
## 内容
要望: 「音声合成クエリ」相当のドメイン用語定義を追加

「音声合成クエリ」はエンジンの中核を担う概念であり、かつVOICEVOX独自用語である。  

#775 の着手にあたって本語の利用を調査したところ、以下のように多様な表現で呼ばれていた：  

- 音声合成クエリ
- 音声合成用のクエリ
- クエリ
- `audio_query`
- `AudioQuery`
- `/audio_query`のレスポンス

中核概念の表記揺れはユーザー・開発者双方にとってコミュニケーションエラーの原因となる。  
またこの語は頻出かつ中核概念であり、ドメイン用語を導入する価値がある。  

上記の背景から、「音声合成クエリ」相当のドメイン用語定義追加を提案します。  

### Pros 良くなる点
- 表記揺れ統一によるコミュニケーションコストの低減
- 表記迷いに伴う開発コストの低減

### Cons 悪くなる点
- 無し

### 実現方法
- 統一用語の議論・決定
- 表記揺れの統一

## VOICEVOXのバージョン
0.14.10

**Comment by Hiroshiba** [comment]
issueの作成ありがとうございます！

APIドキュメントで案内している「音声合成用のクエリ」をそのままドメイン用語にするのが丸いのかなと思いました！

ただまだ長いので、コード内で参照する時は`AudioQuery`や`クエリ`でも良いかもとちょっと思いました。
（この辺りコード内での用語まで定めるべきなのかちょっとわからなかったです。。）
