### ISSUE TITLE
mainブランチ更新時に最新版が-devにリリースされていない

### ISSUE THREAD

**Issue by tarepan** [VOICEVOX/voicevox_engine#854]
## 不具合の内容
バグ概要: mainブランチ更新時に最新版が-devにリリースされていない  

#771 より latest 版自動リリースが実装され、現在であれば `0.15-dev` release が master を反映している。  
しかしこの自動リリース機能が機能せず、「3 weeks ago」を最後に更新されていない。  

### 現象・ログ
最新の `0.15-dev` release 更新は「3 weeks ago」だが、2023-12-11現在の master branch 更新は「yesterday」 

[Releases 0.15.0-dev](https://github.com/VOICEVOX/voicevox_engine/releases/tag/0.15.0-dev):  
```
0.15.0-dev Pre-release
@github-actions github-actions released this 3 weeks ago
```

master branch:  
```
tarepan
Refactor: frame_per_mora による置き換え (#841)
5d7562c
 · 
yesterday
```

最新 release (3 weeks ago) に紐づいた commit は以下：  
```
mainブランチ更新時に最新版が-devにリリースされるようにする (#771)
```

すなわち、latest 版自動リリース機能が導入されたときから動いていない可能性がある。  

### 再現手順
GitHub Actionsにつき不明

### 期待動作
master latest に基づいた release が `0.15.0-dev` release に反映

## VOICEVOXのバージョン
master branch @2023-12-11

**Comment by sevenc-nanashi** [comment]
APIを叩いてみてみましたが、アセット自体は更新されていそうでした。
```js
  {
    // ...
    "html_url": "https://github.com/VOICEVOX/voicevox_engine/releases/tag/0.15.0-dev",
    "id": 130322953,
    // ...
    "tag_name": "0.15.0-dev",
    "target_commitish": "5d7562c51364e4672462f5110c4c87e1a8eaf145",
    "name": "0.15.0-dev",
    "draft": false,
    "prerelease": true,
    "created_at": "2023-11-20T10:25:14Z",
    "published_at": "2023-11-20T10:40:17Z",
    "assets": [
      {
        // ...
        "name": "voicevox_engine-linux-cpu-0.15.0-dev.7z.txt",
        // ...
        "created_at": "2023-12-09T21:53:02Z",
        "updated_at": "2023-12-09T21:53:03Z",
        "browser_download_url": "https://github.com/VOICEVOX/voicevox_engine/releases/download/0.15.0-dev/voicevox_engine-linux-cpu-0.15.0-dev.7z.txt"
      },
      {
```

（生存確認のために、一応ビルド時のコミットハッシュを説明文に書くとかしてもいいなーとは思いました）

**Comment by tarepan** [comment]
> アセット自体は更新  

なるほど、*Assets* が常に最新に保たれているのですね。  
早とちりしました、お手数かけました。  

## Memo for improvement
更新用workflow: `.github/workflows/release_latest_dev.yml`  

その中で呼ばれているworkflowの、アップロードに関係しそうな箇所  

https://github.com/VOICEVOX/voicevox_engine/blob/5d7562c51364e4672462f5110c4c87e1a8eaf145/.github/workflows/build.yml#L575-L585

**Comment by Hiroshiba** [comment]
まとめありがとうございます！！！

もしかしたらrelease`0.15-dev`が参照しているタグ`0.15-dev`のcommitishが変わってないことが原因かもです！
`ncipollo/release-action`の`commit`引数は、`tag`で指定されたタグがなければそも`commit`のとこにタグを打つという挙動で、リプレイスはしないようでした。
どちらかというと`gh release`の仕様っぽい？

- https://github.com/ncipollo/release-action/issues/31

解決策としては @tarepan さんの仰るようにリリースノートに書くのと、あとは[タグを付け直す方法](https://github.com/Chatterino/chatterino2/pull/4374/files)もありそうでした。
･･･リリースノートが手っ取り早い気がしますね！

**Comment by tarepan** [comment]
## 「タグ付け直しによるリリース更新」の検証
### 背景
GitHub では tag に対して release が紐付けられている。  
ゆえに Release ページの情報は tag が付けられた commit の情報を反映する。  

よって tag を付け直しが Release ページ情報の更新と関係してくる。  
この際、以下の疑問点が浮上する：  

- 古い Release はどうなるのか（孤児release的なものとして残る？ 完全に消える？）
- Assets はどうなるのか（旧 Release のものを引き継ぐ？ 新規で作られる？）
  - 自動生成の `Source code (zip)` の場合
  - メンテナが付与した artifacts の場合

これらの疑問点を解決するために、次の検証をおこなった。  

### 手法
0. `README.md` 生成
1. コンテンツを `commit1` として commit ①、`c1` tag を付与、release 作成
2. コンテンツを `commit2` として commit ②、`c1` tag を-f で付与（付け替え）、release の変動を観察
3. release に手動で artifact (.wavファイル) を追加
4. コンテンツを `commit3` として commit ③、`c1` tag を-f で付与（付け替え）、release の変動を観察

すなわち tag 打ち直しによる release の変化を観察した。  

レポジトリ: https://github.com/tarepan/NightlyRelease

### 結果
step2 の後、release が1つだけ存在した。tag は `c1` であり、commit番号は②であった。  
すなわち孤児 release 的な存在は生成されず、release の情報が更新された。  

step4 の後、release が1つだけ存在した。tag は `c1` であり、commit番号は③であった。  
Assetsのうち、`Source code` の中身は commit③のものであった。すなわち再生成されていた。    
一方 artifact (.wavファイル）は引き続き存在した。すなわち引き継がれていた。  

### 考察
tag 付け替えをおこなった場合、release の情報が更新され、source codeは再生成され、手動追加した artifact が引き継がれる仕様である可能性が高い。

**Comment by tarepan** [comment]
@Hiroshiba  
貴重な情報ありがとうございます、全面的に参考にしました。  

上記の検証の結果、タグ付け直しで所望の動作が得られることを確認しました。  
この方法であれば release 更新日もリフレッシュされるため、`0.15-dev` release がリリース一覧の下へ埋もれてく、的な懸念もなくなります。  
コード量も数行で済みそうなので、この方針でPRを生成したいと考えています。  
どうでしょうか？

**Comment by Hiroshiba** [comment]
良いと思います！！

自動リリースがあるたびに通知がいくようになってしまった場合にこのリポジトリのリリースをチェックしている方々がどう感じるかちょっと読めないかも、くらいでしょうか。
まあそこはやってみて、Discordの通知botあたりが毎回リリース作ってるような動きしてたらちょっと考えるって感じで良いのかなと思いました！
