### ISSUE TITLE
Remove: 辞書ハンドラの未使用引数削除

### ISSUE THREAD

**Issue by tarepan** [VOICEVOX/voicevox_engine#859]
## 内容
要望: 辞書ハンドラの未使用引数を削除する

`user_dict` モジュールには辞書ハンドラが複数存在する。  
これらのハンドラはデフォルト辞書を指定する `default_dict_path` 引数をもつ。  
しかしこの引数は引数として利用されず、常にデフォルト値が代入されている。  

このような背景から、辞書ハンドラの未使用 `default_dict_path` 引数の削除を提案します。   

参考として draft PR (#860) を作成しました。可否判断の参考にご利用ください。

### Pros 良くなる点
- 引数削除による関数利用時の見通し改善
- 引数削除による関数内部の見通し改善

### Cons 悪くなる点
- （不使用の）柔軟性低下

### 実現方法
- 引数の削除

## VOICEVOXのバージョン
0.14.10

## OSの種類/ディストリ/バージョン
- [x] Windows
- [x] macOS
- [x] Linux

**Comment by Hiroshiba** [comment]
おお、なるほどです！使ってないなら消してしまっても良さそうに感じました…！
