### ISSUE TITLE
Refactor: `SynthesisEngine` の分割

### ISSUE THREAD

**Issue by tarepan** [VOICEVOX/voicevox_engine#871]
## 内容
要望: `SynthesisEngine` をコア管理とTTSフローに分離するリファクタリング

現在の `SynthesisEngine` は "合成エンジン" という名称で「コア管理」と「TTSフロー」の役割を果たしている。  

https://github.com/VOICEVOX/voicevox_engine/blob/0769a4d58da7adf00605241ada738419f4350af6/voicevox_engine/synthesis_engine/synthesis_engine.py#L362-L363

コア機能は VOICEVOX ENGINE 全体で利用されることから、`SynthesisEngine` インスタンスはコード全体の広い領域で引き回されている。  
例えば「話者情報を得るために合成エンジンを渡す」コードや

https://github.com/VOICEVOX/voicevox_engine/blob/0769a4d58da7adf00605241ada738419f4350af6/run.py#L773

「合成エンジンからコアの対応デバイスを得る」コードがある。  
https://github.com/VOICEVOX/voicevox_engine/blob/0769a4d58da7adf00605241ada738419f4350af6/run.py#L1165

これらのケースで求められているのはコア管理でありTTSフローではない。  
ゆえに「コアの話者情報を得るためになぜ TTS 関連クラスを渡すのだろう？」といった疑問を生む、非直感的コードとなっている。  
そしてこれらコア管理機能は、 合成エンジンの本質的役割であるTTSフローとは切り分けられる。  

このような背景から、`SynthesisEngine` のうちコア管理部を `CoreEngine` として切り出すリファクタリングを提案します。  

### Pros 良くなる点
- 機能ベース分割によるクラス内での見通し改善
- 分割されたインスタンスの引き回し範囲縮小 → コード全体の見通し改善

### Cons 悪くなる点
- 無し

### 実現方法
影響範囲の大きいリファクタリングになるため、複数ステップ/PRに渡って実現予定。  

方向性: `SynthesisEngine` が現在担っているコア管理機能を別クラスに切り出し

- step1: `CoreEngine` へのコア管理機能切り出し、`SynthesisEngine` 内部での `CoreEngine` 利用
- step2: `run.py` の `get_engine()` に相当する `get_core()` 導入
- step3: コア利用目的の `SynthesisEngine` インスタンスアクセスを `CoreEngine` インスタンスアクセスへ切り替え
- step4: `SynthesisEngine` のコア管理関数廃止

## VOICEVOXのバージョン
0.14.10

## OSの種類/ディストリ/バージョン
- [x] Windows
- [x] macOS
- [x] Linux

## その他
機能切り出し（step 1）のイメージとして draft PR (#872) を作成しました。  
可否判断の参考になれば幸いです。

**Comment by Hiroshiba** [comment]
なるほどです、良さそうに思いました！！
