### ISSUE TITLE
Refactor: `/presets.yaml` デフォルトファイルの廃止

### ISSUE THREAD

**Issue by tarepan** [VOICEVOX/voicevox_engine#876]
## 内容
要望: `/presets.yaml` デフォルトファイルの廃止によるリファクタリング  

現在の VOICEVOX ENGINE はAudioQueryプリセット機能を有する。  
これを司る `PresetManager` では `preset_path` 引数を介してプリセットファイルを指定できる。  
`PresetManager` は「デフォルト値・デフォルト保存先の指定」をこの `preset_path` 引数により実現している。  
具体的なデフォルト値・保存先は `/presets.yaml` である。  

この `/presets.yaml` はファイルであり、ビルドプロセスの中でファイルコピー等を必要とする。  
デフォルト値 DI や保存先変更の観点からファイル方式は妥当な一方、ある程度のメンテコストも生じさせている。  

ここで VOICEVOX ENGINE のプリセットデフォルトに関する要求を考えると、以下の2つが挙げられる：  

- デフォルト値は empty でよい。ただし指定があれば変更可能（DI）
- `presets.yaml` をデフォルト保存先とする。ただし指定があれば変更可能

ここで、この2点であれば「`presets.yaml` の事後生成」でも達成できるとわかる。  
すなわち `preset_path="presets.yaml"` かつ `not Path("presets.yaml").exists()` のとき、empty な `presets.yaml` をPythonで生成すればデフォルト `/presets.yaml` ファイル無しに上記の要件を満たせる。  
これによりデフォルトファイルのメンテコストを削減できる。  

このような背景から、 `presets.yaml` デフォルトファイルの廃止によるリファクタリングを提案します。  

### Pros 良くなる点
- ビルドプロセス簡易化によるメンテコスト削減
- `PresetManager` とデフォルト値の近接配置による見通し改善

### Cons 悪くなる点
- 無し

### 実現方法
- `preset_path="presets.yaml" and not Path("presets.yaml").exists()` 時の empty YAML ファイル生成
- `/presets.yaml` の削除
- ビルドプロセスの簡略化

## VOICEVOXのバージョン
0.14.10

## OSの種類/ディストリ/バージョン
- [x] Windows
- [x] macOS
- [x] Linux

**Comment by Hiroshiba** [comment]
ファイルがある場合は（マルチエンジン作成などで）デフォルトのプリセットを作る時にAPIを叩かなくて良い、というメリットがなくはないですが、ユーザー辞書と同様にAPIでのみ作成可能にするという形でまあ問題ないのかなと思いました！！

機能作ってくださった @takana-v さんのコメントもいただけると心強いです･･･！

**Comment by tarepan** [comment]
> デフォルトのプリセットを作る時にAPIを叩かなくて良い  

なるほど、テンプレートファイルとしての機能ですね。  

> APIでのみ作成可能にするという形にするのが良いのかな  

👍  
直書きの是非（手書きミス誘発、validationするならAPIで作っても変わらない、など）も均衡していると思うので、ファイル無しメリットを優先して「APIへ集約」に賛成です。

**Comment by takana-v** [comment]
昔はAPIが無く、`presets.yaml`ファイルを直接編集することでのみプリセットを編集することができました。
この実装に依存している外部ソフトウェアがあるかもしれないので、変更のアナウンスは必要かと思います。
（恐らく無いとは思いますが...）

**Comment by Hiroshiba** [comment]
> 変更のアナウンスは必要かと思います。
> （恐らく無いとは思いますが...）

おそらく困るサードパーティアプリが１つあるかないかくらいかなと思っています！
エンジンリリース時のリリースノートに書いて案内しようかなと！

**Comment by Hiroshiba** [comment]
あ。デフォルトファイルがあるのは、マルチエンジン対応のエンジンを作る時に少し便利かなと思いました！
こう、キャラクターごとにおすすめのプリセットをエンジン開発者側が用意できる、みたいな。
そう考えると、辞書のデフォルトファイル（default.csv）と同じ扱いにするほうがあっているかもです。
（なので消さない方がいいかも･･･？）

---

ちょっと話がずれますが。。
この辺りのエンジンごとのデフォルト値用のファイルは、ルート直下ではなく`engine_manifest_asset`へ移動する形が合っているのかなとか思いました。
ちょっとビジネスロジックにも絡んできてissueの内容と離れてしまいますが･･･。

**Comment by tarepan** [comment]
> デフォルトファイルがあるのは、マルチエンジン対応のエンジンを作る時に少し便利 ... なので消さない方がいいかも･･･？  

👍  
マルチエンジン開発者のユースケースが具体的に理解できました。確かに意義深そうです。  
そして同時に、このユースケースであれば Python ファイルの方が扱いやすそうです。  
デフォルト値作るためにはYAML文法知るべし、を避けられそうです（私もYAMLよくわからない）。  
`default_presets.py` を作るイメージです。  

> デフォルト値用のファイルは、ルート直下ではなくengine_manifest_assetへ移動する形が合っている  

👍  
同意です。  
別 issue として扱うのも同意です。

**Comment by Hiroshiba** [comment]
@tarepan コメントありがとうございます！！

> そして同時に、このユースケースであれば Python ファイルの方が扱いやすそうです。
デフォルト値作るためにはYAML文法知るべし、を避けられそうです（私もYAMLよくわからない）。
`default_presets.py` を作るイメージです。

なるほどです！　いろんなこと考えるとまあ文字列ファイルの方が良さそうかなと思いました！
（別言語で実装する場合、Pythonのバージョンが変わる場合、任意のコードが書けるのでセキュリティ上の懸念、など）

yamlが難しいというのは確かにと思いました。
今はプリセットは1個だけなので、コピペで作るときにリストの記法を調べないとダメになってますね。。
要素を２つにすればかなりマシになるかなと思いました！

---

@takana-v エンジンマニフェストにプリセットのデフォルト値ファイルを含めるの、設計的に何か懸念点とか思いつかれますか･･･？
辞書ファイルとかもこっちに含めちゃえるよな～と考えてます。

**Comment by takana-v** [comment]
現状のエンジン側のプリセット機能がほぼ使われていないことを考えると、マルチエンジン対応のエンジン製作者にとっての利点も少ないのではと思います。
（せっかくプリセットのデフォルト値ファイルを用意しても使ってもらえないと思います。辞書は形態素解析を行う際にユーザーに使われますが...）
エンジンマニフェストにプリセットのデフォルト値ファイルを追加し、エディタ側から参照できるようになれば、便利だと思います。

また、プリセット周りは複雑であり、ユーザーが混乱することが考えられます。
（エンジンのプリセットを編集する導線が複数存在する・エディタとエンジンのプリセット機能は別である）
- https://github.com/VOICEVOX/voicevox/issues/688

そのことを考えると、ルート直下のプリセットファイルを廃止し、`setting.yml`等と同様に、`%localappdata%\voicevox-engine`内に保存するようにしてもいいのかなと思いました。
（外部ソフトウェアの存在に留意する必要はあると思いますが...）

---

エンジンマニフェストの設計に関しては、あまり自信が無いので、 @aoirint さん辺りの意見を伺いたいです。

**Comment by Hiroshiba** [comment]
@takana-v ありがとうございます！！
確かに保存先がルート直下になってるのは僕も気になってました。破壊的変更になっちゃいますけど、一旦仕方ないということで変更しちゃった方が良さそうに感じました！
（まあissueの内容とは直接関係ないですが）

今のところの意見をまとめるとこんな感じですかね～

* /presets.yamlのデフォルトファイルは廃止で良さそう
* それはそれとして、engine_manifest内にデフォルトファイルを移すのは良さそう
	* まだちょっと自信ない
* それはそれとして、保存先ディレクトリを設定ファイルと同じとこにするのも良さそう

**Comment by tarepan** [comment]
着手しました。

**Comment by Hiroshiba** [comment]
- https://github.com/VOICEVOX/voicevox_engine/pull/1323

がマージされたので、このissueは目標達成に思いました！
なのでクローズで良さそう！

---

少し話が変わりますが、presetsファイルのデフォルトの保存先ディレクトリがエンジンのディレクトリになっている関係で、特定条件で問題になることも分かりました。

- https://github.com/VOICEVOX/voicevox_engine/issues/1478

これは

> 保存先ディレクトリを設定ファイルと同じとこにするのも良さそう

で解決できそうな気がしています。
ということでちょっとissue作ろうと思います！

**Comment by Hiroshiba** [comment]
作りました！

- https://github.com/VOICEVOX/voicevox_engine/issues/1479

ということでこちらのissueはクローズします、ありがとうございました！
