### ISSUE TITLE
__init__.py内での再エクスポートは必要？

### ISSUE THREAD

**Issue by Hiroshiba** [VOICEVOX/voicevox_engine#877]
## 質問の内容

Pythonは`__init__.py`内でそのパッケージ内にある関数やクラスを再度エクスポートする風習があります。
これに関して、再エクスポートするのかしないのか・どっちからインポートするのかなど、実はコードがややこしくなりやすいものだなと感じています。

このライブラリをPyPIで配布するなどの場合は、ユーザーにとって使いやすい形で提供するためこの辺のトリミングだとかを頑張るのも良いと思います。
このリポジトリに関してはエンジンを使うことを主に想定しているので、この辺りの剪定はしない方がむしろ良いのではと少し感じています。

とはいえ、エディターの力を借りずにimportする場合は結構探すのが大変かもしれないので、一箇所からエクスポートされているのは便利かもしれません。
そのあたりの意見を知りたくてissue化してみました。

## その他

（must/should/want/canのshould～wantくらいの気持ちです）

**Comment by tarepan** [comment]
Hiroshiba さんの意見をまとめるとこんな感じでしょうか？  

- 利点
  - exposed クラス減 → パッケージ使いやすさ向上
  - クラス一覧性向上 → 手動 import 時の手間減
- 欠点
  - 記述時に都度import/export判断 → メンテコスト増
  - エンジンfork時に `__init__` 理解必要 → 改変コスト増

これら利点・欠点の内容について同意です。  
追加の欠点として「`__init__` をよく利用するパッケージでは `__init__` 内での hook をよく気にする必要がある」が挙げられます。クラスや関数の動作定義がモジュール外で変わりうるのは気を使います。  

バランスに関しては、利点が目立たず欠点は相変わらず → トータルマイナス、な印象です。  
利点が良く効くのは「エディタ補助無しでパッケージ利用する開発者」というニッチ、欠点が良く効くのは「エディタ活用するコントリビュータ」というメジャー。なのでマイナス寄りかなぁと感じます。

**Comment by Hiroshiba** [comment]
@tarepan ご意見ありがとうございます！！

他にもエンジンの開発に詳しい @takana-v さんや @PickledChair さんや @y-chan さんにご意見いただけると心強いです！
まあそこまで重大なことでもないと思うので、特にご意見なければ消す方向で倒してしまって良いのかなと思っています！

**Comment by PickledChair** [comment]
ちょっと考えてみましたが、特にどちらの方が良いという意見はないです……！　開発側の視点で見ると、再エクスポートの記述ありだとややこしくなることがあるかも、というのは理解できるので、再エクスポート無しにしてしまっても良いと思います。

**Comment by takana-v** [comment]
自分も強い意見はないですね。
PickledChairさんと同じ感じの考えです。
