### ISSUE TITLE
Refactor: OpenJTalkドメインの隔離

### ISSUE THREAD

**Issue by tarepan** [VOICEVOX/voicevox_engine#881]
## 内容
要望: OpenJTalk ドメインをモジュールに隔離してリファクタリング  

現在の VOICEVOX ENGINE は日本語テキストからアクセント句系列を生成するために OpenJTalk を利用する。  
この OpenJTalk は OpenJTalk 特有の Linguistic / Phonetic 表現を有する。  
そのため `model.py` モジュールで定義される VOICEVOX ENGINE ドメインのクラスとは異なる、OpenJTalk ドメインのクラスが定義されている（例: `Utterance`）。  

異なるドメイン同士はモジュールを隔離し、その間をアダプターで結合すると機能的凝集を達成できる。  
しかし現在の `vocevox_engine` は OpenJTalk ドメインのクラスが `tts_engine_base.py` へ漏れ出している。  

https://github.com/VOICEVOX/voicevox_engine/blob/6a2a010c400edae6e9a34f787edf8e0d9847ab4e/voicevox_engine/tts_pipeline/tts_engine_base.py#L273-L276

また漏れ出している状況下で同名クラスが両ドメインに定義されている（例: `full_context_label.Mora` と `model.Mora`）

https://github.com/VOICEVOX/voicevox_engine/blob/6a2a010c400edae6e9a34f787edf8e0d9847ab4e/voicevox_engine/tts_pipeline/full_context_label.py#L107

https://github.com/VOICEVOX/voicevox_engine/blob/6a2a010c400edae6e9a34f787edf8e0d9847ab4e/voicevox_engine/model.py#L10

ゆえに都度ドメインを意識・確認する必要があり、メンテ性に改善の余地がある。  

このような背景から、OpenJTalk ドメインをモジュールに隔離してリファクタリングすることを提案します。  

### Pros 良くなる点
- ドメイン隔離による認知負荷の軽減・メンテ性向上
- 機能的凝集による見通しの改善

### Cons 悪くなる点
- 無し

### 実現方法
コードの移動と改名を伴うため、複数ステップ/PR を経て実現する。  

- step1: `SynthesisEngineBase.create_accent_phrases()` 内のドメインアダプターを関数化・テスト追加
- step2: 新関数・`extract_full_context_label()`呼び出し・関連 utilities の `full_context_label.py` 移植
- step3: OpenJTalk ドメインクラス名の変更（prefix 付与）

## VOICEVOXのバージョン
0.14.10

## OSの種類/ディストリ/バージョン
- [x] Windows
- [x] macOS
- [x] Linux

**Comment by Hiroshiba** [comment]
良さそうに感じました！！

なんとなくですが、OpenJTalk側のMoraとかは`Label`をつけて`MoraLabel`にする手もあるかもと思いました。
PhonemeはPhonemeLabelではなくLabelでも良さそう感もあります。ちょっと自信ないですが。。
（こうしてほしいというより、こういう考え方もあるかも、くらいの温度感です！）

**Comment by tarepan** [comment]
上記 suggest ref #880
