### ISSUE TITLE
`Utterance.phonemes` アクセッサによる属性更新

### ISSUE THREAD

**Issue by tarepan** [VOICEVOX/voicevox_engine#892]
## 質問の内容
概要: `Utterance.phonemes` アクセッサが `.set_context()` を介して属性書き換えをおこなう意図と用途は何か

OpenJTalk 系の最上位コンテナである `Utterance` は内包する `Phoneme` をリストアップする `.phonemes` 属性/アクセッサをもつ。  

https://github.com/VOICEVOX/voicevox_engine/blob/11f080ea0168e6c73574be5f84b7b17d27ead69e/voicevox_engine/tts_pipeline/full_context_label.py#L436-L444

しかし一般的なアクセッサと異なり、`.phonemes` は内包する `Phoneme` の `.contexts` を積極的に書き換えている。  

https://github.com/VOICEVOX/voicevox_engine/blob/11f080ea0168e6c73574be5f84b7b17d27ead69e/voicevox_engine/tts_pipeline/full_context_label.py#L466-L467

そして `Utterance.phonemes` はテスト内（とテスト内でのみ利用される `Utterance.labels` 内）でのみ利用されている。  

つまり、`Utterance` は一般的でない書き換えアクセッサを、テストのために持っているように見える。  

このような背景から以下の質問があります：

Q「***`Utterance.phonemes` アクセッサが `.set_context()` を介して属性書き換えをおこなう意図と用途は何か***」

## VOICEVOXのバージョン
0.14.10

## OSの種類/ディストリ/バージョン
- [x] Windows
- [x] macOS
- [x] Linux

**Comment by Hiroshiba** [comment]
ご質問ありがとうございます！

ちょっと色々調べてみたんですが、一番最初のコミットから残っているコードでした。
そこではエンジンを介さずに直接TTSできるチェック用のPythonスクリプトがあって、そっちだけから利用されていそうでした。
メインがWebAPIAになったあたりでそのスクリプトは消えたのですが、その時に一緒に消さずに残っちゃってたっぽいです！

**Comment by tarepan** [comment]
> 一番最初のコミットから残っている ... チェック用のPythonスクリプトがあって、そっちだけから利用 ... 一緒に消さずに残っちゃってた  

👍  
調査ありがとうございます！  
用途は「当初からチェック/テスト目的」ということですね。  

## `.phonemes` の意図
残る「意図」に関する質問です。  

現在の VOICEVOX ENGINE では `test_full_context_label.py` 内の3箇所で `Utterance.phonemes` アクセッサが現役です。  

①  
https://github.com/VOICEVOX/voicevox_engine/blob/35b7158f8ad0bd521dda999f5c332569d92bb6bd/test/test_full_context_label.py#L343-L348

②  
https://github.com/VOICEVOX/voicevox_engine/blob/35b7158f8ad0bd521dda999f5c332569d92bb6bd/test/test_full_context_label.py#L349

③（間接利用）  
https://github.com/VOICEVOX/voicevox_engine/blob/35b7158f8ad0bd521dda999f5c332569d92bb6bd/test/test_full_context_label.py#L418

①と③の用途・意図は次の様になっていると読み取りました：

- ①
  - 用途: contexts 中の音素一致テスト
  - 意図: `Label` を取り出したい（`.set_context()` で書き換える気がない）
- ①
  - 用途: feature 文字列一致テスト
  - 意図: `Label` を取り出したい（`.set_context()` で書き換える気がない）

② の用途と意図を掴みかねています。  
ここでは `Utterance` から `Label` を取り出しそこからまた `Utterance` を再構築しています。   
以後の行で contexts の値をテストしているんですが、これらテストとこの再構築の繋がりがよくわからないです。  

もし②にも `.set_context()` による書き換えの意図がないなら、`.phoneme` を大幅単純化できます（連鎖的に他クラスも単純化されます）。  
よって②の用途と意図が知りたいです。

**Comment by Hiroshiba** [comment]
ちゃんと想定したcontextになってるかチェックするテストだと思います！
なのでset_contextは意図していないかなと。

phonemesを使いつつset_contextも使いたくなるのは、文章構造やアクセントを変えた時くらいかもです。
昔はそれをフルコンテキストラベルでやるのかエンジン用にAdapterされた中でやるのか方針が定まってなかったのですが、いまは後者で行く方針なので、役割が終わった雰囲気を感じます。

**Comment by tarepan** [comment]
> ちゃんと想定したcontextになってるかチェックするテスト  

- `Utterance.from_phonemes()` がテストしたい対象（正しい contexts を構成できるかテスト）
- そのために入力たる `Phoneme` 系列が必要
- なので `self.utterance_hello_hiho.phonemes` で調達した
- ゆえに `.phonemes` には `.set_context` による変更・更新の意図が無い

で私の認識合っているでしょうか？  

> 文章構造やアクセントを変え ... 昔はそれをフルコンテキストラベルでやるのかエンジン用にAdapterされた中でやるのか方針が定まってなかった

はっきり理解できました。  
確かにフルコンテキストラベル側 (`Utterance` や `Label`) で直接操作する選択肢も有りえたわけですもんね。  

> 役割が終わった雰囲気を感じます  

👍

**Comment by Hiroshiba** [comment]
> > ちゃんと想定したcontextになってるかチェックするテスト
> 
> 私の認識合っているでしょうか？

合っていると思います、同じ認識です！

**Comment by tarepan** [comment]
> 同じ認識です  

👍  
`Utterance.phonemes` アクセッサ内の `.set_context()` は役割を終えたとし、`Utterance.phonemes` 内から削除する方針で（影響を精査しつつ）PR 作成します。
