### ISSUE TITLE
Refactor: `.test_synthesis` 重複テストの削除

### ISSUE THREAD

**Issue by tarepan** [VOICEVOX/voicevox_engine#899]
## 内容
要望: `test_synthesis_engine.py` 重複テストの削除によるリファクタリング

`test_synthesis_engine.py` には波形合成のテストとして `.test_synthesis()` が存在する。  
このテストは一般的な入出力テストではなく、`SynthesisEngine._synthesis_impl()` 内部値のテストをおこなっている。  

前提として、`SynthesisEngine._synthesis_impl()` の内部は "preprocess → コア呼び出し → postprocess" の構造を持っている。  
そしてテスト用コアは Mock であり、その出力値に意味はない。  
よって `.test_synthesis()` の入出力テストも意味を持たない。  

この前提に基づいて、（恐らく）`.test_synthesis()` は「preprocess と postprocess だけでもテストしよう」という意図の設計がなされている。  
その証拠として、`.test_synthesis()` ではコアMock を TestSpy として利用しコアへの入力（`decode_args`）をテストしている。  
https://github.com/VOICEVOX/voicevox_engine/blob/35b7158f8ad0bd521dda999f5c332569d92bb6bd/test/test_synthesis_engine.py#L795-L795
（preprocessテストに相当する Spy 値テスト）
https://github.com/VOICEVOX/voicevox_engine/blob/35b7158f8ad0bd521dda999f5c332569d92bb6bd/test/test_synthesis_engine.py#L796-L800

現在、関係者の尽力によって preprocess と postprocess は関数（`query_to_decoder_feature()`・`raw_wave_to_output_wave()`）として切り出されている。  
そして preprocess にはテストがあり、postprocess でも順次テストが追加される予定である。  
よって `.test_synthesis()` の当初設計意図である（あろう）「preprocess と postprocess だけでもテストしよう」は既に達成されている。  

このような背景から、`.test_synthesis()` の削除によるリファクタリングを提案します。  

### Pros 良くなる点
- 重複テスト削除によるメンテ性の（大幅）向上
- 実装-テスト交絡による修正困難バグ (#512) 解消への第一歩

### Cons 悪くなる点
- 無し

### 実現方法
複数ステップを経て実現予定

- step1: preprocess 部の削除
- step2: postprocess 部の削除
- step3: `.test_synthesis` の削除

step1 PR (#900) を作成しました、本 issue の可否判断にご利用ください。  

## VOICEVOXのバージョン
0.14.10

## OSの種類/ディストリ/バージョン
- [x] Windows
- [x] macOS
- [x] Linux

## 依存 issue
step2&3 が以下の issues/PRs に依存：  

- [x] #902

**Comment by Hiroshiba** [comment]
とても難しいのですが、`test_synthesis`をなくしても良い･･･かも？と感じました！
非常に細かい話ですが、説明してみます。

まずテスト内容が重複しているかどうかですが、完全には重複していないと思います。
例えばここで、コアに渡る直前にf0のshapeが変わっています。
https://github.com/VOICEVOX/voicevox_engine/blob/216b40652e23b6510b0bd0285b1551f6db9cd1b3/voicevox_engine/tts_pipeline/tts_engine.py#L655-L655
仮にここをpreprocessに含めた場合も、「コアを叩く時のインターフェースが想定している通りか」をテストしたい場合はspyするしかなさそうに思いました。

そもそもこの辺のコードで何がテストしたいかに立ち返ると、一番大事なのは`.synthesis`の結果が変わらないことだと思います。
この点で言うと「関数に切り出しているpreprocess/postprocessの入出力をチェックする」よりも、「コアの入出力をmockにしてコア入出力及び`.synthesis`の入出力をチェックする」方が目標に合っているかもです。
もっというと「それっぽい結果を返すコアのmockを作って`.synthesis`入出力をチェックする」のが一番目標に近いかもとか思いました。
（テストに対してしっかり知見を持ってるわけではないのでちょっと自信ないですが。。。）

理想論は置いといて今のコードを見てみると、確かに重複部分が目立っていると思います！
ただテストしたい対象が若干ずれているので、どうするのがいいのか分からないなぁというのが本音です。
まあpreprocess/postprocess部分からコアdecode関数部分までの処理はとても短いから`test_synthesis`を消してもいい･･･かも？という気持ちです！

**Comment by tarepan** [comment]
## 理想的テストの在り方

### 入出力テスト
> この辺のコードで何がテストしたいか ... `.synthesis`の結果が変わらないこと  

👍  
同意です。commit を経ても合成結果が一貫していることが最重要だと考えます。  

> コアの入出力をmockにして ... `.synthesis`の入出力をチェック ...  
> 「それっぽい結果を返すコアのmockを作って.synthesisの出力が完全一致するかチェックする」のが一番目標に近い  

👍  
同意です。製品版コアの重さを考えると妥当なアプローチに見えます。  

この手法を取る際の欠点は「テスト整備・メンテのコストが（かなり）高い」点、より具体的には「想定出力を定義するのに高い知識と手間を要するため高コスト」な点です。  
現在の `.synthesis` は出力値へ影響する 9 個のパラメータ（例: `speedScale`）を持ちます。組み合わせ爆発を起こすのでパラメータパターンは絞らざるを得ません。そして絞る（テストを整備する）ためには `.synthesis` の動作を完全に理解できる知識を要します。  
次に「手間」ですが、出力値を決めるには値の手計算とベタ書きが必要です。現在のテスト入力は `"pau k o N n i ch i w a pau h i h o d e s U pau"` なので、大雑把に見積もって 3 [sec] * 24k [Hz] = 72,000 サンプルの値を手計算 & ベタ書きする必要があります。これは…なかなかハードです。  
そしてバグ修正 (例: #512) のたびに手計算し直しコストを払うことになります。つまりメンテコストも高いです。  

値の「正しさ」でなく「不変性」を重視する場合、現 commit での出力値をコピーしてファイル化し、これと比較することは可能だと思います。その場合「現 commit の値が意図通りの出力値である」という保証をどうやってつけるんだ…？という別の問題が出てくるかもです。  

### コア入力テスト
> テスト内容 ... 完全には重複していない ... 「コアを叩く時のインターフェースが想定している通りか」をテスト  

👍  
この保証は preprocess・postprocess の unittest では不可、に同意です。  

一方で、このテストの必要性が私にピンときてません。  
（理想として）入出力テストが導入されている場合、インターフェースを壊すと出力値も壊れるため、入出力テストで十分なように見えます。  
（現行テストには必要、という話でしょうか…？）  

## 現行テストの在り方
> `test_synthesis`をなくしても良い･･･かも？  

👍  

> テストしたい対象が若干ずれているので、どうするのがいいのか分からないなぁというのが本音  

👍  
私も同じ感じです。  

理想的な進行としては  

- 理想的テストの議論をまず確定
- それを先行実装
- その後、現行テストは引退

になると思います。  
かなりヘビーな進行である一方、`.synthesis` が VOICEVOX ENGINE の核心部という点も考えると、やる価値はあると（コントリビュータ的には）思います。  
同時にVOICEVOX 全体の進行等あると思うので、これに取り組むか、現 `test_synthesis` を消してひとまず乗り切るかは、メンテナ判断だと感じます。  
どうしましょうか？

**Comment by Hiroshiba** [comment]
> > テスト内容 ... 完全には重複していない ... 「コアを叩く時のインターフェースが想定している通りか」をテスト
> 
> この保証は preprocess・postprocess の unittest では不可、に同意です。
> 一方で、このテストの必要性が私にピンときてません。

あれ、僕も必要だと思ってないですね！
`.synthesis`の入出力テストするのが一番よくて、それができないなら～という文脈のつもりでした！

> かなりヘビーな進行である一方、.synthesis が VOICEVOX ENGINE の核心部という点も考えると、やる価値はあると（コントリビュータ的には）思います。
同時にVOICEVOX 全体の進行等あると思うので、これに取り組むか、現 test_synthesis を消してひとまず乗り切るかは、メンテナ判断だと感じます。

コアのdecodeの前後の処理の大部分（`query_to_decoder_feature()`と`raw_wave_to_output_wave()`）がテストされてる現状、ひとまず`test_synthesis`を消す形が良いかなと思いました！

---

> 理想的テストの議論をまず確定

同感です！

> 「現 commit の値が意図通りの出力値である」という保証をどうやってつけるんだ…？という別の問題が出てくるかもです。

そうなんですよね･･･。
ただまあコアのdecodeがブラックボックスなので、`.synthesis`が完全に意図通りであることを証明するのはできない気がします！

なので、なるべくブラックボックス以外の箇所のテストを書きつつ、多分バグはないだろうという状態で入出力を固定させるしかないのかなと思いました！

**Comment by tarepan** [comment]
> .synthesisの入出力テストするのが一番よくて、それができないなら～という文脈  

理解しました👍  

> ひとまずtest_synthesisを消す  

👍  
#912 にて `test_synthesis` 削除を提案します、これで当面の問題は解決しそうです🎉  
Reviewよろしくお願いします。  

> コアのdecodeがブラックボックスなので、`.synthesis`が完全に意図通りであることを証明するのはできない ...  
> 多分バグはないだろうという状態で入出力を固定 ...  
> 完全に解析できるコアのdecodeのモック ... 手計算する手 ... そこまでしなくてもいいのかな  

👍  
全面的に同意です。不変性保証でコスパ良くテストするのがベストだと思います。  
リファクタリングとunittest群の追加が終わった近い将来、入出力固定とそれを用いた不変性テストを導入します。
