### ISSUE TITLE
`CancellableEngine` における `engine._synthesis_impl()` の直接 call

### ISSUE THREAD

**Issue by tarepan** [VOICEVOX/voicevox_engine#908]
## 質問の内容
概要: `CancellableEngine` において `engine._synthesis_impl()` が直接 call されている理由が知りたい（バグ？）  

実験機能である `CancellableEngine` はサブプロセスにおいて波形合成をおこなう。  
その際、`.synthesis()` ではなく `._synthesis_impl()` を直接 call している。  
https://github.com/VOICEVOX/voicevox_engine/blob/d8488ff16e0fdf164621665a26ef410c73c908ed/voicevox_engine/cancellable_engine.py#L243

この方法で合成をおこなった場合、疑問文 upspeak 機能が利用されない問題がある。  
また、そもそも論として、private 関数を直接叩いている。  

このような背景から次の質問があります：  
Q「***`CancellableEngine` において `engine._synthesis_impl()` を直接 call しているのは意図的か、その理由は***」

## VOICEVOXのバージョン
0.14.10

## OSの種類/ディストリ/バージョン
- [x] Windows
- [x] macOS
- [x] Linux

## 関連 issues
- #897: `CancellableEngine` の直接 call によりリファクタリングがブロック中

**Comment by Hiroshiba** [comment]
> Q「CancellableEngine において engine._synthesis_impl() を直接 call しているのは意図的か、その理由は」

色々調べてみたんですけど、ちょっとわかんなかったです！
多分`.synthesis`実行のが良いのかなと思いました！！

（@takana-v さん、覚えていらっしゃったりしますか･･･？）

**Comment by tarepan** [comment]
> 多分.synthesis実行のが良いのかな  

👍  
修正案として draft PR (#916) を作成しました。  

追加情報が揃い次第、正式 PR 化します。

**Comment by takana-v** [comment]
自分もはっきりとは覚えてないですね...
`.synthesis`のコールでも問題ないかと思います。
