### ISSUE TITLE
エンジン側のエラー発生時、クライアントにCORSエラーが表示される

### ISSUE THREAD

**Issue by Hiroshiba** [VOICEVOX/voicevox_engine#91]
## 不具合の内容

サーバーがエラーになると、なぜかクライアント側でCORSエラーとなります。
これのせいでエラーの原因を勘違いしやすくなっています。

## その他

正常レスポンスではCORSを考慮したレスポンスが返されるようになっていますが、エラー時にそれが適用されてないかも

**Comment by y-chan** [comment]
Internal Server Error(HTTP Status Code: 500)の時にCORSを吐くようです(以前検証した際の情報ですが、おそらく変わってないかと思います)
Engineのコード内でしっかりエラーハンドリングを行い、500が自動的に吐かれるようなことがないようにする(400番系を吐くように変更?)ことで解決できそうな気がします。

**Comment by Hiroshiba** [comment]
この辺ですかね https://github.com/tiangolo/fastapi/issues/775

**Comment by Hiroshiba** [comment]
もちろん前者の場合はしっかりエラーハンドリングすべきだと思います！

**Comment by sabonerune** [comment]
CORSエラーの原因は500エラーそのものではなく未処理の例外が発生すると`CORSMiddleware`が適用されないことが原因らしいです。
- ref https://github.com/tiangolo/fastapi/discussions/8658

**Comment by Hiroshiba** [comment]
おーー、なるほどです！！
やりとり見るにバグっぽい感じなんですかね。

↓のコメントにもあるように、例外用のミドルウェア作っちゃうワークアラウンドで一旦解決で良いのかなと感じました！！
https://github.com/tiangolo/fastapi/discussions/8658#discussioncomment-5153281
