### ISSUE TITLE
`Mora` に存在しないはずの `is_interrogative` 引数が登場

### ISSUE THREAD

**Issue by tarepan** [VOICEVOX/voicevox_engine#910]
## 不具合の内容
`Mora` コンストラクタ引数に存在しないはずの `is_interrogative` が、`kana_parser.py` で存在している。  

https://github.com/VOICEVOX/voicevox_engine/blob/6f2bec6cb952a3e258000f88b4e35b349bbccfa5/voicevox_engine/model.py#L10-L22

https://github.com/VOICEVOX/voicevox_engine/blob/831d28aad743a7583e8260cfc72da53f205fa966/voicevox_engine/tts_pipeline/kana_parser.py#L34-L42

### 現象・ログ
エラーは発生していない。  

### 再現手順
コード確認。  

エラーが発生しないことの再現は以下：  

```python
from pydantic import BaseModel, Field, conint, validator
from typing import Optional


class Mora(BaseModel):
    """
    モーラ（子音＋母音）ごとの情報
    """

    text: str = Field(title="文字")
    consonant: Optional[str] = Field(title="子音の音素")
    consonant_length: Optional[float] = Field(title="子音の音長")
    vowel: str = Field(title="母音の音素")
    vowel_length: float = Field(title="母音の音長")
    pitch: float = Field(title="音高")  # デフォルト値をつけるとts側のOpenAPIで生成されたコードの型がOptionalになる

    def __hash__(self):
        items = [
            (k, tuple(v)) if isinstance(v, List) else (k, v)
            for k, v in self.__dict__.items()
        ]
        return hash(tuple(sorted(items)))

Mora(
    text="ヘ",
    consonant="h",
    consonant_length=0,
    vowel="e",
    vowel_length=0,
    pitch=0,
    is_interrogative=False,
)

# Mora(text='ヘ', consonant='h', consonant_length=0.0, vowel='e', vowel_length=0.0, pitch=0.0)
```

（`pydantic` がエラーを抑制している模様？ 暗示的に `**kwargs` へ収納？）

### 期待動作
異常終了（正しくエラーを吐くべき）

## VOICEVOXのバージョン
0.14.10

## OSの種類/ディストリ/バージョン
- [x] Linux

**Comment by takana-v** [comment]
エラーが発生しないのは、Pydanticの仕様だと思われます。

https://docs.pydantic.dev/1.10/usage/model_config/
> extra
whether to ignore, allow, or forbid extra attributes during model initialization. Accepts the string values of 'ignore', 'allow', or 'forbid', or values of the Extra enum (default: Extra.ignore). 'forbid' will cause validation to fail if extra attributes are included, 'ignore' will silently ignore any extra attributes, and 'allow' will assign the attributes to the model.

不必要な`is_interrogative`引数に関しては、削除で良いと思います。

**Comment by tarepan** [comment]
@takana-v  
情報ありがとうございます！  

> エラーが発生しないのは、Pydanticの仕様  

👍  
Pydantic のデフォルトが `ignore` であり、`Mora` は `BaseModel` をそのまま継承しているため、おっしゃるとおり Pydantic 仕様で無視されている（エラーが発生しない）で間違いなさそうです。  

> 不必要なis_interrogative引数に関しては、削除  

👍  
削除PR（#914）を作成しました。本PRで解決予定です。
