### ISSUE TITLE
`tts_pipeline` サブモジュールのリネーム

### ISSUE THREAD

**Issue by tarepan** [VOICEVOX/voicevox_engine#913]
## 内容
要望概要: `tts_pipeline` 内のサブモジュールを機能ベースでリネームする

[`tts_pipeline`](https://github.com/VOICEVOX/voicevox_engine/tree/master/voicevox_engine/tts_pipeline) はテキスト音声合成の各段階を実装する、`voicevox_engine` の主要モジュールである。このモジュールはディレクトリ構造整理（#822）で明確化され、またリファクタリングによって配下のサブモジュールの機能的凝集度が向上している。  
一方でサブモジュールの名称はリファクタリング前から維持されており、プログラマーにとっても、機械学習エンジニアにとっても、直感的でないモジュール名となっている。  
より一般的かつ明確なモジュール名にリネームできれば新規コントリビュータの開発体験を更に向上しうる。  

このような背景から、サブモジュールの名称を機能ベースへリネームすることを提案します。  

### Pros 良くなる点
- `tts_pipeline` 内見通し向上
- 新規機能実装箇所を悩むコストの低減

### Cons 悪くなる点
- 無し

### 実現方法
本 issue で新名称を議論したい。  

## VOICEVOXのバージョン
0.14.10

**Comment by tarepan** [comment]
## リネーム第1弾 - テキスト分析

第一弾として次を対象としたい：  

- `full_context_label`
- `kana_parser`

ともに「テキスト ⇔ アクセント句系列」相互変換を担うモジュールである。  
前者はテキストとして日本語文を、後者はテキストとしてAquesTalk風記法テキスト（`kana`）を対象とする。  

TTS の文脈でこのモジュールは「テキスト分析器 "text analyzer"」と呼ばれる。  

> 従来の TTS では ... 入力文がテキスト解析により音素（+ アクセント）系列へと変換され ...  
> Text-analyzer (G2P) ...  
> 
> 岡本. (2022). [*ニューラル音声合成技術*](https://www.nict.go.jp/publication/shuppan/kihou-journal/houkoku68-2_HTML/2022U-02-02-06.pdf). 情報通信研究機構研究報告, Vol.68, No.2.

よって次のリネームを提案します：  

- `japanese_text_analyzer` (← `full_context_label`)
- `kana_text_analyzer` (← `kana_parser`)

**Comment by Hiroshiba** [comment]
issueの作成ありがとうございます！

> japanese_text_analyzer (← full_context_label)

`text_analyzer`が良いかなと思いました！

* `full_context_label`はなんかややこしいから避けたい
* text analyzeという名前はとても良い
	* 辞書周りの機能はここに含まれないという認識
* 現状日本語だけなので`japanese`はつけないほうが良さそう（YAGNI原則）

> kana_text_analyzer (← kana_parser)

ちょっと思いついてないですが、相互変換できることがわかる名前が良さそうかもです。

* やってることはAquesTalk風記法←→AccentPhrases
* parserもalnalyzerもたぶん片方向
* `kana_converter`とか･･･？

**Comment by tarepan** [comment]
> text_analyzerが良い ...  
> ...  
> 現状日本語だけなのでjapaneseはつけないほうが良さそう（YAGNI原則）  

👍  
同意です。  

> 相互変換できることがわかる名前 ... `kana_converter`  

👍  
`kana_converter` は条件を満たしているように感じます。  

対象2モジュールがリファクタリングを終えて安定化し次第、リネームの PR を作成します。

**Comment by tarepan** [comment]
## リネーム第2弾 - 音素
`acoustic_feature_extractor` モジュールは音素文字列型および `Phoneme` クラスを定義する。  
関数等を定義していないため、このモジュールは音素そのものである。  

このような背景から、`acoustic_feature_extractor` → `phoneme` の名称変更を提案します。
