### ISSUE TITLE
`replace_phoneme_length` の無音挿入

### ISSUE THREAD

**Issue by tarepan** [VOICEVOX/voicevox_engine#924]
## 質問の内容
概要: `replace_phoneme_length` における無音挿入は必須か、その役割は何か

`TTSEngine.replace_phoneme_length()` は音素長生成を担っている。  
https://github.com/VOICEVOX/voicevox_engine/blob/68a439d979a0b9186bfa9009dece3309ad956696/voicevox_engine/tts_pipeline/tts_engine.py#L390-L407

この際、コアの `yukarin_s_forward()` へ渡される音素系列には前後無音（*pau*）が付与されている。  
そして `yukarin_s_forward()` から得られた `phoneme_lengths` のうち、*pau* に当たる部分は `mora` へ反映されず捨てられる。  
つまり一見すると *pau* を付けて捨てているように見える。  
一方で音声合成の観点から考えると、生成/推論のための padding はしばしばあるため、そのケースにも見える。  

このような背景から次の質問があります：  
Q「 `replace_phoneme_length` における無音挿入は必須か、必須ならその役割は何か」

## VOICEVOXのバージョン

0.14.10

## OSの種類/ディストリ/バージョン
- [x] Windows
- [x] macOS
- [x] Linux

**Comment by Hiroshiba** [comment]
ご質問ありがとうございます！！

> Q「 replace_phoneme_length における無音挿入は必須か、必須ならその役割は何か」

必須になります！
役割は多分エンジン側にとっては何でもよくて、「コアのAPIがそうなってるから」かなと。

ちなみにここから先はエンジン側に漏れるべきではない情報になりますが一応共有すると、

* コアにとっては「モデルがそういう仕様だから」
* モデルにとっては「学習時がそうだったから」
* 学習時の気持ちは「拡張性があったから」

です！
拡張性というのは、`pau`といっても「。」や「？」や「！」や呼吸音があり得るので、将来そのあたりを追加できるようにしておいた（けど結局使ってない）って感じです！

**Comment by tarepan** [comment]
> エンジン側に漏れるべきではない情報 ... 一応共有  

詳細にありがとうございます！  
末尾表現等の拡張性を考え前後 *pau* が付く前提/仕様になっている、ということですね。理解しました。  

> 必須  

👍  

> 役割は多分エンジン側にとっては何でもよくて  

👍  
コードコメントに残す必要がある（コメント無いとバグに見える）のですが、どういう表現が良いでしょうか？

```python
# 生成のために前後無音を挿入する（コアの仕様。c.f. voicevox_engine#924）
phonemes = [OjtPhoneme("pau")] + phonemes + [OjtPhoneme("pau")] 
```

とかが第一感です。

**Comment by Hiroshiba** [comment]
> コードコメントに残す必要がある（コメント無いとバグに見える）のですが、どういう表現が良いでしょうか？

良さそうに思いました！！
このコードが全体で2箇所以上にあるなら、コアのアダプター側に無音を足す処理を入れても良いかも･･･？
あとはコアの仕様なので、コアアダプターのドキュメントあたりに書いてもいいかも･･･？

どれもこれもそこまでこだわりはないです！！

**Comment by tarepan** [comment]
> 良さそうに思いました！！  

👍  

> コアのアダプター側に無音を足す処理を入れ ...  

👍  
理の通ったコード配置に感じます。影響範囲等を精査して PR できればと思います。  

> コアの仕様なので、コアアダプターのドキュメントあたりに書い  

👍  
コア利用上の注意としてアダプターに記載するのが妥当そうです。PR できればと思います。
