### ISSUE TITLE
refactor: `TTSEngineBase` 廃止

### ISSUE THREAD

**Issue by tarepan** [VOICEVOX/voicevox_engine#939]
## 内容
`TTSEngineBase` 廃止によるリファクタリング  

現在の VOICEVOX ENGINE において `TTSEngineBase` は `TTSEngine` のみから継承されている。  
また `TTSEngineBase` がもつ実処理は薄く（約10行）、`.replace_mora_data()` と `.create_accent_phrases()` のみが複数の関数をファサード的に集約する処理を持っている。  
この分離は「`TTSEngineBase` がインターフェースおよびエンジン責務実装を担い、コア依存部を `TTSEngine` で実装する」という思想・観点からは整理されている。  
一方、継承先が1クラスしかない点で冗長であり、計10行ほどの実処理を分離するために100行以上のベースクラスに対するメンテコストを払っている。  

このような背景から、`TTSEngineBase` 廃止によるリファクタリングを提案します。  

### Pros 良くなる点
- 継承削除による見通し改善
- Baseクラス削除によるメンテ性向上

### Cons 悪くなる点
- コア関連コードとエンジン関連コードの同居

### 実現方法
- `TTSEngineBase` 廃止

## VOICEVOXのバージョン
0.14.10

## OSの種類/ディストリ/バージョン
- [x] Windows
- [x] macOS
- [x] Linux

**Comment by Hiroshiba** [comment]
なるほどです！
別に統合でも良いかと思うのですが、coreはかなり階層を分けたのにengineは統合するのは若干違和感があります。
ちょっといくつか疑問点があるので認識揃えられると･･･！

> 継承先が1クラスしかない点

MockTTSEngineは本当はBaseを継承する形が合っていそうに感じています。
`MockTTSEngine`は`.synthesis`をmockするだけ、という感じにするのであれば現状の形でも良いかもです。

ただまあコアの方は利用先が1つであっても分離していたりしそうなので、設定が不揃いになるという欠点もありそうです。

> 計10行ほどの実処理を分離するために100行以上のベースクラスに対するメンテコストを払っている。

大半はTTSEngineに移るだけなので、メンテコストあんま変わらないかも･･･？

**Comment by tarepan** [comment]
> 違和感 ... 認識揃えられると  

👍  
抽象化層を削る議論なので、丁寧な認識合わせに賛成です。

------------------------------------

> MockTTSEngineは本当はBaseを継承する形が合っていそう

#931 に連なる議論かと思います。すなわち、`MockTTSEngine` の役割で適切な継承関係が決まる、という意味合いです。  
 `MockTTSEngine` は以下のいずれの認識でしょうか？  

- A. `TTSEngineBase` インターフェースの第2実装
- B. `TTSEngine` の軽量音声出力疑似 Fake Object
- C. それ以外

Aの場合「`TTSEngineBase` の継承 & `TTSEngine` との完全隔離」が正しいです。  
Bの場合「`TTSEngine` の継承 & 軽量疑似 Fake `.synthesis()` メソッドオーバーライド」が自然です。

------------------------------------

> コアの方は利用先が1つであっても分離していたりしそうなので、設計が不揃いになる

「コア側は `CoreAdapter` / `CoreWrapper` / CDLL core の多層構造だが、エンジン側は単層構造を志向していて不揃い」で私の認識合っているでしょうか？

------------------------------------

> > 100行以上のベースクラスに対するメンテコスト ... 
> 
> 大半はTTSEngineに移るだけなので、メンテコストあんま変わらない

具体的な削減量を算定しました ([branch](https://github.com/tarepan/voicevox_engine/commit/f5137276d8e9e94c4d96e6bddbad6a03f9f9cbbd))。  

- コード: 55行減（最低でも）
- 関数: 3つ

関数の変更時（例: リネーム #935, 引数追加）に認識・変更する対象が半減するのはメンテ性に寄与します。  

よって「メンテコスト減の絶対量が小さくないか？」ではなく「メンテ性は上がりそうだが、アーキテクチャ認識コストを相対的に上回るメリットが出るのか？」が論点だと認識しています。

------------------------------------

**Comment by Hiroshiba** [comment]
> `MockTTSEngine` は以下のいずれの認識でしょうか？  

Cのそれ以外で、 #931 で書いた「run.pyの--enable_mock引数で使うこと」かなと！
持っているべき機能はさておいて、run.py内の`synthesis_engines`の型にあっていれば何でも良いのかなと思いました！
（つまりTTSEngineの継承でもOK）

> 「コア側は CoreAdapter / CoreWrapper / CDLL core の多層構造だが、エンジン側は単層構造を志向していて不揃い」で私の認識合っているでしょうか？

ですです！

> よって「メンテコスト減の絶対量が小さくないか？」ではなく「メンテ性は上がりそうだが、アーキテクチャ認識コストを相対的に上回るメリットが出るのか？」が論点だと認識しています。

なるほどです。メリットがあるというよりはデメリットが増えるかもと思ってました！
ただまあコアが多層でエンジンが単層なのはアダプターの有無なのでそこまで気にしなくて良さそうに思いました。
もう一つMockTTSEngineが何をモックするのか分かりづらいかもですが（名前からすると全部モックしそう）、synthesisのみのモックだということが伝わるドキュメントかクラス名であれば問題ないのかなと思いました！！

**Comment by tarepan** [comment]
>> MockTTSEngine は以下のいずれの認識でしょうか？  
> 
> Cのそれ以外 ... 「run.pyの--enable_mock引数で使うこと」  

👍  

> 持っているべき機能はさておいて ... `synthesis_engines`の型にあっていれば何でも ... TTSEngineの継承でもOK  
> ...  
> MockTTSEngineが何をモック ... synthesisのみのモック  

👍  

これらを総合すると、以下の認識で合ってますか？  

`python run.py --enable_mock` は `TTSEngine` の代わりに軽量波形合成のみを可能にするフラグ。  
内部的には `synthesis_engines` へ登録された `MockTTSEngine` の `.synthesis()` がコールされる。  
このコールが動けば良く、内部設計の方針（例: 実装・継承関係）は今のところ無い。  

-------------------------------------------


> >「コア側は CoreAdapter / CoreWrapper / CDLL core の多層構造だが、エンジン側は単層構造を志向していて不揃い」  
> 
> ですです！  
> ...  
> ただまあコアが多層でエンジンが単層なのはアダプターの有無なのでそこまで気にしなくて良さそう  

👍  
アダプター1層のみの違いでそもそも大差ない、という見解ですね、同意です。  

私は「アダプターはコアが本来持つべき mutex 等（抽象化漏れの吸収）を担う特殊なレイヤー（ある種のレガシー層）。なのでエンジン内の分割とはまた種類の違う議論？」という感じがぼんやりして、なおのことあまり気にしなくて良さそうに感じます。  

-------------------------------------------

（上の認識が間違ってなければ）ある程度認識は共有できたかと思います。  

継承先が1つで問題ない（ `TTSEngineBase` ← `TTSEngine` ←`MockTTSEngine` でNOTE書けばOK）& コア層構造は気にしなくて良い、に基づくと、`TTSEngineBase` は廃止できそう、と私は考えます。   

本リファクタリングの Go/NoGo はどうしましょうか？

**Comment by Hiroshiba** [comment]
> これらを総合すると、以下の認識で合ってますか？
> `python run.py --enable_mock` は `TTSEngine` の代わりに軽量波形合成のみを可能にするフラグ。  
内部的には `synthesis_engines` へ登録された `MockTTSEngine` の `.synthesis()` がコールされる。  
このコールが動けば良く、内部設計の方針（例: 実装・継承関係）は今のところ無い。  

`enable_mock`の認識が若干ずれてる気がしました！
VOICEVOX COREを使わずモックで音声合成を行う機能です！（ヘルプから引用）

整理するとこうかなと。

* `--enable_mock`
	* 製品版コアなしで音声合成できる引数
	* なので、コアの全機能がモックに置き換わったTTSEngineが必要
* 以前の`MockTTSEngine`の認識
	* `--enable_mock`が指定されたときにこのエンジンをそのまま使っていた
	* TTSEngineBaseを継承していて、コアのモックも不要だった
	* 過去の実装[こんな感じ](https://github.com/VOICEVOX/voicevox_engine/blob/release-0.14/voicevox_engine/dev/synthesis_engine/mock.py)
* 作られようとしている`MockTTSEngine`の認識
	* `TTSEngine`の`synthesis`だけをモックに置き換えるクラス
	* `--enable_mock`が指定されたときは、モック版コアを入れたTTSEngineを継承した`MockTTSEngine`を作ることになりそう
	* クラス名から動作の想像がつかないので、クラス名を変えるかドキュメントを書いた方が良さそう

> 継承先が1つで問題ない（ `TTSEngineBase` ← `TTSEngine` ←`MockTTSEngine` でNOTE書けばOK）& コア層構造は気にしなくて良い、に基づくと、`TTSEngineBase` は廃止できそう

`enable_mock`と`MockTTSEngine`の認識がずれているかもですが、`TTSEngineBase` は廃止できそうという結論は同感です！

**Comment by tarepan** [comment]
> `enable_mock`の認識が若干ずれてる  

👍  
丁寧にありがとうございます、理解しました！  

> 「TTSEngineBase は廃止できそう」という結論は同感 ... Goでも実は問題ない  

👍  
着手します。
