### ISSUE TITLE
`Label.phoneme` が取りうる値

### ISSUE THREAD

**Issue by tarepan** [VOICEVOX/voicevox_engine#954]
## 質問の内容
質問概要: `Label.phoneme` が取りうる値は何か

音素の型付け（#894 など）にあたり、各ドメインで取りうる音素の値を知る必要がある。  
OpenJTalk ドメイン (`text_analyzer`) では `Label.phoneme` の取りうる値がこれにあたる。  
VOICEVOX ENGINE は fork された pyopenjtalk から得られた feature を解析してこれを得ているため、取りうる値を調べるために VOICEVOX 全体への深い理解が必要である。  

このような背景から、次の質問があります：  
Q「`Label.phoneme` が取りうる値は何か」

## VOICEVOXのバージョン
0.14.11

## OSの種類/ディストリ/バージョン
- [x] Windows
- [x] macOS
- [x] Linux

**Comment by Hiroshiba** [comment]
音素一覧に書かれているものと、あとはsilくらいかなと！
何かしらの想定外で`xx`が現れるかもしれません。

たぶん一覧はこちらです。
https://github.com/r9y9/open_jtalk/blob/aade59307b86e8788edf2dd72642e00fab800539/src/jpcommon/jpcommon_rule_utf_8.h
